meta:
  target:
    width: 8
    height: 5
  camera:
    position:
      # in cm, from upper left screen corner
      x: 0.1725
      y: 0.007
  screen:
    resolution:
      # in pixels
      width: 2880
      height: 1800
    measurements:
      # in m
      width: 0.335
      height: 0.207
pipeline:
  - type: SourceCapture
    source: 0
    fps: 30
    width: 640
    height: 360
  - type: FaceLandmarks
    name: FaceLandmarks68
    model: shape_predictor_68_face_landmarks.dat
  - type: FaceLandmarks
    name: FaceLandmarks5
    model: shape_predictor_5_face_landmarks.dat
  - type: HeadPoseEstimation
  - type: PupilLocalization
    table_size: 131
  - type: GazePointCalculation
