meta:
  target:
    width: 8
    height: 5
  camera:
    position:
      # in m, from upper left screen corner
      x: 0.1725
      y: -0.007
  screen:
    resolution:
      # in pixels
      width: 2880
      height: 1800
    measurements:
      # in m
      width: 0.335
      height: 0.207
pipeline:
  - type: SourceCapture
    source: 0
    fps: 30
    width: 640
    height: 360
  - type: FaceLandmarks
    name: FaceLandmarks68
    model: shape_predictor_68_face_landmarks.dat
  - type: HeadPoseEstimation
    name: HeadPose68
    # See https://ibug.doc.ic.ac.uk/resources/facial-point-annotations/
    # (Here the indices are 0-based, so remember to take care of the offset:
    #  0 here is 1 in the ibug figure etc.)
    landmark_indices: [30, 8, 36, 45, 48, 54]
    model: [
      [0.0, 0.0, 0.0],  # Nosetip (Pronasal prn)
      [0.0, -0.33, -0.065],  # Chin tip (Gnathion/Menton gn)
      [-0.225, 0.17, -0.135],  # Right eye outside corner (right exocanthion ex_r)
      [0.225, 0.17, -0.135],  # Left eye outside corner (left exocanthion ex_l)
      [-0.15, -0.15, -0.125],  # Right mouth corner (Cheilion ch_r)
      [0.15, -0.15, -0.125]  # Left mouth corner (Cheilion ch_l)
    ]
    model_scale: 1
# An alternative approach for the pupil localization
#  - type: EyeLike
#    relative_threshold: 0.3
  - type: PupilLocalization
    table_size: 131
    relative_threshold: 0.3
  - type: GazePointCalculation
