gaze: gaze::gui::EventManager Class Reference
gaze::gui::EventManager Class Reference
Handles communication between non-gui and gui processes in a safe way.
#include "gaze/gui/event_manager.h"
Public Member Functions
void publish (void *data, Events event)
void subscribe (dlib::base_window *subscriber)
void unsubscribe (dlib::base_window *subscriber)
Static Public Member Functions
static EventManager & instance ()
Detailed Description
Handles communication between non-gui and gui processes in a safe way.
This EventManager performs no sophisticated distinction about subcribers to specific events, from specific callers, etc., instead it just passes all published events to all subscribers.
Note
The EventManager is implemented as a singleton, it should be accessed via EventManager::instance().
Definition at line 37 of file event_manager.h.
Member Function Documentation
EventManager & gaze::gui::EventManager::instance () static
Returns
a reference to a global static instance of the event manager.
Definition at line 15 of file event_manager.cpp.
Referenced by gaze::gui::DebugWindow::DebugWindow().
{
   static EventManager event_manager;
   return event_manager;
 }
void gaze::gui::EventManager::publish (void * data, Events event)
Publishes an event with the given data to all subscribers using dlib::base_window::trigger_user_event(void*,int).
Parameters
data the data to pass along
event the event identifier
Definition at line 20 of file event_manager.cpp.
{
   for (dlib::base_window* subscriber : this->subscribers) {
     subscriber->trigger_user_event(data, event);
   }
 }
void gaze::gui::EventManager::subscribe (dlib::base_window * subscriber)
Subscribes the new subscriber to all events.
Parameters
subscriber The new subscriber.
Definition at line 26 of file event_manager.cpp.
References std::vector< _Tp, _Alloc >::push_back().
Referenced by gaze::gui::DebugWindow::DebugWindow().
{
   this->subscribers.push_back(subscriber);
 }
void gaze::gui::EventManager::unsubscribe (dlib::base_window * subscriber)
Unsubscribes the subscriber from all events.
Parameters
subscriber The unsubscriber.
Definition at line 30 of file event_manager.cpp.
References std::vector< _Tp, _Alloc >::begin(), std::vector< _Tp, _Alloc >::end(), std::vector< _Tp, _Alloc >::erase(), and std::remove().
{
   this->subscribers.erase(
       std::remove(this->subscribers.begin(),
                   this->subscribers.end(),
                   subscriber),
       this->subscribers.end());
 }
The documentation for this class was generated from the following files:
include/gaze/gui/event_manager.h
src/gaze/gui/event_manager.cpp