gaze: gaze::Pipeline Class Reference
gaze::Pipeline Class Reference
The processing pipeline from input to output.
#include "gaze/pipeline.h"
Public Member Functions
Pipeline (std::vector< PipelineStep * > steps, const bool start=true)
~Pipeline ()
void start ()
void stop ()
util::Data get_data ()
std::vector< PipelineStep * > get_steps ()
Detailed Description
The processing pipeline from input to output.
Definition at line 19 of file pipeline.h.
Constructor & Destructor Documentation
gaze::Pipeline::Pipeline (std::vector< PipelineStep * > steps, const bool start = true) explicit
Initializes the pipeline and starts the processing.
The start can be deferred and manually invoked by a call to start().
Parameters
steps The PipelineSteps to use.
start if true, the processing will start automatically.
Definition at line 47 of file pipeline.cpp.
References std::ref(), and start().
                                      : steps(steps) {
   this->thread = new std::thread(&Pipeline::operator(), std::ref(*this));
   if (start) {
     this->start();
   }
 }
gaze::Pipeline::~Pipeline ()
Stops processing if not already done, joins the thread and deletes it.
Definition at line 55 of file pipeline.cpp.
References stop().
                     {
   this->stop();
   this->thread->join();
   delete this->thread;
 }
Member Function Documentation
util::Data gaze::Pipeline::get_data ()
Returns
the last updated data element.
Definition at line 69 of file pipeline.cpp.
References lock().
Referenced by gaze::GazeTracker::get_current_gaze_point(), and gaze::gui::DebugWindow::on_user_event().
{
   std::shared_lock<std::shared_mutex> lock(this->data_access_mutex);
   return this->current_data;
 }
std::vector< PipelineStep * > gaze::Pipeline::get_steps ()
Returns
The PipelineSteps.
Definition at line 74 of file pipeline.cpp.
{
   return this->steps;
 }
void gaze::Pipeline::start ()
Starts the processing of the underlying thread.
Definition at line 61 of file pipeline.cpp.
Referenced by Pipeline().
                      {
   this->running = true;
 }
void gaze::Pipeline::stop ()
Stops the processing of the underlying thread.
Definition at line 65 of file pipeline.cpp.
Referenced by ~Pipeline().
                     {
   this->running = false;
 }
The documentation for this class was generated from the following files:
include/gaze/pipeline.h
src/gaze/pipeline.cpp