gaze: gaze::pipeline::HeadPoseEstimation Class Reference
gaze::pipeline::HeadPoseEstimation Class Reference final
Estimates the head pose from landmarks and source image.
#include "gaze/pipeline_steps/head_pose_estimation.h"
Public Member Functions
void process (util::Data &data) override
void visualize (util::Data &data) override
Public Member Functions inherited from gaze::PipelineStep
PipelineStep ()
std::string get_name ()
virtual ~PipelineStep ()=default
Public Member Functions inherited from gaze::gui::Visualizeable< widget_type >
std::shared_ptr< dlib::drawable > init (dlib::drawable_window &parent, int width, int height, std::string text="No visualization.") final
void remove_widget () override
Public Member Functions inherited from gaze::gui::VisualizeableBase
virtual ~VisualizeableBase ()=default
Protected Member Functions
cv::Matx33d read_or_set_camera_matrix (const util::Data &data)
cv::Mat get_and_maybe_read_distortions (const util::Data &data)
Additional Inherited Members
Protected Attributes inherited from gaze::PipelineStep
int number
std::string name
Protected Attributes inherited from gaze::gui::Visualizeable< widget_type >
std::shared_ptr< widget_type > widget
Detailed Description
Estimates the head pose from landmarks and source image.
///
Todo:
shoeffner: Write documentation for HeadPoseEstimation.
Definition at line 24 of file head_pose_estimation.h.
Member Function Documentation
cv::Mat gaze::pipeline::HeadPoseEstimation::get_and_maybe_read_distortions (const util::Data & data) protected
Returns a distortions matrix.
If the distortions matrix is available from the configuration, the configuration value is stored and used. Otherwise, it is assumed to be a zero matrix.
Parameters
data The data to read from, if no yaml data is available.
Returns
a distortion matrix.
Definition at line 134 of file head_pose_estimation.cpp.
References CV_64F, gaze::util::get_config(), and cv::Mat::zeros().
Referenced by process().
{
   if (this->has_distortions) {
     return this->distortions;
   }
   YAML::Node camera_config = util::get_config()["meta"]["camera"];
   if (camera_config["distortion_coefficients"]) {
     this->distortions = camera_config["distortion_coefficients"].as<cv::Mat>();
   } else {
     this->distortions = cv::Mat::zeros(4, 1, CV_64F);
   }
   this->has_distortions = true;
   return this->distortions;
 }
void gaze::pipeline::HeadPoseEstimation::process (util::Data & data) override virtual
Estimates the head pose from face landmarks and the input image.
Parameters
data The data object to be updated.
Returns
via data the modified data object.
Implements gaze::PipelineStep.
Definition at line 93 of file head_pose_estimation.cpp.
References get_and_maybe_read_distortions(), gaze::util::Data::head_rotation, gaze::util::Data::head_translation, gaze::util::Data::landmarks, std::vector< _Tp, _Alloc >::push_back(), read_or_set_camera_matrix(), cv::solvePnP(), and cv::SOLVEPNP_ITERATIVE.
{
   if (data.landmarks.num_parts() <= 0) {
     return;
   }
   // Convert dlib::points to cv::Point for solvePNP
   std::vector<cv::Point2d> im_points;
   for (auto i : this->index_list) {
     im_points.push_back(cv::Point2d(data.landmarks.part(i).x(),
                                     data.landmarks.part(i).y()));
   }
   cv::solvePnP(this->model_points, im_points,
       this->read_or_set_camera_matrix(data),
       this->get_and_maybe_read_distortions(data),
       data.head_rotation, data.head_translation, false, cv::SOLVEPNP_ITERATIVE);
 }
cv::Matx33d gaze::pipeline::HeadPoseEstimation::read_or_set_camera_matrix (const util::Data & data) protected
Returns a camera matrix.
If it was not loaded yet, it will be read from gaze.yaml (as created using OpenCV's calibration tool, also check the gaze.default.yaml to see how to integrate it).
If nothing can be found in the configuration, the following matrix is calculated and returned:
Where .
Parameters
data The data to read from, if no yaml data is available.
Returns
a camera matrix.
Definition at line 116 of file head_pose_estimation.cpp.
References cv::Mat::cols, gaze::util::get_config(), cv::Mat::rows, and gaze::util::Data::source_image.
Referenced by process().
{
   if (this->has_camera_matrix) {
     return this->camera_matrix;
   }
   YAML::Node camera_config = util::get_config()["meta"]["camera"];
   if (camera_config["camera_matrix"]) {
     this->camera_matrix = camera_config["camera_matrix"].as<cv::Mat>();
   } else {
     this->camera_matrix <<
       data.source_image.cols, 0, data.source_image.cols / 2,
       0, data.source_image.cols, data.source_image.rows / 2,
       0, 0, 1;
   }
   this->has_camera_matrix = true;
   return this->camera_matrix;
 }
void gaze::pipeline::HeadPoseEstimation::visualize (util::Data & data) override virtual
Visualizes the estimated head pose.
Parameters
data The data object to be visualized.
Implements gaze::gui::VisualizeableBase.
Definition at line 111 of file head_pose_estimation.cpp.
References gaze::util::Data::image, and gaze::gui::Visualizeable< widget_type >::widget.
{
   this->widget->set_image(data.image);
   this->update_overlay(data);
 }
The documentation for this class was generated from the following files:
include/gaze/pipeline_steps/head_pose_estimation.h
src/gaze/pipeline_steps/head_pose_estimation.cpp