gaze: gaze::gui::DebugWindow Class Reference
gaze::gui::DebugWindow Class Reference final
A window to inspect computation results.
#include "gaze/gui/debug_window.h"
Public Member Functions
void process_data (int idx=-1)
DebugWindow (Pipeline *pipeline)
void on_user_event (void *event_data, int event_type) override
Detailed Description
A window to inspect computation results.
Definition at line 22 of file debug_window.h.
Constructor & Destructor Documentation
DebugWindow()
gaze::gui::DebugWindow::DebugWindow (Pipeline * pipeline) explicit
Creates a DebugWindow.
Parameters
pipeline The pipeline to inspect.
Definition at line 22 of file debug_window.cpp.
References gaze::PipelineStep::get_name(), gaze::Pipeline::get_steps(), gaze::gui::VisualizeableBase::init(), gaze::gui::EventManager::instance(), process_data(), and gaze::gui::EventManager::subscribe().
     : dlib::drawable_window(false, false),
       pause_button(*this),
       paused(false),
       pipeline(pipeline),
       pipeline_steps(pipeline->get_steps()),
       pipeline_tabs(*this),
       statistics_widget(*this) {
   this->set_size(this->w_width, this->w_height);
   this->set_title("GazeTracker DebugWindow");
   this->pause_button.set_pos(this->w_margin, this->w_margin);
   this->pause_button.set_name("Pause");
   this->pause_button.set_click_handler([this]() {
         this->paused ^= true;
   });
   this->statistics_widget.set_pos(
       this->w_margin,
       this->pause_button.bottom() + this->w_margin);
   this->statistics_widget.set_size(
       this->stat_width,
       this->w_height - 3 * this->w_margin - this->pause_button.height());
   this->statistics_widget.set_grid_size(this->pipeline_steps.size() + 1, 2);
   this->statistics_widget.set_text(0, 0, "Pipeline step");
   this->statistics_widget.set_text(0, 1,
       dlib::convert_utf8_to_utf32("Execution time (\u00B5s)"));
   for (auto row = decltype(this->statistics_widget.number_of_rows()){0};
        row < this->statistics_widget.number_of_rows();
        ++row) {
     for (auto col = decltype(this->statistics_widget.number_of_columns()){0};
          col < this->statistics_widget.number_of_columns();
          ++col) {
       this->statistics_widget.set_editable(row, col, false);
     }
   }
   this->pipeline_tabs.set_pos(this->statistics_widget.right() + this->w_margin,
                               this->pause_button.bottom() + this->w_margin);
   this->pipeline_tabs.set_size(this->w_width - 3 * this->w_margin
                                    - this->stat_width,
                                this->w_height - 3 * this->w_margin
                                    - this->pause_button.height());
   this->pipeline_tabs.set_number_of_tabs(
       this->pipeline_steps.size() > 0 ? this->pipeline_steps.size() : 1);
   this->pipeline_tabs.set_click_handler([this](auto new_idx, auto)
       -> void {
         this->process_data(new_idx);
       });
   int width = this->pipeline_tabs.width() - 3 * this->w_margin;
   int height = this->pipeline_tabs.height() - 3 * this->w_margin
                   - this->pause_button.height();
   for (auto i = decltype(this->pipeline_steps.size()){0};
        i < this->pipeline_steps.size(); ++i) {
     std::shared_ptr<dlib::drawable> widget;
     if (VisualizeableBase* step =
         dynamic_cast<VisualizeableBase*>(this->pipeline_steps[i])) {
       widget = step->init(*this, width, height);
     } else {
       std::shared_ptr<dlib::label> tmp(new dlib::label(*this));
       tmp->set_text("No visualization.");
       widget = tmp;
     }
     // Create widget group, add widget to it
     std::shared_ptr<dlib::widget_group> widget_group_ptr(
         new dlib::widget_group(*this));
     this->widgets.push_back(widget_group_ptr);
     widget_group_ptr->add(*widget.get(), this->w_margin, this->w_margin);
     // Assign name and add widget group to tab
     this->pipeline_tabs.set_tab_name(i, this->pipeline_steps[i]->get_name());
     this->pipeline_tabs.set_tab_group(i, *widget_group_ptr.get());
     // Assign name to statistics widget
     this->statistics_widget.set_text(i + 1, 0,
         this->pipeline_steps[i]->get_name());
   }
   this->show();
   if (this->pipeline_steps.size() > 0) {
     EventManager::instance().subscribe(this);
   }
 }
Member Function Documentation
on_user_event()
void gaze::gui::DebugWindow::on_user_event (void * event_data, int event_type) override
Checks the event type (
See also
Events) and handles events.
Parameters
event_data data passed along with the event.
event_type the event type (
See also
Events).
Definition at line 140 of file debug_window.cpp.
References gaze::Pipeline::get_data(), gaze::util::Data::operator=(), and process_data().
{
   switch (event_type) {
     case Events::PIPELINE_DATA_UPDATED:
       if (this->paused) {
         break;
       }
       this->data = this->pipeline->get_data();
       this->process_data();
       break;
   }
 }
process_data()
void gaze::gui::DebugWindow::process_data (int idx = -1)
Processes the data to be visualized.
Calls the visualize function of the PipelineStep of the active tab.
Parameters
idx (Optional): If this is a value other than -1, the tab with this index is updated instead of the current tab.
Definition at line 120 of file debug_window.cpp.
References gaze::util::Data::execution_times, and gaze::gui::VisualizeableBase::visualize().
Referenced by DebugWindow(), and on_user_event().
{
   idx = idx < 0 ? this->pipeline_tabs.selected_tab() : idx;
   if (this->pipeline_steps.size() == 0) {
     return;
   }
   if (VisualizeableBase* step =
       dynamic_cast<VisualizeableBase*>(this->pipeline_steps[idx])) {
     step->visualize(this->data);
   }
   for (auto i = decltype(this->pipeline_steps.size()){1};
        i <= this->pipeline_steps.size(); ++i) {
     std::ostringstream os;
     os << this->data.execution_times[this->pipeline_steps[i - 1]->get_name()];
     this->statistics_widget.set_text(i, 1, os.str());
   }
 }
The documentation for this class was generated from the following files:
include/gaze/gui/debug_window.h
src/gaze/gui/debug_window.cpp