gaze: gaze::GazeTracker Class Reference
gaze::GazeTracker Class Reference
This class wraps the gaze tracking process.
#include "gaze/gaze_tracker.h"
Public Member Functions
GazeTracker (const std::string subject_id="default_subject", const bool debug=false)
void calibrate ()
Data access
const std::pair< int, int > get_current_gaze_point () const
Initialization
This method allows initialization of a GazeTracker instance. If GazeTracker() was used to construct the instance, you must call either of these functions before perfoming any actions.
void init (const std::string subject_id, const bool debug=false)
Trial handling
These functions are used to partition an experiment into trials. When you start a trial, call the GazeTracker::start_trial(const std::string) method. After the trial you should issue GazeTracker::stop_trial().
Note that the GazeTracker keeps tracking until you destroy the instance, the only difference in calling the start and stop trial functions is that the identifier will be available next to the data for the specific trial.
void start_trial (const std::string identifier)
void stop_trial ()
Detailed Description
This class wraps the gaze tracking process.
This is the GazeTracker, the heart of gaze. It allows for easy initialization, tracking, and trial definitions.
Definition at line 24 of file gaze_tracker.h.
Constructor & Destructor Documentation
GazeTracker()
gaze::GazeTracker::GazeTracker (const std::string subject_id = "default_subject", const bool debug = false)
Constructs and initializes a GazeTracker instance for a video source. See GazeTracker::init(std::string, std::string, std::string).
Parameters
subject_id The subject identifier.
debug Starts the gaze_tracker in debug mode, bringing up additional debuggin screens.
Definition at line 19 of file gaze_tracker.cpp.
References init().
Referenced by wpl::Experiment::Experiment().
     : debug(debug),
       subject_id(subject_id) {
   this->initialized = false;
   this->init(subject_id, debug);
 }
Member Function Documentation
calibrate()
void gaze::GazeTracker::calibrate ()
Calibrates the GazeTracker.
Note
Currently there is no calibration phase.
Definition at line 36 of file gaze_tracker.cpp.
Referenced by wpl::Experiment::experiment_calibrate().
{
   if (!this->initialized) {
     std::cerr << "[GazeTracker] Not initialized (calibrate())." << std::endl;
     return;
   }
   std::cout << "[GT Stub] Calibrating." << std::endl;
 }
get_current_gaze_point()
const std::pair< int, int > gaze::GazeTracker::get_current_gaze_point () const
Returns
the most recent calculated gaze point. If not initialized, returns .
Definition at line 44 of file gaze_tracker.cpp.
References gaze::util::Data::estimated_gaze_point, and gaze::Pipeline::get_data().
{
   if (!this->initialized) {
     std::cerr << "[GazeTracker] Not initialized (get_current_gaze_point())." <<
       std::endl;
     return std::pair<int, int>(-1, -1);
   }
   int x =
     static_cast<int>(this->pipeline->get_data().estimated_gaze_point(0));
   int y =
     static_cast<int>(this->pipeline->get_data().estimated_gaze_point(1));
   return std::pair<int, int>(x, y);
 }
init()
void gaze::GazeTracker::init (const std::string subject_id, const bool debug = false)
Initializes the GazeTracker.
It immediately starts tracking.
Parameters
subject_id The subject ID, used to store the data in the correct file.
debug Starts the gaze_tracker in debug mode, bringing up additional debuggin screens.
Definition at line 57 of file gaze_tracker.cpp.
Referenced by GazeTracker().
{
   if (this->initialized) {
     return;
   }
   this->debug = debug;
   this->subject_id = subject_id;
   this->init_pipeline(subject_id);
   if (this->debug) {
     gui::open_debug_window(this->pipeline);
   }
   this->initialized = true;
 }
start_trial()
void gaze::GazeTracker::start_trial (const std::string identifier)
Makes the GazeTracker associate its output data with the identifier until either GazeTracker::stop_trial() is called or a new trial is started by calling this function with a different identifier.
The identifiers are not checked for uniqueness! It is very well possible to use the same identifier multiple tames, analyzing the data correctly is then up to you.
Parameters
identifier The trial identifier.
Definition at line 103 of file gaze_tracker.cpp.
{
   if (!this->initialized) {
     std::cerr << "[GazeTracker] Not initialized (start_trial())." <<
       std::endl;
     return;
   }
   this->current_trial_id = identifier;
   std::cout << "[GazeTracker] [Stub] Starting trial " << this->current_trial_id
     << std::endl;
 }
stop_trial()
void gaze::GazeTracker::stop_trial ()
Stops associating data with any specific trial.
Definition at line 114 of file gaze_tracker.cpp.
{
   if (!this->initialized) {
     std::cerr << "[GazeTracker] Not initialized (stop_trial())." <<
       std::endl;
     return;
   }
   std::cout << "[GazeTracker] [Stub] Stopping trial " << this->current_trial_id
     << std::endl;
   this->current_trial_id = "";
 }
The documentation for this class was generated from the following files:
include/gaze/gaze_tracker.h
src/gaze/gaze_tracker.cpp