var searchData=
[
  ['warp',['Warp',['http://docs.opencv.org/3.4.0/d5/d3d/structcv_1_1cudev_1_1Warp.html',1,'cv::cudev']]],
  ['warpercreator',['WarperCreator',['http://docs.opencv.org/3.4.0/d7/d1c/classcv_1_1WarperCreator.html',1,'cv']]],
  ['warrow',['WArrow',['http://docs.opencv.org/3.4.0/dd/d2d/classcv_1_1viz_1_1WArrow.html',1,'cv::viz']]],
  ['wbdetector',['WBDetector',['http://docs.opencv.org/3.4.0/de/d0e/classcv_1_1xobjdetect_1_1WBDetector.html',1,'cv::xobjdetect']]],
  ['wbuffer_5fconvert',['wbuffer_convert',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a04980.html',1,'std']]],
  ['wcameraposition',['WCameraPosition',['http://docs.opencv.org/3.4.0/d6/dcc/classcv_1_1viz_1_1WCameraPosition.html',1,'cv::viz']]],
  ['wcircle',['WCircle',['http://docs.opencv.org/3.4.0/df/d0c/classcv_1_1viz_1_1WCircle.html',1,'cv::viz']]],
  ['wcloud',['WCloud',['http://docs.opencv.org/3.4.0/db/d82/classcv_1_1viz_1_1WCloud.html',1,'cv::viz']]],
  ['wcloudcollection',['WCloudCollection',['http://docs.opencv.org/3.4.0/de/d47/classcv_1_1viz_1_1WCloudCollection.html',1,'cv::viz']]],
  ['wcloudnormals',['WCloudNormals',['http://docs.opencv.org/3.4.0/d5/dd8/classcv_1_1viz_1_1WCloudNormals.html',1,'cv::viz']]],
  ['wcone',['WCone',['http://docs.opencv.org/3.4.0/d5/d1a/classcv_1_1viz_1_1WCone.html',1,'cv::viz']]],
  ['wcoordinatesystem',['WCoordinateSystem',['http://docs.opencv.org/3.4.0/df/d63/classcv_1_1viz_1_1WCoordinateSystem.html',1,'cv::viz']]],
  ['wcube',['WCube',['http://docs.opencv.org/3.4.0/d2/d17/classcv_1_1viz_1_1WCube.html',1,'cv::viz']]],
  ['wcylinder',['WCylinder',['http://docs.opencv.org/3.4.0/d2/d4c/classcv_1_1viz_1_1WCylinder.html',1,'cv::viz']]],
  ['weak_5fptr',['weak_ptr',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05944.html',1,'std']]],
  ['weak_5fptr_3c_20_5fstate_5fbasev2_20_3e',['weak_ptr&lt; _State_baseV2 &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05944.html',1,'']]],
  ['weakclassifierhaarfeature',['WeakClassifierHaarFeature',['http://docs.opencv.org/3.4.0/da/d94/classcv_1_1WeakClassifierHaarFeature.html',1,'cv']]],
  ['weibull_5fdistribution',['weibull_distribution',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05544.html',1,'std']]],
  ['weightingdeblurer',['WeightingDeblurer',['http://docs.opencv.org/3.4.0/df/d5b/classcv_1_1videostab_1_1WeightingDeblurer.html',1,'cv::videostab']]],
  ['wgrid',['WGrid',['http://docs.opencv.org/3.4.0/d2/dea/classcv_1_1viz_1_1WGrid.html',1,'cv::viz']]],
  ['whitebalancer',['WhiteBalancer',['http://docs.opencv.org/3.4.0/d9/d7a/classcv_1_1xphoto_1_1WhiteBalancer.html',1,'cv::xphoto']]],
  ['widget',['Widget',['http://docs.opencv.org/3.4.0/d7/dcd/classcv_1_1viz_1_1Widget.html',1,'cv::viz']]],
  ['widget2d',['Widget2D',['http://docs.opencv.org/3.4.0/d3/d49/classcv_1_1viz_1_1Widget2D.html',1,'cv::viz']]],
  ['widget3d',['Widget3D',['http://docs.opencv.org/3.4.0/d9/d26/classcv_1_1viz_1_1Widget3D.html',1,'cv::viz']]],
  ['widget_5ftrait',['widget_trait',['../structgaze_1_1gui_1_1traits_1_1widget__trait.html',1,'gaze::gui::traits']]],
  ['widget_5ftrait_3c_20dlib_3a_3aimage_5fdisplay_20_3e',['widget_trait&lt; dlib::image_display &gt;',['../structgaze_1_1gui_1_1traits_1_1widget__trait_3_01dlib_1_1image__display_01_4.html',1,'gaze::gui::traits']]],
  ['widget_5ftrait_3c_20dlib_3a_3alabel_20_3e',['widget_trait&lt; dlib::label &gt;',['../structgaze_1_1gui_1_1traits_1_1widget__trait_3_01dlib_1_1label_01_4.html',1,'gaze::gui::traits']]],
  ['widget_5ftrait_3c_20dlib_3a_3aperspective_5fdisplay_20_3e',['widget_trait&lt; dlib::perspective_display &gt;',['../structgaze_1_1gui_1_1traits_1_1widget__trait_3_01dlib_1_1perspective__display_01_4.html',1,'gaze::gui::traits']]],
  ['widgetaccessor',['WidgetAccessor',['http://docs.opencv.org/3.4.0/dd/d02/structcv_1_1viz_1_1WidgetAccessor.html',1,'cv::viz']]],
  ['wimage',['WImage',['http://docs.opencv.org/3.4.0/dc/d0d/classcv_1_1WImage.html',1,'cv']]],
  ['wimage3d',['WImage3D',['http://docs.opencv.org/3.4.0/d7/d3d/classcv_1_1viz_1_1WImage3D.html',1,'cv::viz']]],
  ['wimagebuffer',['WImageBuffer',['http://docs.opencv.org/3.4.0/dd/d85/classcv_1_1WImageBuffer.html',1,'cv']]],
  ['wimagebufferc',['WImageBufferC',['http://docs.opencv.org/3.4.0/d7/d1e/classcv_1_1WImageBufferC.html',1,'cv']]],
  ['wimagec',['WImageC',['http://docs.opencv.org/3.4.0/d0/d9b/classcv_1_1WImageC.html',1,'cv']]],
  ['wimageoverlay',['WImageOverlay',['http://docs.opencv.org/3.4.0/d8/d33/classcv_1_1viz_1_1WImageOverlay.html',1,'cv::viz']]],
  ['wimageview',['WImageView',['http://docs.opencv.org/3.4.0/d0/d33/classcv_1_1WImageView.html',1,'cv']]],
  ['wimageviewc',['WImageViewC',['http://docs.opencv.org/3.4.0/db/d88/classcv_1_1WImageViewC.html',1,'cv']]],
  ['windowscene',['WindowScene',['http://docs.opencv.org/3.4.0/d5/d68/classcv_1_1ovis_1_1WindowScene.html',1,'cv::ovis']]],
  ['withoutmask',['WithOutMask',['http://docs.opencv.org/3.4.0/da/d2c/structcv_1_1cudev_1_1WithOutMask.html',1,'cv::cudev']]],
  ['wline',['WLine',['http://docs.opencv.org/3.4.0/d6/d8e/classcv_1_1viz_1_1WLine.html',1,'cv::viz']]],
  ['wmesh',['WMesh',['http://docs.opencv.org/3.4.0/d2/d76/classcv_1_1viz_1_1WMesh.html',1,'cv::viz']]],
  ['wobblesuppressorbase',['WobbleSuppressorBase',['http://docs.opencv.org/3.4.0/d8/d16/classcv_1_1videostab_1_1WobbleSuppressorBase.html',1,'cv::videostab']]],
  ['word',['word',['http://docs.opencv.org/3.4.0/d7/d98/structcv_1_1datasets_1_1word.html',1,'cv::datasets']]],
  ['wpaintedcloud',['WPaintedCloud',['http://docs.opencv.org/3.4.0/db/de8/classcv_1_1viz_1_1WPaintedCloud.html',1,'cv::viz']]],
  ['wplane',['WPlane',['http://docs.opencv.org/3.4.0/d8/d01/classcv_1_1viz_1_1WPlane.html',1,'cv::viz']]],
  ['wpolyline',['WPolyLine',['http://docs.opencv.org/3.4.0/de/ddb/classcv_1_1viz_1_1WPolyLine.html',1,'cv::viz']]],
  ['wsphere',['WSphere',['http://docs.opencv.org/3.4.0/d1/da7/classcv_1_1viz_1_1WSphere.html',1,'cv::viz']]],
  ['wstring_5fconvert',['wstring_convert',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a04976.html',1,'std']]],
  ['wtext',['WText',['http://docs.opencv.org/3.4.0/de/d0b/classcv_1_1viz_1_1WText.html',1,'cv::viz']]],
  ['wtext3d',['WText3D',['http://docs.opencv.org/3.4.0/d6/d3d/classcv_1_1viz_1_1WText3D.html',1,'cv::viz']]],
  ['wtrajectory',['WTrajectory',['http://docs.opencv.org/3.4.0/d0/da3/classcv_1_1viz_1_1WTrajectory.html',1,'cv::viz']]],
  ['wtrajectoryfrustums',['WTrajectoryFrustums',['http://docs.opencv.org/3.4.0/da/d80/classcv_1_1viz_1_1WTrajectoryFrustums.html',1,'cv::viz']]],
  ['wtrajectoryspheres',['WTrajectorySpheres',['http://docs.opencv.org/3.4.0/d4/dca/classcv_1_1viz_1_1WTrajectorySpheres.html',1,'cv::viz']]],
  ['wwidgetmerger',['WWidgetMerger',['http://docs.opencv.org/3.4.0/df/d97/classcv_1_1viz_1_1WWidgetMerger.html',1,'cv::viz']]]
];
