var searchData=
[
  ['object',['Object',['http://docs.opencv.org/3.4.0/de/d47/structcv_1_1datasets_1_1Object.html',1,'cv::datasets']]],
  ['objectdetection',['ObjectDetection',['http://docs.opencv.org/3.4.0/d7/de4/structcv_1_1dpm_1_1DPMDetector_1_1ObjectDetection.html',1,'cv::dpm::DPMDetector']]],
  ['objectfactory',['ObjectFactory',['http://docs.opencv.org/3.4.0/df/dd6/classcvflann_1_1ObjectFactory.html',1,'cvflann']]],
  ['objectness',['Objectness',['http://docs.opencv.org/3.4.0/d1/d82/classcv_1_1saliency_1_1Objectness.html',1,'cv::saliency']]],
  ['objectnessbing',['ObjectnessBING',['http://docs.opencv.org/3.4.0/db/d63/classcv_1_1saliency_1_1ObjectnessBING.html',1,'cv::saliency']]],
  ['ocrbeamsearchdecoder',['OCRBeamSearchDecoder',['http://docs.opencv.org/3.4.0/da/d07/classcv_1_1text_1_1OCRBeamSearchDecoder.html',1,'cv::text']]],
  ['ocrhmmdecoder',['OCRHMMDecoder',['http://docs.opencv.org/3.4.0/d0/d74/classcv_1_1text_1_1OCRHMMDecoder.html',1,'cv::text']]],
  ['ocrholisticwordrecognizer',['OCRHolisticWordRecognizer',['http://docs.opencv.org/3.4.0/d0/d8f/classcv_1_1text_1_1OCRHolisticWordRecognizer.html',1,'cv::text']]],
  ['ocrtesseract',['OCRTesseract',['http://docs.opencv.org/3.4.0/d7/ddc/classcv_1_1text_1_1OCRTesseract.html',1,'cv::text']]],
  ['odometry',['Odometry',['http://docs.opencv.org/3.4.0/df/ddc/classcv_1_1rgbd_1_1Odometry.html',1,'cv::rgbd']]],
  ['odometryframe',['OdometryFrame',['http://docs.opencv.org/3.4.0/d7/d15/structcv_1_1rgbd_1_1OdometryFrame.html',1,'cv::rgbd']]],
  ['omp_5floop_5fstatic_5ftag',['omp_loop_static_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08652.html',1,'__gnu_parallel']]],
  ['omp_5floop_5ftag',['omp_loop_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08648.html',1,'__gnu_parallel']]],
  ['once_5fflag',['once_flag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02752.html',1,'std']]],
  ['onepassstabilizer',['OnePassStabilizer',['http://docs.opencv.org/3.4.0/d3/db1/classcv_1_1videostab_1_1OnePassStabilizer.html',1,'cv::videostab']]],
  ['oplandiplparvoparameters',['OPLandIplParvoParameters',['http://docs.opencv.org/3.4.0/d0/dc1/structcv_1_1bioinspired_1_1RetinaParameters_1_1OPLandIplParvoParameters.html',1,'cv::bioinspired::RetinaParameters']]],
  ['opticalflowdual_5ftvl1',['OpticalFlowDual_TVL1',['http://docs.opencv.org/3.4.0/d6/d39/classcv_1_1cuda_1_1OpticalFlowDual__TVL1.html',1,'cv::cuda']]],
  ['opticalflowpcaflow',['OpticalFlowPCAFlow',['http://docs.opencv.org/3.4.0/d1/da2/classcv_1_1optflow_1_1OpticalFlowPCAFlow.html',1,'cv::optflow']]],
  ['optional',['optional',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08988.html',1,'std::experimental::fundamentals_v1']]],
  ['optional_5flock_5fguard',['optional_lock_guard',['http://docs.opencv.org/3.4.0/d3/de8/classcv_1_1utils_1_1optional__lock__guard.html',1,'cv::utils']]],
  ['optional_5fshared_5flock_5fguard',['optional_shared_lock_guard',['http://docs.opencv.org/3.4.0/d2/ddd/classcv_1_1utils_1_1optional__shared__lock__guard.html',1,'cv::utils']]],
  ['or_5fimagenet',['OR_imagenet',['http://docs.opencv.org/3.4.0/db/df7/classcv_1_1datasets_1_1OR__imagenet.html',1,'cv::datasets']]],
  ['or_5fimagenetobj',['OR_imagenetObj',['http://docs.opencv.org/3.4.0/de/d3f/structcv_1_1datasets_1_1OR__imagenetObj.html',1,'cv::datasets']]],
  ['or_5fmnist',['OR_mnist',['http://docs.opencv.org/3.4.0/d9/d92/classcv_1_1datasets_1_1OR__mnist.html',1,'cv::datasets']]],
  ['or_5fmnistobj',['OR_mnistObj',['http://docs.opencv.org/3.4.0/d0/d2c/structcv_1_1datasets_1_1OR__mnistObj.html',1,'cv::datasets']]],
  ['or_5fpascal',['OR_pascal',['http://docs.opencv.org/3.4.0/d4/d7e/classcv_1_1datasets_1_1OR__pascal.html',1,'cv::datasets']]],
  ['or_5fpascalobj',['OR_pascalObj',['http://docs.opencv.org/3.4.0/d0/db6/structcv_1_1datasets_1_1OR__pascalObj.html',1,'cv::datasets']]],
  ['or_5fsun',['OR_sun',['http://docs.opencv.org/3.4.0/da/d69/classcv_1_1datasets_1_1OR__sun.html',1,'cv::datasets']]],
  ['or_5fsunobj',['OR_sunObj',['http://docs.opencv.org/3.4.0/d8/d74/structcv_1_1datasets_1_1OR__sunObj.html',1,'cv::datasets']]],
  ['orb',['ORB',['http://docs.opencv.org/3.4.0/da/d44/classcv_1_1cuda_1_1ORB.html',1,'cv::cuda']]],
  ['orb',['ORB',['http://docs.opencv.org/3.4.0/db/d95/classcv_1_1ORB.html',1,'cv']]],
  ['orbfeaturesfinder',['OrbFeaturesFinder',['http://docs.opencv.org/3.4.0/d7/d59/classcv_1_1detail_1_1OrbFeaturesFinder.html',1,'cv::detail']]],
  ['ostream_5fiterator',['ostream_iterator',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06924.html',1,'std']]],
  ['ostream_5fjoiner',['ostream_joiner',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08956.html',1,'std::experimental::fundamentals_v2']]],
  ['ostreambuf_5fiterator',['ostreambuf_iterator',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02604.html',1,'std']]],
  ['out_5fof_5frange',['out_of_range',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02916.html',1,'std']]],
  ['output_5fiterator_5ftag',['output_iterator_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06656.html',1,'std']]],
  ['ov_5ftree_5fmap',['ov_tree_map',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10792.html',1,'__gnu_pbds::detail']]],
  ['ov_5ftree_5fnode_5fconst_5fit_5f',['ov_tree_node_const_it_',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10784.html',1,'__gnu_pbds::detail']]],
  ['ov_5ftree_5fnode_5fit_5f',['ov_tree_node_it_',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10788.html',1,'__gnu_pbds::detail']]],
  ['ov_5ftree_5ftag',['ov_tree_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10172.html',1,'__gnu_pbds']]],
  ['overflow_5ferror',['overflow_error',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02928.html',1,'std']]],
  ['owner_5fless',['owner_less',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05948.html',1,'std']]],
  ['owner_5fless_3c_20shared_5fptr_3c_20_5ftp_20_3e_20_3e',['owner_less&lt; shared_ptr&lt; _Tp &gt; &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08872.html',1,'std::experimental::fundamentals_v2']]],
  ['owner_5fless_3c_20shared_5fptr_3c_20_5ftp_20_3e_20_3e',['owner_less&lt; shared_ptr&lt; _Tp &gt; &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05956.html',1,'std']]],
  ['owner_5fless_3c_20void_20_3e',['owner_less&lt; void &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05952.html',1,'std']]],
  ['owner_5fless_3c_20weak_5fptr_3c_20_5ftp_20_3e_20_3e',['owner_less&lt; weak_ptr&lt; _Tp &gt; &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08876.html',1,'std::experimental::fundamentals_v2']]],
  ['owner_5fless_3c_20weak_5fptr_3c_20_5ftp_20_3e_20_3e',['owner_less&lt; weak_ptr&lt; _Tp &gt; &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05960.html',1,'std']]]
];
