var searchData=
[
  ['packaged_5ftask_3c_20_5fres_28_5fargtypes_2e_2e_2e_29_3e',['packaged_task&lt; _Res(_ArgTypes...)&gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02512.html',1,'std']]],
  ['paddinglayer',['PaddingLayer',['http://docs.opencv.org/3.4.0/d4/db2/classcv_1_1dnn_1_1PaddingLayer.html',1,'cv::dnn']]],
  ['pair',['pair',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06756.html',1,'std']]],
  ['pair_3c_20_5fbi_5fiter_2c_20_5fbi_5fiter_20_3e',['pair&lt; _Bi_iter, _Bi_iter &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06756.html',1,'']]],
  ['pair_3c_20_5fbiiter_2c_20_5fbiiter_20_3e',['pair&lt; _BiIter, _BiIter &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06756.html',1,'']]],
  ['pair_3c_20_5fiterator1_2c_20_5fiterator2_20_3e',['pair&lt; _Iterator1, _Iterator2 &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06756.html',1,'']]],
  ['pair_3c_20_5fraiter_2c_20_5fraiter_20_3e',['pair&lt; _RAIter, _RAIter &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06756.html',1,'pair&lt; _RAIter, _RAIter &gt;'],['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06756.html',1,'std::pair&lt; _RAIter, _RAIter &gt;']]],
  ['pair_3c_20char_2c_20_5ftokent_20_3e',['pair&lt; char, _TokenT &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06756.html',1,'']]],
  ['pair_3c_20char_2c_20char_20_3e',['pair&lt; char, char &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06756.html',1,'']]],
  ['pair_3c_20entry_5fpointer_2c_20typename_20_5falloc_3a_3asize_5ftype_20_3e',['pair&lt; entry_pointer, typename _Alloc::size_type &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06756.html',1,'']]],
  ['pairing_5fheap',['pairing_heap',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10808.html',1,'__gnu_pbds::detail']]],
  ['pairing_5fheap_5ftag',['pairing_heap_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10192.html',1,'__gnu_pbds']]],
  ['pairwiseseamfinder',['PairwiseSeamFinder',['http://docs.opencv.org/3.4.0/dd/d00/classcv_1_1detail_1_1PairwiseSeamFinder.html',1,'cv::detail']]],
  ['paniniportraitprojector',['PaniniPortraitProjector',['http://docs.opencv.org/3.4.0/d3/dd1/structcv_1_1detail_1_1PaniniPortraitProjector.html',1,'cv::detail']]],
  ['paniniportraitwarper',['PaniniPortraitWarper',['http://docs.opencv.org/3.4.0/d0/d8b/classcv_1_1PaniniPortraitWarper.html',1,'cv']]],
  ['paniniportraitwarper',['PaniniPortraitWarper',['http://docs.opencv.org/3.4.0/db/dad/classcv_1_1detail_1_1PaniniPortraitWarper.html',1,'cv::detail']]],
  ['paniniprojector',['PaniniProjector',['http://docs.opencv.org/3.4.0/d2/df1/structcv_1_1detail_1_1PaniniProjector.html',1,'cv::detail']]],
  ['paniniwarper',['PaniniWarper',['http://docs.opencv.org/3.4.0/dd/db0/classcv_1_1PaniniWarper.html',1,'cv']]],
  ['paniniwarper',['PaniniWarper',['http://docs.opencv.org/3.4.0/db/ddd/classcv_1_1detail_1_1PaniniWarper.html',1,'cv::detail']]],
  ['parallel_5ftag',['parallel_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08632.html',1,'__gnu_parallel']]],
  ['parallelloopbody',['ParallelLoopBody',['http://docs.opencv.org/3.4.0/d2/d74/classcv_1_1ParallelLoopBody.html',1,'cv']]],
  ['param',['Param',['http://docs.opencv.org/3.4.0/de/d95/structcv_1_1Param.html',1,'cv']]],
  ['param_5ftype',['param_type',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05436.html',1,'std::uniform_real_distribution']]],
  ['param_5ftype',['param_type',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05500.html',1,'std::bernoulli_distribution']]],
  ['param_5ftype',['param_type',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05508.html',1,'std::binomial_distribution']]],
  ['param_5ftype',['param_type',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05476.html',1,'std::cauchy_distribution']]],
  ['param_5ftype',['param_type',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05468.html',1,'std::chi_squared_distribution']]],
  ['param_5ftype',['param_type',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05548.html',1,'std::weibull_distribution']]],
  ['param_5ftype',['param_type',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05532.html',1,'std::poisson_distribution']]],
  ['param_5ftype',['param_type',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05564.html',1,'std::discrete_distribution']]],
  ['param_5ftype',['param_type',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05556.html',1,'std::extreme_value_distribution']]],
  ['param_5ftype',['param_type',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05484.html',1,'std::fisher_f_distribution']]],
  ['param_5ftype',['param_type',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05460.html',1,'std::gamma_distribution']]],
  ['param_5ftype',['param_type',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05516.html',1,'std::geometric_distribution']]],
  ['param_5ftype',['param_type',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05492.html',1,'std::student_t_distribution']]],
  ['param_5ftype',['param_type',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05452.html',1,'std::lognormal_distribution']]],
  ['param_5ftype',['param_type',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05580.html',1,'std::piecewise_linear_distribution']]],
  ['param_5ftype',['param_type',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05572.html',1,'std::piecewise_constant_distribution']]],
  ['param_5ftype',['param_type',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06932.html',1,'std::uniform_int_distribution']]],
  ['param_5ftype',['param_type',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05524.html',1,'std::negative_binomial_distribution']]],
  ['param_5ftype',['param_type',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05540.html',1,'std::exponential_distribution']]],
  ['param_5ftype',['param_type',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05444.html',1,'std::normal_distribution']]],
  ['paramgrid',['ParamGrid',['http://docs.opencv.org/3.4.0/d6/dca/classcv_1_1ml_1_1ParamGrid.html',1,'cv::ml']]],
  ['params',['Params',['http://docs.opencv.org/3.4.0/df/d68/structcv_1_1face_1_1FacemarkAAM_1_1Params.html',1,'cv::face::FacemarkAAM']]],
  ['params',['Params',['http://docs.opencv.org/3.4.0/da/dae/structcv_1_1TrackerMIL_1_1Params.html',1,'cv::TrackerMIL']]],
  ['params',['Params',['http://docs.opencv.org/3.4.0/d6/dad/structcv_1_1ClfMilBoost_1_1Params.html',1,'cv::ClfMilBoost']]],
  ['params',['Params',['http://docs.opencv.org/3.4.0/d3/dfb/structcv_1_1TrackerSamplerCSC_1_1Params.html',1,'cv::TrackerSamplerCSC']]],
  ['params',['Params',['http://docs.opencv.org/3.4.0/de/d46/structcv_1_1TrackerSamplerPF_1_1Params.html',1,'cv::TrackerSamplerPF']]],
  ['params',['Params',['http://docs.opencv.org/3.4.0/dd/dd9/structcv_1_1TrackerMedianFlow_1_1Params.html',1,'cv::TrackerMedianFlow']]],
  ['params',['Params',['http://docs.opencv.org/3.4.0/d3/dd0/structcv_1_1TrackerTLD_1_1Params.html',1,'cv::TrackerTLD']]],
  ['params',['Params',['http://docs.opencv.org/3.4.0/d8/da7/structcv_1_1SimpleBlobDetector_1_1Params.html',1,'cv::SimpleBlobDetector']]],
  ['params',['Params',['http://docs.opencv.org/3.4.0/dc/d12/structcv_1_1TrackerGOTURN_1_1Params.html',1,'cv::TrackerGOTURN']]],
  ['params',['Params',['http://docs.opencv.org/3.4.0/d6/d86/structcv_1_1phase__unwrapping_1_1HistogramPhaseUnwrapping_1_1Params.html',1,'cv::phase_unwrapping::HistogramPhaseUnwrapping']]],
  ['params',['Params',['http://docs.opencv.org/3.4.0/db/dd1/structcv_1_1TrackerKCF_1_1Params.html',1,'cv::TrackerKCF']]],
  ['params',['Params',['http://docs.opencv.org/3.4.0/d4/d12/structcv_1_1face_1_1FacemarkLBF_1_1Params.html',1,'cv::face::FacemarkLBF']]],
  ['params',['Params',['http://docs.opencv.org/3.4.0/df/d21/structcv_1_1structured__light_1_1SinusoidalPattern_1_1Params.html',1,'cv::structured_light::SinusoidalPattern']]],
  ['params',['Params',['http://docs.opencv.org/3.4.0/d5/d6d/structcv_1_1TrackerSamplerCS_1_1Params.html',1,'cv::TrackerSamplerCS']]],
  ['params',['Params',['http://docs.opencv.org/3.4.0/d1/d00/structcv_1_1TrackerFeatureHAAR_1_1Params.html',1,'cv::TrackerFeatureHAAR']]],
  ['params',['Params',['http://docs.opencv.org/3.4.0/dc/daf/structcv_1_1TrackerBoosting_1_1Params.html',1,'cv::TrackerBoosting']]],
  ['params',['Params',['http://docs.opencv.org/3.4.0/d0/d8c/structcv_1_1face_1_1FacemarkKazemi_1_1Params.html',1,'cv::face::FacemarkKazemi']]],
  ['params',['Params',['http://docs.opencv.org/3.4.0/d3/d4d/structcv_1_1structured__light_1_1GrayCodePattern_1_1Params.html',1,'cv::structured_light::GrayCodePattern']]],
  ['params',['Params',['http://docs.opencv.org/3.4.0/d9/d85/structcv_1_1line__descriptor_1_1BinaryDescriptor_1_1Params.html',1,'cv::line_descriptor::BinaryDescriptor']]],
  ['paramtype',['ParamType',['http://docs.opencv.org/3.4.0/dd/d77/structcv_1_1ParamType.html',1,'cv']]],
  ['paramtype_3c_20algorithm_20_3e',['ParamType&lt; Algorithm &gt;',['http://docs.opencv.org/3.4.0/d2/d39/structcv_1_1ParamType_3_01Algorithm_01_4.html',1,'cv']]],
  ['paramtype_3c_20bool_20_3e',['ParamType&lt; bool &gt;',['http://docs.opencv.org/3.4.0/d1/d87/structcv_1_1ParamType_3_01bool_01_4.html',1,'cv']]],
  ['paramtype_3c_20double_20_3e',['ParamType&lt; double &gt;',['http://docs.opencv.org/3.4.0/d4/d98/structcv_1_1ParamType_3_01double_01_4.html',1,'cv']]],
  ['paramtype_3c_20float_20_3e',['ParamType&lt; float &gt;',['http://docs.opencv.org/3.4.0/dd/df2/structcv_1_1ParamType_3_01float_01_4.html',1,'cv']]],
  ['paramtype_3c_20mat_20_3e',['ParamType&lt; Mat &gt;',['http://docs.opencv.org/3.4.0/db/d5f/structcv_1_1ParamType_3_01Mat_01_4.html',1,'cv']]],
  ['paramtype_3c_20std_3a_3avector_3c_20mat_20_3e_20_3e',['ParamType&lt; std::vector&lt; Mat &gt; &gt;',['http://docs.opencv.org/3.4.0/dc/d1c/structcv_1_1ParamType_3_01std_1_1vector_3_01Mat_01_4_01_4.html',1,'cv']]],
  ['paramtype_3c_20string_20_3e',['ParamType&lt; String &gt;',['http://docs.opencv.org/3.4.0/d0/d5f/structcv_1_1ParamType_3_01String_01_4.html',1,'cv']]],
  ['paramtype_3c_20uchar_20_3e',['ParamType&lt; uchar &gt;',['http://docs.opencv.org/3.4.0/d3/da3/structcv_1_1ParamType_3_01uchar_01_4.html',1,'cv']]],
  ['paramtype_3c_20uint64_20_3e',['ParamType&lt; uint64 &gt;',['http://docs.opencv.org/3.4.0/dc/d63/structcv_1_1ParamType_3_01uint64_01_4.html',1,'cv']]],
  ['paramtype_3c_20unsigned_20_3e',['ParamType&lt; unsigned &gt;',['http://docs.opencv.org/3.4.0/d7/d68/structcv_1_1ParamType_3_01unsigned_01_4.html',1,'cv']]],
  ['pascalobj',['PascalObj',['http://docs.opencv.org/3.4.0/de/d1c/structcv_1_1datasets_1_1PascalObj.html',1,'cv::datasets']]],
  ['pascalpart',['PascalPart',['http://docs.opencv.org/3.4.0/d6/d4e/structcv_1_1datasets_1_1PascalPart.html',1,'cv::datasets']]],
  ['pat_5ftrie_5fbase',['pat_trie_base',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10824.html',1,'__gnu_pbds::detail']]],
  ['pat_5ftrie_5fmap',['pat_trie_map',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10812.html',1,'__gnu_pbds::detail']]],
  ['pat_5ftrie_5ftag',['pat_trie_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10180.html',1,'__gnu_pbds']]],
  ['path',['path',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08784.html',1,'std::experimental::filesystem::v1']]],
  ['pca',['PCA',['http://docs.opencv.org/3.4.0/d3/d8d/classcv_1_1PCA.html',1,'cv']]],
  ['pcaprior',['PCAPrior',['http://docs.opencv.org/3.4.0/d5/d5e/classcv_1_1optflow_1_1PCAPrior.html',1,'cv::optflow']]],
  ['pctsignatures',['PCTSignatures',['http://docs.opencv.org/3.4.0/d0/d74/classcv_1_1xfeatures2d_1_1PCTSignatures.html',1,'cv::xfeatures2d']]],
  ['pctsignaturessqfd',['PCTSignaturesSQFD',['http://docs.opencv.org/3.4.0/d4/dd1/classcv_1_1xfeatures2d_1_1PCTSignaturesSQFD.html',1,'cv::xfeatures2d']]],
  ['pd_5fcaltech',['PD_caltech',['http://docs.opencv.org/3.4.0/da/d8d/classcv_1_1datasets_1_1PD__caltech.html',1,'cv::datasets']]],
  ['pd_5fcaltechobj',['PD_caltechObj',['http://docs.opencv.org/3.4.0/dd/ded/structcv_1_1datasets_1_1PD__caltechObj.html',1,'cv::datasets']]],
  ['pd_5finria',['PD_inria',['http://docs.opencv.org/3.4.0/d2/d61/classcv_1_1datasets_1_1PD__inria.html',1,'cv::datasets']]],
  ['pd_5finriaobj',['PD_inriaObj',['http://docs.opencv.org/3.4.0/db/d88/structcv_1_1datasets_1_1PD__inriaObj.html',1,'cv::datasets']]],
  ['permutelayer',['PermuteLayer',['http://docs.opencv.org/3.4.0/d2/d3c/classcv_1_1dnn_1_1PermuteLayer.html',1,'cv::dnn']]],
  ['perspectivemapptr',['PerspectiveMapPtr',['http://docs.opencv.org/3.4.0/df/d20/structcv_1_1cudev_1_1PerspectiveMapPtr.html',1,'cv::cudev']]],
  ['perspectivemapptrsz',['PerspectiveMapPtrSz',['http://docs.opencv.org/3.4.0/de/d6d/structcv_1_1cudev_1_1PerspectiveMapPtrSz.html',1,'cv::cudev']]],
  ['phaseunwrapping',['PhaseUnwrapping',['http://docs.opencv.org/3.4.0/d8/d83/classcv_1_1phase__unwrapping_1_1PhaseUnwrapping.html',1,'cv::phase_unwrapping']]],
  ['phash',['PHash',['http://docs.opencv.org/3.4.0/df/d4e/classcv_1_1img__hash_1_1PHash.html',1,'cv::img_hash']]],
  ['piecewise_5fconstant_5fdistribution',['piecewise_constant_distribution',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05568.html',1,'std']]],
  ['piecewise_5fconstruct_5ft',['piecewise_construct_t',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06740.html',1,'std']]],
  ['piecewise_5flinear_5fdistribution',['piecewise_linear_distribution',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05576.html',1,'std']]],
  ['pipeline',['Pipeline',['../classgaze_1_1_pipeline.html',1,'gaze']]],
  ['pipelinestep',['PipelineStep',['../classgaze_1_1_pipeline_step.html',1,'gaze']]],
  ['planeportraitprojector',['PlanePortraitProjector',['http://docs.opencv.org/3.4.0/df/d0d/structcv_1_1detail_1_1PlanePortraitProjector.html',1,'cv::detail']]],
  ['planeportraitwarper',['PlanePortraitWarper',['http://docs.opencv.org/3.4.0/d9/d77/classcv_1_1detail_1_1PlanePortraitWarper.html',1,'cv::detail']]],
  ['planeprojector',['PlaneProjector',['http://docs.opencv.org/3.4.0/d6/d1f/structcv_1_1detail_1_1PlaneProjector.html',1,'cv::detail']]],
  ['planewarper',['PlaneWarper',['http://docs.opencv.org/3.4.0/d3/d3d/classcv_1_1detail_1_1PlaneWarper.html',1,'cv::detail']]],
  ['planewarper',['PlaneWarper',['http://docs.opencv.org/3.4.0/d0/d57/classcv_1_1PlaneWarper.html',1,'cv']]],
  ['planewarpergpu',['PlaneWarperGpu',['http://docs.opencv.org/3.4.0/d2/d1a/classcv_1_1detail_1_1PlaneWarperGpu.html',1,'cv::detail']]],
  ['platform',['Platform',['http://docs.opencv.org/3.4.0/d8/d87/classcv_1_1ocl_1_1Platform.html',1,'cv::ocl']]],
  ['platforminfo',['PlatformInfo',['http://docs.opencv.org/3.4.0/d6/d94/classcv_1_1ocl_1_1PlatformInfo.html',1,'cv::ocl']]],
  ['plot2d',['Plot2d',['http://docs.opencv.org/3.4.0/d0/d1e/classcv_1_1plot_1_1Plot2d.html',1,'cv::plot']]],
  ['plus',['plus',['http://docs.opencv.org/3.4.0/d4/dd0/structcv_1_1cudev_1_1plus.html',1,'cv::cudev']]],
  ['plus',['plus',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06400.html',1,'std']]],
  ['point3_5f',['Point3_',['http://docs.opencv.org/3.4.0/df/d6c/classcv_1_1Point3__.html',1,'cv']]],
  ['point_5f',['Point_',['http://docs.opencv.org/3.4.0/db/d4e/classcv_1_1Point__.html',1,'cv']]],
  ['point_5f_3c_20double_20_3e',['Point_&lt; double &gt;',['http://docs.opencv.org/3.4.0/db/d4e/classcv_1_1Point__.html',1,'']]],
  ['point_5f_3c_20float_20_3e',['Point_&lt; float &gt;',['http://docs.opencv.org/3.4.0/db/d4e/classcv_1_1Point__.html',1,'Point_&lt; float &gt;'],['http://docs.opencv.org/3.4.0/db/d4e/classcv_1_1Point__.html',1,'cv::Point_&lt; float &gt;']]],
  ['point_5f_3c_20int_20_3e',['Point_&lt; int &gt;',['http://docs.opencv.org/3.4.0/db/d4e/classcv_1_1Point__.html',1,'']]],
  ['point_5fconst_5fiterator_5f',['point_const_iterator_',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a11020.html',1,'']]],
  ['point_5finvalidation_5fguarantee',['point_invalidation_guarantee',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10120.html',1,'__gnu_pbds']]],
  ['point_5fiterator_5f',['point_iterator_',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a11024.html',1,'']]],
  ['pointer_5fto_5fbinary_5ffunction',['pointer_to_binary_function',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06564.html',1,'std']]],
  ['pointer_5fto_5funary_5ffunction',['pointer_to_unary_function',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06560.html',1,'std']]],
  ['pointer_5ftraits',['pointer_traits',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05380.html',1,'std']]],
  ['pointer_5ftraits_3c_20_5ftp_20_2a_20_3e',['pointer_traits&lt; _Tp * &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05392.html',1,'std']]],
  ['poisson_5fdistribution',['poisson_distribution',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05528.html',1,'std']]],
  ['pooledallocator',['PooledAllocator',['http://docs.opencv.org/3.4.0/d9/d03/classcvflann_1_1PooledAllocator.html',1,'cvflann']]],
  ['poolinglayer',['PoolingLayer',['http://docs.opencv.org/3.4.0/de/d7d/classcv_1_1dnn_1_1PoolingLayer.html',1,'cv::dnn']]],
  ['pose',['pose',['http://docs.opencv.org/3.4.0/dd/dbd/structcv_1_1datasets_1_1pose.html',1,'cv::datasets']]],
  ['pose3d',['Pose3D',['http://docs.opencv.org/3.4.0/d5/d22/classcv_1_1ppf__match__3d_1_1Pose3D.html',1,'cv::ppf_match_3d']]],
  ['posecluster3d',['PoseCluster3D',['http://docs.opencv.org/3.4.0/d2/d4b/classcv_1_1ppf__match__3d_1_1PoseCluster3D.html',1,'cv::ppf_match_3d']]],
  ['pow_5ffunc',['pow_func',['http://docs.opencv.org/3.4.0/da/dda/structcv_1_1cudev_1_1pow__func.html',1,'cv::cudev']]],
  ['pow_5ffunc_3c_20double_20_3e',['pow_func&lt; double &gt;',['http://docs.opencv.org/3.4.0/d2/deb/structcv_1_1cudev_1_1pow__func_3_01double_01_4.html',1,'cv::cudev']]],
  ['powerlayer',['PowerLayer',['http://docs.opencv.org/3.4.0/d2/da0/classcv_1_1dnn_1_1PowerLayer.html',1,'cv::dnn']]],
  ['ppf3ddetector',['PPF3DDetector',['http://docs.opencv.org/3.4.0/db/d25/classcv_1_1ppf__match__3d_1_1PPF3DDetector.html',1,'cv::ppf_match_3d']]],
  ['predictcollector',['PredictCollector',['http://docs.opencv.org/3.4.0/da/d6a/classcv_1_1face_1_1PredictCollector.html',1,'cv::face']]],
  ['predictresult',['PredictResult',['http://docs.opencv.org/3.4.0/d2/d5a/structcv_1_1face_1_1StandardCollector_1_1PredictResult.html',1,'cv::face::StandardCollector']]],
  ['priorboxlayer',['PriorBoxLayer',['http://docs.opencv.org/3.4.0/da/d1e/classcv_1_1dnn_1_1PriorBoxLayer.html',1,'cv::dnn']]],
  ['priority_5fqueue',['priority_queue',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10108.html',1,'__gnu_pbds']]],
  ['priority_5fqueue',['priority_queue',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06768.html',1,'std']]],
  ['priority_5fqueue_5ftag',['priority_queue_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10188.html',1,'__gnu_pbds']]],
  ['probe_5ffn_5fbase',['probe_fn_base',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10664.html',1,'__gnu_pbds::detail']]],
  ['program',['Program',['http://docs.opencv.org/3.4.0/d2/d88/classcv_1_1ocl_1_1Program.html',1,'cv::ocl']]],
  ['programsource',['ProgramSource',['http://docs.opencv.org/3.4.0/d5/de3/classcv_1_1ocl_1_1ProgramSource.html',1,'cv::ocl']]],
  ['project1st',['project1st',['http://docs.opencv.org/3.4.0/d3/dea/structcv_1_1cudev_1_1project1st.html',1,'cv::cudev']]],
  ['project1st',['project1st',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08112.html',1,'__gnu_cxx']]],
  ['project2nd',['project2nd',['http://docs.opencv.org/3.4.0/d2/dd5/structcv_1_1cudev_1_1project2nd.html',1,'cv::cudev']]],
  ['project2nd',['project2nd',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08116.html',1,'__gnu_cxx']]],
  ['projectorbase',['ProjectorBase',['http://docs.opencv.org/3.4.0/dc/d2c/structcv_1_1detail_1_1ProjectorBase.html',1,'cv::detail']]],
  ['promise',['promise',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02360.html',1,'std']]],
  ['promise_3c_20_5fres_20_26_20_3e',['promise&lt; _Res &amp; &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02480.html',1,'std']]],
  ['promise_3c_20void_20_3e',['promise&lt; void &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02484.html',1,'std']]],
  ['propagate_5fconst',['propagate_const',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09052.html',1,'std::experimental::fundamentals_v2']]],
  ['proposallayer',['ProposalLayer',['http://docs.opencv.org/3.4.0/da/d6b/classcv_1_1dnn_1_1ProposalLayer.html',1,'cv::dnn']]],
  ['ptr',['Ptr',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'cv']]],
  ['ptr_3c_20bitarray_20_3e',['Ptr&lt; bitarray &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'']]],
  ['ptr_3c_20const_20cv_3a_3aoptflow_3a_3apcaprior_20_3e',['Ptr&lt; const cv::optflow::PCAPrior &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'cv::Ptr&lt; const cv::optflow::PCAPrior &gt;'],['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'Ptr&lt; const cv::optflow::PCAPrior &gt;']]],
  ['ptr_3c_20cv_3a_3aakaze_20_3e',['Ptr&lt; cv::AKAZE &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'']]],
  ['ptr_3c_20cv_3a_3aaruco_3a_3adictionary_20_3e',['Ptr&lt; cv::aruco::Dictionary &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'cv::Ptr&lt; cv::aruco::Dictionary &gt;'],['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'Ptr&lt; cv::aruco::Dictionary &gt;']]],
  ['ptr_3c_20cv_3a_3abasecascadeclassifier_20_3e',['Ptr&lt; cv::BaseCascadeClassifier &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'Ptr&lt; cv::BaseCascadeClassifier &gt;'],['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'cv::Ptr&lt; cv::BaseCascadeClassifier &gt;']]],
  ['ptr_3c_20cv_3a_3acuda_3a_3agpumat_3a_3acv_3a_3aallocator_20_3e',['Ptr&lt; cv::cuda::GpuMat::cv::Allocator &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'']]],
  ['ptr_3c_20cv_3a_3acvhaarevaluator_20_3e',['Ptr&lt; cv::CvHaarEvaluator &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'']]],
  ['ptr_3c_20cv_3a_3adatasets_3a_3aobject_20_3e',['Ptr&lt; cv::datasets::Object &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'']]],
  ['ptr_3c_20cv_3a_3adescriptormatcher_20_3e',['Ptr&lt; cv::DescriptorMatcher &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'Ptr&lt; cv::DescriptorMatcher &gt;'],['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'cv::Ptr&lt; cv::DescriptorMatcher &gt;']]],
  ['ptr_3c_20cv_3a_3adetail_3a_3afeaturesmatcher_20_3e',['Ptr&lt; cv::detail::FeaturesMatcher &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'cv::Ptr&lt; cv::detail::FeaturesMatcher &gt;'],['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'Ptr&lt; cv::detail::FeaturesMatcher &gt;']]],
  ['ptr_3c_20cv_3a_3adetail_3a_3apairwiseseamfinder_20_3e',['Ptr&lt; cv::detail::PairwiseSeamFinder &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'']]],
  ['ptr_3c_20cv_3a_3afeature2d_20_3e',['Ptr&lt; cv::Feature2D &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'cv::Ptr&lt; cv::Feature2D &gt;'],['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'Ptr&lt; cv::Feature2D &gt;']]],
  ['ptr_3c_20cv_3a_3alinemod_3a_3amodality_20_3e',['Ptr&lt; cv::linemod::Modality &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'']]],
  ['ptr_3c_20cv_3a_3amat_20_3e',['Ptr&lt; cv::Mat &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'']]],
  ['ptr_3c_20cv_3a_3aminproblemsolver_20_3e',['Ptr&lt; cv::MinProblemSolver &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'']]],
  ['ptr_3c_20cv_3a_3aminproblemsolver_3a_3afunction_20_3e',['Ptr&lt; cv::MinProblemSolver::Function &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'']]],
  ['ptr_3c_20cv_3a_3aorb_20_3e',['Ptr&lt; cv::ORB &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'']]],
  ['ptr_3c_20cv_3a_3argbd_3a_3argbdnormals_20_3e',['Ptr&lt; cv::rgbd::RgbdNormals &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'cv::Ptr&lt; cv::rgbd::RgbdNormals &gt;'],['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'Ptr&lt; cv::rgbd::RgbdNormals &gt;']]],
  ['ptr_3c_20cv_3a_3astrongclassifierdirectselection_20_3e',['Ptr&lt; cv::StrongClassifierDirectSelection &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'Ptr&lt; cv::StrongClassifierDirectSelection &gt;'],['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'cv::Ptr&lt; cv::StrongClassifierDirectSelection &gt;']]],
  ['ptr_3c_20cv_3a_3asuperres_3a_3aframesource_20_3e',['Ptr&lt; cv::superres::FrameSource &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'']]],
  ['ptr_3c_20cv_3a_3atext_3a_3aocrbeamsearchdecoder_3a_3aclassifiercallback_20_3e',['Ptr&lt; cv::text::OCRBeamSearchDecoder::ClassifierCallback &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'cv']]],
  ['ptr_3c_20cv_3a_3atext_3a_3aocrbeamsearchdecoder_3a_3acv_3a_3atext_3a_3aocrbeamsearchdecoder_3a_3aclassifiercallback_20_3e',['Ptr&lt; cv::text::OCRBeamSearchDecoder::cv::text::OCRBeamSearchDecoder::ClassifierCallback &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'']]],
  ['ptr_3c_20cv_3a_3atext_3a_3aocrhmmdecoder_3a_3aclassifiercallback_20_3e',['Ptr&lt; cv::text::OCRHMMDecoder::ClassifierCallback &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'cv']]],
  ['ptr_3c_20cv_3a_3atext_3a_3aocrhmmdecoder_3a_3acv_3a_3atext_3a_3aocrhmmdecoder_3a_3aclassifiercallback_20_3e',['Ptr&lt; cv::text::OCRHMMDecoder::cv::text::OCRHMMDecoder::ClassifierCallback &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'']]],
  ['ptr_3c_20cv_3a_3atracker_20_3e',['Ptr&lt; cv::Tracker &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'']]],
  ['ptr_3c_20cv_3a_3atrackerfeatureset_20_3e',['Ptr&lt; cv::TrackerFeatureSet &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'cv::Ptr&lt; cv::TrackerFeatureSet &gt;'],['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'Ptr&lt; cv::TrackerFeatureSet &gt;']]],
  ['ptr_3c_20cv_3a_3atrackermodel_20_3e',['Ptr&lt; cv::TrackerModel &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'Ptr&lt; cv::TrackerModel &gt;'],['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'cv::Ptr&lt; cv::TrackerModel &gt;']]],
  ['ptr_3c_20cv_3a_3atrackersampler_20_3e',['Ptr&lt; cv::TrackerSampler &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'Ptr&lt; cv::TrackerSampler &gt;'],['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'cv::Ptr&lt; cv::TrackerSampler &gt;']]],
  ['ptr_3c_20cv_3a_3atrackerstateestimator_20_3e',['Ptr&lt; cv::TrackerStateEstimator &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'Ptr&lt; cv::TrackerStateEstimator &gt;'],['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'cv::Ptr&lt; cv::TrackerStateEstimator &gt;']]],
  ['ptr_3c_20cv_3a_3atracking_3a_3aukfsystemmodel_20_3e',['Ptr&lt; cv::tracking::UkfSystemModel &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'Ptr&lt; cv::tracking::UkfSystemModel &gt;'],['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'cv::Ptr&lt; cv::tracking::UkfSystemModel &gt;']]],
  ['ptr_3c_20cv_3a_3avideostab_3a_3adeblurerbase_20_3e',['Ptr&lt; cv::videostab::DeblurerBase &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'cv::Ptr&lt; cv::videostab::DeblurerBase &gt;'],['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'Ptr&lt; cv::videostab::DeblurerBase &gt;']]],
  ['ptr_3c_20cv_3a_3avideostab_3a_3aidenseoptflowestimator_20_3e',['Ptr&lt; cv::videostab::IDenseOptFlowEstimator &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'']]],
  ['ptr_3c_20cv_3a_3avideostab_3a_3aiframesource_20_3e',['Ptr&lt; cv::videostab::IFrameSource &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'cv::Ptr&lt; cv::videostab::IFrameSource &gt;'],['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'Ptr&lt; cv::videostab::IFrameSource &gt;']]],
  ['ptr_3c_20cv_3a_3avideostab_3a_3ailog_20_3e',['Ptr&lt; cv::videostab::ILog &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'Ptr&lt; cv::videostab::ILog &gt;'],['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'cv::Ptr&lt; cv::videostab::ILog &gt;']]],
  ['ptr_3c_20cv_3a_3avideostab_3a_3aimagemotionestimatorbase_20_3e',['Ptr&lt; cv::videostab::ImageMotionEstimatorBase &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'Ptr&lt; cv::videostab::ImageMotionEstimatorBase &gt;'],['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'cv::Ptr&lt; cv::videostab::ImageMotionEstimatorBase &gt;']]],
  ['ptr_3c_20cv_3a_3avideostab_3a_3aimotionstabilizer_20_3e',['Ptr&lt; cv::videostab::IMotionStabilizer &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'Ptr&lt; cv::videostab::IMotionStabilizer &gt;'],['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'cv::Ptr&lt; cv::videostab::IMotionStabilizer &gt;']]],
  ['ptr_3c_20cv_3a_3avideostab_3a_3ainpainterbase_20_3e',['Ptr&lt; cv::videostab::InpainterBase &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'cv::Ptr&lt; cv::videostab::InpainterBase &gt;'],['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'Ptr&lt; cv::videostab::InpainterBase &gt;']]],
  ['ptr_3c_20cv_3a_3avideostab_3a_3aioutlierrejector_20_3e',['Ptr&lt; cv::videostab::IOutlierRejector &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'']]],
  ['ptr_3c_20cv_3a_3avideostab_3a_3aisparseoptflowestimator_20_3e',['Ptr&lt; cv::videostab::ISparseOptFlowEstimator &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'']]],
  ['ptr_3c_20cv_3a_3avideostab_3a_3amotionestimatorbase_20_3e',['Ptr&lt; cv::videostab::MotionEstimatorBase &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'']]],
  ['ptr_3c_20cv_3a_3avideostab_3a_3amotionfilterbase_20_3e',['Ptr&lt; cv::videostab::MotionFilterBase &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'cv::Ptr&lt; cv::videostab::MotionFilterBase &gt;'],['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'Ptr&lt; cv::videostab::MotionFilterBase &gt;']]],
  ['ptr_3c_20cv_3a_3avideostab_3a_3awobblesuppressorbase_20_3e',['Ptr&lt; cv::videostab::WobbleSuppressorBase &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'cv::Ptr&lt; cv::videostab::WobbleSuppressorBase &gt;'],['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'Ptr&lt; cv::videostab::WobbleSuppressorBase &gt;']]],
  ['ptr_3c_20cv_3a_3awarpercreator_20_3e',['Ptr&lt; cv::WarperCreator &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'']]],
  ['ptr_3c_20cvcapture_20_3e',['Ptr&lt; CvCapture &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'Ptr&lt; CvCapture &gt;'],['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'cv::Ptr&lt; CvCapture &gt;']]],
  ['ptr_3c_20cvfilestorage_20_3e',['Ptr&lt; CvFileStorage &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'Ptr&lt; CvFileStorage &gt;'],['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'cv::Ptr&lt; CvFileStorage &gt;']]],
  ['ptr_3c_20cvmat_20_3e',['Ptr&lt; CvMat &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'Ptr&lt; CvMat &gt;'],['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'cv::Ptr&lt; CvMat &gt;']]],
  ['ptr_3c_20cvvideowriter_20_3e',['Ptr&lt; CvVideoWriter &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'cv::Ptr&lt; CvVideoWriter &gt;'],['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'Ptr&lt; CvVideoWriter &gt;']]],
  ['ptr_3c_20detail_3a_3ablender_20_3e',['Ptr&lt; detail::Blender &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'']]],
  ['ptr_3c_20detail_3a_3abundleadjusterbase_20_3e',['Ptr&lt; detail::BundleAdjusterBase &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'']]],
  ['ptr_3c_20detail_3a_3aexposurecompensator_20_3e',['Ptr&lt; detail::ExposureCompensator &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'']]],
  ['ptr_3c_20detail_3a_3afeaturesfinder_20_3e',['Ptr&lt; detail::FeaturesFinder &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'']]],
  ['ptr_3c_20detail_3a_3afeaturesmatcher_20_3e',['Ptr&lt; detail::FeaturesMatcher &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'']]],
  ['ptr_3c_20detail_3a_3aseamfinder_20_3e',['Ptr&lt; detail::SeamFinder &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'']]],
  ['ptr_3c_20edlinedetector_20_3e',['Ptr&lt; EDLineDetector &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'']]],
  ['ptr_3c_20flann_3a_3aindex_20_3e',['Ptr&lt; flann::Index &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'Ptr&lt; flann::Index &gt;'],['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'cv::Ptr&lt; flann::Index &gt;']]],
  ['ptr_3c_20flann_3a_3aindexparams_20_3e',['Ptr&lt; flann::IndexParams &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'']]],
  ['ptr_3c_20flann_3a_3asearchparams_20_3e',['Ptr&lt; flann::SearchParams &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'Ptr&lt; flann::SearchParams &gt;'],['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'cv::Ptr&lt; flann::SearchParams &gt;']]],
  ['ptr_3c_20flann_3a_3astd_3a_3amap_20_3e',['Ptr&lt; flann::std::map &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'cv']]],
  ['ptr_3c_20imghashimpl_20_3e',['Ptr&lt; ImgHashImpl &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'cv::Ptr&lt; ImgHashImpl &gt;'],['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'Ptr&lt; ImgHashImpl &gt;']]],
  ['ptr_3c_20impl_20_3e',['Ptr&lt; Impl &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'']]],
  ['ptr_3c_20ivideocapture_20_3e',['Ptr&lt; IVideoCapture &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'Ptr&lt; IVideoCapture &gt;'],['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'cv::Ptr&lt; IVideoCapture &gt;']]],
  ['ptr_3c_20ivideowriter_20_3e',['Ptr&lt; IVideoWriter &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'cv::Ptr&lt; IVideoWriter &gt;'],['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'Ptr&lt; IVideoWriter &gt;']]],
  ['ptr_3c_20mihasher_20_3e',['Ptr&lt; Mihasher &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'']]],
  ['ptr_3c_20std_3a_3adeque_3c_20int_20_3e_20_3e',['Ptr&lt; std::deque&lt; int &gt; &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'Ptr&lt; std::deque&lt; int &gt; &gt;'],['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'cv::Ptr&lt; std::deque&lt; int &gt; &gt;']]],
  ['ptr_3c_20trackertargetstate_20_3e',['Ptr&lt; TrackerTargetState &gt;',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1Ptr.html',1,'']]],
  ['ptrtraits',['PtrTraits',['http://docs.opencv.org/3.4.0/d2/d1a/structcv_1_1cudev_1_1PtrTraits.html',1,'cv::cudev']]],
  ['ptrtraits_3c_20affinemapptrsz_20_3e',['PtrTraits&lt; AffineMapPtrSz &gt;',['http://docs.opencv.org/3.4.0/d5/d59/structcv_1_1cudev_1_1PtrTraits_3_01AffineMapPtrSz_01_4.html',1,'cv::cudev']]],
  ['ptrtraits_3c_20binarytransformptrsz_3c_20src1ptr_2c_20src2ptr_2c_20op_20_3e_20_3e',['PtrTraits&lt; BinaryTransformPtrSz&lt; Src1Ptr, Src2Ptr, Op &gt; &gt;',['http://docs.opencv.org/3.4.0/db/d13/structcv_1_1cudev_1_1PtrTraits_3_01BinaryTransformPtrSz_3_01Src1Ptr_00_01Src2Ptr_00_01Op_01_4_01_4.html',1,'cv::cudev']]],
  ['ptrtraits_3c_20commonareainterptrsz_3c_20srcptr_20_3e_20_3e',['PtrTraits&lt; CommonAreaInterPtrSz&lt; SrcPtr &gt; &gt;',['http://docs.opencv.org/3.4.0/d8/da8/structcv_1_1cudev_1_1PtrTraits_3_01CommonAreaInterPtrSz_3_01SrcPtr_01_4_01_4.html',1,'cv::cudev']]],
  ['ptrtraits_3c_20constantptrsz_3c_20t_20_3e_20_3e',['PtrTraits&lt; ConstantPtrSz&lt; T &gt; &gt;',['http://docs.opencv.org/3.4.0/d3/d15/structcv_1_1cudev_1_1PtrTraits_3_01ConstantPtrSz_3_01T_01_4_01_4.html',1,'cv::cudev']]],
  ['ptrtraits_3c_20cubicinterptrsz_3c_20srcptr_20_3e_20_3e',['PtrTraits&lt; CubicInterPtrSz&lt; SrcPtr &gt; &gt;',['http://docs.opencv.org/3.4.0/d1/d45/structcv_1_1cudev_1_1PtrTraits_3_01CubicInterPtrSz_3_01SrcPtr_01_4_01_4.html',1,'cv::cudev']]],
  ['ptrtraits_3c_20derivxptrsz_3c_20srcptr_20_3e_20_3e',['PtrTraits&lt; DerivXPtrSz&lt; SrcPtr &gt; &gt;',['http://docs.opencv.org/3.4.0/d3/d89/structcv_1_1cudev_1_1PtrTraits_3_01DerivXPtrSz_3_01SrcPtr_01_4_01_4.html',1,'cv::cudev']]],
  ['ptrtraits_3c_20derivyptrsz_3c_20srcptr_20_3e_20_3e',['PtrTraits&lt; DerivYPtrSz&lt; SrcPtr &gt; &gt;',['http://docs.opencv.org/3.4.0/d0/ddb/structcv_1_1cudev_1_1PtrTraits_3_01DerivYPtrSz_3_01SrcPtr_01_4_01_4.html',1,'cv::cudev']]],
  ['ptrtraits_3c_20expr_3c_20body_20_3e_20_3e',['PtrTraits&lt; Expr&lt; Body &gt; &gt;',['http://docs.opencv.org/3.4.0/df/db4/structcv_1_1cudev_1_1PtrTraits_3_01Expr_3_01Body_01_4_01_4.html',1,'cv::cudev']]],
  ['ptrtraits_3c_20globptrsz_3c_20t_20_3e_20_3e',['PtrTraits&lt; GlobPtrSz&lt; T &gt; &gt;',['http://docs.opencv.org/3.4.0/dd/def/structcv_1_1cudev_1_1PtrTraits_3_01GlobPtrSz_3_01T_01_4_01_4.html',1,'cv::cudev']]],
  ['ptrtraits_3c_20gpumat_5f_3c_20t_20_3e_20_3e',['PtrTraits&lt; GpuMat_&lt; T &gt; &gt;',['http://docs.opencv.org/3.4.0/de/d66/structcv_1_1cudev_1_1PtrTraits_3_01GpuMat___3_01T_01_4_01_4.html',1,'cv::cudev']]],
  ['ptrtraits_3c_20integerareainterptrsz_3c_20srcptr_20_3e_20_3e',['PtrTraits&lt; IntegerAreaInterPtrSz&lt; SrcPtr &gt; &gt;',['http://docs.opencv.org/3.4.0/d5/da1/structcv_1_1cudev_1_1PtrTraits_3_01IntegerAreaInterPtrSz_3_01SrcPtr_01_4_01_4.html',1,'cv::cudev']]],
  ['ptrtraits_3c_20laplacianptrsz_3c_20ksize_2c_20srcptr_20_3e_20_3e',['PtrTraits&lt; LaplacianPtrSz&lt; ksize, SrcPtr &gt; &gt;',['http://docs.opencv.org/3.4.0/dd/d0b/structcv_1_1cudev_1_1PtrTraits_3_01LaplacianPtrSz_3_01ksize_00_01SrcPtr_01_4_01_4.html',1,'cv::cudev']]],
  ['ptrtraits_3c_20linearinterptrsz_3c_20srcptr_20_3e_20_3e',['PtrTraits&lt; LinearInterPtrSz&lt; SrcPtr &gt; &gt;',['http://docs.opencv.org/3.4.0/d7/deb/structcv_1_1cudev_1_1PtrTraits_3_01LinearInterPtrSz_3_01SrcPtr_01_4_01_4.html',1,'cv::cudev']]],
  ['ptrtraits_3c_20lutptrsz_3c_20srcptr_2c_20tableptr_20_3e_20_3e',['PtrTraits&lt; LutPtrSz&lt; SrcPtr, TablePtr &gt; &gt;',['http://docs.opencv.org/3.4.0/d1/df8/structcv_1_1cudev_1_1PtrTraits_3_01LutPtrSz_3_01SrcPtr_00_01TablePtr_01_4_01_4.html',1,'cv::cudev']]],
  ['ptrtraits_3c_20nearestinterptrsz_3c_20srcptr_20_3e_20_3e',['PtrTraits&lt; NearestInterPtrSz&lt; SrcPtr &gt; &gt;',['http://docs.opencv.org/3.4.0/d7/da3/structcv_1_1cudev_1_1PtrTraits_3_01NearestInterPtrSz_3_01SrcPtr_01_4_01_4.html',1,'cv::cudev']]],
  ['ptrtraits_3c_20perspectivemapptrsz_20_3e',['PtrTraits&lt; PerspectiveMapPtrSz &gt;',['http://docs.opencv.org/3.4.0/db/dee/structcv_1_1cudev_1_1PtrTraits_3_01PerspectiveMapPtrSz_01_4.html',1,'cv::cudev']]],
  ['ptrtraits_3c_20remapptr1sz_3c_20srcptr_2c_20mapptr_20_3e_20_3e',['PtrTraits&lt; RemapPtr1Sz&lt; SrcPtr, MapPtr &gt; &gt;',['http://docs.opencv.org/3.4.0/dd/d16/structcv_1_1cudev_1_1PtrTraits_3_01RemapPtr1Sz_3_01SrcPtr_00_01MapPtr_01_4_01_4.html',1,'cv::cudev']]],
  ['ptrtraits_3c_20remapptr2sz_3c_20srcptr_2c_20mapxptr_2c_20mapyptr_20_3e_20_3e',['PtrTraits&lt; RemapPtr2Sz&lt; SrcPtr, MapXPtr, MapYPtr &gt; &gt;',['http://docs.opencv.org/3.4.0/d0/dc2/structcv_1_1cudev_1_1PtrTraits_3_01RemapPtr2Sz_3_01SrcPtr_00_01MapXPtr_00_01MapYPtr_01_4_01_4.html',1,'cv::cudev']]],
  ['ptrtraits_3c_20resizeptrsz_3c_20srcptr_20_3e_20_3e',['PtrTraits&lt; ResizePtrSz&lt; SrcPtr &gt; &gt;',['http://docs.opencv.org/3.4.0/da/da2/structcv_1_1cudev_1_1PtrTraits_3_01ResizePtrSz_3_01SrcPtr_01_4_01_4.html',1,'cv::cudev']]],
  ['ptrtraits_3c_20scharrxptrsz_3c_20srcptr_20_3e_20_3e',['PtrTraits&lt; ScharrXPtrSz&lt; SrcPtr &gt; &gt;',['http://docs.opencv.org/3.4.0/d9/d3d/structcv_1_1cudev_1_1PtrTraits_3_01ScharrXPtrSz_3_01SrcPtr_01_4_01_4.html',1,'cv::cudev']]],
  ['ptrtraits_3c_20scharryptrsz_3c_20srcptr_20_3e_20_3e',['PtrTraits&lt; ScharrYPtrSz&lt; SrcPtr &gt; &gt;',['http://docs.opencv.org/3.4.0/d6/d29/structcv_1_1cudev_1_1PtrTraits_3_01ScharrYPtrSz_3_01SrcPtr_01_4_01_4.html',1,'cv::cudev']]],
  ['ptrtraits_3c_20singlemaskchannelssz_3c_20maskptr_20_3e_20_3e',['PtrTraits&lt; SingleMaskChannelsSz&lt; MaskPtr &gt; &gt;',['http://docs.opencv.org/3.4.0/d4/d58/structcv_1_1cudev_1_1PtrTraits_3_01SingleMaskChannelsSz_3_01MaskPtr_01_4_01_4.html',1,'cv::cudev']]],
  ['ptrtraits_3c_20sobelxptrsz_3c_20srcptr_20_3e_20_3e',['PtrTraits&lt; SobelXPtrSz&lt; SrcPtr &gt; &gt;',['http://docs.opencv.org/3.4.0/dd/d73/structcv_1_1cudev_1_1PtrTraits_3_01SobelXPtrSz_3_01SrcPtr_01_4_01_4.html',1,'cv::cudev']]],
  ['ptrtraits_3c_20sobelyptrsz_3c_20srcptr_20_3e_20_3e',['PtrTraits&lt; SobelYPtrSz&lt; SrcPtr &gt; &gt;',['http://docs.opencv.org/3.4.0/d4/d67/structcv_1_1cudev_1_1PtrTraits_3_01SobelYPtrSz_3_01SrcPtr_01_4_01_4.html',1,'cv::cudev']]],
  ['ptrtraits_3c_20srcptr_20_3e',['PtrTraits&lt; SrcPtr &gt;',['http://docs.opencv.org/3.4.0/d2/d1a/structcv_1_1cudev_1_1PtrTraits.html',1,'cv::cudev::PtrTraits&lt; SrcPtr &gt;'],['http://docs.opencv.org/3.4.0/d2/d1a/structcv_1_1cudev_1_1PtrTraits.html',1,'PtrTraits&lt; SrcPtr &gt;']]],
  ['ptrtraits_3c_20texture_3c_20t_20_3e_20_3e',['PtrTraits&lt; Texture&lt; T &gt; &gt;',['http://docs.opencv.org/3.4.0/d2/db7/structcv_1_1cudev_1_1PtrTraits_3_01Texture_3_01T_01_4_01_4.html',1,'cv::cudev']]],
  ['ptrtraits_3c_20unarytransformptrsz_3c_20srcptr_2c_20op_20_3e_20_3e',['PtrTraits&lt; UnaryTransformPtrSz&lt; SrcPtr, Op &gt; &gt;',['http://docs.opencv.org/3.4.0/df/d71/structcv_1_1cudev_1_1PtrTraits_3_01UnaryTransformPtrSz_3_01SrcPtr_00_01Op_01_4_01_4.html',1,'cv::cudev']]],
  ['ptrtraits_3c_20zipptrsz_3c_20ptrtuple_20_3e_20_3e',['PtrTraits&lt; ZipPtrSz&lt; PtrTuple &gt; &gt;',['http://docs.opencv.org/3.4.0/db/d34/structcv_1_1cudev_1_1PtrTraits_3_01ZipPtrSz_3_01PtrTuple_01_4_01_4.html',1,'cv::cudev']]],
  ['ptrtraitsbase',['PtrTraitsBase',['http://docs.opencv.org/3.4.0/db/d3c/structcv_1_1cudev_1_1PtrTraitsBase.html',1,'cv::cudev']]],
  ['ptrtraitsbase_3c_20affinemapptrsz_2c_20affinemapptr_20_3e',['PtrTraitsBase&lt; AffineMapPtrSz, AffineMapPtr &gt;',['http://docs.opencv.org/3.4.0/db/d3c/structcv_1_1cudev_1_1PtrTraitsBase.html',1,'']]],
  ['ptrtraitsbase_3c_20binarytransformptrsz_3c_20src1ptr_2c_20src2ptr_2c_20op_20_3e_2c_20binarytransformptr_3c_20src1ptr_2c_20src2ptr_2c_20op_20_3e_20_3e',['PtrTraitsBase&lt; BinaryTransformPtrSz&lt; Src1Ptr, Src2Ptr, Op &gt;, BinaryTransformPtr&lt; Src1Ptr, Src2Ptr, Op &gt; &gt;',['http://docs.opencv.org/3.4.0/db/d3c/structcv_1_1cudev_1_1PtrTraitsBase.html',1,'']]],
  ['ptrtraitsbase_3c_20commonareainterptrsz_3c_20srcptr_20_3e_2c_20commonareainterptr_3c_20srcptr_20_3e_20_3e',['PtrTraitsBase&lt; CommonAreaInterPtrSz&lt; SrcPtr &gt;, CommonAreaInterPtr&lt; SrcPtr &gt; &gt;',['http://docs.opencv.org/3.4.0/db/d3c/structcv_1_1cudev_1_1PtrTraitsBase.html',1,'']]],
  ['ptrtraitsbase_3c_20constantptrsz_3c_20t_20_3e_2c_20constantptr_3c_20t_20_3e_20_3e',['PtrTraitsBase&lt; ConstantPtrSz&lt; T &gt;, ConstantPtr&lt; T &gt; &gt;',['http://docs.opencv.org/3.4.0/db/d3c/structcv_1_1cudev_1_1PtrTraitsBase.html',1,'']]],
  ['ptrtraitsbase_3c_20cubicinterptrsz_3c_20srcptr_20_3e_2c_20cubicinterptr_3c_20srcptr_20_3e_20_3e',['PtrTraitsBase&lt; CubicInterPtrSz&lt; SrcPtr &gt;, CubicInterPtr&lt; SrcPtr &gt; &gt;',['http://docs.opencv.org/3.4.0/db/d3c/structcv_1_1cudev_1_1PtrTraitsBase.html',1,'']]],
  ['ptrtraitsbase_3c_20derivxptrsz_3c_20srcptr_20_3e_2c_20derivxptr_3c_20srcptr_20_3e_20_3e',['PtrTraitsBase&lt; DerivXPtrSz&lt; SrcPtr &gt;, DerivXPtr&lt; SrcPtr &gt; &gt;',['http://docs.opencv.org/3.4.0/db/d3c/structcv_1_1cudev_1_1PtrTraitsBase.html',1,'']]],
  ['ptrtraitsbase_3c_20derivyptrsz_3c_20srcptr_20_3e_2c_20derivyptr_3c_20srcptr_20_3e_20_3e',['PtrTraitsBase&lt; DerivYPtrSz&lt; SrcPtr &gt;, DerivYPtr&lt; SrcPtr &gt; &gt;',['http://docs.opencv.org/3.4.0/db/d3c/structcv_1_1cudev_1_1PtrTraitsBase.html',1,'']]],
  ['ptrtraitsbase_3c_20globptrsz_3c_20t_20_3e_2c_20globptr_3c_20t_20_3e_20_3e',['PtrTraitsBase&lt; GlobPtrSz&lt; T &gt;, GlobPtr&lt; T &gt; &gt;',['http://docs.opencv.org/3.4.0/db/d3c/structcv_1_1cudev_1_1PtrTraitsBase.html',1,'']]],
  ['ptrtraitsbase_3c_20gpumat_5f_3c_20t_20_3e_2c_20globptr_3c_20t_20_3e_20_3e',['PtrTraitsBase&lt; GpuMat_&lt; T &gt;, GlobPtr&lt; T &gt; &gt;',['http://docs.opencv.org/3.4.0/db/d3c/structcv_1_1cudev_1_1PtrTraitsBase.html',1,'']]],
  ['ptrtraitsbase_3c_20integerareainterptrsz_3c_20srcptr_20_3e_2c_20integerareainterptr_3c_20srcptr_20_3e_20_3e',['PtrTraitsBase&lt; IntegerAreaInterPtrSz&lt; SrcPtr &gt;, IntegerAreaInterPtr&lt; SrcPtr &gt; &gt;',['http://docs.opencv.org/3.4.0/db/d3c/structcv_1_1cudev_1_1PtrTraitsBase.html',1,'']]],
  ['ptrtraitsbase_3c_20laplacianptrsz_3c_20ksize_2c_20srcptr_20_3e_2c_20laplacianptr_3c_20ksize_2c_20srcptr_20_3e_20_3e',['PtrTraitsBase&lt; LaplacianPtrSz&lt; ksize, SrcPtr &gt;, LaplacianPtr&lt; ksize, SrcPtr &gt; &gt;',['http://docs.opencv.org/3.4.0/db/d3c/structcv_1_1cudev_1_1PtrTraitsBase.html',1,'']]],
  ['ptrtraitsbase_3c_20linearinterptrsz_3c_20srcptr_20_3e_2c_20linearinterptr_3c_20srcptr_20_3e_20_3e',['PtrTraitsBase&lt; LinearInterPtrSz&lt; SrcPtr &gt;, LinearInterPtr&lt; SrcPtr &gt; &gt;',['http://docs.opencv.org/3.4.0/db/d3c/structcv_1_1cudev_1_1PtrTraitsBase.html',1,'']]],
  ['ptrtraitsbase_3c_20lutptrsz_3c_20srcptr_2c_20tableptr_20_3e_2c_20lutptr_3c_20srcptr_2c_20tableptr_20_3e_20_3e',['PtrTraitsBase&lt; LutPtrSz&lt; SrcPtr, TablePtr &gt;, LutPtr&lt; SrcPtr, TablePtr &gt; &gt;',['http://docs.opencv.org/3.4.0/db/d3c/structcv_1_1cudev_1_1PtrTraitsBase.html',1,'']]],
  ['ptrtraitsbase_3c_20nearestinterptrsz_3c_20srcptr_20_3e_2c_20nearestinterptr_3c_20srcptr_20_3e_20_3e',['PtrTraitsBase&lt; NearestInterPtrSz&lt; SrcPtr &gt;, NearestInterPtr&lt; SrcPtr &gt; &gt;',['http://docs.opencv.org/3.4.0/db/d3c/structcv_1_1cudev_1_1PtrTraitsBase.html',1,'']]],
  ['ptrtraitsbase_3c_20perspectivemapptrsz_2c_20perspectivemapptr_20_3e',['PtrTraitsBase&lt; PerspectiveMapPtrSz, PerspectiveMapPtr &gt;',['http://docs.opencv.org/3.4.0/db/d3c/structcv_1_1cudev_1_1PtrTraitsBase.html',1,'']]],
  ['ptrtraitsbase_3c_20ptr2dsz_2c_20ptr2dsz_20_3e',['PtrTraitsBase&lt; Ptr2DSz, Ptr2DSz &gt;',['http://docs.opencv.org/3.4.0/db/d3c/structcv_1_1cudev_1_1PtrTraitsBase.html',1,'']]],
  ['ptrtraitsbase_3c_20remapptr1sz_3c_20srcptr_2c_20mapptr_20_3e_2c_20remapptr1_3c_20srcptr_2c_20mapptr_20_3e_20_3e',['PtrTraitsBase&lt; RemapPtr1Sz&lt; SrcPtr, MapPtr &gt;, RemapPtr1&lt; SrcPtr, MapPtr &gt; &gt;',['http://docs.opencv.org/3.4.0/db/d3c/structcv_1_1cudev_1_1PtrTraitsBase.html',1,'']]],
  ['ptrtraitsbase_3c_20remapptr2sz_3c_20srcptr_2c_20mapxptr_2c_20mapyptr_20_3e_2c_20remapptr2_3c_20srcptr_2c_20mapxptr_2c_20mapyptr_20_3e_20_3e',['PtrTraitsBase&lt; RemapPtr2Sz&lt; SrcPtr, MapXPtr, MapYPtr &gt;, RemapPtr2&lt; SrcPtr, MapXPtr, MapYPtr &gt; &gt;',['http://docs.opencv.org/3.4.0/db/d3c/structcv_1_1cudev_1_1PtrTraitsBase.html',1,'']]],
  ['ptrtraitsbase_3c_20resizeptrsz_3c_20srcptr_20_3e_2c_20resizeptr_3c_20srcptr_20_3e_20_3e',['PtrTraitsBase&lt; ResizePtrSz&lt; SrcPtr &gt;, ResizePtr&lt; SrcPtr &gt; &gt;',['http://docs.opencv.org/3.4.0/db/d3c/structcv_1_1cudev_1_1PtrTraitsBase.html',1,'']]],
  ['ptrtraitsbase_3c_20scharrxptrsz_3c_20srcptr_20_3e_2c_20scharrxptr_3c_20srcptr_20_3e_20_3e',['PtrTraitsBase&lt; ScharrXPtrSz&lt; SrcPtr &gt;, ScharrXPtr&lt; SrcPtr &gt; &gt;',['http://docs.opencv.org/3.4.0/db/d3c/structcv_1_1cudev_1_1PtrTraitsBase.html',1,'']]],
  ['ptrtraitsbase_3c_20scharryptrsz_3c_20srcptr_20_3e_2c_20scharryptr_3c_20srcptr_20_3e_20_3e',['PtrTraitsBase&lt; ScharrYPtrSz&lt; SrcPtr &gt;, ScharrYPtr&lt; SrcPtr &gt; &gt;',['http://docs.opencv.org/3.4.0/db/d3c/structcv_1_1cudev_1_1PtrTraitsBase.html',1,'']]],
  ['ptrtraitsbase_3c_20singlemaskchannelssz_3c_20maskptr_20_3e_2c_20singlemaskchannels_3c_20maskptr_20_3e_20_3e',['PtrTraitsBase&lt; SingleMaskChannelsSz&lt; MaskPtr &gt;, SingleMaskChannels&lt; MaskPtr &gt; &gt;',['http://docs.opencv.org/3.4.0/db/d3c/structcv_1_1cudev_1_1PtrTraitsBase.html',1,'']]],
  ['ptrtraitsbase_3c_20sobelxptrsz_3c_20srcptr_20_3e_2c_20sobelxptr_3c_20srcptr_20_3e_20_3e',['PtrTraitsBase&lt; SobelXPtrSz&lt; SrcPtr &gt;, SobelXPtr&lt; SrcPtr &gt; &gt;',['http://docs.opencv.org/3.4.0/db/d3c/structcv_1_1cudev_1_1PtrTraitsBase.html',1,'']]],
  ['ptrtraitsbase_3c_20sobelyptrsz_3c_20srcptr_20_3e_2c_20sobelyptr_3c_20srcptr_20_3e_20_3e',['PtrTraitsBase&lt; SobelYPtrSz&lt; SrcPtr &gt;, SobelYPtr&lt; SrcPtr &gt; &gt;',['http://docs.opencv.org/3.4.0/db/d3c/structcv_1_1cudev_1_1PtrTraitsBase.html',1,'']]],
  ['ptrtraitsbase_3c_20srcptr_2c_20srcptr_20_3e',['PtrTraitsBase&lt; SrcPtr, SrcPtr &gt;',['http://docs.opencv.org/3.4.0/db/d3c/structcv_1_1cudev_1_1PtrTraitsBase.html',1,'']]],
  ['ptrtraitsbase_3c_20texture_3c_20t_20_3e_2c_20textureptr_3c_20t_20_3e_20_3e',['PtrTraitsBase&lt; Texture&lt; T &gt;, TexturePtr&lt; T &gt; &gt;',['http://docs.opencv.org/3.4.0/db/d3c/structcv_1_1cudev_1_1PtrTraitsBase.html',1,'']]],
  ['ptrtraitsbase_3c_20unarytransformptrsz_3c_20srcptr_2c_20op_20_3e_2c_20unarytransformptr_3c_20srcptr_2c_20op_20_3e_20_3e',['PtrTraitsBase&lt; UnaryTransformPtrSz&lt; SrcPtr, Op &gt;, UnaryTransformPtr&lt; SrcPtr, Op &gt; &gt;',['http://docs.opencv.org/3.4.0/db/d3c/structcv_1_1cudev_1_1PtrTraitsBase.html',1,'']]],
  ['ptrtraitsbase_3c_20zipptrsz_3c_20ptrtuple_20_3e_2c_20zipptr_3c_20ptrtuple_20_3e_20_3e',['PtrTraitsBase&lt; ZipPtrSz&lt; PtrTuple &gt;, ZipPtr&lt; PtrTuple &gt; &gt;',['http://docs.opencv.org/3.4.0/db/d3c/structcv_1_1cudev_1_1PtrTraitsBase.html',1,'']]],
  ['pupillocalization',['PupilLocalization',['../classgaze_1_1pipeline_1_1_pupil_localization.html',1,'gaze::pipeline']]],
  ['pyrdownbody',['PyrDownBody',['http://docs.opencv.org/3.4.0/d1/d8a/structcv_1_1cudev_1_1PyrDownBody.html',1,'cv::cudev']]],
  ['pyrlkoptflowestimatorbase',['PyrLkOptFlowEstimatorBase',['http://docs.opencv.org/3.4.0/d2/d86/classcv_1_1videostab_1_1PyrLkOptFlowEstimatorBase.html',1,'cv::videostab']]],
  ['pyrlkopticalflow',['PyrLKOpticalFlow',['http://docs.opencv.org/3.4.0/de/d2b/classcv_1_1superres_1_1PyrLKOpticalFlow.html',1,'cv::superres']]],
  ['pyrupbody',['PyrUpBody',['http://docs.opencv.org/3.4.0/d1/de8/structcv_1_1cudev_1_1PyrUpBody.html',1,'cv::cudev']]]
];
