var searchData=
[
  ['saliency',['Saliency',['http://docs.opencv.org/3.4.0/d9/dcd/classcv_1_1saliency_1_1Saliency.html',1,'cv::saliency']]],
  ['sample_5fprobe_5ffn',['sample_probe_fn',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10704.html',1,'__gnu_pbds']]],
  ['sample_5frange_5fhashing',['sample_range_hashing',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10708.html',1,'__gnu_pbds']]],
  ['sample_5franged_5fhash_5ffn',['sample_ranged_hash_fn',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10712.html',1,'__gnu_pbds']]],
  ['sample_5franged_5fprobe_5ffn',['sample_ranged_probe_fn',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10716.html',1,'__gnu_pbds']]],
  ['sample_5fresize_5fpolicy',['sample_resize_policy',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10928.html',1,'__gnu_pbds']]],
  ['sample_5fresize_5ftrigger',['sample_resize_trigger',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10932.html',1,'__gnu_pbds']]],
  ['sample_5fsize_5fpolicy',['sample_size_policy',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10936.html',1,'__gnu_pbds']]],
  ['sample_5ftree_5fnode_5fupdate',['sample_tree_node_update',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10980.html',1,'__gnu_pbds']]],
  ['sample_5ftrie_5faccess_5ftraits',['sample_trie_access_traits',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a11000.html',1,'__gnu_pbds']]],
  ['sample_5ftrie_5fnode_5fupdate',['sample_trie_node_update',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a11004.html',1,'__gnu_pbds']]],
  ['sample_5fupdate_5fpolicy',['sample_update_policy',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10780.html',1,'__gnu_pbds']]],
  ['sampling_5ftag',['sampling_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08664.html',1,'__gnu_parallel']]],
  ['satcasthelper',['SatCastHelper',['http://docs.opencv.org/3.4.0/dc/db0/structcv_1_1cudev_1_1vec__math__detail_1_1SatCastHelper.html',1,'cv::cudev::vec_math_detail']]],
  ['satcasthelper_3c_201_2c_20vecd_20_3e',['SatCastHelper&lt; 1, VecD &gt;',['http://docs.opencv.org/3.4.0/d2/d31/structcv_1_1cudev_1_1vec__math__detail_1_1SatCastHelper_3_011_00_01VecD_01_4.html',1,'cv::cudev::vec_math_detail']]],
  ['satcasthelper_3c_202_2c_20vecd_20_3e',['SatCastHelper&lt; 2, VecD &gt;',['http://docs.opencv.org/3.4.0/dc/dbc/structcv_1_1cudev_1_1vec__math__detail_1_1SatCastHelper_3_012_00_01VecD_01_4.html',1,'cv::cudev::vec_math_detail']]],
  ['satcasthelper_3c_203_2c_20vecd_20_3e',['SatCastHelper&lt; 3, VecD &gt;',['http://docs.opencv.org/3.4.0/d8/dbe/structcv_1_1cudev_1_1vec__math__detail_1_1SatCastHelper_3_013_00_01VecD_01_4.html',1,'cv::cudev::vec_math_detail']]],
  ['satcasthelper_3c_204_2c_20vecd_20_3e',['SatCastHelper&lt; 4, VecD &gt;',['http://docs.opencv.org/3.4.0/df/d18/structcv_1_1cudev_1_1vec__math__detail_1_1SatCastHelper_3_014_00_01VecD_01_4.html',1,'cv::cudev::vec_math_detail']]],
  ['saturate_5fcast_5ffp16_5ffunc',['saturate_cast_fp16_func',['http://docs.opencv.org/3.4.0/de/d9b/structcv_1_1cudev_1_1saturate__cast__fp16__func.html',1,'cv::cudev']]],
  ['saturate_5fcast_5ffp16_5ffunc_3c_20float_2c_20short_20_3e',['saturate_cast_fp16_func&lt; float, short &gt;',['http://docs.opencv.org/3.4.0/d3/d11/structcv_1_1cudev_1_1saturate__cast__fp16__func_3_01float_00_01short_01_4.html',1,'cv::cudev']]],
  ['saturate_5fcast_5ffp16_5ffunc_3c_20short_2c_20float_20_3e',['saturate_cast_fp16_func&lt; short, float &gt;',['http://docs.opencv.org/3.4.0/dc/dc5/structcv_1_1cudev_1_1saturate__cast__fp16__func_3_01short_00_01float_01_4.html',1,'cv::cudev']]],
  ['saturate_5fcast_5ffunc',['saturate_cast_func',['http://docs.opencv.org/3.4.0/dc/d99/structcv_1_1cudev_1_1saturate__cast__func.html',1,'cv::cudev']]],
  ['savedindexparams',['SavedIndexParams',['http://docs.opencv.org/3.4.0/de/de8/structcv_1_1flann_1_1SavedIndexParams.html',1,'cv::flann']]],
  ['savedindexparams',['SavedIndexParams',['http://docs.opencv.org/3.4.0/dc/d2a/structcvflann_1_1SavedIndexParams.html',1,'cvflann']]],
  ['scalar_5f',['Scalar_',['http://docs.opencv.org/3.4.0/d1/da0/classcv_1_1Scalar__.html',1,'cv']]],
  ['scalar_5f_3c_20double_20_3e',['Scalar_&lt; double &gt;',['http://docs.opencv.org/3.4.0/d1/da0/classcv_1_1Scalar__.html',1,'cv::Scalar_&lt; double &gt;'],['http://docs.opencv.org/3.4.0/d1/da0/classcv_1_1Scalar__.html',1,'Scalar_&lt; double &gt;']]],
  ['scalelayer',['ScaleLayer',['http://docs.opencv.org/3.4.0/dd/dde/classcv_1_1dnn_1_1ScaleLayer.html',1,'cv::dnn']]],
  ['scharrxptr',['ScharrXPtr',['http://docs.opencv.org/3.4.0/d7/d71/structcv_1_1cudev_1_1ScharrXPtr.html',1,'cv::cudev']]],
  ['scharrxptrsz',['ScharrXPtrSz',['http://docs.opencv.org/3.4.0/d2/d88/structcv_1_1cudev_1_1ScharrXPtrSz.html',1,'cv::cudev']]],
  ['scharryptr',['ScharrYPtr',['http://docs.opencv.org/3.4.0/d0/d70/structcv_1_1cudev_1_1ScharrYPtr.html',1,'cv::cudev']]],
  ['scharryptrsz',['ScharrYPtrSz',['http://docs.opencv.org/3.4.0/dd/def/structcv_1_1cudev_1_1ScharrYPtrSz.html',1,'cv::cudev']]],
  ['scoped_5fallocator_5fadaptor',['scoped_allocator_adaptor',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02864.html',1,'std']]],
  ['scoped_5fallocator_5fadaptor_3c_20_5finnerhead_2c_20_5finnertail_2e_2e_2e_20_3e',['scoped_allocator_adaptor&lt; _InnerHead, _InnerTail... &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02864.html',1,'']]],
  ['seamfinder',['SeamFinder',['http://docs.opencv.org/3.4.0/d7/d09/classcv_1_1detail_1_1SeamFinder.html',1,'cv::detail']]],
  ['searchparams',['SearchParams',['http://docs.opencv.org/3.4.0/d6/d59/structcvflann_1_1SearchParams.html',1,'cvflann']]],
  ['searchparams',['SearchParams',['http://docs.opencv.org/3.4.0/d5/d03/structcv_1_1flann_1_1SearchParams.html',1,'cv::flann']]],
  ['seed_5fseq',['seed_seq',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05584.html',1,'std']]],
  ['segmentationparameters',['SegmentationParameters',['http://docs.opencv.org/3.4.0/d9/dbf/structcv_1_1bioinspired_1_1SegmentationParameters.html',1,'cv::bioinspired']]],
  ['select1st',['select1st',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08096.html',1,'__gnu_cxx']]],
  ['select2nd',['select2nd',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08100.html',1,'__gnu_cxx']]],
  ['selectif',['SelectIf',['http://docs.opencv.org/3.4.0/d8/d1b/structcv_1_1cudev_1_1SelectIf.html',1,'cv::cudev']]],
  ['selectif_3c_20false_2c_20thentype_2c_20elsetype_20_3e',['SelectIf&lt; false, ThenType, ElseType &gt;',['http://docs.opencv.org/3.4.0/dd/da7/structcv_1_1cudev_1_1SelectIf_3_01false_00_01ThenType_00_01ElseType_01_4.html',1,'cv::cudev']]],
  ['selectivesearchsegmentation',['SelectiveSearchSegmentation',['http://docs.opencv.org/3.4.0/d6/d6d/classcv_1_1ximgproc_1_1segmentation_1_1SelectiveSearchSegmentation.html',1,'cv::ximgproc::segmentation']]],
  ['selectivesearchsegmentationstrategy',['SelectiveSearchSegmentationStrategy',['http://docs.opencv.org/3.4.0/dc/d7a/classcv_1_1ximgproc_1_1segmentation_1_1SelectiveSearchSegmentationStrategy.html',1,'cv::ximgproc::segmentation']]],
  ['selectivesearchsegmentationstrategycolor',['SelectiveSearchSegmentationStrategyColor',['http://docs.opencv.org/3.4.0/de/dab/classcv_1_1ximgproc_1_1segmentation_1_1SelectiveSearchSegmentationStrategyColor.html',1,'cv::ximgproc::segmentation']]],
  ['selectivesearchsegmentationstrategyfill',['SelectiveSearchSegmentationStrategyFill',['http://docs.opencv.org/3.4.0/d9/db3/classcv_1_1ximgproc_1_1segmentation_1_1SelectiveSearchSegmentationStrategyFill.html',1,'cv::ximgproc::segmentation']]],
  ['selectivesearchsegmentationstrategymultiple',['SelectiveSearchSegmentationStrategyMultiple',['http://docs.opencv.org/3.4.0/d8/d8e/classcv_1_1ximgproc_1_1segmentation_1_1SelectiveSearchSegmentationStrategyMultiple.html',1,'cv::ximgproc::segmentation']]],
  ['selectivesearchsegmentationstrategysize',['SelectiveSearchSegmentationStrategySize',['http://docs.opencv.org/3.4.0/d0/d10/classcv_1_1ximgproc_1_1segmentation_1_1SelectiveSearchSegmentationStrategySize.html',1,'cv::ximgproc::segmentation']]],
  ['selectivesearchsegmentationstrategytexture',['SelectiveSearchSegmentationStrategyTexture',['http://docs.opencv.org/3.4.0/d6/d17/classcv_1_1ximgproc_1_1segmentation_1_1SelectiveSearchSegmentationStrategyTexture.html',1,'cv::ximgproc::segmentation']]],
  ['sentry',['sentry',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02608.html',1,'std::basic_istream']]],
  ['sentry',['sentry',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02756.html',1,'std::basic_ostream']]],
  ['seq',['Seq',['http://docs.opencv.org/3.4.0/de/dd1/classcv_1_1Seq.html',1,'cv']]],
  ['seqiterator',['SeqIterator',['http://docs.opencv.org/3.4.0/dd/d28/classcv_1_1SeqIterator.html',1,'cv']]],
  ['seqreader',['SeqReader',['http://docs.opencv.org/3.4.0/dc/db7/structcv_1_1FileNodeIterator_1_1SeqReader.html',1,'cv::FileNodeIterator']]],
  ['sequence_5ftag',['sequence_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10132.html',1,'__gnu_pbds']]],
  ['sequential_5ftag',['sequential_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08628.html',1,'__gnu_parallel']]],
  ['set',['set',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07864.html',1,'std::__profile']]],
  ['set',['set',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07728.html',1,'std::__debug']]],
  ['set',['set',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06732.html',1,'std']]],
  ['set_3c_20distindex_20_3e',['set&lt; DistIndex &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06732.html',1,'std']]],
  ['sfmlibmveuclideanreconstruction',['SFMLibmvEuclideanReconstruction',['http://docs.opencv.org/3.4.0/de/d42/classcv_1_1sfm_1_1SFMLibmvEuclideanReconstruction.html',1,'cv::sfm']]],
  ['shapecontextdistanceextractor',['ShapeContextDistanceExtractor',['http://docs.opencv.org/3.4.0/d8/de3/classcv_1_1ShapeContextDistanceExtractor.html',1,'cv']]],
  ['shapedistanceextractor',['ShapeDistanceExtractor',['http://docs.opencv.org/3.4.0/dc/dbf/classcv_1_1ShapeDistanceExtractor.html',1,'cv']]],
  ['shapetransformer',['ShapeTransformer',['http://docs.opencv.org/3.4.0/df/dfe/classcv_1_1ShapeTransformer.html',1,'cv']]],
  ['shared_5ffuture',['shared_future',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02352.html',1,'std']]],
  ['shared_5ffuture_3c_20_5fres_20_26_20_3e',['shared_future&lt; _Res &amp; &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02468.html',1,'std']]],
  ['shared_5ffuture_3c_20void_20_3e',['shared_future&lt; void &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02472.html',1,'std']]],
  ['shared_5flock',['shared_lock',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02892.html',1,'std']]],
  ['shared_5flock_5fguard',['shared_lock_guard',['http://docs.opencv.org/3.4.0/d9/d7f/classcv_1_1utils_1_1shared__lock__guard.html',1,'cv::utils']]],
  ['shared_5fptr',['shared_ptr',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05936.html',1,'std']]],
  ['shared_5fptr_3c_20_5fdir_20_3e',['shared_ptr&lt; _Dir &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05936.html',1,'']]],
  ['shared_5fptr_3c_20_5fdir_5fstack_20_3e',['shared_ptr&lt; _Dir_stack &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05936.html',1,'']]],
  ['shared_5fptr_3c_20_5fregext_20_3e',['shared_ptr&lt; _RegexT &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05936.html',1,'']]],
  ['shared_5fptr_3c_20_5fstate_20_3e',['shared_ptr&lt; _State &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05936.html',1,'']]],
  ['shared_5fptr_3c_20_5fstate_5fbase_20_3e',['shared_ptr&lt; _State_base &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05936.html',1,'']]],
  ['shared_5fptr_3c_20_5fstate_5ftype_20_3e',['shared_ptr&lt; _State_type &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05936.html',1,'']]],
  ['shared_5fptr_3c_20const_20_5f_5fdetail_3a_3a_5fnfa_3c_20_5frx_5ftraits_20_3e_20_3e',['shared_ptr&lt; const __detail::_NFA&lt; _Rx_traits &gt; &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05936.html',1,'']]],
  ['shared_5fptr_3c_20std_3a_3amutex_20_3e',['shared_ptr&lt; std::mutex &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05936.html',1,'']]],
  ['shared_5fptr_3c_20widget_5ftype_20_3e',['shared_ptr&lt; widget_type &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05936.html',1,'std']]],
  ['shared_5ftimed_5fmutex',['shared_timed_mutex',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02888.html',1,'std']]],
  ['shiftlayer',['ShiftLayer',['http://docs.opencv.org/3.4.0/d3/dd8/classcv_1_1dnn_1_1ShiftLayer.html',1,'cv::dnn']]],
  ['shuffle_5forder_5fengine',['shuffle_order_engine',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05420.html',1,'std']]],
  ['sift',['SIFT',['http://docs.opencv.org/3.4.0/d5/d3c/classcv_1_1xfeatures2d_1_1SIFT.html',1,'cv::xfeatures2d']]],
  ['sigmoidlayer',['SigmoidLayer',['http://docs.opencv.org/3.4.0/dc/d09/classcv_1_1dnn_1_1SigmoidLayer.html',1,'cv::dnn']]],
  ['similarrects',['SimilarRects',['http://docs.opencv.org/3.4.0/d1/d65/classcv_1_1SimilarRects.html',1,'cv']]],
  ['simpleblobdetector',['SimpleBlobDetector',['http://docs.opencv.org/3.4.0/d0/d7a/classcv_1_1SimpleBlobDetector.html',1,'cv']]],
  ['simpledistance',['simpleDistance',['http://docs.opencv.org/3.4.0/d9/d12/structcvflann_1_1simpleDistance.html',1,'cvflann']]],
  ['simpledistance_3c_20chisquaredistance_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['simpleDistance&lt; ChiSquareDistance&lt; ElementType &gt;, ElementType &gt;',['http://docs.opencv.org/3.4.0/dd/d95/structcvflann_1_1simpleDistance_3_01ChiSquareDistance_3_01ElementType_01_4_00_01ElementType_01_4.html',1,'cvflann']]],
  ['simpledistance_3c_20hellingerdistance_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['simpleDistance&lt; HellingerDistance&lt; ElementType &gt;, ElementType &gt;',['http://docs.opencv.org/3.4.0/db/d88/structcvflann_1_1simpleDistance_3_01HellingerDistance_3_01ElementType_01_4_00_01ElementType_01_4.html',1,'cvflann']]],
  ['simpledistance_3c_20l2_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['simpleDistance&lt; L2&lt; ElementType &gt;, ElementType &gt;',['http://docs.opencv.org/3.4.0/dc/d3c/structcvflann_1_1simpleDistance_3_01L2_3_01ElementType_01_4_00_01ElementType_01_4.html',1,'cvflann']]],
  ['simpledistance_3c_20l2_5fsimple_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['simpleDistance&lt; L2_Simple&lt; ElementType &gt;, ElementType &gt;',['http://docs.opencv.org/3.4.0/d5/da0/structcvflann_1_1simpleDistance_3_01L2__Simple_3_01ElementType_01_4_00_01ElementType_01_4.html',1,'cvflann']]],
  ['simpledistance_3c_20minkowskidistance_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['simpleDistance&lt; MinkowskiDistance&lt; ElementType &gt;, ElementType &gt;',['http://docs.opencv.org/3.4.0/db/dd1/structcvflann_1_1simpleDistance_3_01MinkowskiDistance_3_01ElementType_01_4_00_01ElementType_01_4.html',1,'cvflann']]],
  ['simplewb',['SimpleWB',['http://docs.opencv.org/3.4.0/d1/d8b/classcv_1_1xphoto_1_1SimpleWB.html',1,'cv::xphoto']]],
  ['simulatedannealingsolversystem',['SimulatedAnnealingSolverSystem',['http://docs.opencv.org/3.4.0/dc/db4/structcv_1_1ml_1_1SimulatedAnnealingSolverSystem.html',1,'cv::ml']]],
  ['sin_5ffunc',['sin_func',['http://docs.opencv.org/3.4.0/d1/d05/structcv_1_1cudev_1_1sin__func.html',1,'cv::cudev']]],
  ['sin_5ffunc_3c_20double_20_3e',['sin_func&lt; double &gt;',['http://docs.opencv.org/3.4.0/d8/d1c/structcv_1_1cudev_1_1sin__func_3_01double_01_4.html',1,'cv::cudev']]],
  ['sin_5ffunc_3c_20float_20_3e',['sin_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/d6/d2b/structcv_1_1cudev_1_1sin__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['sin_5ffunc_3c_20schar_20_3e',['sin_func&lt; schar &gt;',['http://docs.opencv.org/3.4.0/d8/d1b/structcv_1_1cudev_1_1sin__func_3_01schar_01_4.html',1,'cv::cudev']]],
  ['sin_5ffunc_3c_20short_20_3e',['sin_func&lt; short &gt;',['http://docs.opencv.org/3.4.0/dd/d6f/structcv_1_1cudev_1_1sin__func_3_01short_01_4.html',1,'cv::cudev']]],
  ['sin_5ffunc_3c_20uchar_20_3e',['sin_func&lt; uchar &gt;',['http://docs.opencv.org/3.4.0/d2/dfd/structcv_1_1cudev_1_1sin__func_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['sin_5ffunc_3c_20uint_20_3e',['sin_func&lt; uint &gt;',['http://docs.opencv.org/3.4.0/d5/dbd/structcv_1_1cudev_1_1sin__func_3_01uint_01_4.html',1,'cv::cudev']]],
  ['sin_5ffunc_3c_20ushort_20_3e',['sin_func&lt; ushort &gt;',['http://docs.opencv.org/3.4.0/d8/d22/structcv_1_1cudev_1_1sin__func_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['singlemaskchannels',['SingleMaskChannels',['http://docs.opencv.org/3.4.0/db/dce/structcv_1_1cudev_1_1SingleMaskChannels.html',1,'cv::cudev']]],
  ['singlemaskchannelssz',['SingleMaskChannelsSz',['http://docs.opencv.org/3.4.0/d0/d19/structcv_1_1cudev_1_1SingleMaskChannelsSz.html',1,'cv::cudev']]],
  ['singlepolicy',['SinglePolicy',['http://docs.opencv.org/3.4.0/de/d31/classcvflann_1_1anyimpl_1_1SinglePolicy.html',1,'cvflann::anyimpl']]],
  ['sinh_5ffunc',['sinh_func',['http://docs.opencv.org/3.4.0/d8/da0/structcv_1_1cudev_1_1sinh__func.html',1,'cv::cudev']]],
  ['sinh_5ffunc_3c_20double_20_3e',['sinh_func&lt; double &gt;',['http://docs.opencv.org/3.4.0/db/dde/structcv_1_1cudev_1_1sinh__func_3_01double_01_4.html',1,'cv::cudev']]],
  ['sinh_5ffunc_3c_20float_20_3e',['sinh_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/d3/df1/structcv_1_1cudev_1_1sinh__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['sinh_5ffunc_3c_20schar_20_3e',['sinh_func&lt; schar &gt;',['http://docs.opencv.org/3.4.0/de/df6/structcv_1_1cudev_1_1sinh__func_3_01schar_01_4.html',1,'cv::cudev']]],
  ['sinh_5ffunc_3c_20short_20_3e',['sinh_func&lt; short &gt;',['http://docs.opencv.org/3.4.0/da/d3e/structcv_1_1cudev_1_1sinh__func_3_01short_01_4.html',1,'cv::cudev']]],
  ['sinh_5ffunc_3c_20uchar_20_3e',['sinh_func&lt; uchar &gt;',['http://docs.opencv.org/3.4.0/d4/dd2/structcv_1_1cudev_1_1sinh__func_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['sinh_5ffunc_3c_20uint_20_3e',['sinh_func&lt; uint &gt;',['http://docs.opencv.org/3.4.0/de/d13/structcv_1_1cudev_1_1sinh__func_3_01uint_01_4.html',1,'cv::cudev']]],
  ['sinh_5ffunc_3c_20ushort_20_3e',['sinh_func&lt; ushort &gt;',['http://docs.opencv.org/3.4.0/d9/d38/structcv_1_1cudev_1_1sinh__func_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['sinusoidalpattern',['SinusoidalPattern',['http://docs.opencv.org/3.4.0/d6/d96/classcv_1_1structured__light_1_1SinusoidalPattern.html',1,'cv::structured_light']]],
  ['size_5f',['Size_',['http://docs.opencv.org/3.4.0/d6/d50/classcv_1_1Size__.html',1,'cv']]],
  ['size_5f_3c_20float_20_3e',['Size_&lt; float &gt;',['http://docs.opencv.org/3.4.0/d6/d50/classcv_1_1Size__.html',1,'Size_&lt; float &gt;'],['http://docs.opencv.org/3.4.0/d6/d50/classcv_1_1Size__.html',1,'cv::Size_&lt; float &gt;']]],
  ['sizeable',['sizeable',['../structgaze_1_1gui_1_1traits_1_1sizeable.html',1,'gaze::gui::traits']]],
  ['skeleton',['skeleton',['http://docs.opencv.org/3.4.0/d4/d66/structcv_1_1datasets_1_1skeleton.html',1,'cv::datasets']]],
  ['sl2',['SL2',['http://docs.opencv.org/3.4.0/d5/d46/structcv_1_1SL2.html',1,'cv']]],
  ['slam_5fkitti',['SLAM_kitti',['http://docs.opencv.org/3.4.0/d6/d92/classcv_1_1datasets_1_1SLAM__kitti.html',1,'cv::datasets']]],
  ['slam_5fkittiobj',['SLAM_kittiObj',['http://docs.opencv.org/3.4.0/da/df4/structcv_1_1datasets_1_1SLAM__kittiObj.html',1,'cv::datasets']]],
  ['slam_5ftumindoor',['SLAM_tumindoor',['http://docs.opencv.org/3.4.0/da/d91/classcv_1_1datasets_1_1SLAM__tumindoor.html',1,'cv::datasets']]],
  ['slam_5ftumindoorobj',['SLAM_tumindoorObj',['http://docs.opencv.org/3.4.0/d7/d56/structcv_1_1datasets_1_1SLAM__tumindoorObj.html',1,'cv::datasets']]],
  ['slice',['slice',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06152.html',1,'std']]],
  ['slice_5farray',['slice_array',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a03752.html',1,'std']]],
  ['slicelayer',['SliceLayer',['http://docs.opencv.org/3.4.0/de/d61/classcv_1_1dnn_1_1SliceLayer.html',1,'cv::dnn']]],
  ['slist',['slist',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08260.html',1,'__gnu_cxx']]],
  ['small_5fany_5fpolicy',['small_any_policy',['http://docs.opencv.org/3.4.0/d7/d8e/structcvflann_1_1anyimpl_1_1small__any__policy.html',1,'cvflann::anyimpl']]],
  ['sobelxptr',['SobelXPtr',['http://docs.opencv.org/3.4.0/de/dc8/structcv_1_1cudev_1_1SobelXPtr.html',1,'cv::cudev']]],
  ['sobelxptrsz',['SobelXPtrSz',['http://docs.opencv.org/3.4.0/d7/d84/structcv_1_1cudev_1_1SobelXPtrSz.html',1,'cv::cudev']]],
  ['sobelyptr',['SobelYPtr',['http://docs.opencv.org/3.4.0/d0/da6/structcv_1_1cudev_1_1SobelYPtr.html',1,'cv::cudev']]],
  ['sobelyptrsz',['SobelYPtrSz',['http://docs.opencv.org/3.4.0/dd/dc6/structcv_1_1cudev_1_1SobelYPtrSz.html',1,'cv::cudev']]],
  ['softdouble',['softdouble',['http://docs.opencv.org/3.4.0/de/df1/structcv_1_1softdouble.html',1,'cv']]],
  ['softfloat',['softfloat',['http://docs.opencv.org/3.4.0/d7/d2f/structcv_1_1softfloat.html',1,'cv']]],
  ['softmaxlayer',['SoftmaxLayer',['http://docs.opencv.org/3.4.0/d8/d18/classcv_1_1dnn_1_1SoftmaxLayer.html',1,'cv::dnn']]],
  ['sourcecapture',['SourceCapture',['../classgaze_1_1pipeline_1_1_source_capture.html',1,'gaze::pipeline']]],
  ['sparsemat',['SparseMat',['http://docs.opencv.org/3.4.0/dd/da9/classcv_1_1SparseMat.html',1,'cv']]],
  ['sparsemat_5f',['SparseMat_',['http://docs.opencv.org/3.4.0/d7/d8a/classcv_1_1SparseMat__.html',1,'cv']]],
  ['sparsematchinterpolator',['SparseMatchInterpolator',['http://docs.opencv.org/3.4.0/d4/da8/classcv_1_1ximgproc_1_1SparseMatchInterpolator.html',1,'cv::ximgproc']]],
  ['sparsematconstiterator',['SparseMatConstIterator',['http://docs.opencv.org/3.4.0/df/dec/classcv_1_1SparseMatConstIterator.html',1,'cv']]],
  ['sparsematconstiterator_5f',['SparseMatConstIterator_',['http://docs.opencv.org/3.4.0/d9/d29/classcv_1_1SparseMatConstIterator__.html',1,'cv']]],
  ['sparsematiterator',['SparseMatIterator',['http://docs.opencv.org/3.4.0/d5/d9b/classcv_1_1SparseMatIterator.html',1,'cv']]],
  ['sparsematiterator_5f',['SparseMatIterator_',['http://docs.opencv.org/3.4.0/d3/d24/classcv_1_1SparseMatIterator__.html',1,'cv']]],
  ['sparseopticalflow',['SparseOpticalFlow',['http://docs.opencv.org/3.4.0/de/d14/classcv_1_1SparseOpticalFlow.html',1,'cv']]],
  ['sparseopticalflow',['SparseOpticalFlow',['http://docs.opencv.org/3.4.0/d5/dcf/classcv_1_1cuda_1_1SparseOpticalFlow.html',1,'cv::cuda']]],
  ['sparsepyrlkoptflowestimator',['SparsePyrLkOptFlowEstimator',['http://docs.opencv.org/3.4.0/d1/d4b/classcv_1_1videostab_1_1SparsePyrLkOptFlowEstimator.html',1,'cv::videostab']]],
  ['sparsepyrlkopticalflow',['SparsePyrLKOpticalFlow',['http://docs.opencv.org/3.4.0/d7/d08/classcv_1_1SparsePyrLKOpticalFlow.html',1,'cv']]],
  ['sparsepyrlkopticalflow',['SparsePyrLKOpticalFlow',['http://docs.opencv.org/3.4.0/d7/d05/classcv_1_1cuda_1_1SparsePyrLKOpticalFlow.html',1,'cv::cuda']]],
  ['sphericalportraitprojector',['SphericalPortraitProjector',['http://docs.opencv.org/3.4.0/d3/d0d/structcv_1_1detail_1_1SphericalPortraitProjector.html',1,'cv::detail']]],
  ['sphericalportraitwarper',['SphericalPortraitWarper',['http://docs.opencv.org/3.4.0/d8/d70/classcv_1_1detail_1_1SphericalPortraitWarper.html',1,'cv::detail']]],
  ['sphericalprojector',['SphericalProjector',['http://docs.opencv.org/3.4.0/d0/d88/structcv_1_1detail_1_1SphericalProjector.html',1,'cv::detail']]],
  ['sphericalwarper',['SphericalWarper',['http://docs.opencv.org/3.4.0/d6/dd0/classcv_1_1detail_1_1SphericalWarper.html',1,'cv::detail']]],
  ['sphericalwarper',['SphericalWarper',['http://docs.opencv.org/3.4.0/d3/d3c/classcv_1_1SphericalWarper.html',1,'cv']]],
  ['sphericalwarpergpu',['SphericalWarperGpu',['http://docs.opencv.org/3.4.0/db/d09/classcv_1_1detail_1_1SphericalWarperGpu.html',1,'cv::detail']]],
  ['splay_5ftree_5fmap',['splay_tree_map',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10948.html',1,'__gnu_pbds::detail']]],
  ['splay_5ftree_5fnode_5f',['splay_tree_node_',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10940.html',1,'__gnu_pbds::detail']]],
  ['splay_5ftree_5ftag',['splay_tree_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10168.html',1,'__gnu_pbds']]],
  ['split',['Split',['http://docs.opencv.org/3.4.0/d9/d37/classcv_1_1ml_1_1DTrees_1_1Split.html',1,'cv::ml::DTrees']]],
  ['splitlayer',['SplitLayer',['http://docs.opencv.org/3.4.0/dd/df9/classcv_1_1dnn_1_1SplitLayer.html',1,'cv::dnn']]],
  ['sqr_5ffunc',['sqr_func',['http://docs.opencv.org/3.4.0/d9/d1d/structcv_1_1cudev_1_1sqr__func.html',1,'cv::cudev']]],
  ['sqrt_5ffunc',['sqrt_func',['http://docs.opencv.org/3.4.0/d9/d47/structcv_1_1cudev_1_1sqrt__func.html',1,'cv::cudev']]],
  ['sqrt_5ffunc_3c_20double_20_3e',['sqrt_func&lt; double &gt;',['http://docs.opencv.org/3.4.0/d4/d9d/structcv_1_1cudev_1_1sqrt__func_3_01double_01_4.html',1,'cv::cudev']]],
  ['sqrt_5ffunc_3c_20float_20_3e',['sqrt_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/d8/dd2/structcv_1_1cudev_1_1sqrt__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['sqrt_5ffunc_3c_20schar_20_3e',['sqrt_func&lt; schar &gt;',['http://docs.opencv.org/3.4.0/da/d64/structcv_1_1cudev_1_1sqrt__func_3_01schar_01_4.html',1,'cv::cudev']]],
  ['sqrt_5ffunc_3c_20short_20_3e',['sqrt_func&lt; short &gt;',['http://docs.opencv.org/3.4.0/d2/d6a/structcv_1_1cudev_1_1sqrt__func_3_01short_01_4.html',1,'cv::cudev']]],
  ['sqrt_5ffunc_3c_20uchar_20_3e',['sqrt_func&lt; uchar &gt;',['http://docs.opencv.org/3.4.0/d9/d33/structcv_1_1cudev_1_1sqrt__func_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['sqrt_5ffunc_3c_20uint_20_3e',['sqrt_func&lt; uint &gt;',['http://docs.opencv.org/3.4.0/d0/d7b/structcv_1_1cudev_1_1sqrt__func_3_01uint_01_4.html',1,'cv::cudev']]],
  ['sqrt_5ffunc_3c_20ushort_20_3e',['sqrt_func&lt; ushort &gt;',['http://docs.opencv.org/3.4.0/df/df4/structcv_1_1cudev_1_1sqrt__func_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['squaredistance',['squareDistance',['http://docs.opencv.org/3.4.0/dc/d68/structcvflann_1_1squareDistance.html',1,'cvflann']]],
  ['squaredistance_3c_20chisquaredistance_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['squareDistance&lt; ChiSquareDistance&lt; ElementType &gt;, ElementType &gt;',['http://docs.opencv.org/3.4.0/d2/deb/structcvflann_1_1squareDistance_3_01ChiSquareDistance_3_01ElementType_01_4_00_01ElementType_01_4.html',1,'cvflann']]],
  ['squaredistance_3c_20hellingerdistance_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['squareDistance&lt; HellingerDistance&lt; ElementType &gt;, ElementType &gt;',['http://docs.opencv.org/3.4.0/dc/d3f/structcvflann_1_1squareDistance_3_01HellingerDistance_3_01ElementType_01_4_00_01ElementType_01_4.html',1,'cvflann']]],
  ['squaredistance_3c_20l2_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['squareDistance&lt; L2&lt; ElementType &gt;, ElementType &gt;',['http://docs.opencv.org/3.4.0/d8/db8/structcvflann_1_1squareDistance_3_01L2_3_01ElementType_01_4_00_01ElementType_01_4.html',1,'cvflann']]],
  ['squaredistance_3c_20l2_5fsimple_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['squareDistance&lt; L2_Simple&lt; ElementType &gt;, ElementType &gt;',['http://docs.opencv.org/3.4.0/d3/d86/structcvflann_1_1squareDistance_3_01L2__Simple_3_01ElementType_01_4_00_01ElementType_01_4.html',1,'cvflann']]],
  ['squaredistance_3c_20minkowskidistance_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['squareDistance&lt; MinkowskiDistance&lt; ElementType &gt;, ElementType &gt;',['http://docs.opencv.org/3.4.0/dc/d73/structcvflann_1_1squareDistance_3_01MinkowskiDistance_3_01ElementType_01_4_00_01ElementType_01_4.html',1,'cvflann']]],
  ['stabilizerbase',['StabilizerBase',['http://docs.opencv.org/3.4.0/d2/d6c/classcv_1_1videostab_1_1StabilizerBase.html',1,'cv::videostab']]],
  ['stack',['stack',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06780.html',1,'std']]],
  ['stack_3c_20_5fstateseqt_20_3e',['stack&lt; _StateSeqT &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06780.html',1,'']]],
  ['standardcollector',['StandardCollector',['http://docs.opencv.org/3.4.0/d4/d8d/classcv_1_1face_1_1StandardCollector.html',1,'cv::face']]],
  ['stardetector',['StarDetector',['http://docs.opencv.org/3.4.0/dd/d39/classcv_1_1xfeatures2d_1_1StarDetector.html',1,'cv::xfeatures2d']]],
  ['starkernelcensus',['StarKernelCensus',['http://docs.opencv.org/3.4.0/db/d3b/classcv_1_1stereo_1_1StarKernelCensus.html',1,'cv::stereo']]],
  ['startstoptimer',['StartStopTimer',['http://docs.opencv.org/3.4.0/de/dd0/classcvflann_1_1StartStopTimer.html',1,'cvflann']]],
  ['staticsaliency',['StaticSaliency',['http://docs.opencv.org/3.4.0/d5/d87/classcv_1_1saliency_1_1StaticSaliency.html',1,'cv::saliency']]],
  ['staticsaliencyfinegrained',['StaticSaliencyFineGrained',['http://docs.opencv.org/3.4.0/da/dd0/classcv_1_1saliency_1_1StaticSaliencyFineGrained.html',1,'cv::saliency']]],
  ['staticsaliencyspectralresidual',['StaticSaliencySpectralResidual',['http://docs.opencv.org/3.4.0/df/d37/classcv_1_1saliency_1_1StaticSaliencySpectralResidual.html',1,'cv::saliency']]],
  ['statmodel',['StatModel',['http://docs.opencv.org/3.4.0/db/d7d/classcv_1_1ml_1_1StatModel.html',1,'cv::ml']]],
  ['stdio_5ffilebuf',['stdio_filebuf',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09588.html',1,'__gnu_cxx']]],
  ['stdio_5fsync_5ffilebuf',['stdio_sync_filebuf',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09592.html',1,'__gnu_cxx']]],
  ['steady_5fclock',['steady_clock',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01916.html',1,'std::chrono::_V2']]],
  ['stereobeliefpropagation',['StereoBeliefPropagation',['http://docs.opencv.org/3.4.0/de/d7a/classcv_1_1cuda_1_1StereoBeliefPropagation.html',1,'cv::cuda']]],
  ['stereobinarybm',['StereoBinaryBM',['http://docs.opencv.org/3.4.0/d7/d8e/classcv_1_1stereo_1_1StereoBinaryBM.html',1,'cv::stereo']]],
  ['stereobinarysgbm',['StereoBinarySGBM',['http://docs.opencv.org/3.4.0/d1/d9f/classcv_1_1stereo_1_1StereoBinarySGBM.html',1,'cv::stereo']]],
  ['stereobm',['StereoBM',['http://docs.opencv.org/3.4.0/d9/dba/classcv_1_1StereoBM.html',1,'cv']]],
  ['stereobm',['StereoBM',['http://docs.opencv.org/3.4.0/db/d8a/classcv_1_1cuda_1_1StereoBM.html',1,'cv::cuda']]],
  ['stereoconstantspacebp',['StereoConstantSpaceBP',['http://docs.opencv.org/3.4.0/d7/d09/classcv_1_1cuda_1_1StereoConstantSpaceBP.html',1,'cv::cuda']]],
  ['stereographicprojector',['StereographicProjector',['http://docs.opencv.org/3.4.0/d0/ddf/structcv_1_1detail_1_1StereographicProjector.html',1,'cv::detail']]],
  ['stereographicwarper',['StereographicWarper',['http://docs.opencv.org/3.4.0/d1/d3d/classcv_1_1detail_1_1StereographicWarper.html',1,'cv::detail']]],
  ['stereographicwarper',['StereographicWarper',['http://docs.opencv.org/3.4.0/d2/d5e/classcv_1_1StereographicWarper.html',1,'cv']]],
  ['stereomatcher',['StereoMatcher',['http://docs.opencv.org/3.4.0/d2/d6e/classcv_1_1StereoMatcher.html',1,'cv']]],
  ['stereomatcher',['StereoMatcher',['http://docs.opencv.org/3.4.0/d9/d07/classcv_1_1stereo_1_1StereoMatcher.html',1,'cv::stereo']]],
  ['stereosgbm',['StereoSGBM',['http://docs.opencv.org/3.4.0/d2/d85/classcv_1_1StereoSGBM.html',1,'cv']]],
  ['stitcher',['Stitcher',['http://docs.opencv.org/3.4.0/d2/d8d/classcv_1_1Stitcher.html',1,'cv']]],
  ['stored_5fdata',['stored_data',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10452.html',1,'__gnu_pbds::detail']]],
  ['stored_5fdata_3c_20_5ftv_2c_20null_5ftype_20_3e',['stored_data&lt; _Tv, null_type &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10456.html',1,'__gnu_pbds::detail']]],
  ['stored_5fhash',['stored_hash',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10448.html',1,'__gnu_pbds::detail']]],
  ['stored_5fvalue',['stored_value',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10444.html',1,'__gnu_pbds::detail']]],
  ['stream',['Stream',['http://docs.opencv.org/3.4.0/d9/df3/classcv_1_1cuda_1_1Stream.html',1,'cv::cuda']]],
  ['streamaccessor',['StreamAccessor',['http://docs.opencv.org/3.4.0/d6/df1/structcv_1_1cuda_1_1StreamAccessor.html',1,'cv::cuda']]],
  ['string',['String',['http://docs.opencv.org/3.4.0/d1/d8f/classcv_1_1String.html',1,'cv']]],
  ['string_5ftag',['string_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10136.html',1,'__gnu_pbds']]],
  ['strongclassifierdirectselection',['StrongClassifierDirectSelection',['http://docs.opencv.org/3.4.0/d4/d1e/classcv_1_1StrongClassifierDirectSelection.html',1,'cv']]],
  ['structurededgedetection',['StructuredEdgeDetection',['http://docs.opencv.org/3.4.0/d8/d54/classcv_1_1ximgproc_1_1StructuredEdgeDetection.html',1,'cv::ximgproc']]],
  ['structuredlightpattern',['StructuredLightPattern',['http://docs.opencv.org/3.4.0/d9/dbb/classcv_1_1structured__light_1_1StructuredLightPattern.html',1,'cv::structured_light']]],
  ['student_5ft_5fdistribution',['student_t_distribution',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05488.html',1,'std']]],
  ['sub_5fmatch',['sub_match',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05800.html',1,'std']]],
  ['sub_5fmatch_3c_20_5fbi_5fiter_20_3e',['sub_match&lt; _Bi_iter &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05800.html',1,'']]],
  ['subdiv2d',['Subdiv2D',['http://docs.opencv.org/3.4.0/df/dbf/classcv_1_1Subdiv2D.html',1,'cv']]],
  ['subtract_5fwith_5fcarry_5fengine',['subtract_with_carry_engine',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05408.html',1,'std']]],
  ['subtractive_5frng',['subtractive_rng',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08144.html',1,'__gnu_cxx']]],
  ['sum',['Sum',['http://docs.opencv.org/3.4.0/d8/d60/structcv_1_1cudev_1_1Sum.html',1,'cv::cudev']]],
  ['sumexprbody',['SumExprBody',['http://docs.opencv.org/3.4.0/dd/d33/structcv_1_1cudev_1_1SumExprBody.html',1,'cv::cudev']]],
  ['superpixellsc',['SuperpixelLSC',['http://docs.opencv.org/3.4.0/d5/da0/classcv_1_1ximgproc_1_1SuperpixelLSC.html',1,'cv::ximgproc']]],
  ['superpixelseeds',['SuperpixelSEEDS',['http://docs.opencv.org/3.4.0/df/d81/classcv_1_1ximgproc_1_1SuperpixelSEEDS.html',1,'cv::ximgproc']]],
  ['superpixelslic',['SuperpixelSLIC',['http://docs.opencv.org/3.4.0/d3/da9/classcv_1_1ximgproc_1_1SuperpixelSLIC.html',1,'cv::ximgproc']]],
  ['superresolution',['SuperResolution',['http://docs.opencv.org/3.4.0/d9/dd6/classcv_1_1superres_1_1SuperResolution.html',1,'cv::superres']]],
  ['surf',['SURF',['http://docs.opencv.org/3.4.0/d5/df7/classcv_1_1xfeatures2d_1_1SURF.html',1,'cv::xfeatures2d']]],
  ['surf_5fcuda',['SURF_CUDA',['http://docs.opencv.org/3.4.0/db/d06/classcv_1_1cuda_1_1SURF__CUDA.html',1,'cv::cuda']]],
  ['surffeaturesfinder',['SurfFeaturesFinder',['http://docs.opencv.org/3.4.0/df/d27/classcv_1_1detail_1_1SurfFeaturesFinder.html',1,'cv::detail']]],
  ['svd',['SVD',['http://docs.opencv.org/3.4.0/df/df7/classcv_1_1SVD.html',1,'cv']]],
  ['svm',['SVM',['http://docs.opencv.org/3.4.0/d1/d2d/classcv_1_1ml_1_1SVM.html',1,'cv::ml']]],
  ['svmsgd',['SVMSGD',['http://docs.opencv.org/3.4.0/de/d54/classcv_1_1ml_1_1SVMSGD.html',1,'cv::ml']]],
  ['symetriccensus',['SymetricCensus',['http://docs.opencv.org/3.4.0/dd/d24/classcv_1_1stereo_1_1SymetricCensus.html',1,'cv::stereo']]],
  ['synth_5faccess_5ftraits',['synth_access_traits',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10876.html',1,'__gnu_pbds::detail']]],
  ['syntheticsequencegenerator',['SyntheticSequenceGenerator',['http://docs.opencv.org/3.4.0/d1/dda/classcv_1_1bgsegm_1_1SyntheticSequenceGenerator.html',1,'cv::bgsegm']]],
  ['system_5fclock',['system_clock',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01912.html',1,'std::chrono::_V2']]],
  ['system_5ferror',['system_error',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02964.html',1,'std']]]
];
