var searchData=
[
  ['hal_2ehpp',['hal.hpp',['http://docs.opencv.org/3.4.0/de/d0c/core_2include_2opencv2_2core_2hal_2hal_8hpp.html',1,'(Global Namespace)'],['http://docs.opencv.org/3.4.0/d4/d44/imgproc_2include_2opencv2_2imgproc_2hal_2hal_8hpp.html',1,'(Global Namespace)']]],
  ['hal_5freplacement_2ehpp',['hal_replacement.hpp',['http://docs.opencv.org/3.4.0/db/ddd/core_2src_2hal__replacement_8hpp.html',1,'(Global Namespace)'],['http://docs.opencv.org/3.4.0/df/d91/imgproc_2src_2hal__replacement_8hpp.html',1,'(Global Namespace)']]],
  ['harris_5fdetector_2emarkdown',['harris_detector.markdown',['http://docs.opencv.org/3.4.0/db/d48/harris__detector_8markdown.html',1,'']]],
  ['hash_5fbytes_2eh',['hash_bytes.h',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00362.html',1,'']]],
  ['hash_5feq_5ffn_2ehpp',['hash_eq_fn.hpp',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01295.html',1,'']]],
  ['hash_5fexponential_5fsize_5fpolicy_5fimp_2ehpp',['hash_exponential_size_policy_imp.hpp',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01400.html',1,'']]],
  ['hash_5ffun_2eh',['hash_fun.h',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00722.html',1,'']]],
  ['hash_5fload_5fcheck_5fresize_5ftrigger_5fimp_2ehpp',['hash_load_check_resize_trigger_imp.hpp',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01403.html',1,'']]],
  ['hash_5fload_5fcheck_5fresize_5ftrigger_5fsize_5fbase_2ehpp',['hash_load_check_resize_trigger_size_base.hpp',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01406.html',1,'']]],
  ['hash_5fmap',['hash_map',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00725.html',1,'']]],
  ['hash_5fpolicy_2ehpp',['hash_policy.hpp',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01118.html',1,'']]],
  ['hash_5fprime_5fsize_5fpolicy_5fimp_2ehpp',['hash_prime_size_policy_imp.hpp',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01409.html',1,'']]],
  ['hash_5fset',['hash_set',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00728.html',1,'']]],
  ['hash_5fstandard_5fresize_5fpolicy_5fimp_2ehpp',['hash_standard_resize_policy_imp.hpp',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01412.html',1,'']]],
  ['hashtable_5fpolicy_2eh',['hashtable_policy.h',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00368.html',1,'']]],
  ['hdf_2ehpp',['hdf.hpp',['http://docs.opencv.org/3.4.0/d7/d55/hdf_8hpp.html',1,'']]],
  ['hdf5_2eh',['hdf5.h',['http://docs.opencv.org/3.4.0/db/d87/hdf5_8h.html',1,'']]],
  ['hdf5_2ehpp',['hdf5.hpp',['http://docs.opencv.org/3.4.0/de/d24/hdf5_8hpp.html',1,'']]],
  ['hdr_5fimaging_2emarkdown',['hdr_imaging.markdown',['http://docs.opencv.org/3.4.0/d9/d87/hdr__imaging_8markdown.html',1,'']]],
  ['heap_2eh',['heap.h',['http://docs.opencv.org/3.4.0/da/ddb/heap_8h.html',1,'']]],
  ['hello_2emarkdown',['hello.markdown',['http://docs.opencv.org/3.4.0/da/da0/hello_8markdown.html',1,'']]],
  ['helper_5ffunctions_2eh',['helper_functions.h',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00746.html',1,'']]],
  ['hierarchical_5fclustering_5findex_2eh',['hierarchical_clustering_index.h',['http://docs.opencv.org/3.4.0/de/d1d/hierarchical__clustering__index_8h.html',1,'']]],
  ['highgui_2ehpp',['highgui.hpp',['http://docs.opencv.org/3.4.0/d0/dce/highgui_2highgui_8hpp.html',1,'(Global Namespace)'],['http://docs.opencv.org/3.4.0/d4/dd5/highgui_8hpp.html',1,'(Global Namespace)']]],
  ['highgui_5fc_2eh',['highgui_c.h',['http://docs.opencv.org/3.4.0/d5/d59/highgui__c_8h.html',1,'']]],
  ['highgui_5fwinrt_2ehpp',['highgui_winrt.hpp',['http://docs.opencv.org/3.4.0/d9/d22/highgui__winrt_8hpp.html',1,'']]],
  ['hist_5fcost_2ehpp',['hist_cost.hpp',['http://docs.opencv.org/3.4.0/df/d08/hist__cost_8hpp.html',1,'']]],
  ['histo3d_2emarkdown',['histo3D.markdown',['http://docs.opencv.org/3.4.0/df/dd7/histo3D_8markdown.html',1,'']]],
  ['histogram_2ehpp',['histogram.hpp',['http://docs.opencv.org/3.4.0/d5/d6e/histogram_8hpp.html',1,'']]],
  ['histogram_5fcalculation_2emarkdown',['histogram_calculation.markdown',['http://docs.opencv.org/3.4.0/d2/d3a/histogram__calculation_8markdown.html',1,'']]],
  ['histogram_5fcomparison_2emarkdown',['histogram_comparison.markdown',['http://docs.opencv.org/3.4.0/de/d12/histogram__comparison_8markdown.html',1,'']]],
  ['histogram_5fequalization_2emarkdown',['histogram_equalization.markdown',['http://docs.opencv.org/3.4.0/db/de8/histogram__equalization_8markdown.html',1,'']]],
  ['histogramphaseunwrapping_2ehpp',['histogramphaseunwrapping.hpp',['http://docs.opencv.org/3.4.0/df/dce/histogramphaseunwrapping_8hpp.html',1,'']]],
  ['hitormiss_2emarkdown',['hitOrMiss.markdown',['http://docs.opencv.org/3.4.0/d2/dbf/hitOrMiss_8markdown.html',1,'']]],
  ['homography_2emarkdown',['homography.markdown',['http://docs.opencv.org/3.4.0/d2/dc8/homography_8markdown.html',1,'']]],
  ['hough_5fcircle_2emarkdown',['hough_circle.markdown',['http://docs.opencv.org/3.4.0/d4/d67/hough__circle_8markdown.html',1,'']]],
  ['hough_5flines_2emarkdown',['hough_lines.markdown',['http://docs.opencv.org/3.4.0/da/d5a/hough__lines_8markdown.html',1,'']]],
  ['how_5fto_5fscan_5fimages_2emarkdown',['how_to_scan_images.markdown',['http://docs.opencv.org/3.4.0/d5/d91/how__to__scan__images_8markdown.html',1,'']]],
  ['how_5fto_5fuse_5fippa_5fconversion_2emarkdown',['how_to_use_ippa_conversion.markdown',['http://docs.opencv.org/3.4.0/da/d1e/how__to__use__ippa__conversion_8markdown.html',1,'']]],
  ['how_5fto_5fuse_5fopencv_5fparallel_5ffor_5f_2emarkdown',['how_to_use_OpenCV_parallel_for_.markdown',['http://docs.opencv.org/3.4.0/d5/d45/how__to__use__OpenCV__parallel__for___8markdown.html',1,'']]],
  ['hpe_5fhumaneva_2ehpp',['hpe_humaneva.hpp',['http://docs.opencv.org/3.4.0/d8/da7/hpe__humaneva_8hpp.html',1,'']]],
  ['hpe_5fparse_2ehpp',['hpe_parse.hpp',['http://docs.opencv.org/3.4.0/da/da9/hpe__parse_8hpp.html',1,'']]],
  ['hull_2emarkdown',['hull.markdown',['http://docs.opencv.org/3.4.0/d0/dbd/hull_8markdown.html',1,'']]]
];
