var searchData=
[
  ['singular_20value_20matrix_20decomposition',['Singular value matrix decomposition',['http://docs.opencv.org/3.4.0/dd/d2a/group__core__hal__interface__decomp__svd.html',1,'']]],
  ['square_20root_20calculation',['Square root calculation',['http://docs.opencv.org/3.4.0/d5/dc3/group__core__hal__interface__sqrt.html',1,'']]],
  ['softfloat_20support',['Softfloat support',['http://docs.opencv.org/3.4.0/d7/dcc/group__core__utils__softfloat.html',1,'']]],
  ['sse_20utilities',['SSE utilities',['http://docs.opencv.org/3.4.0/d6/d06/group__core__utils__sse.html',1,'']]],
  ['stereo_20correspondence',['Stereo Correspondence',['http://docs.opencv.org/3.4.0/dd/d47/group__cudastereo.html',1,'']]],
  ['slam',['SLAM',['http://docs.opencv.org/3.4.0/dc/dfb/group__datasets__slam.html',1,'']]],
  ['structural_20analysis_20and_20shape_20descriptors',['Structural Analysis and Shape Descriptors',['http://docs.opencv.org/3.4.0/d3/dc0/group__imgproc__shape.html',1,'']]],
  ['seamless_20cloning',['Seamless Cloning',['http://docs.opencv.org/3.4.0/df/da0/group__photo__clone.html',1,'']]],
  ['saliency_20api',['Saliency API',['http://docs.opencv.org/3.4.0/d8/d65/group__saliency.html',1,'']]],
  ['sequences',['Sequences',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01467.html',1,'']]],
  ['set_20operation',['Set Operation',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01489.html',1,'']]],
  ['structure_20from_20motion',['Structure From Motion',['http://docs.opencv.org/3.4.0/d8/d8c/group__sfm.html',1,'']]],
  ['sgi',['SGI',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01465.html',1,'']]],
  ['shape_20distance_20and_20matching',['Shape Distance and Matching',['http://docs.opencv.org/3.4.0/d1/d85/group__shape.html',1,'']]],
  ['simple_20pipeline',['Simple Pipeline',['http://docs.opencv.org/3.4.0/d7/de2/group__simple__pipeline.html',1,'']]],
  ['sorting',['Sorting',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01488.html',1,'']]],
  ['stereo_20correspondance_20algorithms',['Stereo Correspondance Algorithms',['http://docs.opencv.org/3.4.0/dd/d86/group__stereo.html',1,'']]],
  ['seam_20estimation',['Seam Estimation',['http://docs.opencv.org/3.4.0/d9/d24/group__stitching__seam.html',1,'']]],
  ['strings',['Strings',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01512.html',1,'']]],
  ['structured_20light_20api',['Structured Light API',['http://docs.opencv.org/3.4.0/d1/d90/group__structured__light.html',1,'']]],
  ['super_20resolution',['Super Resolution',['http://docs.opencv.org/3.4.0/d7/d0a/group__superres.html',1,'']]],
  ['surface_20matching',['Surface Matching',['http://docs.opencv.org/3.4.0/d9/d25/group__surface__matching.html',1,'']]],
  ['scene_20text_20detection_20and_20recognition',['Scene Text Detection and Recognition',['http://docs.opencv.org/3.4.0/d4/d61/group__text.html',1,'']]],
  ['scene_20text_20detection',['Scene Text Detection',['http://docs.opencv.org/3.4.0/da/d56/group__text__detect.html',1,'']]],
  ['scene_20text_20recognition',['Scene Text Recognition',['http://docs.opencv.org/3.4.0/d8/df2/group__text__recognize.html',1,'']]],
  ['structured_20forests_20for_20fast_20edge_20detection',['Structured forests for fast edge detection',['http://docs.opencv.org/3.4.0/de/d51/group__ximgproc__edge.html',1,'']]],
  ['superpixels',['Superpixels',['http://docs.opencv.org/3.4.0/df/d6c/group__ximgproc__superpixel.html',1,'']]]
];
