var searchData=
[
  ['cuda_20module_20introduction',['CUDA Module Introduction',['http://docs.opencv.org/3.4.0/d2/dbc/cuda_intro.html',1,'']]],
  ['color_20conversions',['Color conversions',['http://docs.opencv.org/3.4.0/de/d25/imgproc_color_conversions.html',1,'']]],
  ['cross_20compilation_20for_20arm_20based_20linux_20systems',['Cross compilation for ARM based Linux systems',['http://docs.opencv.org/3.4.0/d0/d76/tutorial_arm_crosscompile_with_cmake.html',1,'']]],
  ['calibration_20with_20aruco_20and_20charuco',['Calibration with ArUco and ChArUco',['http://docs.opencv.org/3.4.0/da/d13/tutorial_aruco_calibration.html',1,'']]],
  ['changing_20the_20contrast_20and_20brightness_20of_20an_20image_21',['Changing the contrast and brightness of an image!',['http://docs.opencv.org/3.4.0/d3/dc1/tutorial_basic_linear_transform.html',1,'']]],
  ['creating_20bounding_20boxes_20and_20circles_20for_20contours',['Creating Bounding boxes and circles for contours',['http://docs.opencv.org/3.4.0/da/d0c/tutorial_bounding_rects_circles.html',1,'']]],
  ['creating_20bounding_20rotated_20boxes_20and_20ellipses_20for_20contours',['Creating Bounding rotated boxes and ellipses for contours',['http://docs.opencv.org/3.4.0/de/d62/tutorial_bounding_rotated_ellipses.html',1,'']]],
  ['camera_20calibration_20with_20opencv',['Camera calibration With OpenCV',['http://docs.opencv.org/3.4.0/d4/d94/tutorial_camera_calibration.html',1,'']]],
  ['camera_20calibration_20with_20square_20chessboard',['Camera calibration with square chessboard',['http://docs.opencv.org/3.4.0/dc/d43/tutorial_camera_calibration_square_chess.html',1,'']]],
  ['canny_20edge_20detector',['Canny Edge Detector',['http://docs.opencv.org/3.4.0/da/d5c/tutorial_canny_detector.html',1,'']]],
  ['capture_20gray_20code_20pattern_20tutorial',['Capture Gray code pattern tutorial',['http://docs.opencv.org/3.4.0/db/d56/tutorial_capture_graycode_pattern.html',1,'']]],
  ['capture_20sinusoidal_20pattern_20tutorial',['Capture Sinusoidal pattern tutorial',['http://docs.opencv.org/3.4.0/d0/de8/tutorial_capture_sinusoidal_pattern.html',1,'']]],
  ['cascade_20classifier',['Cascade Classifier',['http://docs.opencv.org/3.4.0/db/d28/tutorial_cascade_classifier.html',1,'']]],
  ['creating_20widgets',['Creating Widgets',['http://docs.opencv.org/3.4.0/d2/d64/tutorial_creating_widgets.html',1,'']]],
  ['cross_20referencing_20opencv_20from_20other_20doxygen_20projects',['Cross referencing OpenCV from other Doxygen projects',['http://docs.opencv.org/3.4.0/d3/dff/tutorial_cross_referencing.html',1,'']]],
  ['customizing_20the_20cn_20tracker',['Customizing the CN Tracker',['http://docs.opencv.org/3.4.0/dc/db8/tutorial_customizing_cn_tracker.html',1,'']]],
  ['classify',['Classify',['http://docs.opencv.org/3.4.0/df/d38/tutorial_feature_classification.html',1,'']]],
  ['creating_20yor_20own_20corner_20detector',['Creating yor own corner detector',['http://docs.opencv.org/3.4.0/d9/dbc/tutorial_generic_corner_detector.html',1,'']]],
  ['creating_20a_203d_20histogram',['Creating a 3D histogram',['http://docs.opencv.org/3.4.0/d1/d1d/tutorial_histo3D.html',1,'']]],
  ['convex_20hull',['Convex Hull',['http://docs.opencv.org/3.4.0/d7/d1d/tutorial_hull.html',1,'']]],
  ['canny_20edge_20detection',['Canny Edge Detection',['http://docs.opencv.org/3.4.0/d7/de1/tutorial_js_canny.html',1,'']]],
  ['changing_20colorspaces',['Changing Colorspaces',['http://docs.opencv.org/3.4.0/db/d64/tutorial_js_colorspaces.html',1,'']]],
  ['contour_20features',['Contour Features',['http://docs.opencv.org/3.4.0/dc/dcf/tutorial_js_contour_features.html',1,'']]],
  ['contour_20properties',['Contour Properties',['http://docs.opencv.org/3.4.0/da/dc1/tutorial_js_contour_properties.html',1,'']]],
  ['contours_20_3a_20getting_20started',['Contours : Getting Started',['http://docs.opencv.org/3.4.0/d5/daa/tutorial_js_contours_begin.html',1,'']]],
  ['contours_20hierarchy',['Contours Hierarchy',['http://docs.opencv.org/3.4.0/da/d0a/tutorial_js_contours_hierarchy.html',1,'']]],
  ['contours_20_3a_20more_20functions',['Contours : More Functions',['http://docs.opencv.org/3.4.0/d8/d1c/tutorial_js_contours_more_functions.html',1,'']]],
  ['contours_20in_20opencv_2ejs',['Contours in OpenCV.js',['http://docs.opencv.org/3.4.0/d0/d43/tutorial_js_table_of_contents_contours.html',1,'']]],
  ['core_20operations',['Core Operations',['http://docs.opencv.org/3.4.0/d1/d78/tutorial_js_table_of_contents_core.html',1,'']]],
  ['camera_20calibration',['Camera Calibration',['http://docs.opencv.org/3.4.0/dc/dbb/tutorial_py_calibration.html',1,'']]],
  ['canny_20edge_20detection',['Canny Edge Detection',['http://docs.opencv.org/3.4.0/da/d22/tutorial_py_canny.html',1,'']]],
  ['changing_20colorspaces',['Changing Colorspaces',['http://docs.opencv.org/3.4.0/df/d9d/tutorial_py_colorspaces.html',1,'']]],
  ['contour_20features',['Contour Features',['http://docs.opencv.org/3.4.0/dd/d49/tutorial_py_contour_features.html',1,'']]],
  ['contour_20properties',['Contour Properties',['http://docs.opencv.org/3.4.0/d1/d32/tutorial_py_contour_properties.html',1,'']]],
  ['contours_20_3a_20getting_20started',['Contours : Getting Started',['http://docs.opencv.org/3.4.0/d4/d73/tutorial_py_contours_begin.html',1,'']]],
  ['contours_20hierarchy',['Contours Hierarchy',['http://docs.opencv.org/3.4.0/d9/d8b/tutorial_py_contours_hierarchy.html',1,'']]],
  ['contours_20_3a_20more_20functions',['Contours : More Functions',['http://docs.opencv.org/3.4.0/d5/d45/tutorial_py_contours_more_functions.html',1,'']]],
  ['camera_20calibration_20and_203d_20reconstruction',['Camera Calibration and 3D Reconstruction',['http://docs.opencv.org/3.4.0/d9/db7/tutorial_py_table_of_contents_calib3d.html',1,'']]],
  ['contours_20in_20opencv',['Contours in OpenCV',['http://docs.opencv.org/3.4.0/d3/d05/tutorial_py_table_of_contents_contours.html',1,'']]],
  ['core_20operations',['Core Operations',['http://docs.opencv.org/3.4.0/d7/d16/tutorial_py_table_of_contents_core.html',1,'']]],
  ['computational_20photography',['Computational Photography',['http://docs.opencv.org/3.4.0/d0/d07/tutorial_py_table_of_contents_photo.html',1,'']]],
  ['camera_20motion_20estimation',['Camera Motion Estimation',['http://docs.opencv.org/3.4.0/d5/dab/tutorial_sfm_trajectory_estimation.html',1,'']]],
  ['camera_20calibration_20and_203d_20reconstruction_20_28calib3d_20module_29',['Camera calibration and 3D reconstruction (calib3d module)',['http://docs.opencv.org/3.4.0/d6/d55/tutorial_table_of_content_calib3d.html',1,'']]],
  ['cnn_20for_203d_20object_20classification_20and_20pose_20estimation',['CNN for 3D Object Classification and Pose Estimation',['http://docs.opencv.org/3.4.0/d2/d42/tutorial_table_of_content_cnn_3dobj.html',1,'']]],
  ['computational_20photography_20_28photo_20module_29',['Computational photography (photo module)',['http://docs.opencv.org/3.4.0/da/de7/tutorial_table_of_content_photo.html',1,'']]],
  ['cascade_20classifier_20training',['Cascade Classifier Training',['http://docs.opencv.org/3.4.0/dc/d88/tutorial_traincascade.html',1,'']]],
  ['creating_20a_20video_20with_20opencv',['Creating a video with OpenCV',['http://docs.opencv.org/3.4.0/d7/d9e/tutorial_video_write.html',1,'']]]
];
