var searchData=
[
  ['how_20to_20use_20background_20subtraction_20methods',['How to Use Background Subtraction Methods',['http://docs.opencv.org/3.4.0/d1/dc5/tutorial_background_subtraction.html',1,'']]],
  ['how_20to_20run_20deep_20networks_20on_20android_20device',['How to run deep networks on Android device',['http://docs.opencv.org/3.4.0/d0/d6c/tutorial_dnn_android.html',1,'']]],
  ['how_20to_20enable_20halide_20backend_20for_20improve_20efficiency',['How to enable Halide backend for improve efficiency',['http://docs.opencv.org/3.4.0/de/d37/tutorial_dnn_halide.html',1,'']]],
  ['how_20to_20schedule_20your_20network_20for_20halide_20backend',['How to schedule your network for Halide backend',['http://docs.opencv.org/3.4.0/de/d5d/tutorial_dnn_halide_scheduling.html',1,'']]],
  ['how_20to_20run_20deep_20networks_20in_20browser',['How to run deep networks in browser',['http://docs.opencv.org/3.4.0/d5/d86/tutorial_dnn_javascript.html',1,'']]],
  ['harris_20corner_20detector',['Harris corner detector',['http://docs.opencv.org/3.4.0/d4/d7d/tutorial_harris_detector.html',1,'']]],
  ['high_20dynamic_20range_20imaging',['High Dynamic Range Imaging',['http://docs.opencv.org/3.4.0/d3/db7/tutorial_hdr_imaging.html',1,'']]],
  ['histogram_20calculation',['Histogram Calculation',['http://docs.opencv.org/3.4.0/d8/dbc/tutorial_histogram_calculation.html',1,'']]],
  ['histogram_20comparison',['Histogram Comparison',['http://docs.opencv.org/3.4.0/d8/dc8/tutorial_histogram_comparison.html',1,'']]],
  ['histogram_20equalization',['Histogram Equalization',['http://docs.opencv.org/3.4.0/d4/d1b/tutorial_histogram_equalization.html',1,'']]],
  ['hit_2dor_2dmiss',['Hit-or-Miss',['http://docs.opencv.org/3.4.0/db/d06/tutorial_hitOrMiss.html',1,'']]],
  ['hough_20circle_20transform',['Hough Circle Transform',['http://docs.opencv.org/3.4.0/d4/d70/tutorial_hough_circle.html',1,'']]],
  ['hough_20line_20transform',['Hough Line Transform',['http://docs.opencv.org/3.4.0/d9/db0/tutorial_hough_lines.html',1,'']]],
  ['how_20to_20scan_20images_2c_20lookup_20tables_20and_20time_20measurement_20with_20opencv',['How to scan images, lookup tables and time measurement with OpenCV',['http://docs.opencv.org/3.4.0/db/da5/tutorial_how_to_scan_images.html',1,'']]],
  ['how_20to_20use_20the_20opencv_20parallel_5ffor_5f_20to_20parallelize_20your_20code',['How to use the OpenCV parallel_for_ to parallelize your code',['http://docs.opencv.org/3.4.0/d7/dff/tutorial_how_to_use_OpenCV_parallel_for_.html',1,'']]],
  ['histogram_20_2d_203_20_3a_20histogram_20backprojection',['Histogram - 3 : Histogram Backprojection',['http://docs.opencv.org/3.4.0/dd/d4d/tutorial_js_histogram_backprojection.html',1,'']]],
  ['histograms_20_2d_201_20_3a_20find_2c_20plot_2c_20analyze_20_21_21_21',['Histograms - 1 : Find, Plot, Analyze !!!',['http://docs.opencv.org/3.4.0/d7/d32/tutorial_js_histogram_begins.html',1,'']]],
  ['histograms_20_2d_202_3a_20histogram_20equalization',['Histograms - 2: Histogram Equalization',['http://docs.opencv.org/3.4.0/d2/d74/tutorial_js_histogram_equalization.html',1,'']]],
  ['hough_20circle_20transform',['Hough Circle Transform',['http://docs.opencv.org/3.4.0/d3/de5/tutorial_js_houghcircles.html',1,'']]],
  ['hough_20line_20transform',['Hough Line Transform',['http://docs.opencv.org/3.4.0/d3/de6/tutorial_js_houghlines.html',1,'']]],
  ['histograms_20in_20opencv_2ejs',['Histograms in OpenCV.js',['http://docs.opencv.org/3.4.0/d5/dc0/tutorial_js_table_of_contents_histograms.html',1,'']]],
  ['histograms_20_2d_203_20_3a_202d_20histograms',['Histograms - 3 : 2D Histograms',['http://docs.opencv.org/3.4.0/dd/d0d/tutorial_py_2d_histogram.html',1,'']]],
  ['how_20opencv_2dpython_20bindings_20works_3f',['How OpenCV-Python Bindings Works?',['http://docs.opencv.org/3.4.0/da/d49/tutorial_py_bindings_basics.html',1,'']]],
  ['harris_20corner_20detection',['Harris Corner Detection',['http://docs.opencv.org/3.4.0/dc/d0d/tutorial_py_features_harris.html',1,'']]],
  ['high_20dynamic_20range_20_28hdr_29',['High Dynamic Range (HDR)',['http://docs.opencv.org/3.4.0/d2/df0/tutorial_py_hdr.html',1,'']]],
  ['histogram_20_2d_204_20_3a_20histogram_20backprojection',['Histogram - 4 : Histogram Backprojection',['http://docs.opencv.org/3.4.0/dc/df6/tutorial_py_histogram_backprojection.html',1,'']]],
  ['histograms_20_2d_201_20_3a_20find_2c_20plot_2c_20analyze_20_21_21_21',['Histograms - 1 : Find, Plot, Analyze !!!',['http://docs.opencv.org/3.4.0/d1/db7/tutorial_py_histogram_begins.html',1,'']]],
  ['histograms_20_2d_202_3a_20histogram_20equalization',['Histograms - 2: Histogram Equalization',['http://docs.opencv.org/3.4.0/d5/daf/tutorial_py_histogram_equalization.html',1,'']]],
  ['hough_20circle_20transform',['Hough Circle Transform',['http://docs.opencv.org/3.4.0/da/d53/tutorial_py_houghcircles.html',1,'']]],
  ['hough_20line_20transform',['Hough Line Transform',['http://docs.opencv.org/3.4.0/d6/d10/tutorial_py_houghlines.html',1,'']]],
  ['histograms_20in_20opencv',['Histograms in OpenCV',['http://docs.opencv.org/3.4.0/de/db2/tutorial_py_table_of_contents_histograms.html',1,'']]],
  ['high_20level_20stitching_20api_20_28stitcher_20class_29',['High level stitching API (Stitcher class)',['http://docs.opencv.org/3.4.0/d8/d19/tutorial_stitcher.html',1,'']]],
  ['high_20level_20gui_20and_20media_20_28highgui_20module_29',['High Level GUI and Media (highgui module)',['http://docs.opencv.org/3.4.0/d0/de2/tutorial_table_of_content_highgui.html',1,'']]],
  ['how_20to_20build_20applications_20with_20opencv_20inside_20the_20_22microsoft_20visual_20studio_22',['How to build applications with OpenCV inside the &quot;Microsoft Visual Studio&quot;',['http://docs.opencv.org/3.4.0/dd/d6e/tutorial_windows_visual_studio_opencv.html',1,'']]]
];
