gaze: gaze::pipeline::FaceLandmarks Class Reference
gaze::pipeline::FaceLandmarks Class Reference final
Uses dlibs pretrained models to detect face landmarks.
#include "gaze/pipeline_steps/face_landmarks.h"
Public Member Functions
void process (util::Data &data) override
void visualize (util::Data &data) override
Public Member Functions inherited from gaze::PipelineStep
PipelineStep ()
std::string get_name ()
virtual ~PipelineStep ()=default
Public Member Functions inherited from gaze::gui::Visualizeable< widget_type >
std::shared_ptr< dlib::drawable > init (dlib::drawable_window &parent, int width, int height, std::string text="No visualization.") final
void remove_widget () override
Public Member Functions inherited from gaze::gui::VisualizeableBase
virtual ~VisualizeableBase ()=default
Additional Inherited Members
Protected Attributes inherited from gaze::PipelineStep
int number
std::string name
Protected Attributes inherited from gaze::gui::Visualizeable< widget_type >
std::shared_ptr< widget_type > widget
Detailed Description
Uses dlibs pretrained models to detect face landmarks.
///
Todo:
shoeffner: Write documentation for FaceLandmarks.
Definition at line 22 of file face_landmarks.h.
Member Function Documentation
void gaze::pipeline::FaceLandmarks::process (util::Data & data) override virtual
Detects face landmarks inside the source image.
Updates both eyes and face bounding boxes of data.
Parameters
data The data object to be updated.
Returns
via data the modified data object.
Implements gaze::PipelineStep.
Definition at line 32 of file face_landmarks.cpp.
References gaze::util::Data::image, gaze::util::Data::landmarks, and std::vector< _Tp, _Alloc >::size().
Referenced by visualize().
{
   std::vector<dlib::rectangle> faces = this->face_detector(data.image);
   if (faces.size() > 0) {
     data.landmarks = this->shape_predictor(data.image, faces[0]);
   }
 }
void gaze::pipeline::FaceLandmarks::visualize (util::Data & data) override virtual
Parameters
data The data object to be updated.
Implements gaze::gui::VisualizeableBase.
Definition at line 39 of file face_landmarks.cpp.
References gaze::util::Data::image, gaze::util::Data::landmarks, process(), and gaze::gui::Visualizeable< widget_type >::widget.
{
   this->widget->clear_overlay();
   // Reprocess the data in case multiple pipeline steps
   // interfered - this is good for comparisons.
   this->process(data);
   if (data.landmarks.get_rect().is_empty()) {
     this->widget->set_image(data.image);
     return;
   }
   this->widget->set_image(data.image);
   this->widget->add_overlay(dlib::image_display::overlay_rect(
         data.landmarks.get_rect(),
         dlib::rgb_pixel(0, 0, 255)));
   this->widget->add_overlay(dlib::render_face_detections(data.landmarks));
 }
The documentation for this class was generated from the following files:
include/gaze/pipeline_steps/face_landmarks.h
src/gaze/pipeline_steps/face_landmarks.cpp