gaze: YAML::convert< cv::Mat > Struct Template Reference
YAML::convert< cv::Mat > Struct Template Reference
Allows to convert between cv::Mat and YAML::Node.
#include <config.h>
Static Public Member Functions
static Node encode (const cv::Mat &rhs)
static bool decode (const Node &node, cv::Mat &rhs)
Detailed Description
template<>
struct YAML::convert< cv::Mat >
Allows to convert between cv::Mat and YAML::Node.
Definition at line 136 of file config.h.
Member Function Documentation
static bool YAML::convert< cv::Mat >::decode (const Node & node, cv::Mat & rhs) inline static
Decodes a cv::Mat from a YAML node.
Parameters
node The node to decode.
rhs The matrix to decode into.
Returns
true on success.
Definition at line 165 of file config.h.
References cols(), cv::Mat::copyTo(), CV_64F, rows(), and size().
                                                    {  // NOLINT
     if (!node["rows"] || !node["cols"] || !node["dt"] || !node["data"] ||
         !node["data"].IsSequence()) {
       return false;
     }
     char dt = node["dt"].as<char>();
     if (dt != 'd') {
       return false;
     }
     int rows = node["rows"].as<int>();
     int cols = node["cols"].as<int>();
     if (static_cast<decltype(node["data"].size())>(rows * cols) !=
         node["data"].size()) {
       return false;
     }
     double* data = new double[rows * cols];
     for (auto i = decltype(node["data"].size()){0}; i < node["data"].size();
         ++i) {
       data[i] = node["data"][i].as<double>();
     }
     cv::Mat mat = cv::Mat(rows, cols, CV_64F, data);
     mat.copyTo(rhs);
     delete[] data;
     return true;
   }
static Node YAML::convert< cv::Mat >::encode (const cv::Mat & rhs) inline static
Encodes a cv::Mat as a YAML node.
Parameters
rhs The matrix
Returns
A YAML node representing the matrix
Definition at line 143 of file config.h.
References cv::Mat::cols, cv::Mat::dataend, cv::Mat::datastart, and cv::Mat::rows.
{
     Node node;
     node["rows"] = rhs.rows;
     node["cols"] = rhs.cols;
     node["dt"] = 'd';
     Node data;
     for (auto d = rhs.datastart; d != rhs.dataend; ++d) {
       data.push_back(static_cast<double>(*d));
     }
     node["data"] = data;
     return node;
   }
The documentation for this struct was generated from the following file:
include/gaze/util/config.h