var searchData=
[
  ['l1',['L1',['http://docs.opencv.org/3.4.0/df/d95/structcvflann_1_1L1.html',1,'cvflann::L1&lt; class &gt;'],['http://docs.opencv.org/3.4.0/d4/d7f/structcv_1_1L1.html',1,'cv::L1&lt; class &gt;']]],
  ['l2',['L2',['http://docs.opencv.org/3.4.0/d9/da3/structcvflann_1_1L2.html',1,'cvflann::L2&lt; class &gt;'],['http://docs.opencv.org/3.4.0/dc/daa/structcv_1_1L2.html',1,'cv::L2&lt; class &gt;']]],
  ['l2_5fsimple',['L2_Simple',['http://docs.opencv.org/3.4.0/da/d59/structcvflann_1_1L2__Simple.html',1,'cvflann']]],
  ['lab2rgb',['Lab2RGB',['http://docs.opencv.org/3.4.0/d0/de5/classcv_1_1cudev_1_1color__cvt__detail_1_1Lab2RGB.html',1,'cv::cudev::color_cvt_detail']]],
  ['lab4_5fto_5fbgr_5ffunc',['Lab4_to_BGR_func',['http://docs.opencv.org/3.4.0/d0/d9b/structcv_1_1cudev_1_1Lab4__to__BGR__func.html',1,'cv::cudev']]],
  ['lab4_5fto_5fbgra_5ffunc',['Lab4_to_BGRA_func',['http://docs.opencv.org/3.4.0/dd/d90/structcv_1_1cudev_1_1Lab4__to__BGRA__func.html',1,'cv::cudev']]],
  ['lab4_5fto_5flbgr_5ffunc',['Lab4_to_LBGR_func',['http://docs.opencv.org/3.4.0/d6/daa/structcv_1_1cudev_1_1Lab4__to__LBGR__func.html',1,'cv::cudev']]],
  ['lab4_5fto_5flbgra_5ffunc',['Lab4_to_LBGRA_func',['http://docs.opencv.org/3.4.0/d5/d42/structcv_1_1cudev_1_1Lab4__to__LBGRA__func.html',1,'cv::cudev']]],
  ['lab4_5fto_5flrgb_5ffunc',['Lab4_to_LRGB_func',['http://docs.opencv.org/3.4.0/d8/d8b/structcv_1_1cudev_1_1Lab4__to__LRGB__func.html',1,'cv::cudev']]],
  ['lab4_5fto_5flrgba_5ffunc',['Lab4_to_LRGBA_func',['http://docs.opencv.org/3.4.0/da/d79/structcv_1_1cudev_1_1Lab4__to__LRGBA__func.html',1,'cv::cudev']]],
  ['lab4_5fto_5frgb_5ffunc',['Lab4_to_RGB_func',['http://docs.opencv.org/3.4.0/d6/d85/structcv_1_1cudev_1_1Lab4__to__RGB__func.html',1,'cv::cudev']]],
  ['lab4_5fto_5frgba_5ffunc',['Lab4_to_RGBA_func',['http://docs.opencv.org/3.4.0/d2/d63/structcv_1_1cudev_1_1Lab4__to__RGBA__func.html',1,'cv::cudev']]],
  ['lab_5fto_5fbgr_5ffunc',['Lab_to_BGR_func',['http://docs.opencv.org/3.4.0/d7/d73/structcv_1_1cudev_1_1Lab__to__BGR__func.html',1,'cv::cudev']]],
  ['lab_5fto_5fbgra_5ffunc',['Lab_to_BGRA_func',['http://docs.opencv.org/3.4.0/d0/dd1/structcv_1_1cudev_1_1Lab__to__BGRA__func.html',1,'cv::cudev']]],
  ['lab_5fto_5flbgr_5ffunc',['Lab_to_LBGR_func',['http://docs.opencv.org/3.4.0/d6/d7e/structcv_1_1cudev_1_1Lab__to__LBGR__func.html',1,'cv::cudev']]],
  ['lab_5fto_5flbgra_5ffunc',['Lab_to_LBGRA_func',['http://docs.opencv.org/3.4.0/df/ddf/structcv_1_1cudev_1_1Lab__to__LBGRA__func.html',1,'cv::cudev']]],
  ['lab_5fto_5flrgb_5ffunc',['Lab_to_LRGB_func',['http://docs.opencv.org/3.4.0/d0/d79/structcv_1_1cudev_1_1Lab__to__LRGB__func.html',1,'cv::cudev']]],
  ['lab_5fto_5flrgba_5ffunc',['Lab_to_LRGBA_func',['http://docs.opencv.org/3.4.0/dc/d4d/structcv_1_1cudev_1_1Lab__to__LRGBA__func.html',1,'cv::cudev']]],
  ['lab_5fto_5frgb_5ffunc',['Lab_to_RGB_func',['http://docs.opencv.org/3.4.0/d4/d08/structcv_1_1cudev_1_1Lab__to__RGB__func.html',1,'cv::cudev']]],
  ['lab_5fto_5frgba_5ffunc',['Lab_to_RGBA_func',['http://docs.opencv.org/3.4.0/df/df8/structcv_1_1cudev_1_1Lab__to__RGBA__func.html',1,'cv::cudev']]],
  ['laplacianptr',['LaplacianPtr',['http://docs.opencv.org/3.4.0/da/d40/structcv_1_1cudev_1_1LaplacianPtr.html',1,'cv::cudev']]],
  ['laplacianptr_3c_201_2c_20srcptr_20_3e',['LaplacianPtr&lt; 1, SrcPtr &gt;',['http://docs.opencv.org/3.4.0/d0/de6/structcv_1_1cudev_1_1LaplacianPtr_3_011_00_01SrcPtr_01_4.html',1,'cv::cudev']]],
  ['laplacianptr_3c_203_2c_20srcptr_20_3e',['LaplacianPtr&lt; 3, SrcPtr &gt;',['http://docs.opencv.org/3.4.0/d4/d89/structcv_1_1cudev_1_1LaplacianPtr_3_013_00_01SrcPtr_01_4.html',1,'cv::cudev']]],
  ['laplacianptrsz',['LaplacianPtrSz',['http://docs.opencv.org/3.4.0/da/dd9/structcv_1_1cudev_1_1LaplacianPtrSz.html',1,'cv::cudev']]],
  ['largertype',['LargerType',['http://docs.opencv.org/3.4.0/d5/d33/structcv_1_1cudev_1_1LargerType.html',1,'cv::cudev']]],
  ['latch',['LATCH',['http://docs.opencv.org/3.4.0/d6/d36/classcv_1_1xfeatures2d_1_1LATCH.html',1,'cv::xfeatures2d']]],
  ['layer',['Layer',['http://docs.opencv.org/3.4.0/d3/d6c/classcv_1_1dnn_1_1Layer.html',1,'cv::dnn']]],
  ['layerfactory',['LayerFactory',['http://docs.opencv.org/3.4.0/d4/d67/classcv_1_1dnn_1_1LayerFactory.html',1,'cv::dnn']]],
  ['layerparams',['LayerParams',['http://docs.opencv.org/3.4.0/db/db6/classcv_1_1dnn_1_1LayerParams.html',1,'cv::dnn']]],
  ['lbgr_5fto_5flab4_5ffunc',['LBGR_to_Lab4_func',['http://docs.opencv.org/3.4.0/d3/d25/structcv_1_1cudev_1_1LBGR__to__Lab4__func.html',1,'cv::cudev']]],
  ['lbgr_5fto_5flab_5ffunc',['LBGR_to_Lab_func',['http://docs.opencv.org/3.4.0/dd/d07/structcv_1_1cudev_1_1LBGR__to__Lab__func.html',1,'cv::cudev']]],
  ['lbgr_5fto_5fluv4_5ffunc',['LBGR_to_Luv4_func',['http://docs.opencv.org/3.4.0/db/d4d/structcv_1_1cudev_1_1LBGR__to__Luv4__func.html',1,'cv::cudev']]],
  ['lbgr_5fto_5fluv_5ffunc',['LBGR_to_Luv_func',['http://docs.opencv.org/3.4.0/d8/d9e/structcv_1_1cudev_1_1LBGR__to__Luv__func.html',1,'cv::cudev']]],
  ['lbgra_5fto_5flab4_5ffunc',['LBGRA_to_Lab4_func',['http://docs.opencv.org/3.4.0/dc/db6/structcv_1_1cudev_1_1LBGRA__to__Lab4__func.html',1,'cv::cudev']]],
  ['lbgra_5fto_5flab_5ffunc',['LBGRA_to_Lab_func',['http://docs.opencv.org/3.4.0/d5/d55/structcv_1_1cudev_1_1LBGRA__to__Lab__func.html',1,'cv::cudev']]],
  ['lbgra_5fto_5fluv4_5ffunc',['LBGRA_to_Luv4_func',['http://docs.opencv.org/3.4.0/df/d4b/structcv_1_1cudev_1_1LBGRA__to__Luv4__func.html',1,'cv::cudev']]],
  ['lbgra_5fto_5fluv_5ffunc',['LBGRA_to_Luv_func',['http://docs.opencv.org/3.4.0/d2/d19/structcv_1_1cudev_1_1LBGRA__to__Luv__func.html',1,'cv::cudev']]],
  ['lbphfacerecognizer',['LBPHFaceRecognizer',['http://docs.opencv.org/3.4.0/df/d25/classcv_1_1face_1_1LBPHFaceRecognizer.html',1,'cv::face']]],
  ['lda',['LDA',['http://docs.opencv.org/3.4.0/db/d59/classcv_1_1LDA.html',1,'cv']]],
  ['learningbasedwb',['LearningBasedWB',['http://docs.opencv.org/3.4.0/d4/d3b/classcv_1_1xphoto_1_1LearningBasedWB.html',1,'cv::xphoto']]],
  ['left_5fchild_5fnext_5fsibling_5fheap',['left_child_next_sibling_heap',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10724.html',1,'__gnu_pbds::detail']]],
  ['left_5fchild_5fnext_5fsibling_5fheap_3c_20value_5ftype_2c_20cmp_5ffn_2c_20_5falloc_3a_3asize_5ftype_2c_20_5falloc_20_3e',['left_child_next_sibling_heap&lt; Value_Type, Cmp_Fn, _Alloc::size_type, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10724.html',1,'']]],
  ['left_5fchild_5fnext_5fsibling_5fheap_3c_20value_5ftype_2c_20cmp_5ffn_2c_20null_5ftype_2c_20_5falloc_20_3e',['left_child_next_sibling_heap&lt; Value_Type, Cmp_Fn, null_type, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10724.html',1,'']]],
  ['left_5fchild_5fnext_5fsibling_5fheap_5fconst_5fiterator_5f',['left_child_next_sibling_heap_const_iterator_',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10720.html',1,'__gnu_pbds::detail']]],
  ['left_5fchild_5fnext_5fsibling_5fheap_5fnode_5f',['left_child_next_sibling_heap_node_',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10728.html',1,'__gnu_pbds::detail']]],
  ['left_5fchild_5fnext_5fsibling_5fheap_5fnode_5fpoint_5fconst_5fiterator_5f',['left_child_next_sibling_heap_node_point_const_iterator_',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10736.html',1,'__gnu_pbds::detail']]],
  ['length_5ferror',['length_error',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02912.html',1,'std']]],
  ['less',['less',['http://docs.opencv.org/3.4.0/d0/d04/structcv_1_1cudev_1_1less.html',1,'cv::cudev::less&lt; class &gt;'],['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06460.html',1,'std::less&lt; _Tp &gt;']]],
  ['less_3c_20void_20_3e',['less&lt; void &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06484.html',1,'std']]],
  ['less_5fequal',['less_equal',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06468.html',1,'std::less_equal&lt; class &gt;'],['http://docs.opencv.org/3.4.0/d1/d03/structcv_1_1cudev_1_1less__equal.html',1,'cv::cudev::less_equal&lt; class &gt;']]],
  ['less_5fequal_3c_20void_20_3e',['less_equal&lt; void &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06492.html',1,'std']]],
  ['libmv_5fcameraintrinsicsoptions',['libmv_CameraIntrinsicsOptions',['http://docs.opencv.org/3.4.0/d9/d5a/classcv_1_1sfm_1_1libmv__CameraIntrinsicsOptions.html',1,'cv::sfm']]],
  ['libmv_5freconstructionoptions',['libmv_ReconstructionOptions',['http://docs.opencv.org/3.4.0/d1/d61/classcv_1_1sfm_1_1libmv__ReconstructionOptions.html',1,'cv::sfm']]],
  ['limit_5fadjustor',['limit_adjustor',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09624.html',1,'__gnu_cxx::limit_condition']]],
  ['limit_5fcondition',['limit_condition',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09608.html',1,'__gnu_cxx']]],
  ['linear_5fcongruential_5fengine',['linear_congruential_engine',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05400.html',1,'std']]],
  ['linear_5fprobe_5ffn',['linear_probe_fn',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10064.html',1,'__gnu_pbds']]],
  ['linearindex',['LinearIndex',['http://docs.opencv.org/3.4.0/d2/d37/classcvflann_1_1LinearIndex.html',1,'cvflann']]],
  ['linearindexparams',['LinearIndexParams',['http://docs.opencv.org/3.4.0/d5/d24/structcvflann_1_1LinearIndexParams.html',1,'cvflann::LinearIndexParams'],['http://docs.opencv.org/3.4.0/da/d5d/structcv_1_1flann_1_1LinearIndexParams.html',1,'cv::flann::LinearIndexParams']]],
  ['linearinterptr',['LinearInterPtr',['http://docs.opencv.org/3.4.0/d7/d8a/structcv_1_1cudev_1_1LinearInterPtr.html',1,'cv::cudev']]],
  ['linearinterptrsz',['LinearInterPtrSz',['http://docs.opencv.org/3.4.0/d9/d2e/structcv_1_1cudev_1_1LinearInterPtrSz.html',1,'cv::cudev']]],
  ['lineiterator',['LineIterator',['http://docs.opencv.org/3.4.0/dc/dd2/classcv_1_1LineIterator.html',1,'cv']]],
  ['linesegmentdetector',['LineSegmentDetector',['http://docs.opencv.org/3.4.0/db/d73/classcv_1_1LineSegmentDetector.html',1,'cv']]],
  ['list',['list',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06712.html',1,'std::list&lt; _Tp, _Alloc &gt;'],['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07788.html',1,'std::__debug::list&lt; _Tp, _Allocator &gt;'],['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08044.html',1,'std::__profile::list&lt; _Tp, _Allocator &gt;']]],
  ['list_3c_20_5f_5finp_2c_20_5f_5frebind_5finp_20_3e',['list&lt; __inp, __rebind_inp &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06712.html',1,'']]],
  ['list_5fupdate',['list_update',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10044.html',1,'__gnu_pbds']]],
  ['list_5fupdate_5ftag',['list_update_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10184.html',1,'__gnu_pbds']]],
  ['locale',['locale',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a04952.html',1,'std']]],
  ['lock_5fguard',['lock_guard',['http://docs.opencv.org/3.4.0/de/d29/classcv_1_1utils_1_1lock__guard.html',1,'cv::utils::lock_guard&lt; class &gt;'],['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06256.html',1,'std::lock_guard&lt; _Mutex &gt;']]],
  ['log10_5ffunc',['log10_func',['http://docs.opencv.org/3.4.0/d8/da8/structcv_1_1cudev_1_1log10__func.html',1,'cv::cudev']]],
  ['log10_5ffunc_3c_20double_20_3e',['log10_func&lt; double &gt;',['http://docs.opencv.org/3.4.0/dc/d32/structcv_1_1cudev_1_1log10__func_3_01double_01_4.html',1,'cv::cudev']]],
  ['log10_5ffunc_3c_20float_20_3e',['log10_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/d0/d42/structcv_1_1cudev_1_1log10__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['log10_5ffunc_3c_20schar_20_3e',['log10_func&lt; schar &gt;',['http://docs.opencv.org/3.4.0/dd/d4b/structcv_1_1cudev_1_1log10__func_3_01schar_01_4.html',1,'cv::cudev']]],
  ['log10_5ffunc_3c_20short_20_3e',['log10_func&lt; short &gt;',['http://docs.opencv.org/3.4.0/d9/d00/structcv_1_1cudev_1_1log10__func_3_01short_01_4.html',1,'cv::cudev']]],
  ['log10_5ffunc_3c_20uchar_20_3e',['log10_func&lt; uchar &gt;',['http://docs.opencv.org/3.4.0/dd/dcc/structcv_1_1cudev_1_1log10__func_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['log10_5ffunc_3c_20uint_20_3e',['log10_func&lt; uint &gt;',['http://docs.opencv.org/3.4.0/df/d6e/structcv_1_1cudev_1_1log10__func_3_01uint_01_4.html',1,'cv::cudev']]],
  ['log10_5ffunc_3c_20ushort_20_3e',['log10_func&lt; ushort &gt;',['http://docs.opencv.org/3.4.0/d0/df1/structcv_1_1cudev_1_1log10__func_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['log2',['Log2',['http://docs.opencv.org/3.4.0/d5/da6/structcv_1_1cudev_1_1Log2.html',1,'cv::cudev']]],
  ['log2_3c_20n_2c_200_2c_20count_20_3e',['Log2&lt; N, 0, COUNT &gt;',['http://docs.opencv.org/3.4.0/d5/d16/structcv_1_1cudev_1_1Log2_3_01N_00_010_00_01COUNT_01_4.html',1,'cv::cudev']]],
  ['log2_5ffunc',['log2_func',['http://docs.opencv.org/3.4.0/d9/d23/structcv_1_1cudev_1_1log2__func.html',1,'cv::cudev']]],
  ['log2_5ffunc_3c_20double_20_3e',['log2_func&lt; double &gt;',['http://docs.opencv.org/3.4.0/dc/d17/structcv_1_1cudev_1_1log2__func_3_01double_01_4.html',1,'cv::cudev']]],
  ['log2_5ffunc_3c_20float_20_3e',['log2_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/db/dba/structcv_1_1cudev_1_1log2__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['log2_5ffunc_3c_20schar_20_3e',['log2_func&lt; schar &gt;',['http://docs.opencv.org/3.4.0/d6/ded/structcv_1_1cudev_1_1log2__func_3_01schar_01_4.html',1,'cv::cudev']]],
  ['log2_5ffunc_3c_20short_20_3e',['log2_func&lt; short &gt;',['http://docs.opencv.org/3.4.0/d6/d0b/structcv_1_1cudev_1_1log2__func_3_01short_01_4.html',1,'cv::cudev']]],
  ['log2_5ffunc_3c_20uchar_20_3e',['log2_func&lt; uchar &gt;',['http://docs.opencv.org/3.4.0/d6/d41/structcv_1_1cudev_1_1log2__func_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['log2_5ffunc_3c_20uint_20_3e',['log2_func&lt; uint &gt;',['http://docs.opencv.org/3.4.0/df/d69/structcv_1_1cudev_1_1log2__func_3_01uint_01_4.html',1,'cv::cudev']]],
  ['log2_5ffunc_3c_20ushort_20_3e',['log2_func&lt; ushort &gt;',['http://docs.opencv.org/3.4.0/d0/dda/structcv_1_1cudev_1_1log2__func_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['log_5ffunc',['log_func',['http://docs.opencv.org/3.4.0/dc/d41/structcv_1_1cudev_1_1log__func.html',1,'cv::cudev']]],
  ['log_5ffunc_3c_20double_20_3e',['log_func&lt; double &gt;',['http://docs.opencv.org/3.4.0/dd/dad/structcv_1_1cudev_1_1log__func_3_01double_01_4.html',1,'cv::cudev']]],
  ['log_5ffunc_3c_20float_20_3e',['log_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/d2/d85/structcv_1_1cudev_1_1log__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['log_5ffunc_3c_20schar_20_3e',['log_func&lt; schar &gt;',['http://docs.opencv.org/3.4.0/d2/de1/structcv_1_1cudev_1_1log__func_3_01schar_01_4.html',1,'cv::cudev']]],
  ['log_5ffunc_3c_20short_20_3e',['log_func&lt; short &gt;',['http://docs.opencv.org/3.4.0/d0/d19/structcv_1_1cudev_1_1log__func_3_01short_01_4.html',1,'cv::cudev']]],
  ['log_5ffunc_3c_20uchar_20_3e',['log_func&lt; uchar &gt;',['http://docs.opencv.org/3.4.0/d3/db5/structcv_1_1cudev_1_1log__func_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['log_5ffunc_3c_20uint_20_3e',['log_func&lt; uint &gt;',['http://docs.opencv.org/3.4.0/d0/dee/structcv_1_1cudev_1_1log__func_3_01uint_01_4.html',1,'cv::cudev']]],
  ['log_5ffunc_3c_20ushort_20_3e',['log_func&lt; ushort &gt;',['http://docs.opencv.org/3.4.0/d5/d0c/structcv_1_1cudev_1_1log__func_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['logger',['Logger',['http://docs.opencv.org/3.4.0/d1/d50/classcvflann_1_1Logger.html',1,'cvflann']]],
  ['logic_5ferror',['logic_error',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02900.html',1,'std']]],
  ['logical_5fand',['logical_and',['http://docs.opencv.org/3.4.0/d7/de9/structcv_1_1cudev_1_1logical__and.html',1,'cv::cudev::logical_and&lt; class &gt;'],['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06496.html',1,'std::logical_and&lt; class &gt;']]],
  ['logical_5fand_3c_20void_20_3e',['logical_and&lt; void &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06508.html',1,'std']]],
  ['logical_5fnot',['logical_not',['http://docs.opencv.org/3.4.0/d4/d01/structcv_1_1cudev_1_1logical__not.html',1,'cv::cudev::logical_not&lt; class &gt;'],['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06504.html',1,'std::logical_not&lt; class &gt;']]],
  ['logical_5fnot_3c_20void_20_3e',['logical_not&lt; void &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06516.html',1,'std']]],
  ['logical_5for',['logical_or',['http://docs.opencv.org/3.4.0/d3/db2/structcv_1_1cudev_1_1logical__or.html',1,'cv::cudev::logical_or&lt; class &gt;'],['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06500.html',1,'std::logical_or&lt; class &gt;']]],
  ['logical_5for_3c_20void_20_3e',['logical_or&lt; void &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06512.html',1,'std']]],
  ['logisticregression',['LogisticRegression',['http://docs.opencv.org/3.4.0/d6/df9/classcv_1_1ml_1_1LogisticRegression.html',1,'cv::ml']]],
  ['lognormal_5fdistribution',['lognormal_distribution',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05448.html',1,'std']]],
  ['logtostdout',['LogToStdout',['http://docs.opencv.org/3.4.0/d5/de0/classcv_1_1videostab_1_1LogToStdout.html',1,'cv::videostab']]],
  ['lookuptable',['LookUpTable',['http://docs.opencv.org/3.4.0/df/d29/classcv_1_1cuda_1_1LookUpTable.html',1,'cv::cuda']]],
  ['lpmotionstabilizer',['LpMotionStabilizer',['http://docs.opencv.org/3.4.0/d3/d59/classcv_1_1videostab_1_1LpMotionStabilizer.html',1,'cv::videostab']]],
  ['lrgb_5fto_5flab4_5ffunc',['LRGB_to_Lab4_func',['http://docs.opencv.org/3.4.0/db/d2b/structcv_1_1cudev_1_1LRGB__to__Lab4__func.html',1,'cv::cudev']]],
  ['lrgb_5fto_5flab_5ffunc',['LRGB_to_Lab_func',['http://docs.opencv.org/3.4.0/d6/db7/structcv_1_1cudev_1_1LRGB__to__Lab__func.html',1,'cv::cudev']]],
  ['lrgb_5fto_5fluv4_5ffunc',['LRGB_to_Luv4_func',['http://docs.opencv.org/3.4.0/d7/dc8/structcv_1_1cudev_1_1LRGB__to__Luv4__func.html',1,'cv::cudev']]],
  ['lrgb_5fto_5fluv_5ffunc',['LRGB_to_Luv_func',['http://docs.opencv.org/3.4.0/d7/d62/structcv_1_1cudev_1_1LRGB__to__Luv__func.html',1,'cv::cudev']]],
  ['lrgba_5fto_5flab4_5ffunc',['LRGBA_to_Lab4_func',['http://docs.opencv.org/3.4.0/de/d7f/structcv_1_1cudev_1_1LRGBA__to__Lab4__func.html',1,'cv::cudev']]],
  ['lrgba_5fto_5flab_5ffunc',['LRGBA_to_Lab_func',['http://docs.opencv.org/3.4.0/dc/d12/structcv_1_1cudev_1_1LRGBA__to__Lab__func.html',1,'cv::cudev']]],
  ['lrgba_5fto_5fluv4_5ffunc',['LRGBA_to_Luv4_func',['http://docs.opencv.org/3.4.0/dd/dea/structcv_1_1cudev_1_1LRGBA__to__Luv4__func.html',1,'cv::cudev']]],
  ['lrgba_5fto_5fluv_5ffunc',['LRGBA_to_Luv_func',['http://docs.opencv.org/3.4.0/d2/d19/structcv_1_1cudev_1_1LRGBA__to__Luv__func.html',1,'cv::cudev']]],
  ['lrnlayer',['LRNLayer',['http://docs.opencv.org/3.4.0/d8/d8d/classcv_1_1dnn_1_1LRNLayer.html',1,'cv::dnn']]],
  ['lsddetector',['LSDDetector',['http://docs.opencv.org/3.4.0/d1/dbd/classcv_1_1line__descriptor_1_1LSDDetector.html',1,'cv::line_descriptor']]],
  ['lshindex',['LshIndex',['http://docs.opencv.org/3.4.0/d5/d34/classcvflann_1_1LshIndex.html',1,'cvflann']]],
  ['lshindexparams',['LshIndexParams',['http://docs.opencv.org/3.4.0/d5/ddf/structcvflann_1_1LshIndexParams.html',1,'cvflann::LshIndexParams'],['http://docs.opencv.org/3.4.0/d5/dff/structcv_1_1flann_1_1LshIndexParams.html',1,'cv::flann::LshIndexParams']]],
  ['lshstats',['LshStats',['http://docs.opencv.org/3.4.0/d5/d3e/structcvflann_1_1lsh_1_1LshStats.html',1,'cvflann::lsh']]],
  ['lshtable',['LshTable',['http://docs.opencv.org/3.4.0/d4/d86/classcvflann_1_1lsh_1_1LshTable.html',1,'cvflann::lsh']]],
  ['lstmlayer',['LSTMLayer',['http://docs.opencv.org/3.4.0/db/d3e/classcv_1_1dnn_1_1LSTMLayer.html',1,'cv::dnn']]],
  ['lu_5fcounter_5fmetadata',['lu_counter_metadata',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10776.html',1,'__gnu_pbds::detail']]],
  ['lu_5fcounter_5fpolicy',['lu_counter_policy',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10104.html',1,'__gnu_pbds']]],
  ['lu_5fcounter_5fpolicy_5fbase',['lu_counter_policy_base',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10772.html',1,'__gnu_pbds::detail']]],
  ['lu_5fcounter_5fpolicy_5fbase_3c_20_5falloc_3a_3asize_5ftype_20_3e',['lu_counter_policy_base&lt; _Alloc::size_type &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10772.html',1,'']]],
  ['lu_5fmap',['lu_map',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10748.html',1,'__gnu_pbds::detail']]],
  ['lu_5fmove_5fto_5ffront_5fpolicy',['lu_move_to_front_policy',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10100.html',1,'__gnu_pbds']]],
  ['lucid',['LUCID',['http://docs.opencv.org/3.4.0/d4/d86/classcv_1_1xfeatures2d_1_1LUCID.html',1,'cv::xfeatures2d']]],
  ['lutptr',['LutPtr',['http://docs.opencv.org/3.4.0/df/daa/structcv_1_1cudev_1_1LutPtr.html',1,'cv::cudev']]],
  ['lutptrsz',['LutPtrSz',['http://docs.opencv.org/3.4.0/d5/d22/structcv_1_1cudev_1_1LutPtrSz.html',1,'cv::cudev']]],
  ['luv2rgb',['Luv2RGB',['http://docs.opencv.org/3.4.0/d6/d2a/classcv_1_1cudev_1_1color__cvt__detail_1_1Luv2RGB.html',1,'cv::cudev::color_cvt_detail']]],
  ['luv4_5fto_5fbgr_5ffunc',['Luv4_to_BGR_func',['http://docs.opencv.org/3.4.0/d5/d34/structcv_1_1cudev_1_1Luv4__to__BGR__func.html',1,'cv::cudev']]],
  ['luv4_5fto_5fbgra_5ffunc',['Luv4_to_BGRA_func',['http://docs.opencv.org/3.4.0/d4/d0b/structcv_1_1cudev_1_1Luv4__to__BGRA__func.html',1,'cv::cudev']]],
  ['luv4_5fto_5flbgr_5ffunc',['Luv4_to_LBGR_func',['http://docs.opencv.org/3.4.0/d6/d9a/structcv_1_1cudev_1_1Luv4__to__LBGR__func.html',1,'cv::cudev']]],
  ['luv4_5fto_5flbgra_5ffunc',['Luv4_to_LBGRA_func',['http://docs.opencv.org/3.4.0/df/d46/structcv_1_1cudev_1_1Luv4__to__LBGRA__func.html',1,'cv::cudev']]],
  ['luv4_5fto_5flrgb_5ffunc',['Luv4_to_LRGB_func',['http://docs.opencv.org/3.4.0/d8/db0/structcv_1_1cudev_1_1Luv4__to__LRGB__func.html',1,'cv::cudev']]],
  ['luv4_5fto_5flrgba_5ffunc',['Luv4_to_LRGBA_func',['http://docs.opencv.org/3.4.0/d2/dc0/structcv_1_1cudev_1_1Luv4__to__LRGBA__func.html',1,'cv::cudev']]],
  ['luv4_5fto_5frgb_5ffunc',['Luv4_to_RGB_func',['http://docs.opencv.org/3.4.0/de/d9f/structcv_1_1cudev_1_1Luv4__to__RGB__func.html',1,'cv::cudev']]],
  ['luv4_5fto_5frgba_5ffunc',['Luv4_to_RGBA_func',['http://docs.opencv.org/3.4.0/d2/dda/structcv_1_1cudev_1_1Luv4__to__RGBA__func.html',1,'cv::cudev']]],
  ['luv_5fto_5fbgr_5ffunc',['Luv_to_BGR_func',['http://docs.opencv.org/3.4.0/d2/da9/structcv_1_1cudev_1_1Luv__to__BGR__func.html',1,'cv::cudev']]],
  ['luv_5fto_5fbgra_5ffunc',['Luv_to_BGRA_func',['http://docs.opencv.org/3.4.0/df/d49/structcv_1_1cudev_1_1Luv__to__BGRA__func.html',1,'cv::cudev']]],
  ['luv_5fto_5flbgr_5ffunc',['Luv_to_LBGR_func',['http://docs.opencv.org/3.4.0/d3/dfb/structcv_1_1cudev_1_1Luv__to__LBGR__func.html',1,'cv::cudev']]],
  ['luv_5fto_5flbgra_5ffunc',['Luv_to_LBGRA_func',['http://docs.opencv.org/3.4.0/d0/da4/structcv_1_1cudev_1_1Luv__to__LBGRA__func.html',1,'cv::cudev']]],
  ['luv_5fto_5flrgb_5ffunc',['Luv_to_LRGB_func',['http://docs.opencv.org/3.4.0/d7/d11/structcv_1_1cudev_1_1Luv__to__LRGB__func.html',1,'cv::cudev']]],
  ['luv_5fto_5flrgba_5ffunc',['Luv_to_LRGBA_func',['http://docs.opencv.org/3.4.0/d0/d32/structcv_1_1cudev_1_1Luv__to__LRGBA__func.html',1,'cv::cudev']]],
  ['luv_5fto_5frgb_5ffunc',['Luv_to_RGB_func',['http://docs.opencv.org/3.4.0/d4/d45/structcv_1_1cudev_1_1Luv__to__RGB__func.html',1,'cv::cudev']]],
  ['luv_5fto_5frgba_5ffunc',['Luv_to_RGBA_func',['http://docs.opencv.org/3.4.0/d8/d1e/structcv_1_1cudev_1_1Luv__to__RGBA__func.html',1,'cv::cudev']]]
];
