var searchData=
[
  ['t',['T',['http://docs.opencv.org/3.4.0/d1/def/classT.html',1,'']]],
  ['tag',['tag',['http://docs.opencv.org/3.4.0/d3/d02/structcv_1_1datasets_1_1tag.html',1,'cv::datasets']]],
  ['tan_5ffunc',['tan_func',['http://docs.opencv.org/3.4.0/d7/d3e/structcv_1_1cudev_1_1tan__func.html',1,'cv::cudev']]],
  ['tan_5ffunc_3c_20double_20_3e',['tan_func&lt; double &gt;',['http://docs.opencv.org/3.4.0/db/dc4/structcv_1_1cudev_1_1tan__func_3_01double_01_4.html',1,'cv::cudev']]],
  ['tan_5ffunc_3c_20float_20_3e',['tan_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/d5/d4e/structcv_1_1cudev_1_1tan__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['tan_5ffunc_3c_20schar_20_3e',['tan_func&lt; schar &gt;',['http://docs.opencv.org/3.4.0/d7/d9d/structcv_1_1cudev_1_1tan__func_3_01schar_01_4.html',1,'cv::cudev']]],
  ['tan_5ffunc_3c_20short_20_3e',['tan_func&lt; short &gt;',['http://docs.opencv.org/3.4.0/d6/dbd/structcv_1_1cudev_1_1tan__func_3_01short_01_4.html',1,'cv::cudev']]],
  ['tan_5ffunc_3c_20uchar_20_3e',['tan_func&lt; uchar &gt;',['http://docs.opencv.org/3.4.0/d2/d0d/structcv_1_1cudev_1_1tan__func_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['tan_5ffunc_3c_20uint_20_3e',['tan_func&lt; uint &gt;',['http://docs.opencv.org/3.4.0/d6/d9e/structcv_1_1cudev_1_1tan__func_3_01uint_01_4.html',1,'cv::cudev']]],
  ['tan_5ffunc_3c_20ushort_20_3e',['tan_func&lt; ushort &gt;',['http://docs.opencv.org/3.4.0/d2/d63/structcv_1_1cudev_1_1tan__func_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['tanh_5ffunc',['tanh_func',['http://docs.opencv.org/3.4.0/d5/d7b/structcv_1_1cudev_1_1tanh__func.html',1,'cv::cudev']]],
  ['tanh_5ffunc_3c_20double_20_3e',['tanh_func&lt; double &gt;',['http://docs.opencv.org/3.4.0/d4/d9f/structcv_1_1cudev_1_1tanh__func_3_01double_01_4.html',1,'cv::cudev']]],
  ['tanh_5ffunc_3c_20float_20_3e',['tanh_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/dc/da0/structcv_1_1cudev_1_1tanh__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['tanh_5ffunc_3c_20schar_20_3e',['tanh_func&lt; schar &gt;',['http://docs.opencv.org/3.4.0/d5/dfc/structcv_1_1cudev_1_1tanh__func_3_01schar_01_4.html',1,'cv::cudev']]],
  ['tanh_5ffunc_3c_20short_20_3e',['tanh_func&lt; short &gt;',['http://docs.opencv.org/3.4.0/d8/db4/structcv_1_1cudev_1_1tanh__func_3_01short_01_4.html',1,'cv::cudev']]],
  ['tanh_5ffunc_3c_20uchar_20_3e',['tanh_func&lt; uchar &gt;',['http://docs.opencv.org/3.4.0/d8/d5a/structcv_1_1cudev_1_1tanh__func_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['tanh_5ffunc_3c_20uint_20_3e',['tanh_func&lt; uint &gt;',['http://docs.opencv.org/3.4.0/df/dc6/structcv_1_1cudev_1_1tanh__func_3_01uint_01_4.html',1,'cv::cudev']]],
  ['tanh_5ffunc_3c_20ushort_20_3e',['tanh_func&lt; ushort &gt;',['http://docs.opencv.org/3.4.0/d6/d68/structcv_1_1cudev_1_1tanh__func_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['tanhlayer',['TanHLayer',['http://docs.opencv.org/3.4.0/df/d66/classcv_1_1dnn_1_1TanHLayer.html',1,'cv::dnn']]],
  ['targetarchs',['TargetArchs',['http://docs.opencv.org/3.4.0/d9/dee/classcv_1_1cuda_1_1TargetArchs.html',1,'cv::cuda']]],
  ['template',['Template',['http://docs.opencv.org/3.4.0/d2/dc7/structcv_1_1linemod_1_1Template.html',1,'cv::linemod']]],
  ['templatematching',['TemplateMatching',['http://docs.opencv.org/3.4.0/d2/d58/classcv_1_1cuda_1_1TemplateMatching.html',1,'cv::cuda']]],
  ['temporary_5fbuffer',['temporary_buffer',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08148.html',1,'__gnu_cxx']]],
  ['termcriteria',['TermCriteria',['http://docs.opencv.org/3.4.0/d9/d5d/classcv_1_1TermCriteria.html',1,'cv']]],
  ['textable',['textable',['../structgaze_1_1gui_1_1traits_1_1textable.html',1,'gaze::gui::traits']]],
  ['textdetector',['TextDetector',['http://docs.opencv.org/3.4.0/de/d25/classcv_1_1text_1_1TextDetector.html',1,'cv::text']]],
  ['textdetectorcnn',['TextDetectorCNN',['http://docs.opencv.org/3.4.0/d1/d66/classcv_1_1text_1_1TextDetectorCNN.html',1,'cv::text']]],
  ['texture',['Texture',['http://docs.opencv.org/3.4.0/d0/dc5/structcv_1_1cudev_1_1Texture.html',1,'cv::cudev::Texture&lt; class &gt;'],['http://docs.opencv.org/3.4.0/db/d26/structcv_1_1face_1_1FacemarkAAM_1_1Model_1_1Texture.html',1,'cv::face::FacemarkAAM::Model::Texture']]],
  ['texture2d',['Texture2D',['http://docs.opencv.org/3.4.0/d5/ddf/classcv_1_1ogl_1_1Texture2D.html',1,'cv::ogl']]],
  ['textureptr',['TexturePtr',['http://docs.opencv.org/3.4.0/d2/d09/structcv_1_1cudev_1_1TexturePtr.html',1,'cv::cudev']]],
  ['thash',['THash',['http://docs.opencv.org/3.4.0/da/dff/structTHash.html',1,'']]],
  ['thin_5fheap',['thin_heap',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10960.html',1,'__gnu_pbds::detail']]],
  ['thin_5fheap_5ftag',['thin_heap_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10208.html',1,'__gnu_pbds']]],
  ['thinplatesplineshapetransformer',['ThinPlateSplineShapeTransformer',['http://docs.opencv.org/3.4.0/dc/d18/classcv_1_1ThinPlateSplineShapeTransformer.html',1,'cv']]],
  ['thread',['thread',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02972.html',1,'std']]],
  ['threshbinaryfunc',['ThreshBinaryFunc',['http://docs.opencv.org/3.4.0/df/df5/structcv_1_1cudev_1_1ThreshBinaryFunc.html',1,'cv::cudev']]],
  ['threshbinaryinvfunc',['ThreshBinaryInvFunc',['http://docs.opencv.org/3.4.0/da/d5e/structcv_1_1cudev_1_1ThreshBinaryInvFunc.html',1,'cv::cudev']]],
  ['threshtozerofunc',['ThreshToZeroFunc',['http://docs.opencv.org/3.4.0/df/dd9/structcv_1_1cudev_1_1ThreshToZeroFunc.html',1,'cv::cudev']]],
  ['threshtozeroinvfunc',['ThreshToZeroInvFunc',['http://docs.opencv.org/3.4.0/d8/d7e/structcv_1_1cudev_1_1ThreshToZeroInvFunc.html',1,'cv::cudev']]],
  ['threshtruncfunc',['ThreshTruncFunc',['http://docs.opencv.org/3.4.0/d0/d44/structcv_1_1cudev_1_1ThreshTruncFunc.html',1,'cv::cudev']]],
  ['throw_5fallocator_5fbase',['throw_allocator_base',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09660.html',1,'__gnu_cxx']]],
  ['throw_5fallocator_5fbase_3c_20_5ftp_2c_20limit_5fcondition_20_3e',['throw_allocator_base&lt; _Tp, limit_condition &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09660.html',1,'']]],
  ['throw_5fallocator_5fbase_3c_20_5ftp_2c_20random_5fcondition_20_3e',['throw_allocator_base&lt; _Tp, random_condition &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09660.html',1,'']]],
  ['throw_5fallocator_5flimit',['throw_allocator_limit',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09664.html',1,'__gnu_cxx']]],
  ['throw_5fallocator_5frandom',['throw_allocator_random',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09672.html',1,'__gnu_cxx']]],
  ['throw_5fvalue_5fbase',['throw_value_base',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09648.html',1,'__gnu_cxx']]],
  ['throw_5fvalue_5fbase_3c_20limit_5fcondition_20_3e',['throw_value_base&lt; limit_condition &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09648.html',1,'']]],
  ['throw_5fvalue_5fbase_3c_20random_5fcondition_20_3e',['throw_value_base&lt; random_condition &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09648.html',1,'']]],
  ['throw_5fvalue_5flimit',['throw_value_limit',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09652.html',1,'__gnu_cxx']]],
  ['throw_5fvalue_5frandom',['throw_value_random',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09656.html',1,'__gnu_cxx']]],
  ['tickmeter',['TickMeter',['http://docs.opencv.org/3.4.0/d9/d6f/classcv_1_1TickMeter.html',1,'cv']]],
  ['time_5fbase',['time_base',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05048.html',1,'std']]],
  ['time_5fget',['time_get',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05060.html',1,'std']]],
  ['time_5fget_5fbyname',['time_get_byname',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05064.html',1,'std']]],
  ['time_5fpoint',['time_point',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01836.html',1,'std::chrono']]],
  ['time_5fpoint_3c_20_5fclock_2c_20_5fduration_20_3e',['time_point&lt; _Clock, _Duration &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01836.html',1,'']]],
  ['time_5fput',['time_put',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05068.html',1,'std']]],
  ['time_5fput_5fbyname',['time_put_byname',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05072.html',1,'std']]],
  ['timed_5fmutex',['timed_mutex',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02732.html',1,'std']]],
  ['timelapser',['Timelapser',['http://docs.opencv.org/3.4.0/dd/dac/classcv_1_1detail_1_1Timelapser.html',1,'cv::detail']]],
  ['timelapsercrop',['TimelapserCrop',['http://docs.opencv.org/3.4.0/df/db9/classcv_1_1detail_1_1TimelapserCrop.html',1,'cv::detail']]],
  ['timer',['Timer',['http://docs.opencv.org/3.4.0/df/d4a/classcv_1_1ocl_1_1Timer.html',1,'cv::ocl']]],
  ['tlsdata',['TLSData',['http://docs.opencv.org/3.4.0/d9/db0/classcv_1_1TLSData.html',1,'cv']]],
  ['tlsdata_3c_20cv_3a_3ainstr_3a_3anodedatatls_20_3e',['TLSData&lt; cv::instr::NodeDataTls &gt;',['http://docs.opencv.org/3.4.0/d9/db0/classcv_1_1TLSData.html',1,'cv::TLSData&lt; cv::instr::NodeDataTls &gt;'],['http://docs.opencv.org/3.4.0/d9/db0/classcv_1_1TLSData.html',1,'TLSData&lt; cv::instr::NodeDataTls &gt;']]],
  ['tlsdatacontainer',['TLSDataContainer',['http://docs.opencv.org/3.4.0/df/d21/classcv_1_1TLSDataContainer.html',1,'cv']]],
  ['tofilemotionwriter',['ToFileMotionWriter',['http://docs.opencv.org/3.4.0/dc/dc1/classcv_1_1videostab_1_1ToFileMotionWriter.html',1,'cv::videostab']]],
  ['tonemap',['Tonemap',['http://docs.opencv.org/3.4.0/d8/d5e/classcv_1_1Tonemap.html',1,'cv']]],
  ['tonemapdrago',['TonemapDrago',['http://docs.opencv.org/3.4.0/da/d53/classcv_1_1TonemapDrago.html',1,'cv']]],
  ['tonemapdurand',['TonemapDurand',['http://docs.opencv.org/3.4.0/da/d3d/classcv_1_1TonemapDurand.html',1,'cv']]],
  ['tonemapmantiuk',['TonemapMantiuk',['http://docs.opencv.org/3.4.0/de/d76/classcv_1_1TonemapMantiuk.html',1,'cv']]],
  ['tonemapreinhard',['TonemapReinhard',['http://docs.opencv.org/3.4.0/d0/dec/classcv_1_1TonemapReinhard.html',1,'cv']]],
  ['tr_5fchars',['TR_chars',['http://docs.opencv.org/3.4.0/d7/dc3/classcv_1_1datasets_1_1TR__chars.html',1,'cv::datasets']]],
  ['tr_5fcharsobj',['TR_charsObj',['http://docs.opencv.org/3.4.0/d8/d14/structcv_1_1datasets_1_1TR__charsObj.html',1,'cv::datasets']]],
  ['tr_5ficdar',['TR_icdar',['http://docs.opencv.org/3.4.0/d7/dfb/classcv_1_1datasets_1_1TR__icdar.html',1,'cv::datasets']]],
  ['tr_5ficdarobj',['TR_icdarObj',['http://docs.opencv.org/3.4.0/de/d04/structcv_1_1datasets_1_1TR__icdarObj.html',1,'cv::datasets']]],
  ['tr_5fsvt',['TR_svt',['http://docs.opencv.org/3.4.0/da/dc9/classcv_1_1datasets_1_1TR__svt.html',1,'cv::datasets']]],
  ['tr_5fsvtobj',['TR_svtObj',['http://docs.opencv.org/3.4.0/d3/dc5/structcv_1_1datasets_1_1TR__svtObj.html',1,'cv::datasets']]],
  ['track_5falov',['TRACK_alov',['http://docs.opencv.org/3.4.0/d8/d1c/classcv_1_1datasets_1_1TRACK__alov.html',1,'cv::datasets']]],
  ['track_5falovobj',['TRACK_alovObj',['http://docs.opencv.org/3.4.0/dd/d88/structcv_1_1datasets_1_1TRACK__alovObj.html',1,'cv::datasets']]],
  ['track_5fvot',['TRACK_vot',['http://docs.opencv.org/3.4.0/dc/d52/classcv_1_1datasets_1_1TRACK__vot.html',1,'cv::datasets']]],
  ['track_5fvotobj',['TRACK_votObj',['http://docs.opencv.org/3.4.0/d9/d36/structcv_1_1datasets_1_1TRACK__votObj.html',1,'cv::datasets']]],
  ['tracker',['Tracker',['http://docs.opencv.org/3.4.0/d0/d0a/classcv_1_1Tracker.html',1,'cv']]],
  ['trackeradaboostingtargetstate',['TrackerAdaBoostingTargetState',['http://docs.opencv.org/3.4.0/d1/dd1/classcv_1_1TrackerStateEstimatorAdaBoosting_1_1TrackerAdaBoostingTargetState.html',1,'cv::TrackerStateEstimatorAdaBoosting']]],
  ['trackerboosting',['TrackerBoosting',['http://docs.opencv.org/3.4.0/d1/d1a/classcv_1_1TrackerBoosting.html',1,'cv']]],
  ['trackerfeature',['TrackerFeature',['http://docs.opencv.org/3.4.0/d7/da2/classcv_1_1TrackerFeature.html',1,'cv']]],
  ['trackerfeaturefeature2d',['TrackerFeatureFeature2d',['http://docs.opencv.org/3.4.0/d3/d4c/classcv_1_1TrackerFeatureFeature2d.html',1,'cv']]],
  ['trackerfeaturehaar',['TrackerFeatureHAAR',['http://docs.opencv.org/3.4.0/d6/d00/classcv_1_1TrackerFeatureHAAR.html',1,'cv']]],
  ['trackerfeaturehog',['TrackerFeatureHOG',['http://docs.opencv.org/3.4.0/d2/da3/classcv_1_1TrackerFeatureHOG.html',1,'cv']]],
  ['trackerfeaturelbp',['TrackerFeatureLBP',['http://docs.opencv.org/3.4.0/dc/d73/classcv_1_1TrackerFeatureLBP.html',1,'cv']]],
  ['trackerfeatureset',['TrackerFeatureSet',['http://docs.opencv.org/3.4.0/dc/da7/classcv_1_1TrackerFeatureSet.html',1,'cv']]],
  ['trackergoturn',['TrackerGOTURN',['http://docs.opencv.org/3.4.0/d7/d4c/classcv_1_1TrackerGOTURN.html',1,'cv']]],
  ['trackerkcf',['TrackerKCF',['http://docs.opencv.org/3.4.0/d2/dff/classcv_1_1TrackerKCF.html',1,'cv']]],
  ['trackermedianflow',['TrackerMedianFlow',['http://docs.opencv.org/3.4.0/d7/d86/classcv_1_1TrackerMedianFlow.html',1,'cv']]],
  ['trackermil',['TrackerMIL',['http://docs.opencv.org/3.4.0/d0/d26/classcv_1_1TrackerMIL.html',1,'cv']]],
  ['trackermiltargetstate',['TrackerMILTargetState',['http://docs.opencv.org/3.4.0/d8/dd1/classcv_1_1TrackerStateEstimatorMILBoosting_1_1TrackerMILTargetState.html',1,'cv::TrackerStateEstimatorMILBoosting']]],
  ['trackermodel',['TrackerModel',['http://docs.opencv.org/3.4.0/d0/dfc/classcv_1_1TrackerModel.html',1,'cv']]],
  ['trackermosse',['TrackerMOSSE',['http://docs.opencv.org/3.4.0/d0/d02/classcv_1_1TrackerMOSSE.html',1,'cv']]],
  ['trackersampler',['TrackerSampler',['http://docs.opencv.org/3.4.0/da/d76/classcv_1_1TrackerSampler.html',1,'cv']]],
  ['trackersampleralgorithm',['TrackerSamplerAlgorithm',['http://docs.opencv.org/3.4.0/dc/d75/classcv_1_1TrackerSamplerAlgorithm.html',1,'cv']]],
  ['trackersamplercs',['TrackerSamplerCS',['http://docs.opencv.org/3.4.0/da/d3e/classcv_1_1TrackerSamplerCS.html',1,'cv']]],
  ['trackersamplercsc',['TrackerSamplerCSC',['http://docs.opencv.org/3.4.0/dc/d5c/classcv_1_1TrackerSamplerCSC.html',1,'cv']]],
  ['trackersamplerpf',['TrackerSamplerPF',['http://docs.opencv.org/3.4.0/d3/df4/classcv_1_1TrackerSamplerPF.html',1,'cv']]],
  ['trackerstateestimator',['TrackerStateEstimator',['http://docs.opencv.org/3.4.0/d2/db9/classcv_1_1TrackerStateEstimator.html',1,'cv']]],
  ['trackerstateestimatoradaboosting',['TrackerStateEstimatorAdaBoosting',['http://docs.opencv.org/3.4.0/de/df6/classcv_1_1TrackerStateEstimatorAdaBoosting.html',1,'cv']]],
  ['trackerstateestimatormilboosting',['TrackerStateEstimatorMILBoosting',['http://docs.opencv.org/3.4.0/d9/d20/classcv_1_1TrackerStateEstimatorMILBoosting.html',1,'cv']]],
  ['trackerstateestimatorsvm',['TrackerStateEstimatorSVM',['http://docs.opencv.org/3.4.0/d3/db6/classcv_1_1TrackerStateEstimatorSVM.html',1,'cv']]],
  ['trackertargetstate',['TrackerTargetState',['http://docs.opencv.org/3.4.0/dd/d9d/classcv_1_1TrackerTargetState.html',1,'cv']]],
  ['trackertld',['TrackerTLD',['http://docs.opencv.org/3.4.0/dc/d1c/classcv_1_1TrackerTLD.html',1,'cv']]],
  ['traindata',['TrainData',['http://docs.opencv.org/3.4.0/dc/d32/classcv_1_1ml_1_1TrainData.html',1,'cv::ml']]],
  ['traits',['Traits',['http://docs.opencv.org/3.4.0/d1/d77/classmatlab_1_1Traits.html',1,'matlab']]],
  ['traits_3c_20bool_20_3e',['Traits&lt; bool &gt;',['http://docs.opencv.org/3.4.0/dc/dd4/classmatlab_1_1Traits_3_01bool_01_4.html',1,'matlab']]],
  ['traits_3c_20char_20_3e',['Traits&lt; char &gt;',['http://docs.opencv.org/3.4.0/d9/d5c/classmatlab_1_1Traits_3_01char_01_4.html',1,'matlab']]],
  ['traits_3c_20double_20_3e',['Traits&lt; double &gt;',['http://docs.opencv.org/3.4.0/da/d44/classmatlab_1_1Traits_3_01double_01_4.html',1,'matlab']]],
  ['traits_3c_20float_20_3e',['Traits&lt; float &gt;',['http://docs.opencv.org/3.4.0/d9/d7b/classmatlab_1_1Traits_3_01float_01_4.html',1,'matlab']]],
  ['traits_3c_20int16_5ft_20_3e',['Traits&lt; int16_t &gt;',['http://docs.opencv.org/3.4.0/d1/d19/classmatlab_1_1Traits_3_01int16__t_01_4.html',1,'matlab']]],
  ['traits_3c_20int32_5ft_20_3e',['Traits&lt; int32_t &gt;',['http://docs.opencv.org/3.4.0/d9/de9/classmatlab_1_1Traits_3_01int32__t_01_4.html',1,'matlab']]],
  ['traits_3c_20int64_5ft_20_3e',['Traits&lt; int64_t &gt;',['http://docs.opencv.org/3.4.0/d1/d9b/classmatlab_1_1Traits_3_01int64__t_01_4.html',1,'matlab']]],
  ['traits_3c_20int8_5ft_20_3e',['Traits&lt; int8_t &gt;',['http://docs.opencv.org/3.4.0/d5/d2f/classmatlab_1_1Traits_3_01int8__t_01_4.html',1,'matlab']]],
  ['traits_3c_20matlab_3a_3ainherittype_20_3e',['Traits&lt; matlab::InheritType &gt;',['http://docs.opencv.org/3.4.0/d5/d94/classmatlab_1_1Traits_3_01matlab_1_1InheritType_01_4.html',1,'matlab']]],
  ['traits_3c_20uint16_5ft_20_3e',['Traits&lt; uint16_t &gt;',['http://docs.opencv.org/3.4.0/d6/d7e/classmatlab_1_1Traits_3_01uint16__t_01_4.html',1,'matlab']]],
  ['traits_3c_20uint32_5ft_20_3e',['Traits&lt; uint32_t &gt;',['http://docs.opencv.org/3.4.0/df/d31/classmatlab_1_1Traits_3_01uint32__t_01_4.html',1,'matlab']]],
  ['traits_3c_20uint64_5ft_20_3e',['Traits&lt; uint64_t &gt;',['http://docs.opencv.org/3.4.0/d1/d5a/classmatlab_1_1Traits_3_01uint64__t_01_4.html',1,'matlab']]],
  ['traits_3c_20uint8_5ft_20_3e',['Traits&lt; uint8_t &gt;',['http://docs.opencv.org/3.4.0/de/d89/classmatlab_1_1Traits_3_01uint8__t_01_4.html',1,'matlab']]],
  ['transientareassegmentationmodule',['TransientAreasSegmentationModule',['http://docs.opencv.org/3.4.0/da/d6e/classcv_1_1bioinspired_1_1TransientAreasSegmentationModule.html',1,'cv::bioinspired']]],
  ['translationbasedlocaloutlierrejector',['TranslationBasedLocalOutlierRejector',['http://docs.opencv.org/3.4.0/dd/d13/classcv_1_1videostab_1_1TranslationBasedLocalOutlierRejector.html',1,'cv::videostab']]],
  ['transposebody',['TransposeBody',['http://docs.opencv.org/3.4.0/d2/d40/structcv_1_1cudev_1_1TransposeBody.html',1,'cv::cudev']]],
  ['transversemercatorprojector',['TransverseMercatorProjector',['http://docs.opencv.org/3.4.0/d5/df7/structcv_1_1detail_1_1TransverseMercatorProjector.html',1,'cv::detail']]],
  ['transversemercatorwarper',['TransverseMercatorWarper',['http://docs.opencv.org/3.4.0/df/d33/classcv_1_1TransverseMercatorWarper.html',1,'cv::TransverseMercatorWarper'],['http://docs.opencv.org/3.4.0/d4/d6b/classcv_1_1detail_1_1TransverseMercatorWarper.html',1,'cv::detail::TransverseMercatorWarper']]],
  ['treat_5fas_5ffloating_5fpoint',['treat_as_floating_point',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01888.html',1,'std::chrono']]],
  ['tree',['tree',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10036.html',1,'__gnu_pbds']]],
  ['tree_5fmetadata_5fhelper',['tree_metadata_helper',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10964.html',1,'__gnu_pbds::detail']]],
  ['tree_5fmetadata_5fhelper_3c_20node_5fupdate_2c_20false_20_3e',['tree_metadata_helper&lt; Node_Update, false &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10968.html',1,'__gnu_pbds::detail']]],
  ['tree_5fmetadata_5fhelper_3c_20node_5fupdate_2c_20true_20_3e',['tree_metadata_helper&lt; Node_Update, true &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10972.html',1,'__gnu_pbds::detail']]],
  ['tree_5fnode_5fmetadata_5fdispatch',['tree_node_metadata_dispatch',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10976.html',1,'__gnu_pbds::detail']]],
  ['tree_5forder_5fstatistics_5fnode_5fupdate',['tree_order_statistics_node_update',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10280.html',1,'__gnu_pbds']]],
  ['tree_5ftag',['tree_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10160.html',1,'__gnu_pbds']]],
  ['tree_5ftraits',['tree_traits',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10584.html',1,'__gnu_pbds::detail']]],
  ['tree_5ftraits_3c_20key_2c_20mapped_2c_20cmp_5ffn_2c_20node_5fupdate_2c_20ov_5ftree_5ftag_2c_20_5falloc_20_3e',['tree_traits&lt; Key, Mapped, Cmp_Fn, Node_Update, ov_tree_tag, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10800.html',1,'__gnu_pbds::detail']]],
  ['tree_5ftraits_3c_20key_2c_20mapped_2c_20cmp_5ffn_2c_20node_5fupdate_2c_20rb_5ftree_5ftag_2c_20_5falloc_20_3e',['tree_traits&lt; Key, Mapped, Cmp_Fn, Node_Update, rb_tree_tag, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10900.html',1,'__gnu_pbds::detail']]],
  ['tree_5ftraits_3c_20key_2c_20mapped_2c_20cmp_5ffn_2c_20node_5fupdate_2c_20splay_5ftree_5ftag_2c_20_5falloc_20_3e',['tree_traits&lt; Key, Mapped, Cmp_Fn, Node_Update, splay_tree_tag, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10952.html',1,'__gnu_pbds::detail']]],
  ['tree_5ftraits_3c_20key_2c_20null_5ftype_2c_20cmp_5ffn_2c_20node_5fupdate_2c_20ov_5ftree_5ftag_2c_20_5falloc_20_3e',['tree_traits&lt; Key, null_type, Cmp_Fn, Node_Update, ov_tree_tag, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10804.html',1,'__gnu_pbds::detail']]],
  ['tree_5ftraits_3c_20key_2c_20null_5ftype_2c_20cmp_5ffn_2c_20node_5fupdate_2c_20rb_5ftree_5ftag_2c_20_5falloc_20_3e',['tree_traits&lt; Key, null_type, Cmp_Fn, Node_Update, rb_tree_tag, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10904.html',1,'__gnu_pbds::detail']]],
  ['tree_5ftraits_3c_20key_2c_20null_5ftype_2c_20cmp_5ffn_2c_20node_5fupdate_2c_20splay_5ftree_5ftag_2c_20_5falloc_20_3e',['tree_traits&lt; Key, null_type, Cmp_Fn, Node_Update, splay_tree_tag, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10956.html',1,'__gnu_pbds::detail']]],
  ['trie',['trie',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10040.html',1,'__gnu_pbds']]],
  ['trie_5fmetadata_5fhelper',['trie_metadata_helper',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10984.html',1,'__gnu_pbds::detail']]],
  ['trie_5fmetadata_5fhelper_3c_20node_5fupdate_2c_20false_20_3e',['trie_metadata_helper&lt; Node_Update, false &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10988.html',1,'__gnu_pbds::detail']]],
  ['trie_5fmetadata_5fhelper_3c_20node_5fupdate_2c_20true_20_3e',['trie_metadata_helper&lt; Node_Update, true &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10992.html',1,'__gnu_pbds::detail']]],
  ['trie_5fnode_5fmetadata_5fdispatch',['trie_node_metadata_dispatch',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10996.html',1,'__gnu_pbds::detail']]],
  ['trie_5forder_5fstatistics_5fnode_5fupdate',['trie_order_statistics_node_update',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10292.html',1,'__gnu_pbds']]],
  ['trie_5fpolicy_5fbase',['trie_policy_base',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a11008.html',1,'__gnu_pbds::detail']]],
  ['trie_5fprefix_5fsearch_5fnode_5fupdate',['trie_prefix_search_node_update',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10288.html',1,'__gnu_pbds']]],
  ['trie_5fstring_5faccess_5ftraits',['trie_string_access_traits',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10284.html',1,'__gnu_pbds']]],
  ['trie_5ftag',['trie_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10176.html',1,'__gnu_pbds']]],
  ['trie_5ftraits',['trie_traits',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10588.html',1,'__gnu_pbds::detail']]],
  ['trie_5ftraits_3c_20key_2c_20mapped_2c_20_5fatraits_2c_20node_5fupdate_2c_20pat_5ftrie_5ftag_2c_20_5falloc_20_3e',['trie_traits&lt; Key, Mapped, _ATraits, Node_Update, pat_trie_tag, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10880.html',1,'__gnu_pbds::detail']]],
  ['trie_5ftraits_3c_20key_2c_20null_5ftype_2c_20_5fatraits_2c_20node_5fupdate_2c_20pat_5ftrie_5ftag_2c_20_5falloc_20_3e',['trie_traits&lt; Key, null_type, _ATraits, Node_Update, pat_trie_tag, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10884.html',1,'__gnu_pbds::detail']]],
  ['trivial_5fiterator_5ftag',['trivial_iterator_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10112.html',1,'__gnu_pbds']]],
  ['true',['True',['http://docs.opencv.org/3.4.0/d3/d87/classcvflann_1_1True.html',1,'cvflann']]],
  ['try_5fto_5flock_5ft',['try_to_lock_t',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06248.html',1,'std']]],
  ['tuple',['tuple',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02996.html',1,'std']]],
  ['tuple_3c_20_5fbound_5fargs_2e_2e_2e_20_3e',['tuple&lt; _Bound_args... &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02996.html',1,'']]],
  ['tuple_3c_20_5fforwarditerator1_2c_20_5fforwarditerator1_2c_20_5fbinarypredicate_20_3e',['tuple&lt; _ForwardIterator1, _ForwardIterator1, _BinaryPredicate &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02996.html',1,'']]],
  ['tuple_3c_20_5ft1_2c_20_5ft2_20_3e',['tuple&lt; _T1, _T2 &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a03048.html',1,'std']]],
  ['tuple_3c_20pointer_2c_20_5fdp_20_3e',['tuple&lt; pointer, _Dp &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02996.html',1,'']]],
  ['tuple_3c_20pointer_2c_20default_5fdelete_3c_20_5fcodecvt_20_3e_20_3e',['tuple&lt; pointer, default_delete&lt; _Codecvt &gt; &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02996.html',1,'']]],
  ['tuple_3c_20pointer_2c_20default_5fdelete_3c_20_5fres_5ftype_20_3e_20_3e',['tuple&lt; pointer, default_delete&lt; _Res_type &gt; &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02996.html',1,'']]],
  ['tuple_3c_20pointer_2c_20default_5fdelete_3c_20_5fresult_3c_20_5fres_20_3e_20_3e_20_3e',['tuple&lt; pointer, default_delete&lt; _Result&lt; _Res &gt; &gt; &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02996.html',1,'']]],
  ['tuple_3c_20pointer_2c_20default_5fdelete_3c_20_5fresult_5fbase_20_3e_20_3e',['tuple&lt; pointer, default_delete&lt; _Result_base &gt; &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02996.html',1,'']]],
  ['tuple_3c_20pointer_2c_20default_5fdelete_3c_20bool_20_3e_20_3e',['tuple&lt; pointer, default_delete&lt; bool &gt; &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02996.html',1,'']]],
  ['tuple_3c_20std_3a_3aarray_3c_20_5ftp_2c_20_5flen_20_3e_2c_20_5fpred_20_3e',['tuple&lt; std::array&lt; _Tp, _Len &gt;, _Pred &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02996.html',1,'']]],
  ['tuple_5felement',['tuple_element',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01708.html',1,'std']]],
  ['tuple_5felement_3c_200_2c_20std_3a_3apair_3c_20_5ftp1_2c_20_5ftp2_20_3e_20_3e',['tuple_element&lt; 0, std::pair&lt; _Tp1, _Tp2 &gt; &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a03656.html',1,'std']]],
  ['tuple_5felement_3c_200_2c_20tuple_3c_20_5fhead_2c_20_5ftail_2e_2e_2e_20_3e_20_3e',['tuple_element&lt; 0, tuple&lt; _Head, _Tail... &gt; &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a03060.html',1,'std']]],
  ['tuple_5felement_3c_201_2c_20std_3a_3apair_3c_20_5ftp1_2c_20_5ftp2_20_3e_20_3e',['tuple_element&lt; 1, std::pair&lt; _Tp1, _Tp2 &gt; &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a03660.html',1,'std']]],
  ['tuple_5felement_3c_20_5f_5fi_20_2d_201_2c_20tuple_3c_20_5ftail_2e_2e_2e_20_3e_20_3e',['tuple_element&lt; __i - 1, tuple&lt; _Tail... &gt; &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01708.html',1,'']]],
  ['tuple_5felement_3c_20_5f_5fi_2c_20tuple_3c_20_5fhead_2c_20_5ftail_2e_2e_2e_20_3e_20_3e',['tuple_element&lt; __i, tuple&lt; _Head, _Tail... &gt; &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a03056.html',1,'std']]],
  ['tuple_5felement_3c_20_5f_5fi_2c_20tuple_3c_3e_20_3e',['tuple_element&lt; __i, tuple&lt;&gt; &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a03064.html',1,'std']]],
  ['tuple_5felement_3c_20_5fint_2c_20_3a_3aarray_3c_20_5ftp_2c_20_5fnm_20_3e_20_3e',['tuple_element&lt; _Int, ::array&lt; _Tp, _Nm &gt; &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01712.html',1,'std']]],
  ['tuple_5felement_3c_20_5fint_2c_20std_3a_3a_5f_5fdebug_3a_3aarray_3c_20_5ftp_2c_20_5fnm_20_3e_20_3e',['tuple_element&lt; _Int, std::__debug::array&lt; _Tp, _Nm &gt; &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07748.html',1,'std']]],
  ['tuple_5fsize',['tuple_size',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01700.html',1,'std']]],
  ['tuple_5fsize_3c_20std_3a_3a_5f_5fdebug_3a_3aarray_3c_20_5ftp_2c_20_5fnm_20_3e_20_3e',['tuple_size&lt; std::__debug::array&lt; _Tp, _Nm &gt; &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07744.html',1,'std']]],
  ['tuple_5fsize_3c_20std_3a_3apair_3c_20_5ftp1_2c_20_5ftp2_20_3e_20_3e',['tuple_size&lt; std::pair&lt; _Tp1, _Tp2 &gt; &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a03652.html',1,'std']]],
  ['tuple_5fsize_3c_20tuple_3c_20_5felements_2e_2e_2e_20_3e_20_3e',['tuple_size&lt; tuple&lt; _Elements... &gt; &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a03052.html',1,'std']]],
  ['tuple_5fsize_3c_3a_3aarray_3c_20_5ftp_2c_20_5fnm_20_3e_20_3e',['tuple_size&lt;::array&lt; _Tp, _Nm &gt; &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01704.html',1,'std']]],
  ['tupletraits',['TupleTraits',['http://docs.opencv.org/3.4.0/dd/d08/structcv_1_1cudev_1_1TupleTraits.html',1,'cv::cudev']]],
  ['tupletraits_3c_20tuple_3c_20p0_2c_20p1_2c_20p2_2c_20p3_2c_20p4_2c_20p5_2c_20p6_2c_20p7_2c_20p8_2c_20p9_20_3e_20_3e',['TupleTraits&lt; tuple&lt; P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 &gt; &gt;',['http://docs.opencv.org/3.4.0/d2/dae/structcv_1_1cudev_1_1TupleTraits_3_01tuple_3_01P0_00_01P1_00_01P2_00_01P3_00_01P4_00_01P5_00_01P41642a2d25b95a5ddb87ca2004b28336.html',1,'cv::cudev']]],
  ['twopassstabilizer',['TwoPassStabilizer',['http://docs.opencv.org/3.4.0/d8/d9c/classcv_1_1videostab_1_1TwoPassStabilizer.html',1,'cv::videostab']]],
  ['type',['type',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10508.html',1,'__gnu_pbds::detail::entry_cmp&lt; _VTp, Cmp_Fn, _Alloc, false &gt;']]],
  ['type_5fbase',['type_base',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10460.html',1,'__gnu_pbds::detail']]],
  ['type_5fbase_3c_20key_2c_20mapped_2c_20_5falloc_2c_20false_20_3e',['type_base&lt; Key, Mapped, _Alloc, false &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10464.html',1,'__gnu_pbds::detail']]],
  ['type_5fbase_3c_20key_2c_20mapped_2c_20_5falloc_2c_20true_20_3e',['type_base&lt; Key, Mapped, _Alloc, true &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10468.html',1,'__gnu_pbds::detail']]],
  ['type_5fbase_3c_20key_2c_20null_5ftype_2c_20_5falloc_2c_20false_20_3e',['type_base&lt; Key, null_type, _Alloc, false &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10472.html',1,'__gnu_pbds::detail']]],
  ['type_5fbase_3c_20key_2c_20null_5ftype_2c_20_5falloc_2c_20true_20_3e',['type_base&lt; Key, null_type, _Alloc, true &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10476.html',1,'__gnu_pbds::detail']]],
  ['type_5fdispatch',['type_dispatch',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10480.html',1,'__gnu_pbds::detail']]],
  ['type_5findex',['type_index',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a03148.html',1,'std']]],
  ['type_5finfo',['type_info',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01672.html',1,'std']]],
  ['typed_5fbase_5fany_5fpolicy',['typed_base_any_policy',['http://docs.opencv.org/3.4.0/d5/d0f/structcvflann_1_1anyimpl_1_1typed__base__any__policy.html',1,'cvflann::anyimpl']]],
  ['types_5ftraits',['types_traits',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10484.html',1,'__gnu_pbds::detail']]],
  ['types_5ftraits_3c_20key_2c_20mapped_2c_20_5falloc_2c_20false_20_3e',['types_traits&lt; Key, Mapped, _Alloc, false &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10484.html',1,'']]],
  ['typesequals',['TypesEquals',['http://docs.opencv.org/3.4.0/df/d71/structcv_1_1cudev_1_1TypesEquals.html',1,'cv::cudev']]],
  ['typesequals_3c_20a_2c_20a_20_3e',['TypesEquals&lt; A, A &gt;',['http://docs.opencv.org/3.4.0/df/dbf/structcv_1_1cudev_1_1TypesEquals_3_01A_00_01A_01_4.html',1,'cv::cudev']]],
  ['typetraits',['TypeTraits',['http://docs.opencv.org/3.4.0/d7/d97/structcv_1_1cudev_1_1TypeTraits.html',1,'cv::cudev']]]
];
