var searchData=
[
  ['ukfsystemmodel',['UkfSystemModel',['http://docs.opencv.org/3.4.0/da/d2b/classcv_1_1tracking_1_1UkfSystemModel.html',1,'cv::tracking']]],
  ['umat',['UMat',['http://docs.opencv.org/3.4.0/d7/d45/classcv_1_1UMat.html',1,'cv']]],
  ['umatdata',['UMatData',['http://docs.opencv.org/3.4.0/db/d58/structcv_1_1UMatData.html',1,'cv']]],
  ['umatdataautolock',['UMatDataAutoLock',['http://docs.opencv.org/3.4.0/d7/df8/structcv_1_1UMatDataAutoLock.html',1,'cv']]],
  ['unary_5fcompose',['unary_compose',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08084.html',1,'__gnu_cxx']]],
  ['unary_5ffunction',['unary_function',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06392.html',1,'std::unary_function&lt; _Arg, _Result &gt;'],['http://docs.opencv.org/3.4.0/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'cv::cudev::unary_function&lt; _Arg, _Result &gt;']]],
  ['unary_5ffunction_3c_20_5f_5fgnu_5fcxx_3a_3athrow_5fvalue_5flimit_2c_20size_5ft_20_3e',['unary_function&lt; __gnu_cxx::throw_value_limit, size_t &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06392.html',1,'']]],
  ['unary_5ffunction_3c_20_5f_5fgnu_5fcxx_3a_3athrow_5fvalue_5frandom_2c_20size_5ft_20_3e',['unary_function&lt; __gnu_cxx::throw_value_random, size_t &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06392.html',1,'']]],
  ['unary_5ffunction_3c_20_5ffirstargumenttype_2c_20_5fresulttype_20_3e',['unary_function&lt; _FirstArgumentType, _ResultType &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06392.html',1,'']]],
  ['unary_5ffunction_3c_20_5ffunctor_3a_3aargument_5ftype_2c_20_5ffunctor_3a_3aresult_5ftype_20_3e',['unary_function&lt; _Functor::argument_type, _Functor::result_type &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06392.html',1,'']]],
  ['unary_5ffunction_3c_20_5foperation2_3a_3aargument_5ftype_2c_20_5foperation1_3a_3aresult_5ftype_20_3e',['unary_function&lt; _Operation2::argument_type, _Operation1::result_type &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06392.html',1,'']]],
  ['unary_5ffunction_3c_20_5foperation_3a_3afirst_5fargument_5ftype_2c_20_5foperation_3a_3aresult_5ftype_20_3e',['unary_function&lt; _Operation::first_argument_type, _Operation::result_type &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06392.html',1,'']]],
  ['unary_5ffunction_3c_20_5foperation_3a_3asecond_5fargument_5ftype_2c_20_5foperation_3a_3aresult_5ftype_20_3e',['unary_function&lt; _Operation::second_argument_type, _Operation::result_type &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06392.html',1,'']]],
  ['unary_5ffunction_3c_20_5fpair_2c_20_5fpair_3a_3afirst_5ftype_20_3e',['unary_function&lt; _Pair, _Pair::first_type &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06392.html',1,'']]],
  ['unary_5ffunction_3c_20_5fpair_2c_20_5fpair_3a_3asecond_5ftype_20_3e',['unary_function&lt; _Pair, _Pair::second_type &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06392.html',1,'']]],
  ['unary_5ffunction_3c_20_5fpredicate_3a_3aargument_5ftype_2c_20bool_20_3e',['unary_function&lt; _Predicate::argument_type, bool &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06392.html',1,'']]],
  ['unary_5ffunction_3c_20_5fsecondargumenttype_2c_20_5fresulttype_20_3e',['unary_function&lt; _SecondArgumentType, _ResultType &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06392.html',1,'']]],
  ['unary_5ffunction_3c_20_5ft1_20_2a_2c_20_5fres_20_3e',['unary_function&lt; _T1 *, _Res &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06392.html',1,'']]],
  ['unary_5ffunction_3c_20_5ft1_2c_20_5fres_20_3e',['unary_function&lt; _T1, _Res &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06392.html',1,'']]],
  ['unary_5ffunction_3c_20_5ftp_20_2a_2c_20_5fret_20_3e',['unary_function&lt; _Tp *, _Ret &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06392.html',1,'']]],
  ['unary_5ffunction_3c_20_5ftp_2c_20_5fret_20_3e',['unary_function&lt; _Tp, _Ret &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06392.html',1,'']]],
  ['unary_5ffunction_3c_20_5ftp_2c_20_5ftp_20_3e',['unary_function&lt; _Tp, _Tp &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06392.html',1,'']]],
  ['unary_5ffunction_3c_20_5ftp_2c_20bool_20_3e',['unary_function&lt; _Tp, bool &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06392.html',1,'']]],
  ['unary_5ffunction_3c_20_5fvalue_2c_20_5fvalue_20_3e',['unary_function&lt; _Value, _Value &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06392.html',1,'']]],
  ['unary_5ffunction_3c_20argument_5ftype_2c_20bool_20_3e',['unary_function&lt; argument_type, bool &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06392.html',1,'']]],
  ['unary_5ffunction_3c_20const_20_5ft1_20_2a_2c_20_5fres_20_3e',['unary_function&lt; const _T1 *, _Res &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06392.html',1,'']]],
  ['unary_5ffunction_3c_20const_20_5ftp_20_2a_2c_20_5fret_20_3e',['unary_function&lt; const _Tp *, _Ret &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06392.html',1,'']]],
  ['unary_5ffunction_3c_20const_20volatile_20_5ft1_20_2a_2c_20_5fres_20_3e',['unary_function&lt; const volatile _T1 *, _Res &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06392.html',1,'']]],
  ['unary_5ffunction_3c_20double_2c_20double_20_3e',['unary_function&lt; double, double &gt;',['http://docs.opencv.org/3.4.0/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20float_2c_20float_20_3e',['unary_function&lt; float, float &gt;',['http://docs.opencv.org/3.4.0/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20float_2c_20short_20_3e',['unary_function&lt; float, short &gt;',['http://docs.opencv.org/3.4.0/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20int_2c_20float_20_3e',['unary_function&lt; int, float &gt;',['http://docs.opencv.org/3.4.0/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20int_2c_20int_20_3e',['unary_function&lt; int, int &gt;',['http://docs.opencv.org/3.4.0/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20op_3a_3afirst_5fargument_5ftype_2c_20op_3a_3aresult_5ftype_20_3e',['unary_function&lt; Op::first_argument_type, Op::result_type &gt;',['http://docs.opencv.org/3.4.0/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20op_3a_3asecond_5fargument_5ftype_2c_20op_3a_3aresult_5ftype_20_3e',['unary_function&lt; Op::second_argument_type, Op::result_type &gt;',['http://docs.opencv.org/3.4.0/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20pair_3c_20const_20_5fkey_2c_20_5ftp_20_3e_2c_20pair_3c_20const_20_5fkey_2c_20_5ftp_20_3e_20_3a_3afirst_5ftype_20_3e',['unary_function&lt; pair&lt; const _Key, _Tp &gt;, pair&lt; const _Key, _Tp &gt; ::first_type &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06392.html',1,'']]],
  ['unary_5ffunction_3c_20predicate_3a_3aargument_5ftype_2c_20predicate_3a_3aresult_5ftype_20_3e',['unary_function&lt; Predicate::argument_type, Predicate::result_type &gt;',['http://docs.opencv.org/3.4.0/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20schar_2c_20float_20_3e',['unary_function&lt; schar, float &gt;',['http://docs.opencv.org/3.4.0/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20schar_2c_20schar_20_3e',['unary_function&lt; schar, schar &gt;',['http://docs.opencv.org/3.4.0/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20short_2c_20float_20_3e',['unary_function&lt; short, float &gt;',['http://docs.opencv.org/3.4.0/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20short_2c_20short_20_3e',['unary_function&lt; short, short &gt;',['http://docs.opencv.org/3.4.0/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20std_3a_3apair_3c_20_5ftp_2c_20_5ftp_20_3e_2c_20bool_20_3e',['unary_function&lt; std::pair&lt; _Tp, _Tp &gt;, bool &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06392.html',1,'']]],
  ['unary_5ffunction_3c_20t_2c_20d_20_3e',['unary_function&lt; T, D &gt;',['http://docs.opencv.org/3.4.0/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20t_2c_20functional_5fdetail_3a_3afloattype_3c_20t_20_3e_3a_3atype_20_3e',['unary_function&lt; T, functional_detail::FloatType&lt; T &gt;::type &gt;',['http://docs.opencv.org/3.4.0/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20t_2c_20makevec_3c_20uchar_2c_20vectraits_3c_20t_20_3e_3a_3acn_20_3e_3a_3atype_20_3e',['unary_function&lt; T, MakeVec&lt; uchar, VecTraits&lt; T &gt;::cn &gt;::type &gt;',['http://docs.opencv.org/3.4.0/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20t_2c_20t_20_3e',['unary_function&lt; T, T &gt;',['http://docs.opencv.org/3.4.0/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20uchar_2c_20float_20_3e',['unary_function&lt; uchar, float &gt;',['http://docs.opencv.org/3.4.0/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20uchar_2c_20uchar_20_3e',['unary_function&lt; uchar, uchar &gt;',['http://docs.opencv.org/3.4.0/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20uint_2c_20float_20_3e',['unary_function&lt; uint, float &gt;',['http://docs.opencv.org/3.4.0/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20uint_2c_20uint_20_3e',['unary_function&lt; uint, uint &gt;',['http://docs.opencv.org/3.4.0/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20unsigned_20int_2c_20unsigned_20int_20_3e',['unary_function&lt; unsigned int, unsigned int &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06392.html',1,'']]],
  ['unary_5ffunction_3c_20ushort_2c_20float_20_3e',['unary_function&lt; ushort, float &gt;',['http://docs.opencv.org/3.4.0/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20ushort_2c_20ushort_20_3e',['unary_function&lt; ushort, ushort &gt;',['http://docs.opencv.org/3.4.0/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20volatile_20_5ft1_20_2a_2c_20_5fres_20_3e',['unary_function&lt; volatile _T1 *, _Res &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06392.html',1,'']]],
  ['unary_5fnegate',['unary_negate',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06552.html',1,'std']]],
  ['unarynegate',['UnaryNegate',['http://docs.opencv.org/3.4.0/d2/d83/structcv_1_1cudev_1_1UnaryNegate.html',1,'cv::cudev']]],
  ['unarytransformptr',['UnaryTransformPtr',['http://docs.opencv.org/3.4.0/dd/d01/structcv_1_1cudev_1_1UnaryTransformPtr.html',1,'cv::cudev']]],
  ['unarytransformptrsz',['UnaryTransformPtrSz',['http://docs.opencv.org/3.4.0/d0/db7/structcv_1_1cudev_1_1UnaryTransformPtrSz.html',1,'cv::cudev']]],
  ['unarytupleadapter',['UnaryTupleAdapter',['http://docs.opencv.org/3.4.0/d4/d57/structcv_1_1cudev_1_1UnaryTupleAdapter.html',1,'cv::cudev']]],
  ['unbalanced_5ftag',['unbalanced_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08644.html',1,'__gnu_parallel']]],
  ['underflow_5ferror',['underflow_error',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02932.html',1,'std']]],
  ['uniform_5fint_5fdistribution',['uniform_int_distribution',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06928.html',1,'std']]],
  ['uniform_5freal_5fdistribution',['uniform_real_distribution',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05432.html',1,'std']]],
  ['unique_5flock',['unique_lock',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06260.html',1,'std']]],
  ['unique_5fptr',['unique_ptr',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06956.html',1,'std']]],
  ['unique_5fptr_3c_20_5fcodecvt_20_3e',['unique_ptr&lt; _Codecvt &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06956.html',1,'']]],
  ['unique_5fptr_3c_20_5fres_5ftype_20_3e',['unique_ptr&lt; _Res_type &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06956.html',1,'']]],
  ['unique_5fptr_3c_20_5fresult_3c_20_5fres_20_3e_20_3e',['unique_ptr&lt; _Result&lt; _Res &gt; &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06956.html',1,'']]],
  ['unique_5fptr_3c_20_5fresult_5fbase_20_3e',['unique_ptr&lt; _Result_base &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06956.html',1,'']]],
  ['unique_5fptr_3c_20_5ftp_5b_5d_2c_20_5fdp_20_3e',['unique_ptr&lt; _Tp[], _Dp &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06960.html',1,'std']]],
  ['unique_5fptr_3c_20bool_5b_5d_3e',['unique_ptr&lt; bool[]&gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06956.html',1,'']]],
  ['unique_5fptr_3c_20caffe_3a_3anet_3c_20float_20_3e_20_3e',['unique_ptr&lt; caffe::Net&lt; float &gt; &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06956.html',1,'std']]],
  ['unique_5fptr_3c_20gaze_3a_3agazetracker_20_3e',['unique_ptr&lt; gaze::GazeTracker &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06956.html',1,'std']]],
  ['uniquerandom',['UniqueRandom',['http://docs.opencv.org/3.4.0/d9/de3/classcvflann_1_1UniqueRandom.html',1,'cvflann']]],
  ['uniqueresultset',['UniqueResultSet',['http://docs.opencv.org/3.4.0/d4/dca/classcvflann_1_1UniqueResultSet.html',1,'cvflann']]],
  ['unordered_5fmap',['unordered_map',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06988.html',1,'std::unordered_map&lt; _Key, _Tp, _Hash, _Pred, _Alloc &gt;'],['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08048.html',1,'std::__profile::unordered_map&lt; _Key, _Tp, _Hash, _Pred, _Alloc &gt;'],['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07808.html',1,'std::__debug::unordered_map&lt; _Key, _Tp, _Hash, _Pred, _Alloc &gt;']]],
  ['unordered_5fmap_3c_20_5fkey_2c_20_5ftp_2c_20_5fhash_2c_20_5fpred_20_3e',['unordered_map&lt; _Key, _Tp, _Hash, _Pred &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06988.html',1,'']]],
  ['unordered_5fmultimap',['unordered_multimap',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07812.html',1,'std::__debug::unordered_multimap&lt; _Key, _Tp, _Hash, _Pred, _Alloc &gt;'],['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06984.html',1,'std::unordered_multimap&lt; _Key, _Tp, _Hash, _Pred, _Alloc &gt;'],['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08052.html',1,'std::__profile::unordered_multimap&lt; _Key, _Tp, _Hash, _Pred, _Alloc &gt;']]],
  ['unordered_5fmultiset',['unordered_multiset',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07820.html',1,'std::__debug::unordered_multiset&lt; _Value, _Hash, _Pred, _Alloc &gt;'],['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08060.html',1,'std::__profile::unordered_multiset&lt; _Value, _Hash, _Pred, _Alloc &gt;'],['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06992.html',1,'std::unordered_multiset&lt; _Value, _Hash, _Pred, _Alloc &gt;']]],
  ['unordered_5fset',['unordered_set',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06996.html',1,'std::unordered_set&lt; _Value, _Hash, _Pred, _Alloc &gt;'],['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07816.html',1,'std::__debug::unordered_set&lt; _Value, _Hash, _Pred, _Alloc &gt;'],['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08056.html',1,'std::__profile::unordered_set&lt; _Key, _Hash, _Pred, _Alloc &gt;']]],
  ['unscentedkalmanfilter',['UnscentedKalmanFilter',['http://docs.opencv.org/3.4.0/de/d72/classcv_1_1tracking_1_1UnscentedKalmanFilter.html',1,'cv::tracking']]],
  ['unscentedkalmanfilterparams',['UnscentedKalmanFilterParams',['http://docs.opencv.org/3.4.0/da/d73/classcv_1_1tracking_1_1UnscentedKalmanFilterParams.html',1,'cv::tracking']]],
  ['untypedmatrix',['UntypedMatrix',['http://docs.opencv.org/3.4.0/d4/d5a/classcvflann_1_1UntypedMatrix.html',1,'cvflann']]],
  ['uses_5fallocator',['uses_allocator',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05120.html',1,'std']]],
  ['uses_5fallocator_3c_20tuple_3c_20_5ftypes_2e_2e_2e_20_3e_2c_20_5falloc_20_3e',['uses_allocator&lt; tuple&lt; _Types... &gt;, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a03144.html',1,'std']]]
];
