var searchData=
[
  ['narymatiterator',['NAryMatIterator',['http://docs.opencv.org/3.4.0/d5/dd2/classcv_1_1NAryMatIterator.html',1,'cv']]],
  ['ncvbroxopticalflowdescriptor',['NCVBroxOpticalFlowDescriptor',['http://docs.opencv.org/3.4.0/db/d7a/structNCVBroxOpticalFlowDescriptor.html',1,'']]],
  ['ncvmatrix',['NCVMatrix',['http://docs.opencv.org/3.4.0/de/d26/classNCVMatrix.html',1,'']]],
  ['ncvmatrixalloc',['NCVMatrixAlloc',['http://docs.opencv.org/3.4.0/d7/d3a/classNCVMatrixAlloc.html',1,'']]],
  ['ncvmatrixreuse',['NCVMatrixReuse',['http://docs.opencv.org/3.4.0/df/d82/classNCVMatrixReuse.html',1,'']]],
  ['ncvmemnativeallocator',['NCVMemNativeAllocator',['http://docs.opencv.org/3.4.0/dc/d18/classNCVMemNativeAllocator.html',1,'']]],
  ['ncvmemptr',['NCVMemPtr',['http://docs.opencv.org/3.4.0/d6/d86/structNCVMemPtr.html',1,'']]],
  ['ncvmemsegment',['NCVMemSegment',['http://docs.opencv.org/3.4.0/d2/d12/structNCVMemSegment.html',1,'']]],
  ['ncvmemstackallocator',['NCVMemStackAllocator',['http://docs.opencv.org/3.4.0/db/d74/classNCVMemStackAllocator.html',1,'']]],
  ['ncvpoint2d32s',['NcvPoint2D32s',['http://docs.opencv.org/3.4.0/d5/d93/structNcvPoint2D32s.html',1,'']]],
  ['ncvpoint2d32u',['NcvPoint2D32u',['http://docs.opencv.org/3.4.0/dc/d16/structNcvPoint2D32u.html',1,'']]],
  ['ncvrect32s',['NcvRect32s',['http://docs.opencv.org/3.4.0/d3/dfe/structNcvRect32s.html',1,'']]],
  ['ncvrect32u',['NcvRect32u',['http://docs.opencv.org/3.4.0/d0/d62/structNcvRect32u.html',1,'']]],
  ['ncvrect8u',['NcvRect8u',['http://docs.opencv.org/3.4.0/da/d3f/structNcvRect8u.html',1,'']]],
  ['ncvsize32s',['NcvSize32s',['http://docs.opencv.org/3.4.0/d7/dda/structNcvSize32s.html',1,'']]],
  ['ncvsize32u',['NcvSize32u',['http://docs.opencv.org/3.4.0/d8/dde/structNcvSize32u.html',1,'']]],
  ['ncvvector',['NCVVector',['http://docs.opencv.org/3.4.0/dc/d73/classNCVVector.html',1,'']]],
  ['ncvvectoralloc',['NCVVectorAlloc',['http://docs.opencv.org/3.4.0/d8/da0/classNCVVectorAlloc.html',1,'']]],
  ['ncvvectorreuse',['NCVVectorReuse',['http://docs.opencv.org/3.4.0/da/d61/classNCVVectorReuse.html',1,'']]],
  ['nearestinterptr',['NearestInterPtr',['http://docs.opencv.org/3.4.0/d0/df5/structcv_1_1cudev_1_1NearestInterPtr.html',1,'cv::cudev']]],
  ['nearestinterptrsz',['NearestInterPtrSz',['http://docs.opencv.org/3.4.0/df/dd0/structcv_1_1cudev_1_1NearestInterPtrSz.html',1,'cv::cudev']]],
  ['negate',['negate',['http://docs.opencv.org/3.4.0/d9/d77/structcv_1_1cudev_1_1negate.html',1,'cv::cudev::negate&lt; class &gt;'],['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06420.html',1,'std::negate&lt; class &gt;']]],
  ['negate_3c_20void_20_3e',['negate&lt; void &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06444.html',1,'std']]],
  ['negative_5fbinomial_5fdistribution',['negative_binomial_distribution',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05520.html',1,'std']]],
  ['nested_5fexception',['nested_exception',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05128.html',1,'std']]],
  ['net',['Net',['http://docs.opencv.org/3.4.0/db/d30/classcv_1_1dnn_1_1Net.html',1,'cv::dnn']]],
  ['never_5fadjustor',['never_adjustor',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09640.html',1,'__gnu_cxx::random_condition::never_adjustor'],['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09616.html',1,'__gnu_cxx::limit_condition::never_adjustor']]],
  ['new_5fallocator',['new_allocator',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09432.html',1,'__gnu_cxx']]],
  ['nnindex',['NNIndex',['http://docs.opencv.org/3.4.0/d9/d10/classcvflann_1_1NNIndex.html',1,'cvflann']]],
  ['nnindex_3c_20cv_3a_3al1_3c_20elementtype_20_3e_20_3e',['NNIndex&lt; cv::L1&lt; ElementType &gt; &gt;',['http://docs.opencv.org/3.4.0/d9/d10/classcvflann_1_1NNIndex.html',1,'']]],
  ['nnindex_3c_20cv_3a_3al2_3c_20elementtype_20_3e_20_3e',['NNIndex&lt; cv::L2&lt; ElementType &gt; &gt;',['http://docs.opencv.org/3.4.0/d9/d10/classcvflann_1_1NNIndex.html',1,'']]],
  ['no',['No',['http://docs.opencv.org/3.4.0/db/d13/structcv_1_1cudev_1_1IsBinaryFunction_1_1No.html',1,'cv::cudev::IsBinaryFunction&lt; class &gt;::No'],['http://docs.opencv.org/3.4.0/dc/d5a/structcv_1_1cudev_1_1IsUnaryFunction_1_1No.html',1,'cv::cudev::IsUnaryFunction&lt; class &gt;::No']]],
  ['no_5fthrow_5fcopies',['no_throw_copies',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10436.html',1,'__gnu_pbds::detail']]],
  ['no_5fthrow_5fcopies_3c_20key_2c_20null_5ftype_20_3e',['no_throw_copies&lt; Key, null_type &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10440.html',1,'__gnu_pbds::detail']]],
  ['nobundleadjuster',['NoBundleAdjuster',['http://docs.opencv.org/3.4.0/db/dd4/classcv_1_1detail_1_1NoBundleAdjuster.html',1,'cv::detail']]],
  ['node',['Node',['http://docs.opencv.org/3.4.0/d2/d7d/structcv_1_1optflow_1_1GPCTree_1_1Node.html',1,'cv::optflow::GPCTree::Node'],['http://docs.opencv.org/3.4.0/d9/de0/structcv_1_1SparseMat_1_1Node.html',1,'cv::SparseMat::Node'],['http://docs.opencv.org/3.4.0/d4/d7d/classcv_1_1ml_1_1DTrees_1_1Node.html',1,'cv::ml::DTrees::Node'],['http://docs.opencv.org/3.4.0/d3/de3/classcv_1_1Node.html',1,'cv::Node&lt; OBJECT &gt;']]],
  ['nodedata',['NodeData',['http://docs.opencv.org/3.4.0/d7/dc2/classcv_1_1instr_1_1NodeData.html',1,'cv::instr']]],
  ['nodedatatls',['NodeDataTls',['http://docs.opencv.org/3.4.0/da/df1/structcv_1_1instr_1_1NodeDataTls.html',1,'cv::instr']]],
  ['noexposurecompensator',['NoExposureCompensator',['http://docs.opencv.org/3.4.0/d2/dc1/classcv_1_1detail_1_1NoExposureCompensator.html',1,'cv::detail']]],
  ['normal_5fdistribution',['normal_distribution',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05440.html',1,'std']]],
  ['normal_5fdistribution_3c_20double_20_3e',['normal_distribution&lt; double &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05440.html',1,'']]],
  ['normal_5fdistribution_3c_20result_5ftype_20_3e',['normal_distribution&lt; result_type &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05440.html',1,'']]],
  ['normalbayesclassifier',['NormalBayesClassifier',['http://docs.opencv.org/3.4.0/d4/d8e/classcv_1_1ml_1_1NormalBayesClassifier.html',1,'cv::ml']]],
  ['normalizebboxlayer',['NormalizeBBoxLayer',['http://docs.opencv.org/3.4.0/dc/df8/classcv_1_1dnn_1_1NormalizeBBoxLayer.html',1,'cv::dnn']]],
  ['normhamming',['NormHamming',['http://docs.opencv.org/3.4.0/d5/d7b/structcv_1_1cudev_1_1NormHamming.html',1,'cv::cudev']]],
  ['normhistogramcostextractor',['NormHistogramCostExtractor',['http://docs.opencv.org/3.4.0/df/d65/classcv_1_1NormHistogramCostExtractor.html',1,'cv']]],
  ['norml1',['NormL1',['http://docs.opencv.org/3.4.0/d7/df8/structcv_1_1cudev_1_1NormL1.html',1,'cv::cudev']]],
  ['norml1_3c_20float_20_3e',['NormL1&lt; float &gt;',['http://docs.opencv.org/3.4.0/d5/d1e/structcv_1_1cudev_1_1NormL1_3_01float_01_4.html',1,'cv::cudev']]],
  ['norml2',['NormL2',['http://docs.opencv.org/3.4.0/dc/da6/structcv_1_1cudev_1_1NormL2.html',1,'cv::cudev']]],
  ['noseamfinder',['NoSeamFinder',['http://docs.opencv.org/3.4.0/d3/da9/classcv_1_1detail_1_1NoSeamFinder.html',1,'cv::detail']]],
  ['not_5fequal_5fto',['not_equal_to',['http://docs.opencv.org/3.4.0/df/d9f/structcv_1_1cudev_1_1not__equal__to.html',1,'cv::cudev::not_equal_to&lt; T &gt;'],['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06452.html',1,'std::not_equal_to&lt; class &gt;']]],
  ['not_5fequal_5fto_3c_20void_20_3e',['not_equal_to&lt; void &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06476.html',1,'std']]],
  ['nppstinterpolationstate',['NppStInterpolationState',['http://docs.opencv.org/3.4.0/da/da9/structNppStInterpolationState.html',1,'']]],
  ['nsobject',['NSObject',['http://docs.opencv.org/3.4.0/d4/d19/classNSObject.html',1,'']]],
  ['nsobject_2dp_2dp',['NSObject-p-p',['http://docs.opencv.org/3.4.0/d9/d15/classNSObject-p.html',1,'']]],
  ['nsobjectnsobject_2dp_2dp',['NSObjectNSObject-p-p',['http://docs.opencv.org/3.4.0/d5/d25/classNSObjectNSObject-p.html',1,'']]],
  ['null_5fnode_5fupdate',['null_node_update',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10216.html',1,'__gnu_pbds']]],
  ['null_5ftype',['null_type',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10212.html',1,'__gnu_pbds']]],
  ['nulldeblurer',['NullDeblurer',['http://docs.opencv.org/3.4.0/dc/d86/classcv_1_1videostab_1_1NullDeblurer.html',1,'cv::videostab']]],
  ['nullframesource',['NullFrameSource',['http://docs.opencv.org/3.4.0/dd/d5b/classcv_1_1videostab_1_1NullFrameSource.html',1,'cv::videostab']]],
  ['nullinpainter',['NullInpainter',['http://docs.opencv.org/3.4.0/d4/d1d/classcv_1_1videostab_1_1NullInpainter.html',1,'cv::videostab']]],
  ['nulllog',['NullLog',['http://docs.opencv.org/3.4.0/d6/d78/classcv_1_1videostab_1_1NullLog.html',1,'cv::videostab']]],
  ['nullopt_5ft',['nullopt_t',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08996.html',1,'std::experimental::fundamentals_v1']]],
  ['nulloutlierrejector',['NullOutlierRejector',['http://docs.opencv.org/3.4.0/d3/de9/classcv_1_1videostab_1_1NullOutlierRejector.html',1,'cv::videostab']]],
  ['nulltype',['NullType',['http://docs.opencv.org/3.4.0/d5/d71/structcv_1_1cudev_1_1NullType.html',1,'cv::cudev']]],
  ['nullwobblesuppressor',['NullWobbleSuppressor',['http://docs.opencv.org/3.4.0/d0/da4/classcv_1_1videostab_1_1NullWobbleSuppressor.html',1,'cv::videostab']]],
  ['num_5fget',['num_get',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05032.html',1,'std']]],
  ['num_5fput',['num_put',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05036.html',1,'std']]],
  ['numeric_5flimits',['numeric_limits',['http://docs.opencv.org/3.4.0/db/dc8/structcv_1_1cudev_1_1numeric__limits.html',1,'cv::cudev::numeric_limits&lt; class &gt;'],['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02636.html',1,'std::numeric_limits&lt; class &gt;']]],
  ['numeric_5flimits_3c_20bool_20_3e',['numeric_limits&lt; bool &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02652.html',1,'std::numeric_limits&lt; bool &gt;'],['http://docs.opencv.org/3.4.0/da/d81/structcv_1_1cudev_1_1numeric__limits_3_01bool_01_4.html',1,'cv::cudev::numeric_limits&lt; bool &gt;']]],
  ['numeric_5flimits_3c_20char_20_3e',['numeric_limits&lt; char &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02656.html',1,'std']]],
  ['numeric_5flimits_3c_20char16_5ft_20_3e',['numeric_limits&lt; char16_t &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02672.html',1,'std']]],
  ['numeric_5flimits_3c_20char32_5ft_20_3e',['numeric_limits&lt; char32_t &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02676.html',1,'std']]],
  ['numeric_5flimits_3c_20double_20_3e',['numeric_limits&lt; double &gt;',['http://docs.opencv.org/3.4.0/d2/d80/structcv_1_1cudev_1_1numeric__limits_3_01double_01_4.html',1,'cv::cudev::numeric_limits&lt; double &gt;'],['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02716.html',1,'std::numeric_limits&lt; double &gt;']]],
  ['numeric_5flimits_3c_20float_20_3e',['numeric_limits&lt; float &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02712.html',1,'std::numeric_limits&lt; float &gt;'],['http://docs.opencv.org/3.4.0/db/d88/structcv_1_1cudev_1_1numeric__limits_3_01float_01_4.html',1,'cv::cudev::numeric_limits&lt; float &gt;']]],
  ['numeric_5flimits_3c_20int_20_3e',['numeric_limits&lt; int &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02688.html',1,'std']]],
  ['numeric_5flimits_3c_20long_20_3e',['numeric_limits&lt; long &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02696.html',1,'std']]],
  ['numeric_5flimits_3c_20long_20double_20_3e',['numeric_limits&lt; long double &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02720.html',1,'std']]],
  ['numeric_5flimits_3c_20long_20long_20_3e',['numeric_limits&lt; long long &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02704.html',1,'std']]],
  ['numeric_5flimits_3c_20schar_20_3e',['numeric_limits&lt; schar &gt;',['http://docs.opencv.org/3.4.0/da/d4e/structcv_1_1cudev_1_1numeric__limits_3_01schar_01_4.html',1,'cv::cudev']]],
  ['numeric_5flimits_3c_20short_20_3e',['numeric_limits&lt; short &gt;',['http://docs.opencv.org/3.4.0/d1/d8b/structcv_1_1cudev_1_1numeric__limits_3_01short_01_4.html',1,'cv::cudev::numeric_limits&lt; short &gt;'],['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02680.html',1,'std::numeric_limits&lt; short &gt;']]],
  ['numeric_5flimits_3c_20signed_20char_20_3e',['numeric_limits&lt; signed char &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02660.html',1,'std']]],
  ['numeric_5flimits_3c_20uchar_20_3e',['numeric_limits&lt; uchar &gt;',['http://docs.opencv.org/3.4.0/d3/dc7/structcv_1_1cudev_1_1numeric__limits_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['numeric_5flimits_3c_20uint_20_3e',['numeric_limits&lt; uint &gt;',['http://docs.opencv.org/3.4.0/dd/d89/structcv_1_1cudev_1_1numeric__limits_3_01uint_01_4.html',1,'cv::cudev']]],
  ['numeric_5flimits_3c_20unsigned_20char_20_3e',['numeric_limits&lt; unsigned char &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02664.html',1,'std']]],
  ['numeric_5flimits_3c_20unsigned_20int_20_3e',['numeric_limits&lt; unsigned int &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02692.html',1,'std']]],
  ['numeric_5flimits_3c_20unsigned_20long_20_3e',['numeric_limits&lt; unsigned long &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02700.html',1,'std']]],
  ['numeric_5flimits_3c_20unsigned_20long_20long_20_3e',['numeric_limits&lt; unsigned long long &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02708.html',1,'std']]],
  ['numeric_5flimits_3c_20unsigned_20short_20_3e',['numeric_limits&lt; unsigned short &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02684.html',1,'std']]],
  ['numeric_5flimits_3c_20ushort_20_3e',['numeric_limits&lt; ushort &gt;',['http://docs.opencv.org/3.4.0/df/d47/structcv_1_1cudev_1_1numeric__limits_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['numeric_5flimits_3c_20wchar_5ft_20_3e',['numeric_limits&lt; wchar_t &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02668.html',1,'std']]],
  ['numpunct',['numpunct',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05024.html',1,'std']]],
  ['numpunct_5fbyname',['numpunct_byname',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05028.html',1,'std']]]
];
