var searchData=
[
  ['back_5finsert_5fiterator',['back_insert_iterator',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06620.html',1,'std']]],
  ['backendnode',['BackendNode',['http://docs.opencv.org/3.4.0/d2/dbb/classcv_1_1dnn_1_1BackendNode.html',1,'cv::dnn']]],
  ['backendwrapper',['BackendWrapper',['http://docs.opencv.org/3.4.0/df/d7b/classcv_1_1dnn_1_1BackendWrapper.html',1,'cv::dnn']]],
  ['backgroundsubtractor',['BackgroundSubtractor',['http://docs.opencv.org/3.4.0/d7/df6/classcv_1_1BackgroundSubtractor.html',1,'cv']]],
  ['backgroundsubtractorcnt',['BackgroundSubtractorCNT',['http://docs.opencv.org/3.4.0/de/dca/classcv_1_1bgsegm_1_1BackgroundSubtractorCNT.html',1,'cv::bgsegm']]],
  ['backgroundsubtractorfgd',['BackgroundSubtractorFGD',['http://docs.opencv.org/3.4.0/d3/dd2/classcv_1_1cuda_1_1BackgroundSubtractorFGD.html',1,'cv::cuda']]],
  ['backgroundsubtractorgmg',['BackgroundSubtractorGMG',['http://docs.opencv.org/3.4.0/d1/d5c/classcv_1_1bgsegm_1_1BackgroundSubtractorGMG.html',1,'cv::bgsegm']]],
  ['backgroundsubtractorgmg',['BackgroundSubtractorGMG',['http://docs.opencv.org/3.4.0/d5/df2/classcv_1_1cuda_1_1BackgroundSubtractorGMG.html',1,'cv::cuda']]],
  ['backgroundsubtractorgsoc',['BackgroundSubtractorGSOC',['http://docs.opencv.org/3.4.0/d4/dd5/classcv_1_1bgsegm_1_1BackgroundSubtractorGSOC.html',1,'cv::bgsegm']]],
  ['backgroundsubtractorknn',['BackgroundSubtractorKNN',['http://docs.opencv.org/3.4.0/db/d88/classcv_1_1BackgroundSubtractorKNN.html',1,'cv']]],
  ['backgroundsubtractorlsbp',['BackgroundSubtractorLSBP',['http://docs.opencv.org/3.4.0/de/d4c/classcv_1_1bgsegm_1_1BackgroundSubtractorLSBP.html',1,'cv::bgsegm']]],
  ['backgroundsubtractorlsbpdesc',['BackgroundSubtractorLSBPDesc',['http://docs.opencv.org/3.4.0/d1/de5/classcv_1_1bgsegm_1_1BackgroundSubtractorLSBPDesc.html',1,'cv::bgsegm']]],
  ['backgroundsubtractormog',['BackgroundSubtractorMOG',['http://docs.opencv.org/3.4.0/d1/dfe/classcv_1_1cuda_1_1BackgroundSubtractorMOG.html',1,'cv::cuda']]],
  ['backgroundsubtractormog',['BackgroundSubtractorMOG',['http://docs.opencv.org/3.4.0/d6/da7/classcv_1_1bgsegm_1_1BackgroundSubtractorMOG.html',1,'cv::bgsegm']]],
  ['backgroundsubtractormog2',['BackgroundSubtractorMOG2',['http://docs.opencv.org/3.4.0/d7/d7b/classcv_1_1BackgroundSubtractorMOG2.html',1,'cv']]],
  ['backgroundsubtractormog2',['BackgroundSubtractorMOG2',['http://docs.opencv.org/3.4.0/df/d23/classcv_1_1cuda_1_1BackgroundSubtractorMOG2.html',1,'cv::cuda']]],
  ['bad_5falloc',['bad_alloc',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01660.html',1,'std']]],
  ['bad_5fany_5fcast',['bad_any_cast',['http://docs.opencv.org/3.4.0/da/d73/structcvflann_1_1anyimpl_1_1bad__any__cast.html',1,'cvflann::anyimpl']]],
  ['bad_5fany_5fcast',['bad_any_cast',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08888.html',1,'std::experimental::fundamentals_v1']]],
  ['bad_5fcast',['bad_cast',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01676.html',1,'std']]],
  ['bad_5fexception',['bad_exception',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01652.html',1,'std']]],
  ['bad_5ffunction_5fcall',['bad_function_call',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06168.html',1,'std']]],
  ['bad_5foptional_5faccess',['bad_optional_access',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09000.html',1,'std::experimental::fundamentals_v1']]],
  ['bad_5ftypeid',['bad_typeid',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01680.html',1,'std']]],
  ['bad_5fweak_5fptr',['bad_weak_ptr',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05976.html',1,'std']]],
  ['balanced_5fquicksort_5ftag',['balanced_quicksort_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08684.html',1,'__gnu_parallel']]],
  ['balanced_5ftag',['balanced_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08640.html',1,'__gnu_parallel']]],
  ['base_5fany_5fpolicy',['base_any_policy',['http://docs.opencv.org/3.4.0/df/dca/structcvflann_1_1anyimpl_1_1base__any__policy.html',1,'cvflann::anyimpl']]],
  ['basecascadeclassifier',['BaseCascadeClassifier',['http://docs.opencv.org/3.4.0/da/dd5/classcv_1_1BaseCascadeClassifier.html',1,'cv']]],
  ['baseclassifier',['BaseClassifier',['http://docs.opencv.org/3.4.0/d7/d03/classcv_1_1BaseClassifier.html',1,'cv']]],
  ['baseconverter',['BaseConverter',['http://docs.opencv.org/3.4.0/db/d08/classcv_1_1dnn2_1_1BaseConverter.html',1,'cv::dnn2']]],
  ['baseconvolutionlayer',['BaseConvolutionLayer',['http://docs.opencv.org/3.4.0/d5/d1f/classcv_1_1dnn_1_1BaseConvolutionLayer.html',1,'cv::dnn']]],
  ['baseocr',['BaseOCR',['http://docs.opencv.org/3.4.0/de/d3a/classcv_1_1text_1_1BaseOCR.html',1,'cv::text']]],
  ['bases',['bases',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08740.html',1,'std::tr2']]],
  ['basesfm',['BaseSFM',['http://docs.opencv.org/3.4.0/d7/db1/classcv_1_1sfm_1_1BaseSFM.html',1,'cv::sfm']]],
  ['basic_5fbranch',['basic_branch',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10032.html',1,'__gnu_pbds']]],
  ['basic_5fbranch_3c_20key_2c_20mapped_2c_20tag_2c_20detail_3a_3atree_5ftraits_3c_20key_2c_20mapped_2c_20cmp_5ffn_2c_20node_5fupdate_2c_20tag_2c_20_5falloc_20_3e_3a_3anode_5fupdate_2c_20_5f_5fgnu_5fcxx_3a_3atypelist_3a_3acreate2_3c_20cmp_5ffn_2c_20detail_3a_3atree_5ftraits_3c_20key_2c_20mapped_2c_20cmp_5ffn_2c_20node_5fupdate_2c_20tag_2c_20_5falloc_20_3e_20_3e_3a_3atype_2c_20_5falloc_20_3e',['basic_branch&lt; Key, Mapped, Tag, detail::tree_traits&lt; Key, Mapped, Cmp_Fn, Node_Update, Tag, _Alloc &gt;::node_update, __gnu_cxx::typelist::create2&lt; Cmp_Fn, detail::tree_traits&lt; Key, Mapped, Cmp_Fn, Node_Update, Tag, _Alloc &gt; &gt;::type, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10032.html',1,'']]],
  ['basic_5fbranch_3c_20key_2c_20mapped_2c_20tag_2c_20detail_3a_3atrie_5ftraits_3c_20key_2c_20mapped_2c_20_5fatraits_2c_20node_5fupdate_2c_20tag_2c_20_5falloc_20_3e_3a_3anode_5fupdate_2c_20_5f_5fgnu_5fcxx_3a_3atypelist_3a_3acreate2_3c_20_5fatraits_2c_20detail_3a_3atrie_5ftraits_3c_20key_2c_20mapped_2c_20_5fatraits_2c_20node_5fupdate_2c_20tag_2c_20_5falloc_20_3e_20_3e_3a_3atype_2c_20_5falloc_20_3e',['basic_branch&lt; Key, Mapped, Tag, detail::trie_traits&lt; Key, Mapped, _ATraits, Node_Update, Tag, _Alloc &gt;::node_update, __gnu_cxx::typelist::create2&lt; _ATraits, detail::trie_traits&lt; Key, Mapped, _ATraits, Node_Update, Tag, _Alloc &gt; &gt;::type, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10032.html',1,'']]],
  ['basic_5fbranch_5ftag',['basic_branch_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10156.html',1,'__gnu_pbds']]],
  ['basic_5ffilebuf',['basic_filebuf',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02072.html',1,'std']]],
  ['basic_5ffilebuf_3c_20_5fchart_2c_20encoding_5fchar_5ftraits_3c_20_5fchart_20_3e_20_3e',['basic_filebuf&lt; _CharT, encoding_char_traits&lt; _CharT &gt; &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02072.html',1,'']]],
  ['basic_5ffilebuf_3c_20char_5ftype_2c_20traits_5ftype_20_3e',['basic_filebuf&lt; char_type, traits_type &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02072.html',1,'']]],
  ['basic_5ffstream',['basic_fstream',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02084.html',1,'std']]],
  ['basic_5fhash_5ftable',['basic_hash_table',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10020.html',1,'__gnu_pbds']]],
  ['basic_5fhash_5ftable_3c_20key_2c_20mapped_2c_20hash_5ffn_2c_20eq_5ffn_2c_20resize_5fpolicy_2c_20store_5fhash_2c_20cc_5fhash_5ftag_2c_20_5f_5fgnu_5fcxx_3a_3atypelist_3a_3acreate1_3c_20comb_5fhash_5ffn_20_3e_3a_3atype_2c_20_5falloc_20_3e',['basic_hash_table&lt; Key, Mapped, Hash_Fn, Eq_Fn, Resize_Policy, Store_Hash, cc_hash_tag, __gnu_cxx::typelist::create1&lt; Comb_Hash_Fn &gt;::type, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10020.html',1,'']]],
  ['basic_5fhash_5ftable_3c_20key_2c_20mapped_2c_20hash_5ffn_2c_20eq_5ffn_2c_20resize_5fpolicy_2c_20store_5fhash_2c_20gp_5fhash_5ftag_2c_20_5f_5fgnu_5fcxx_3a_3atypelist_3a_3acreate2_3c_20comb_5fprobe_5ffn_2c_20probe_5ffn_20_3e_3a_3atype_2c_20_5falloc_20_3e',['basic_hash_table&lt; Key, Mapped, Hash_Fn, Eq_Fn, Resize_Policy, Store_Hash, gp_hash_tag, __gnu_cxx::typelist::create2&lt; Comb_Probe_Fn, Probe_Fn &gt;::type, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10020.html',1,'']]],
  ['basic_5fhash_5ftag',['basic_hash_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10144.html',1,'__gnu_pbds']]],
  ['basic_5fifstream',['basic_ifstream',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02076.html',1,'std']]],
  ['basic_5finvalidation_5fguarantee',['basic_invalidation_guarantee',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10116.html',1,'__gnu_pbds']]],
  ['basic_5fios',['basic_ios',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02564.html',1,'std']]],
  ['basic_5fios_3c_20char_2c_20_5ftraits_20_3e',['basic_ios&lt; char, _Traits &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02564.html',1,'']]],
  ['basic_5fiostream',['basic_iostream',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02580.html',1,'std']]],
  ['basic_5fiostream_3c_20char_20_3e',['basic_iostream&lt; char &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02580.html',1,'']]],
  ['basic_5fistream',['basic_istream',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02572.html',1,'std']]],
  ['basic_5fistream_3c_20char_20_3e',['basic_istream&lt; char &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02572.html',1,'']]],
  ['basic_5fistream_3c_20char_2c_20_5ftraits_20_3e',['basic_istream&lt; char, _Traits &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02572.html',1,'']]],
  ['basic_5fistringstream',['basic_istringstream',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02588.html',1,'std']]],
  ['basic_5fofstream',['basic_ofstream',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02080.html',1,'std']]],
  ['basic_5fostream',['basic_ostream',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02576.html',1,'std']]],
  ['basic_5fostream_3c_20char_20_3e',['basic_ostream&lt; char &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02576.html',1,'']]],
  ['basic_5fostream_3c_20char_2c_20_5ftraits_20_3e',['basic_ostream&lt; char, _Traits &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02576.html',1,'']]],
  ['basic_5fostringstream',['basic_ostringstream',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02592.html',1,'std']]],
  ['basic_5fregex',['basic_regex',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05780.html',1,'std']]],
  ['basic_5fstreambuf',['basic_streambuf',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02568.html',1,'std']]],
  ['basic_5fstreambuf_3c_20_5felem_2c_20_5ftr_20_3e',['basic_streambuf&lt; _Elem, _Tr &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02568.html',1,'']]],
  ['basic_5fstreambuf_3c_20char_2c_20_5ftraits_20_3e',['basic_streambuf&lt; char, _Traits &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02568.html',1,'']]],
  ['basic_5fstreambuf_3c_20char_2c_20char_5ftraits_3c_20char_20_3e_20_3e',['basic_streambuf&lt; char, char_traits&lt; char &gt; &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02568.html',1,'']]],
  ['basic_5fstring',['basic_string',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a03900.html',1,'std']]],
  ['basic_5fstring',['basic_string',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07800.html',1,'__gnu_debug']]],
  ['basic_5fstring_3c_20_5fchart_20_3e',['basic_string&lt; _CharT &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a03900.html',1,'']]],
  ['basic_5fstring_3c_20_5fchart_2c_20_5ftraits_2c_20_5fallocator_20_3e',['basic_string&lt; _CharT, _Traits, _Allocator &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a03900.html',1,'']]],
  ['basic_5fstring_3c_20_5felem_2c_20char_5ftraits_3c_20_5felem_20_3e_2c_20_5fwide_5falloc_20_3e',['basic_string&lt; _Elem, char_traits&lt; _Elem &gt;, _Wide_alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a03900.html',1,'']]],
  ['basic_5fstring_3c_20char_20_3e',['basic_string&lt; char &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a03900.html',1,'']]],
  ['basic_5fstring_3c_20char_2c_20char_5ftraits_3c_20char_20_3e_2c_20_5fbyte_5falloc_20_3e',['basic_string&lt; char, char_traits&lt; char &gt;, _Byte_alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a03900.html',1,'']]],
  ['basic_5fstring_3c_20char_5ftype_2c_20_5ftraits_2c_20_5falloc_20_3e',['basic_string&lt; char_type, _Traits, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a03900.html',1,'']]],
  ['basic_5fstring_3c_20value_5ftype_20_3e',['basic_string&lt; value_type &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a03900.html',1,'']]],
  ['basic_5fstring_5fview',['basic_string_view',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09092.html',1,'std::experimental::fundamentals_v1']]],
  ['basic_5fstringbuf',['basic_stringbuf',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02584.html',1,'std']]],
  ['basic_5fstringstream',['basic_stringstream',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02596.html',1,'std']]],
  ['basicfacerecognizer',['BasicFaceRecognizer',['http://docs.opencv.org/3.4.0/dc/dd7/classcv_1_1face_1_1BasicFaceRecognizer.html',1,'cv::face']]],
  ['batchnormlayer',['BatchNormLayer',['http://docs.opencv.org/3.4.0/d4/dd2/classcv_1_1dnn_1_1BatchNormLayer.html',1,'cv::dnn']]],
  ['bbox',['BBox',['http://docs.opencv.org/3.4.0/db/d18/classcv_1_1face_1_1FacemarkLBF_1_1BBox.html',1,'cv::face::FacemarkLBF']]],
  ['bernoulli_5fdistribution',['bernoulli_distribution',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05496.html',1,'std']]],
  ['bestof2nearestmatcher',['BestOf2NearestMatcher',['http://docs.opencv.org/3.4.0/d4/d26/classcv_1_1detail_1_1BestOf2NearestMatcher.html',1,'cv::detail']]],
  ['bestof2nearestrangematcher',['BestOf2NearestRangeMatcher',['http://docs.opencv.org/3.4.0/d8/d72/classcv_1_1detail_1_1BestOf2NearestRangeMatcher.html',1,'cv::detail']]],
  ['bfmatcher',['BFMatcher',['http://docs.opencv.org/3.4.0/d3/da1/classcv_1_1BFMatcher.html',1,'cv']]],
  ['bgr_5fto_5fbgra_5ffunc',['BGR_to_BGRA_func',['http://docs.opencv.org/3.4.0/d2/def/structcv_1_1cudev_1_1BGR__to__BGRA__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5fgray_5ffunc',['BGR_to_GRAY_func',['http://docs.opencv.org/3.4.0/d1/d6e/structcv_1_1cudev_1_1BGR__to__GRAY__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5fhls4_5ffull_5ffunc',['BGR_to_HLS4_FULL_func',['http://docs.opencv.org/3.4.0/d5/d9d/structcv_1_1cudev_1_1BGR__to__HLS4__FULL__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5fhls4_5ffull_5ffunc_3c_20float_20_3e',['BGR_to_HLS4_FULL_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/dd/d95/structcv_1_1cudev_1_1BGR__to__HLS4__FULL__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['bgr_5fto_5fhls4_5ffunc',['BGR_to_HLS4_func',['http://docs.opencv.org/3.4.0/d1/d99/structcv_1_1cudev_1_1BGR__to__HLS4__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5fhls4_5ffunc_3c_20float_20_3e',['BGR_to_HLS4_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/d5/dfd/structcv_1_1cudev_1_1BGR__to__HLS4__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['bgr_5fto_5fhls_5ffull_5ffunc',['BGR_to_HLS_FULL_func',['http://docs.opencv.org/3.4.0/de/d50/structcv_1_1cudev_1_1BGR__to__HLS__FULL__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5fhls_5ffull_5ffunc_3c_20float_20_3e',['BGR_to_HLS_FULL_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/d7/db4/structcv_1_1cudev_1_1BGR__to__HLS__FULL__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['bgr_5fto_5fhls_5ffunc',['BGR_to_HLS_func',['http://docs.opencv.org/3.4.0/d7/d28/structcv_1_1cudev_1_1BGR__to__HLS__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5fhls_5ffunc_3c_20float_20_3e',['BGR_to_HLS_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/db/d58/structcv_1_1cudev_1_1BGR__to__HLS__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['bgr_5fto_5fhsv4_5ffull_5ffunc',['BGR_to_HSV4_FULL_func',['http://docs.opencv.org/3.4.0/de/d04/structcv_1_1cudev_1_1BGR__to__HSV4__FULL__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5fhsv4_5ffull_5ffunc_3c_20float_20_3e',['BGR_to_HSV4_FULL_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/d1/d5e/structcv_1_1cudev_1_1BGR__to__HSV4__FULL__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['bgr_5fto_5fhsv4_5ffunc',['BGR_to_HSV4_func',['http://docs.opencv.org/3.4.0/d9/db2/structcv_1_1cudev_1_1BGR__to__HSV4__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5fhsv4_5ffunc_3c_20float_20_3e',['BGR_to_HSV4_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/d7/dc2/structcv_1_1cudev_1_1BGR__to__HSV4__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['bgr_5fto_5fhsv_5ffull_5ffunc',['BGR_to_HSV_FULL_func',['http://docs.opencv.org/3.4.0/d5/d12/structcv_1_1cudev_1_1BGR__to__HSV__FULL__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5fhsv_5ffull_5ffunc_3c_20float_20_3e',['BGR_to_HSV_FULL_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/dd/d00/structcv_1_1cudev_1_1BGR__to__HSV__FULL__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['bgr_5fto_5fhsv_5ffunc',['BGR_to_HSV_func',['http://docs.opencv.org/3.4.0/dd/d23/structcv_1_1cudev_1_1BGR__to__HSV__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5fhsv_5ffunc_3c_20float_20_3e',['BGR_to_HSV_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/d6/df7/structcv_1_1cudev_1_1BGR__to__HSV__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['bgr_5fto_5flab4_5ffunc',['BGR_to_Lab4_func',['http://docs.opencv.org/3.4.0/d9/df2/structcv_1_1cudev_1_1BGR__to__Lab4__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5flab_5ffunc',['BGR_to_Lab_func',['http://docs.opencv.org/3.4.0/d5/d91/structcv_1_1cudev_1_1BGR__to__Lab__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5fluv4_5ffunc',['BGR_to_Luv4_func',['http://docs.opencv.org/3.4.0/de/d8b/structcv_1_1cudev_1_1BGR__to__Luv4__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5fluv_5ffunc',['BGR_to_Luv_func',['http://docs.opencv.org/3.4.0/da/d92/structcv_1_1cudev_1_1BGR__to__Luv__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5frgb_5ffunc',['BGR_to_RGB_func',['http://docs.opencv.org/3.4.0/df/dd8/structcv_1_1cudev_1_1BGR__to__RGB__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5frgba_5ffunc',['BGR_to_RGBA_func',['http://docs.opencv.org/3.4.0/d8/d77/structcv_1_1cudev_1_1BGR__to__RGBA__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5fxyz4_5ffunc',['BGR_to_XYZ4_func',['http://docs.opencv.org/3.4.0/d7/d78/structcv_1_1cudev_1_1BGR__to__XYZ4__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5fxyz_5ffunc',['BGR_to_XYZ_func',['http://docs.opencv.org/3.4.0/d1/d61/structcv_1_1cudev_1_1BGR__to__XYZ__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5fycrcb4_5ffunc',['BGR_to_YCrCb4_func',['http://docs.opencv.org/3.4.0/d3/d27/structcv_1_1cudev_1_1BGR__to__YCrCb4__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5fycrcb_5ffunc',['BGR_to_YCrCb_func',['http://docs.opencv.org/3.4.0/d5/d3a/structcv_1_1cudev_1_1BGR__to__YCrCb__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5fyuv4_5ffunc',['BGR_to_YUV4_func',['http://docs.opencv.org/3.4.0/db/d18/structcv_1_1cudev_1_1BGR__to__YUV4__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5fyuv_5ffunc',['BGR_to_YUV_func',['http://docs.opencv.org/3.4.0/d7/d5d/structcv_1_1cudev_1_1BGR__to__YUV__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5fbgr_5ffunc',['BGRA_to_BGR_func',['http://docs.opencv.org/3.4.0/d6/d66/structcv_1_1cudev_1_1BGRA__to__BGR__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5fgray_5ffunc',['BGRA_to_GRAY_func',['http://docs.opencv.org/3.4.0/de/d7e/structcv_1_1cudev_1_1BGRA__to__GRAY__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5fhls4_5ffull_5ffunc',['BGRA_to_HLS4_FULL_func',['http://docs.opencv.org/3.4.0/d8/d7c/structcv_1_1cudev_1_1BGRA__to__HLS4__FULL__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5fhls4_5ffull_5ffunc_3c_20float_20_3e',['BGRA_to_HLS4_FULL_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/dd/d9f/structcv_1_1cudev_1_1BGRA__to__HLS4__FULL__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['bgra_5fto_5fhls4_5ffunc',['BGRA_to_HLS4_func',['http://docs.opencv.org/3.4.0/dc/da3/structcv_1_1cudev_1_1BGRA__to__HLS4__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5fhls4_5ffunc_3c_20float_20_3e',['BGRA_to_HLS4_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/d2/d33/structcv_1_1cudev_1_1BGRA__to__HLS4__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['bgra_5fto_5fhls_5ffull_5ffunc',['BGRA_to_HLS_FULL_func',['http://docs.opencv.org/3.4.0/d9/ddf/structcv_1_1cudev_1_1BGRA__to__HLS__FULL__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5fhls_5ffull_5ffunc_3c_20float_20_3e',['BGRA_to_HLS_FULL_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/d0/d64/structcv_1_1cudev_1_1BGRA__to__HLS__FULL__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['bgra_5fto_5fhls_5ffunc',['BGRA_to_HLS_func',['http://docs.opencv.org/3.4.0/de/d08/structcv_1_1cudev_1_1BGRA__to__HLS__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5fhls_5ffunc_3c_20float_20_3e',['BGRA_to_HLS_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/d8/d90/structcv_1_1cudev_1_1BGRA__to__HLS__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['bgra_5fto_5fhsv4_5ffull_5ffunc',['BGRA_to_HSV4_FULL_func',['http://docs.opencv.org/3.4.0/d6/da1/structcv_1_1cudev_1_1BGRA__to__HSV4__FULL__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5fhsv4_5ffull_5ffunc_3c_20float_20_3e',['BGRA_to_HSV4_FULL_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/d4/df0/structcv_1_1cudev_1_1BGRA__to__HSV4__FULL__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['bgra_5fto_5fhsv4_5ffunc',['BGRA_to_HSV4_func',['http://docs.opencv.org/3.4.0/d0/d82/structcv_1_1cudev_1_1BGRA__to__HSV4__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5fhsv4_5ffunc_3c_20float_20_3e',['BGRA_to_HSV4_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/d3/d25/structcv_1_1cudev_1_1BGRA__to__HSV4__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['bgra_5fto_5fhsv_5ffull_5ffunc',['BGRA_to_HSV_FULL_func',['http://docs.opencv.org/3.4.0/db/d15/structcv_1_1cudev_1_1BGRA__to__HSV__FULL__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5fhsv_5ffull_5ffunc_3c_20float_20_3e',['BGRA_to_HSV_FULL_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/d3/d43/structcv_1_1cudev_1_1BGRA__to__HSV__FULL__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['bgra_5fto_5fhsv_5ffunc',['BGRA_to_HSV_func',['http://docs.opencv.org/3.4.0/dc/d1f/structcv_1_1cudev_1_1BGRA__to__HSV__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5fhsv_5ffunc_3c_20float_20_3e',['BGRA_to_HSV_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/d9/d8a/structcv_1_1cudev_1_1BGRA__to__HSV__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['bgra_5fto_5flab4_5ffunc',['BGRA_to_Lab4_func',['http://docs.opencv.org/3.4.0/d0/de7/structcv_1_1cudev_1_1BGRA__to__Lab4__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5flab_5ffunc',['BGRA_to_Lab_func',['http://docs.opencv.org/3.4.0/d4/d7d/structcv_1_1cudev_1_1BGRA__to__Lab__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5fluv4_5ffunc',['BGRA_to_Luv4_func',['http://docs.opencv.org/3.4.0/de/d52/structcv_1_1cudev_1_1BGRA__to__Luv4__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5fluv_5ffunc',['BGRA_to_Luv_func',['http://docs.opencv.org/3.4.0/de/d8c/structcv_1_1cudev_1_1BGRA__to__Luv__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5frgb_5ffunc',['BGRA_to_RGB_func',['http://docs.opencv.org/3.4.0/d4/de2/structcv_1_1cudev_1_1BGRA__to__RGB__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5frgba_5ffunc',['BGRA_to_RGBA_func',['http://docs.opencv.org/3.4.0/d4/ddf/structcv_1_1cudev_1_1BGRA__to__RGBA__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5fxyz4_5ffunc',['BGRA_to_XYZ4_func',['http://docs.opencv.org/3.4.0/d8/d57/structcv_1_1cudev_1_1BGRA__to__XYZ4__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5fxyz_5ffunc',['BGRA_to_XYZ_func',['http://docs.opencv.org/3.4.0/de/d69/structcv_1_1cudev_1_1BGRA__to__XYZ__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5fycrcb4_5ffunc',['BGRA_to_YCrCb4_func',['http://docs.opencv.org/3.4.0/d3/d09/structcv_1_1cudev_1_1BGRA__to__YCrCb4__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5fycrcb_5ffunc',['BGRA_to_YCrCb_func',['http://docs.opencv.org/3.4.0/d6/dbd/structcv_1_1cudev_1_1BGRA__to__YCrCb__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5fyuv4_5ffunc',['BGRA_to_YUV4_func',['http://docs.opencv.org/3.4.0/db/d43/structcv_1_1cudev_1_1BGRA__to__YUV4__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5fyuv_5ffunc',['BGRA_to_YUV_func',['http://docs.opencv.org/3.4.0/db/d7e/structcv_1_1cudev_1_1BGRA__to__YUV__func.html',1,'cv::cudev']]],
  ['bidirectional_5fiterator_5ftag',['bidirectional_iterator_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06664.html',1,'std']]],
  ['bif',['BIF',['http://docs.opencv.org/3.4.0/dc/d12/classcv_1_1face_1_1BIF.html',1,'cv::face']]],
  ['big_5fany_5fpolicy',['big_any_policy',['http://docs.opencv.org/3.4.0/d3/d9e/structcvflann_1_1anyimpl_1_1big__any__policy.html',1,'cvflann::anyimpl']]],
  ['bin_5fsearch_5ftree_5fconst_5fit_5f',['bin_search_tree_const_it_',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10556.html',1,'__gnu_pbds::detail']]],
  ['bin_5fsearch_5ftree_5fconst_5fnode_5fit_5f',['bin_search_tree_const_node_it_',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10548.html',1,'__gnu_pbds::detail']]],
  ['bin_5fsearch_5ftree_5fit_5f',['bin_search_tree_it_',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10560.html',1,'__gnu_pbds::detail']]],
  ['bin_5fsearch_5ftree_5fnode_5fit_5f',['bin_search_tree_node_it_',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10552.html',1,'__gnu_pbds::detail']]],
  ['bin_5fsearch_5ftree_5ftraits',['bin_search_tree_traits',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10564.html',1,'__gnu_pbds::detail']]],
  ['bin_5fsearch_5ftree_5ftraits_3c_20key_2c_20mapped_2c_20cmp_5ffn_2c_20node_5fupdate_2c_20rb_5ftree_5fnode_5f_3c_20types_5ftraits_3c_20key_2c_20mapped_2c_20_5falloc_2c_20false_20_3e_3a_3avalue_5ftype_2c_20tree_5fnode_5fmetadata_5fdispatch_3c_20key_2c_20mapped_2c_20cmp_5ffn_2c_20node_5fupdate_2c_20_5falloc_20_3e_3a_3atype_2c_20_5falloc_20_3e_2c_20_5falloc_20_3e',['bin_search_tree_traits&lt; Key, Mapped, Cmp_Fn, Node_Update, rb_tree_node_&lt; types_traits&lt; Key, Mapped, _Alloc, false &gt;::value_type, tree_node_metadata_dispatch&lt; Key, Mapped, Cmp_Fn, Node_Update, _Alloc &gt;::type, _Alloc &gt;, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10564.html',1,'']]],
  ['bin_5fsearch_5ftree_5ftraits_3c_20key_2c_20mapped_2c_20cmp_5ffn_2c_20node_5fupdate_2c_20splay_5ftree_5fnode_5f_3c_20types_5ftraits_3c_20key_2c_20mapped_2c_20_5falloc_2c_20false_20_3e_3a_3avalue_5ftype_2c_20tree_5fnode_5fmetadata_5fdispatch_3c_20key_2c_20mapped_2c_20cmp_5ffn_2c_20node_5fupdate_2c_20_5falloc_20_3e_3a_3atype_2c_20_5falloc_20_3e_2c_20_5falloc_20_3e',['bin_search_tree_traits&lt; Key, Mapped, Cmp_Fn, Node_Update, splay_tree_node_&lt; types_traits&lt; Key, Mapped, _Alloc, false &gt;::value_type, tree_node_metadata_dispatch&lt; Key, Mapped, Cmp_Fn, Node_Update, _Alloc &gt;::type, _Alloc &gt;, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10564.html',1,'']]],
  ['bin_5fsearch_5ftree_5ftraits_3c_20key_2c_20null_5ftype_2c_20cmp_5ffn_2c_20node_5fupdate_2c_20node_2c_20_5falloc_20_3e',['bin_search_tree_traits&lt; Key, null_type, Cmp_Fn, Node_Update, Node, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10568.html',1,'__gnu_pbds::detail']]],
  ['bin_5fsearch_5ftree_5ftraits_3c_20key_2c_20null_5ftype_2c_20cmp_5ffn_2c_20node_5fupdate_2c_20rb_5ftree_5fnode_5f_3c_20types_5ftraits_3c_20key_2c_20null_5ftype_2c_20_5falloc_2c_20false_20_3e_3a_3avalue_5ftype_2c_20tree_5fnode_5fmetadata_5fdispatch_3c_20key_2c_20null_5ftype_2c_20cmp_5ffn_2c_20node_5fupdate_2c_20_5falloc_20_3e_3a_3atype_2c_20_5falloc_20_3e_2c_20_5falloc_20_3e',['bin_search_tree_traits&lt; Key, null_type, Cmp_Fn, Node_Update, rb_tree_node_&lt; types_traits&lt; Key, null_type, _Alloc, false &gt;::value_type, tree_node_metadata_dispatch&lt; Key, null_type, Cmp_Fn, Node_Update, _Alloc &gt;::type, _Alloc &gt;, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10564.html',1,'']]],
  ['bin_5fsearch_5ftree_5ftraits_3c_20key_2c_20null_5ftype_2c_20cmp_5ffn_2c_20node_5fupdate_2c_20splay_5ftree_5fnode_5f_3c_20types_5ftraits_3c_20key_2c_20null_5ftype_2c_20_5falloc_2c_20false_20_3e_3a_3avalue_5ftype_2c_20tree_5fnode_5fmetadata_5fdispatch_3c_20key_2c_20null_5ftype_2c_20cmp_5ffn_2c_20node_5fupdate_2c_20_5falloc_20_3e_3a_3atype_2c_20_5falloc_20_3e_2c_20_5falloc_20_3e',['bin_search_tree_traits&lt; Key, null_type, Cmp_Fn, Node_Update, splay_tree_node_&lt; types_traits&lt; Key, null_type, _Alloc, false &gt;::value_type, tree_node_metadata_dispatch&lt; Key, null_type, Cmp_Fn, Node_Update, _Alloc &gt;::type, _Alloc &gt;, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10564.html',1,'']]],
  ['binary_5fcompose',['binary_compose',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08088.html',1,'__gnu_cxx']]],
  ['binary_5ffunction',['binary_function',['http://docs.opencv.org/3.4.0/d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'cv::cudev']]],
  ['binary_5ffunction',['binary_function',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'std']]],
  ['binary_5ffunction_3c_20_5f_5fshared_5fptr_3c_20_5ftp_2c_20_5flp_20_3e_2c_20_5f_5fshared_5fptr_3c_20_5ftp_2c_20_5flp_20_3e_2c_20bool_20_3e',['binary_function&lt; __shared_ptr&lt; _Tp, _Lp &gt;, __shared_ptr&lt; _Tp, _Lp &gt;, bool &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20_5f_5fweak_5fptr_3c_20_5ftp_2c_20_5flp_20_3e_2c_20_5f_5fweak_5fptr_3c_20_5ftp_2c_20_5flp_20_3e_2c_20bool_20_3e',['binary_function&lt; __weak_ptr&lt; _Tp, _Lp &gt;, __weak_ptr&lt; _Tp, _Lp &gt;, bool &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20_5farg1_2c_20_5farg2_2c_20_5farg1_20_3e',['binary_function&lt; _Arg1, _Arg2, _Arg1 &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20_5farg1_2c_20_5farg2_2c_20_5farg2_20_3e',['binary_function&lt; _Arg1, _Arg2, _Arg2 &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20_5fpredicate_3a_3afirst_5fargument_5ftype_2c_20_5fpredicate_3a_3asecond_5fargument_5ftype_2c_20bool_20_3e',['binary_function&lt; _Predicate::first_argument_type, _Predicate::second_argument_type, bool &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20_5fsp_2c_20_5fsp_2c_20bool_20_3e',['binary_function&lt; _Sp, _Sp, bool &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20_5ft1_20_2a_2c_20_5ft2_2c_20_5fres_20_3e',['binary_function&lt; _T1 *, _T2, _Res &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20_5ft1_2c_20_5ft2_2c_20_5fres_20_3e',['binary_function&lt; _T1, _T2, _Res &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20_5ft1_2c_20_5ft2_2c_20bool_20_3e',['binary_function&lt; _T1, _T2, bool &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20_5ftp_20_2a_2c_20_5farg_2c_20_5fret_20_3e',['binary_function&lt; _Tp *, _Arg, _Ret &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20_5ftp_2c_20_5farg_2c_20_5fret_20_3e',['binary_function&lt; _Tp, _Arg, _Ret &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20_5ftp_2c_20_5ftp_2c_20_5ftp_20_3e',['binary_function&lt; _Tp, _Tp, _Tp &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20_5ftp_2c_20_5ftp_2c_20bool_20_3e',['binary_function&lt; _Tp, _Tp, bool &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20_5ftp1_2c_20_5ftp2_2c_20_5fresult_20_3e',['binary_function&lt; _Tp1, _Tp2, _Result &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20const_20_5ft1_20_2a_2c_20_5ft2_2c_20_5fres_20_3e',['binary_function&lt; const _T1 *, _T2, _Res &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20const_20_5ftp_20_2a_2c_20_5farg_2c_20_5fret_20_3e',['binary_function&lt; const _Tp *, _Arg, _Ret &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20const_20volatile_20_5ft1_20_2a_2c_20_5ft2_2c_20_5fres_20_3e',['binary_function&lt; const volatile _T1 *, _T2, _Res &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20double_2c_20double_2c_20double_20_3e',['binary_function&lt; double, double, double &gt;',['http://docs.opencv.org/3.4.0/d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'']]],
  ['binary_5ffunction_3c_20float_2c_20float_2c_20float_20_3e',['binary_function&lt; float, float, float &gt;',['http://docs.opencv.org/3.4.0/d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'']]],
  ['binary_5ffunction_3c_20int_2c_20int_2c_20float_20_3e',['binary_function&lt; int, int, float &gt;',['http://docs.opencv.org/3.4.0/d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'']]],
  ['binary_5ffunction_3c_20int_2c_20int_2c_20int_20_3e',['binary_function&lt; int, int, int &gt;',['http://docs.opencv.org/3.4.0/d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'']]],
  ['binary_5ffunction_3c_20predicate_3a_3afirst_5fargument_5ftype_2c_20predicate_3a_3asecond_5fargument_5ftype_2c_20predicate_3a_3aresult_5ftype_20_3e',['binary_function&lt; Predicate::first_argument_type, Predicate::second_argument_type, Predicate::result_type &gt;',['http://docs.opencv.org/3.4.0/d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'']]],
  ['binary_5ffunction_3c_20rope_3c_20_5fchart_2c_20_5falloc_20_3e_2c_20rope_3c_20_5fchart_2c_20_5falloc_20_3e_2c_20rope_3c_20_5fchart_2c_20_5falloc_20_3e_20_3e',['binary_function&lt; rope&lt; _CharT, _Alloc &gt;, rope&lt; _CharT, _Alloc &gt;, rope&lt; _CharT, _Alloc &gt; &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20schar_2c_20schar_2c_20float_20_3e',['binary_function&lt; schar, schar, float &gt;',['http://docs.opencv.org/3.4.0/d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'']]],
  ['binary_5ffunction_3c_20schar_2c_20schar_2c_20schar_20_3e',['binary_function&lt; schar, schar, schar &gt;',['http://docs.opencv.org/3.4.0/d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'']]],
  ['binary_5ffunction_3c_20shared_5fptr_3c_20_5ftp_20_3e_2c_20shared_5fptr_3c_20_5ftp_20_3e_2c_20bool_20_3e',['binary_function&lt; shared_ptr&lt; _Tp &gt;, shared_ptr&lt; _Tp &gt;, bool &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20short_2c_20short_2c_20float_20_3e',['binary_function&lt; short, short, float &gt;',['http://docs.opencv.org/3.4.0/d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'']]],
  ['binary_5ffunction_3c_20short_2c_20short_2c_20short_20_3e',['binary_function&lt; short, short, short &gt;',['http://docs.opencv.org/3.4.0/d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'']]],
  ['binary_5ffunction_3c_20std_3a_3apair_3c_20_5ft1_2c_20_5ft2_20_3e_2c_20std_3a_3apair_3c_20_5ft1_2c_20_5ft2_20_3e_2c_20bool_20_3e',['binary_function&lt; std::pair&lt; _T1, _T2 &gt;, std::pair&lt; _T1, _T2 &gt;, bool &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20t_2c_20float_2c_20float_20_3e',['binary_function&lt; T, float, float &gt;',['http://docs.opencv.org/3.4.0/d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'']]],
  ['binary_5ffunction_3c_20t_2c_20t_2c_20functional_5fdetail_3a_3afloattype_3c_20t_20_3e_3a_3atype_20_3e',['binary_function&lt; T, T, functional_detail::FloatType&lt; T &gt;::type &gt;',['http://docs.opencv.org/3.4.0/d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'']]],
  ['binary_5ffunction_3c_20t_2c_20t_2c_20makevec_3c_20uchar_2c_20vectraits_3c_20t_20_3e_3a_3acn_20_3e_3a_3atype_20_3e',['binary_function&lt; T, T, MakeVec&lt; uchar, VecTraits&lt; T &gt;::cn &gt;::type &gt;',['http://docs.opencv.org/3.4.0/d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'']]],
  ['binary_5ffunction_3c_20t_2c_20t_2c_20t_20_3e',['binary_function&lt; T, T, T &gt;',['http://docs.opencv.org/3.4.0/d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'']]],
  ['binary_5ffunction_3c_20t1_2c_20t2_2c_20t1_20_3e',['binary_function&lt; T1, T2, T1 &gt;',['http://docs.opencv.org/3.4.0/d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'']]],
  ['binary_5ffunction_3c_20t1_2c_20t2_2c_20t2_20_3e',['binary_function&lt; T1, T2, T2 &gt;',['http://docs.opencv.org/3.4.0/d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'']]],
  ['binary_5ffunction_3c_20uchar_2c_20uchar_2c_20float_20_3e',['binary_function&lt; uchar, uchar, float &gt;',['http://docs.opencv.org/3.4.0/d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'']]],
  ['binary_5ffunction_3c_20uchar_2c_20uchar_2c_20uchar_20_3e',['binary_function&lt; uchar, uchar, uchar &gt;',['http://docs.opencv.org/3.4.0/d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'']]],
  ['binary_5ffunction_3c_20uint_2c_20uint_2c_20float_20_3e',['binary_function&lt; uint, uint, float &gt;',['http://docs.opencv.org/3.4.0/d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'']]],
  ['binary_5ffunction_3c_20uint_2c_20uint_2c_20uint_20_3e',['binary_function&lt; uint, uint, uint &gt;',['http://docs.opencv.org/3.4.0/d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'']]],
  ['binary_5ffunction_3c_20ushort_2c_20ushort_2c_20float_20_3e',['binary_function&lt; ushort, ushort, float &gt;',['http://docs.opencv.org/3.4.0/d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'']]],
  ['binary_5ffunction_3c_20ushort_2c_20ushort_2c_20ushort_20_3e',['binary_function&lt; ushort, ushort, ushort &gt;',['http://docs.opencv.org/3.4.0/d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'']]],
  ['binary_5ffunction_3c_20value_5ftype_2c_20value_5ftype_2c_20bool_20_3e',['binary_function&lt; value_type, value_type, bool &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20void_2c_20void_2c_20bool_20_3e',['binary_function&lt; void, void, bool &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20volatile_20_5ft1_20_2a_2c_20_5ft2_2c_20_5fres_20_3e',['binary_function&lt; volatile _T1 *, _T2, _Res &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5ffunction_3c_20weak_5fptr_3c_20_5ftp_20_3e_2c_20weak_5fptr_3c_20_5ftp_20_3e_2c_20bool_20_3e',['binary_function&lt; weak_ptr&lt; _Tp &gt;, weak_ptr&lt; _Tp &gt;, bool &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06396.html',1,'']]],
  ['binary_5fheap',['binary_heap',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10488.html',1,'__gnu_pbds::detail']]],
  ['binary_5fheap_5fconst_5fiterator_5f',['binary_heap_const_iterator_',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10492.html',1,'__gnu_pbds::detail']]],
  ['binary_5fheap_5fpoint_5fconst_5fiterator_5f',['binary_heap_point_const_iterator_',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10528.html',1,'__gnu_pbds::detail']]],
  ['binary_5fheap_5ftag',['binary_heap_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10204.html',1,'__gnu_pbds']]],
  ['binary_5fnegate',['binary_negate',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06556.html',1,'std']]],
  ['binarydescriptor',['BinaryDescriptor',['http://docs.opencv.org/3.4.0/d6/d83/classcv_1_1line__descriptor_1_1BinaryDescriptor.html',1,'cv::line_descriptor']]],
  ['binarydescriptormatcher',['BinaryDescriptorMatcher',['http://docs.opencv.org/3.4.0/d2/dde/classcv_1_1line__descriptor_1_1BinaryDescriptorMatcher.html',1,'cv::line_descriptor']]],
  ['binarynegate',['BinaryNegate',['http://docs.opencv.org/3.4.0/d1/d81/structcv_1_1cudev_1_1BinaryNegate.html',1,'cv::cudev']]],
  ['binarytransformptr',['BinaryTransformPtr',['http://docs.opencv.org/3.4.0/db/d77/structcv_1_1cudev_1_1BinaryTransformPtr.html',1,'cv::cudev']]],
  ['binarytransformptrsz',['BinaryTransformPtrSz',['http://docs.opencv.org/3.4.0/d1/d0a/structcv_1_1cudev_1_1BinaryTransformPtrSz.html',1,'cv::cudev']]],
  ['binarytupleadapter',['BinaryTupleAdapter',['http://docs.opencv.org/3.4.0/dc/da3/structcv_1_1cudev_1_1BinaryTupleAdapter.html',1,'cv::cudev']]],
  ['binder1st',['binder1st',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07452.html',1,'std']]],
  ['binder1st',['Binder1st',['http://docs.opencv.org/3.4.0/d5/dee/structcv_1_1cudev_1_1Binder1st.html',1,'cv::cudev']]],
  ['binder2nd',['Binder2nd',['http://docs.opencv.org/3.4.0/d6/db4/structcv_1_1cudev_1_1Binder2nd.html',1,'cv::cudev']]],
  ['binder2nd',['binder2nd',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07456.html',1,'std']]],
  ['binomial_5fdistribution',['binomial_distribution',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05504.html',1,'std']]],
  ['binomial_5fheap',['binomial_heap',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10536.html',1,'__gnu_pbds::detail']]],
  ['binomial_5fheap_5fbase',['binomial_heap_base',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10540.html',1,'__gnu_pbds::detail']]],
  ['binomial_5fheap_5ftag',['binomial_heap_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10196.html',1,'__gnu_pbds']]],
  ['bit_5fand',['bit_and',['http://docs.opencv.org/3.4.0/d9/de7/structcv_1_1cudev_1_1bit__and.html',1,'cv::cudev']]],
  ['bit_5flshift',['bit_lshift',['http://docs.opencv.org/3.4.0/d3/d65/structcv_1_1cudev_1_1bit__lshift.html',1,'cv::cudev']]],
  ['bit_5fnot',['bit_not',['http://docs.opencv.org/3.4.0/d0/d8a/structcv_1_1cudev_1_1bit__not.html',1,'cv::cudev']]],
  ['bit_5for',['bit_or',['http://docs.opencv.org/3.4.0/dd/d1c/structcv_1_1cudev_1_1bit__or.html',1,'cv::cudev']]],
  ['bit_5frshift',['bit_rshift',['http://docs.opencv.org/3.4.0/d4/d2a/structcv_1_1cudev_1_1bit__rshift.html',1,'cv::cudev']]],
  ['bit_5fxor',['bit_xor',['http://docs.opencv.org/3.4.0/df/d44/structcv_1_1cudev_1_1bit__xor.html',1,'cv::cudev']]],
  ['bitmap_5fallocator',['bitmap_allocator',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09212.html',1,'__gnu_cxx']]],
  ['bitset',['bitset',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01816.html',1,'std']]],
  ['bitset',['bitset',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08024.html',1,'std::__profile']]],
  ['bitset',['bitset',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07756.html',1,'std::__debug']]],
  ['blanklayer',['BlankLayer',['http://docs.opencv.org/3.4.0/d8/d2d/classcv_1_1dnn_1_1BlankLayer.html',1,'cv::dnn']]],
  ['blender',['Blender',['http://docs.opencv.org/3.4.0/d6/d4a/classcv_1_1detail_1_1Blender.html',1,'cv::detail']]],
  ['block',['Block',['http://docs.opencv.org/3.4.0/d3/d6c/structcv_1_1cudev_1_1Block.html',1,'cv::cudev']]],
  ['blockmeanhash',['BlockMeanHash',['http://docs.opencv.org/3.4.0/df/d55/classcv_1_1img__hash_1_1BlockMeanHash.html',1,'cv::img_hash']]],
  ['blocksgaincompensator',['BlocksGainCompensator',['http://docs.opencv.org/3.4.0/d7/d81/classcv_1_1detail_1_1BlocksGainCompensator.html',1,'cv::detail']]],
  ['bnlllayer',['BNLLLayer',['http://docs.opencv.org/3.4.0/d0/d87/classcv_1_1dnn_1_1BNLLLayer.html',1,'cv::dnn']]],
  ['board',['Board',['http://docs.opencv.org/3.4.0/d4/db2/classcv_1_1aruco_1_1Board.html',1,'cv::aruco']]],
  ['bool_5fset',['bool_set',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08704.html',1,'std::tr2']]],
  ['boost',['Boost',['http://docs.opencv.org/3.4.0/d6/d7a/classcv_1_1ml_1_1Boost.html',1,'cv::ml']]],
  ['boostdesc',['BoostDesc',['http://docs.opencv.org/3.4.0/d1/dfd/classcv_1_1xfeatures2d_1_1BoostDesc.html',1,'cv::xfeatures2d']]],
  ['bowimgdescriptorextractor',['BOWImgDescriptorExtractor',['http://docs.opencv.org/3.4.0/d2/d6b/classcv_1_1BOWImgDescriptorExtractor.html',1,'cv']]],
  ['bowkmeanstrainer',['BOWKMeansTrainer',['http://docs.opencv.org/3.4.0/d4/d72/classcv_1_1BOWKMeansTrainer.html',1,'cv']]],
  ['bowtrainer',['BOWTrainer',['http://docs.opencv.org/3.4.0/d5/d14/classcv_1_1BOWTrainer.html',1,'cv']]],
  ['box',['Box',['http://docs.opencv.org/3.4.0/d7/d59/structcv_1_1ximgproc_1_1Box.html',1,'cv::ximgproc']]],
  ['branch_5fpolicy',['branch_policy',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10572.html',1,'__gnu_pbds::detail']]],
  ['branch_5fpolicy_3c_20node_5fcitr_2c_20node_5fcitr_2c_20_5falloc_20_3e',['branch_policy&lt; Node_CItr, Node_CItr, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10576.html',1,'__gnu_pbds::detail']]],
  ['branchstruct',['BranchStruct',['http://docs.opencv.org/3.4.0/dc/d72/structcvflann_1_1BranchStruct.html',1,'cvflann']]],
  ['brdbase',['BrdBase',['http://docs.opencv.org/3.4.0/de/d53/structcv_1_1cudev_1_1BrdBase.html',1,'cv::cudev']]],
  ['brdconstant',['BrdConstant',['http://docs.opencv.org/3.4.0/da/dfa/structcv_1_1cudev_1_1BrdConstant.html',1,'cv::cudev']]],
  ['brdreflect',['BrdReflect',['http://docs.opencv.org/3.4.0/dc/dff/structcv_1_1cudev_1_1BrdReflect.html',1,'cv::cudev']]],
  ['brdreflect101',['BrdReflect101',['http://docs.opencv.org/3.4.0/d3/d12/structcv_1_1cudev_1_1BrdReflect101.html',1,'cv::cudev']]],
  ['brdreplicate',['BrdReplicate',['http://docs.opencv.org/3.4.0/d7/de8/structcv_1_1cudev_1_1BrdReplicate.html',1,'cv::cudev']]],
  ['brdwrap',['BrdWrap',['http://docs.opencv.org/3.4.0/da/d69/structcv_1_1cudev_1_1BrdWrap.html',1,'cv::cudev']]],
  ['bridge',['Bridge',['http://docs.opencv.org/3.4.0/df/d5d/classcv_1_1bridge_1_1Bridge.html',1,'cv::bridge']]],
  ['briefdescriptorextractor',['BriefDescriptorExtractor',['http://docs.opencv.org/3.4.0/d1/d93/classcv_1_1xfeatures2d_1_1BriefDescriptorExtractor.html',1,'cv::xfeatures2d']]],
  ['brisk',['BRISK',['http://docs.opencv.org/3.4.0/de/dbf/classcv_1_1BRISK.html',1,'cv']]],
  ['broxopticalflow',['BroxOpticalFlow',['http://docs.opencv.org/3.4.0/d7/d18/classcv_1_1cuda_1_1BroxOpticalFlow.html',1,'cv::cuda']]],
  ['broxopticalflow',['BroxOpticalFlow',['http://docs.opencv.org/3.4.0/dc/dd1/classcv_1_1superres_1_1BroxOpticalFlow.html',1,'cv::superres']]],
  ['buffer',['Buffer',['http://docs.opencv.org/3.4.0/d3/d68/classcv_1_1ogl_1_1Buffer.html',1,'cv::ogl']]],
  ['bufferpool',['BufferPool',['http://docs.opencv.org/3.4.0/d5/d08/classcv_1_1cuda_1_1BufferPool.html',1,'cv::cuda']]],
  ['bufferpoolcontroller',['BufferPoolController',['http://docs.opencv.org/3.4.0/d4/dad/classcv_1_1BufferPoolController.html',1,'cv']]],
  ['bundleadjusteraffine',['BundleAdjusterAffine',['http://docs.opencv.org/3.4.0/d6/d8d/classcv_1_1detail_1_1BundleAdjusterAffine.html',1,'cv::detail']]],
  ['bundleadjusteraffinepartial',['BundleAdjusterAffinePartial',['http://docs.opencv.org/3.4.0/d4/dbb/classcv_1_1detail_1_1BundleAdjusterAffinePartial.html',1,'cv::detail']]],
  ['bundleadjusterbase',['BundleAdjusterBase',['http://docs.opencv.org/3.4.0/d5/d56/classcv_1_1detail_1_1BundleAdjusterBase.html',1,'cv::detail']]],
  ['bundleadjusterray',['BundleAdjusterRay',['http://docs.opencv.org/3.4.0/da/d7c/classcv_1_1detail_1_1BundleAdjusterRay.html',1,'cv::detail']]],
  ['bundleadjusterreproj',['BundleAdjusterReproj',['http://docs.opencv.org/3.4.0/dc/d54/classcv_1_1detail_1_1BundleAdjusterReproj.html',1,'cv::detail']]]
];
