var searchData=
[
  ['caffeconverter',['CaffeConverter',['http://docs.opencv.org/3.4.0/d7/dc5/classcv_1_1dnn2_1_1CaffeConverter.html',1,'cv::dnn2']]],
  ['calibratecrf',['CalibrateCRF',['http://docs.opencv.org/3.4.0/dd/de3/classcv_1_1CalibrateCRF.html',1,'cv']]],
  ['calibratedebevec',['CalibrateDebevec',['http://docs.opencv.org/3.4.0/da/d27/classcv_1_1CalibrateDebevec.html',1,'cv']]],
  ['calibraterobertson',['CalibrateRobertson',['http://docs.opencv.org/3.4.0/d3/d30/classcv_1_1CalibrateRobertson.html',1,'cv']]],
  ['callback',['Callback',['http://docs.opencv.org/3.4.0/d0/d4f/classcv_1_1text_1_1ERFilter_1_1Callback.html',1,'cv::text::ERFilter']]],
  ['callmetadata',['CallMetaData',['http://docs.opencv.org/3.4.0/d4/dd9/structcvv_1_1impl_1_1CallMetaData.html',1,'cvv::impl']]],
  ['camera',['Camera',['http://docs.opencv.org/3.4.0/dc/d3a/classcv_1_1viz_1_1Camera.html',1,'cv::viz']]],
  ['cameraparam',['cameraParam',['http://docs.opencv.org/3.4.0/d3/d99/structcv_1_1datasets_1_1cameraParam.html',1,'cv::datasets']]],
  ['cameraparams',['CameraParams',['http://docs.opencv.org/3.4.0/d4/d0a/structcv_1_1detail_1_1CameraParams.html',1,'cv::detail']]],
  ['camerapos',['cameraPos',['http://docs.opencv.org/3.4.0/d1/d64/structcv_1_1datasets_1_1cameraPos.html',1,'cv::datasets']]],
  ['candidate',['Candidate',['http://docs.opencv.org/3.4.0/df/da3/structcv_1_1linemod_1_1QuantizedPyramid_1_1Candidate.html',1,'cv::linemod::QuantizedPyramid']]],
  ['cannyedgedetector',['CannyEdgeDetector',['http://docs.opencv.org/3.4.0/d0/d43/classcv_1_1cuda_1_1CannyEdgeDetector.html',1,'cv::cuda']]],
  ['cascadeclassifier',['CascadeClassifier',['http://docs.opencv.org/3.4.0/d9/d80/classcv_1_1cuda_1_1CascadeClassifier.html',1,'cv::cuda']]],
  ['cascadeclassifier',['CascadeClassifier',['http://docs.opencv.org/3.4.0/d1/de5/classcv_1_1CascadeClassifier.html',1,'cv']]],
  ['cauchy_5fdistribution',['cauchy_distribution',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05472.html',1,'std']]],
  ['cc_5fhash_5fmax_5fcollision_5fcheck_5fresize_5ftrigger',['cc_hash_max_collision_check_resize_trigger',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10084.html',1,'__gnu_pbds']]],
  ['cc_5fhash_5ftable',['cc_hash_table',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10024.html',1,'__gnu_pbds']]],
  ['cc_5fhash_5ftag',['cc_hash_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10148.html',1,'__gnu_pbds']]],
  ['cc_5fht_5fmap',['cc_ht_map',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10592.html',1,'__gnu_pbds::detail']]],
  ['censuskernel',['CensusKernel',['http://docs.opencv.org/3.4.0/dc/d9a/structcv_1_1stereo_1_1CensusKernel.html',1,'cv::stereo']]],
  ['channelsprelulayer',['ChannelsPReLULayer',['http://docs.opencv.org/3.4.0/d7/de9/classcv_1_1dnn_1_1ChannelsPReLULayer.html',1,'cv::dnn']]],
  ['char_5ftraits',['char_traits',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a04240.html',1,'std']]],
  ['char_5ftraits',['char_traits',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a04236.html',1,'__gnu_cxx']]],
  ['char_5ftraits_3c_20_5f_5fgnu_5fcxx_3a_3acharacter_3c_20_5fvalue_2c_20_5fint_2c_20_5fst_20_3e_20_3e',['char_traits&lt; __gnu_cxx::character&lt; _Value, _Int, _St &gt; &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09456.html',1,'std']]],
  ['char_5ftraits_3c_20char_20_3e',['char_traits&lt; char &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a04244.html',1,'std']]],
  ['char_5ftraits_3c_20wchar_5ft_20_3e',['char_traits&lt; wchar_t &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a04248.html',1,'std']]],
  ['character',['character',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09452.html',1,'__gnu_cxx']]],
  ['charucoboard',['CharucoBoard',['http://docs.opencv.org/3.4.0/d0/d3c/classcv_1_1aruco_1_1CharucoBoard.html',1,'cv::aruco']]],
  ['chi_5fsquared_5fdistribution',['chi_squared_distribution',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05464.html',1,'std']]],
  ['chihistogramcostextractor',['ChiHistogramCostExtractor',['http://docs.opencv.org/3.4.0/dd/d43/classcv_1_1ChiHistogramCostExtractor.html',1,'cv']]],
  ['chisquaredistance',['ChiSquareDistance',['http://docs.opencv.org/3.4.0/dd/dd8/structcvflann_1_1ChiSquareDistance.html',1,'cvflann']]],
  ['choose_5fpolicy',['choose_policy',['http://docs.opencv.org/3.4.0/d5/da1/structcvflann_1_1anyimpl_1_1choose__policy.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20any_20_3e',['choose_policy&lt; any &gt;',['http://docs.opencv.org/3.4.0/d5/d51/structcvflann_1_1anyimpl_1_1choose__policy_3_01any_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20bool_20_3e',['choose_policy&lt; bool &gt;',['http://docs.opencv.org/3.4.0/d9/d10/structcvflann_1_1anyimpl_1_1choose__policy_3_01bool_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20float_20_3e',['choose_policy&lt; float &gt;',['http://docs.opencv.org/3.4.0/d2/d87/structcvflann_1_1anyimpl_1_1choose__policy_3_01float_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20signed_20char_20_3e',['choose_policy&lt; signed char &gt;',['http://docs.opencv.org/3.4.0/dc/d84/structcvflann_1_1anyimpl_1_1choose__policy_3_01signed_01char_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20signed_20long_20_3e',['choose_policy&lt; signed long &gt;',['http://docs.opencv.org/3.4.0/d7/d22/structcvflann_1_1anyimpl_1_1choose__policy_3_01signed_01long_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20signed_20short_20_3e',['choose_policy&lt; signed short &gt;',['http://docs.opencv.org/3.4.0/d3/d4a/structcvflann_1_1anyimpl_1_1choose__policy_3_01signed_01short_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20t_20_2a_20_3e',['choose_policy&lt; T * &gt;',['http://docs.opencv.org/3.4.0/d0/db0/structcvflann_1_1anyimpl_1_1choose__policy_3_01T_01_5_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20unsigned_20char_20_3e',['choose_policy&lt; unsigned char &gt;',['http://docs.opencv.org/3.4.0/dd/dd1/structcvflann_1_1anyimpl_1_1choose__policy_3_01unsigned_01char_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20unsigned_20long_20_3e',['choose_policy&lt; unsigned long &gt;',['http://docs.opencv.org/3.4.0/d9/dcd/structcvflann_1_1anyimpl_1_1choose__policy_3_01unsigned_01long_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20unsigned_20short_20_3e',['choose_policy&lt; unsigned short &gt;',['http://docs.opencv.org/3.4.0/d9/dd6/structcvflann_1_1anyimpl_1_1choose__policy_3_01unsigned_01short_01_4.html',1,'cvflann::anyimpl']]],
  ['circlesgridfinderparameters',['CirclesGridFinderParameters',['http://docs.opencv.org/3.4.0/d2/dd1/structcv_1_1CirclesGridFinderParameters.html',1,'cv']]],
  ['circlesgridfinderparameters2',['CirclesGridFinderParameters2',['http://docs.opencv.org/3.4.0/df/d58/structcv_1_1CirclesGridFinderParameters2.html',1,'cv']]],
  ['clahe',['CLAHE',['http://docs.opencv.org/3.4.0/db/d79/classcv_1_1cuda_1_1CLAHE.html',1,'cv::cuda']]],
  ['clahe',['CLAHE',['http://docs.opencv.org/3.4.0/d6/db6/classcv_1_1CLAHE.html',1,'cv']]],
  ['classifiercallback',['ClassifierCallback',['http://docs.opencv.org/3.4.0/db/dc0/classcv_1_1text_1_1OCRHMMDecoder_1_1ClassifierCallback.html',1,'cv::text::OCRHMMDecoder']]],
  ['classifiercallback',['ClassifierCallback',['http://docs.opencv.org/3.4.0/de/d2d/classcv_1_1text_1_1OCRBeamSearchDecoder_1_1ClassifierCallback.html',1,'cv::text::OCRBeamSearchDecoder']]],
  ['classifierthreshold',['ClassifierThreshold',['http://docs.opencv.org/3.4.0/d7/dd9/classcv_1_1ClassifierThreshold.html',1,'cv']]],
  ['clfmilboost',['ClfMilBoost',['http://docs.opencv.org/3.4.0/dc/d72/classcv_1_1ClfMilBoost.html',1,'cv']]],
  ['clfonlinestump',['ClfOnlineStump',['http://docs.opencv.org/3.4.0/dc/dac/classcv_1_1ClfOnlineStump.html',1,'cv']]],
  ['codecvt',['codecvt',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a04268.html',1,'std']]],
  ['codecvt_3c_20_5felem_2c_20char_2c_20mbstate_5ft_20_3e',['codecvt&lt; _Elem, char, mbstate_t &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a04268.html',1,'']]],
  ['codecvt_3c_20_5finternt_2c_20_5fexternt_2c_20encoding_5fstate_20_3e',['codecvt&lt; _InternT, _ExternT, encoding_state &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09252.html',1,'std']]],
  ['codecvt_3c_20char_2c_20char_2c_20mbstate_5ft_20_3e',['codecvt&lt; char, char, mbstate_t &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a04272.html',1,'std']]],
  ['codecvt_3c_20char16_5ft_2c_20char_2c_20mbstate_5ft_20_3e',['codecvt&lt; char16_t, char, mbstate_t &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a04280.html',1,'std']]],
  ['codecvt_3c_20char32_5ft_2c_20char_2c_20mbstate_5ft_20_3e',['codecvt&lt; char32_t, char, mbstate_t &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a04284.html',1,'std']]],
  ['codecvt_3c_20wchar_5ft_2c_20char_2c_20mbstate_5ft_20_3e',['codecvt&lt; wchar_t, char, mbstate_t &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a04276.html',1,'std']]],
  ['codecvt_5fbase',['codecvt_base',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a04260.html',1,'std']]],
  ['codecvt_5fbyname',['codecvt_byname',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a04288.html',1,'std']]],
  ['collate',['collate',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a04968.html',1,'std']]],
  ['collate_5fbyname',['collate_byname',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a04972.html',1,'std']]],
  ['color',['Color',['http://docs.opencv.org/3.4.0/d4/dba/classcv_1_1viz_1_1Color.html',1,'cv::viz']]],
  ['coloraverageinpainter',['ColorAverageInpainter',['http://docs.opencv.org/3.4.0/d1/dc6/classcv_1_1videostab_1_1ColorAverageInpainter.html',1,'cv::videostab']]],
  ['colorgradient',['ColorGradient',['http://docs.opencv.org/3.4.0/dc/d64/classcv_1_1linemod_1_1ColorGradient.html',1,'cv::linemod']]],
  ['colorinpainter',['ColorInpainter',['http://docs.opencv.org/3.4.0/d3/d2b/classcv_1_1videostab_1_1ColorInpainter.html',1,'cv::videostab']]],
  ['colormomenthash',['ColorMomentHash',['http://docs.opencv.org/3.4.0/df/d52/classcv_1_1img__hash_1_1ColorMomentHash.html',1,'cv::img_hash']]],
  ['combineddescriptor',['CombinedDescriptor',['http://docs.opencv.org/3.4.0/d4/d5b/classcv_1_1stereo_1_1CombinedDescriptor.html',1,'cv::stereo']]],
  ['commandlineparser',['CommandLineParser',['http://docs.opencv.org/3.4.0/d0/d2e/classcv_1_1CommandLineParser.html',1,'cv']]],
  ['commonareainterptr',['CommonAreaInterPtr',['http://docs.opencv.org/3.4.0/d8/d3d/structcv_1_1cudev_1_1CommonAreaInterPtr.html',1,'cv::cudev']]],
  ['commonareainterptrsz',['CommonAreaInterPtrSz',['http://docs.opencv.org/3.4.0/db/d1c/structcv_1_1cudev_1_1CommonAreaInterPtrSz.html',1,'cv::cudev']]],
  ['comparet',['CompareT',['http://docs.opencv.org/3.4.0/d2/d76/structcvflann_1_1Heap_1_1CompareT.html',1,'cvflann::Heap']]],
  ['complex',['Complex',['http://docs.opencv.org/3.4.0/da/df6/classcv_1_1Complex.html',1,'cv']]],
  ['complex',['complex',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01924.html',1,'std']]],
  ['complex_3c_20double_20_3e',['complex&lt; double &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01940.html',1,'std']]],
  ['complex_3c_20float_20_3e',['complex&lt; float &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01936.html',1,'std']]],
  ['complex_3c_20long_20double_20_3e',['complex&lt; long double &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01944.html',1,'std']]],
  ['compositeindex',['CompositeIndex',['http://docs.opencv.org/3.4.0/dc/d59/classcvflann_1_1CompositeIndex.html',1,'cvflann']]],
  ['compositeindexparams',['CompositeIndexParams',['http://docs.opencv.org/3.4.0/db/d3f/structcvflann_1_1CompositeIndexParams.html',1,'cvflann']]],
  ['compositeindexparams',['CompositeIndexParams',['http://docs.opencv.org/3.4.0/d5/d94/structcv_1_1flann_1_1CompositeIndexParams.html',1,'cv::flann']]],
  ['compressedrectilinearportraitprojector',['CompressedRectilinearPortraitProjector',['http://docs.opencv.org/3.4.0/d0/ded/structcv_1_1detail_1_1CompressedRectilinearPortraitProjector.html',1,'cv::detail']]],
  ['compressedrectilinearportraitwarper',['CompressedRectilinearPortraitWarper',['http://docs.opencv.org/3.4.0/dd/dc8/classcv_1_1detail_1_1CompressedRectilinearPortraitWarper.html',1,'cv::detail']]],
  ['compressedrectilinearportraitwarper',['CompressedRectilinearPortraitWarper',['http://docs.opencv.org/3.4.0/de/d9a/classcv_1_1CompressedRectilinearPortraitWarper.html',1,'cv']]],
  ['compressedrectilinearprojector',['CompressedRectilinearProjector',['http://docs.opencv.org/3.4.0/db/dbb/structcv_1_1detail_1_1CompressedRectilinearProjector.html',1,'cv::detail']]],
  ['compressedrectilinearwarper',['CompressedRectilinearWarper',['http://docs.opencv.org/3.4.0/dd/dbe/classcv_1_1detail_1_1CompressedRectilinearWarper.html',1,'cv::detail']]],
  ['compressedrectilinearwarper',['CompressedRectilinearWarper',['http://docs.opencv.org/3.4.0/d0/dd5/classcv_1_1CompressedRectilinearWarper.html',1,'cv']]],
  ['concatlayer',['ConcatLayer',['http://docs.opencv.org/3.4.0/da/d5c/classcv_1_1dnn_1_1ConcatLayer.html',1,'cv::dnn']]],
  ['cond_5fdealtor',['cond_dealtor',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10296.html',1,'__gnu_pbds::detail']]],
  ['cond_5fdtor',['cond_dtor',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10796.html',1,'__gnu_pbds::detail::ov_tree_map']]],
  ['condition_5fbase',['condition_base',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09604.html',1,'__gnu_cxx']]],
  ['condition_5fvariable',['condition_variable',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02056.html',1,'std']]],
  ['condition_5fvariable_5fany',['condition_variable_any',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02064.html',1,'std::_V2']]],
  ['config',['Config',['../classwpl_1_1_config.html',1,'wpl']]],
  ['config',['Config',['http://docs.opencv.org/3.4.0/d0/ded/structcv_1_1face_1_1FacemarkAAM_1_1Config.html',1,'cv::face::FacemarkAAM']]],
  ['conjgradsolver',['ConjGradSolver',['http://docs.opencv.org/3.4.0/d0/d21/classcv_1_1ConjGradSolver.html',1,'cv']]],
  ['consistentmosaicinpainter',['ConsistentMosaicInpainter',['http://docs.opencv.org/3.4.0/d9/dba/classcv_1_1videostab_1_1ConsistentMosaicInpainter.html',1,'cv::videostab']]],
  ['const_5fiterator',['const_iterator',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10852.html',1,'__gnu_pbds::detail::pat_trie_base::_Inode']]],
  ['const_5fiterator_5f',['const_iterator_',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a11012.html',1,'']]],
  ['const_5fmem_5ffun1_5fref_5ft',['const_mem_fun1_ref_t',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06608.html',1,'std']]],
  ['const_5fmem_5ffun1_5ft',['const_mem_fun1_t',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06600.html',1,'std']]],
  ['const_5fmem_5ffun_5fref_5ft',['const_mem_fun_ref_t',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06592.html',1,'std']]],
  ['const_5fmem_5ffun_5ft',['const_mem_fun_t',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06584.html',1,'std']]],
  ['constant_5fbinary_5ffun',['constant_binary_fun',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08140.html',1,'__gnu_cxx']]],
  ['constant_5fsize_5fblocks_5ftag',['constant_size_blocks_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08692.html',1,'__gnu_parallel']]],
  ['constant_5funary_5ffun',['constant_unary_fun',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08136.html',1,'__gnu_cxx']]],
  ['constant_5fvoid_5ffun',['constant_void_fun',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08132.html',1,'__gnu_cxx']]],
  ['constantptr',['ConstantPtr',['http://docs.opencv.org/3.4.0/d5/db7/structcv_1_1cudev_1_1ConstantPtr.html',1,'cv::cudev']]],
  ['constantptrsz',['ConstantPtrSz',['http://docs.opencv.org/3.4.0/d2/df7/structcv_1_1cudev_1_1ConstantPtrSz.html',1,'cv::cudev']]],
  ['container_5fbase_5fdispatch',['container_base_dispatch',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10276.html',1,'__gnu_pbds::detail']]],
  ['container_5fbase_5fdispatch_3c_20_5fvtp_2c_20cmp_5ffn_2c_20_5falloc_2c_20binary_5fheap_5ftag_2c_20null_5ftype_20_3e',['container_base_dispatch&lt; _VTp, Cmp_Fn, _Alloc, binary_heap_tag, null_type &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10368.html',1,'__gnu_pbds::detail']]],
  ['container_5fbase_5fdispatch_3c_20_5fvtp_2c_20cmp_5ffn_2c_20_5falloc_2c_20binomial_5fheap_5ftag_2c_20null_5ftype_20_3e',['container_base_dispatch&lt; _VTp, Cmp_Fn, _Alloc, binomial_heap_tag, null_type &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10360.html',1,'__gnu_pbds::detail']]],
  ['container_5fbase_5fdispatch_3c_20_5fvtp_2c_20cmp_5ffn_2c_20_5falloc_2c_20pairing_5fheap_5ftag_2c_20null_5ftype_20_3e',['container_base_dispatch&lt; _VTp, Cmp_Fn, _Alloc, pairing_heap_tag, null_type &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10356.html',1,'__gnu_pbds::detail']]],
  ['container_5fbase_5fdispatch_3c_20_5fvtp_2c_20cmp_5ffn_2c_20_5falloc_2c_20rc_5fbinomial_5fheap_5ftag_2c_20null_5ftype_20_3e',['container_base_dispatch&lt; _VTp, Cmp_Fn, _Alloc, rc_binomial_heap_tag, null_type &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10364.html',1,'__gnu_pbds::detail']]],
  ['container_5fbase_5fdispatch_3c_20_5fvtp_2c_20cmp_5ffn_2c_20_5falloc_2c_20thin_5fheap_5ftag_2c_20null_5ftype_20_3e',['container_base_dispatch&lt; _VTp, Cmp_Fn, _Alloc, thin_heap_tag, null_type &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10372.html',1,'__gnu_pbds::detail']]],
  ['container_5fbase_5fdispatch_3c_20key_2c_20mapped_2c_20_5falloc_2c_20cc_5fhash_5ftag_2c_20policy_5ftl_20_3e',['container_base_dispatch&lt; Key, Mapped, _Alloc, cc_hash_tag, Policy_Tl &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10340.html',1,'__gnu_pbds::detail']]],
  ['container_5fbase_5fdispatch_3c_20key_2c_20mapped_2c_20_5falloc_2c_20gp_5fhash_5ftag_2c_20policy_5ftl_20_3e',['container_base_dispatch&lt; Key, Mapped, _Alloc, gp_hash_tag, Policy_Tl &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10348.html',1,'__gnu_pbds::detail']]],
  ['container_5fbase_5fdispatch_3c_20key_2c_20mapped_2c_20_5falloc_2c_20list_5fupdate_5ftag_2c_20policy_5ftl_20_3e',['container_base_dispatch&lt; Key, Mapped, _Alloc, list_update_tag, Policy_Tl &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10300.html',1,'__gnu_pbds::detail']]],
  ['container_5fbase_5fdispatch_3c_20key_2c_20mapped_2c_20_5falloc_2c_20ov_5ftree_5ftag_2c_20policy_5ftl_20_3e',['container_base_dispatch&lt; Key, Mapped, _Alloc, ov_tree_tag, Policy_Tl &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10332.html',1,'__gnu_pbds::detail']]],
  ['container_5fbase_5fdispatch_3c_20key_2c_20mapped_2c_20_5falloc_2c_20pat_5ftrie_5ftag_2c_20policy_5ftl_20_3e',['container_base_dispatch&lt; Key, Mapped, _Alloc, pat_trie_tag, Policy_Tl &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10308.html',1,'__gnu_pbds::detail']]],
  ['container_5fbase_5fdispatch_3c_20key_2c_20mapped_2c_20_5falloc_2c_20rb_5ftree_5ftag_2c_20policy_5ftl_20_3e',['container_base_dispatch&lt; Key, Mapped, _Alloc, rb_tree_tag, Policy_Tl &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10316.html',1,'__gnu_pbds::detail']]],
  ['container_5fbase_5fdispatch_3c_20key_2c_20mapped_2c_20_5falloc_2c_20splay_5ftree_5ftag_2c_20policy_5ftl_20_3e',['container_base_dispatch&lt; Key, Mapped, _Alloc, splay_tree_tag, Policy_Tl &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10324.html',1,'__gnu_pbds::detail']]],
  ['container_5fbase_5fdispatch_3c_20key_2c_20null_5ftype_2c_20_5falloc_2c_20cc_5fhash_5ftag_2c_20policy_5ftl_20_3e',['container_base_dispatch&lt; Key, null_type, _Alloc, cc_hash_tag, Policy_Tl &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10344.html',1,'__gnu_pbds::detail']]],
  ['container_5fbase_5fdispatch_3c_20key_2c_20null_5ftype_2c_20_5falloc_2c_20gp_5fhash_5ftag_2c_20policy_5ftl_20_3e',['container_base_dispatch&lt; Key, null_type, _Alloc, gp_hash_tag, Policy_Tl &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10352.html',1,'__gnu_pbds::detail']]],
  ['container_5fbase_5fdispatch_3c_20key_2c_20null_5ftype_2c_20_5falloc_2c_20list_5fupdate_5ftag_2c_20policy_5ftl_20_3e',['container_base_dispatch&lt; Key, null_type, _Alloc, list_update_tag, Policy_Tl &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10304.html',1,'__gnu_pbds::detail']]],
  ['container_5fbase_5fdispatch_3c_20key_2c_20null_5ftype_2c_20_5falloc_2c_20ov_5ftree_5ftag_2c_20policy_5ftl_20_3e',['container_base_dispatch&lt; Key, null_type, _Alloc, ov_tree_tag, Policy_Tl &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10336.html',1,'__gnu_pbds::detail']]],
  ['container_5fbase_5fdispatch_3c_20key_2c_20null_5ftype_2c_20_5falloc_2c_20pat_5ftrie_5ftag_2c_20policy_5ftl_20_3e',['container_base_dispatch&lt; Key, null_type, _Alloc, pat_trie_tag, Policy_Tl &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10312.html',1,'__gnu_pbds::detail']]],
  ['container_5fbase_5fdispatch_3c_20key_2c_20null_5ftype_2c_20_5falloc_2c_20rb_5ftree_5ftag_2c_20policy_5ftl_20_3e',['container_base_dispatch&lt; Key, null_type, _Alloc, rb_tree_tag, Policy_Tl &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10320.html',1,'__gnu_pbds::detail']]],
  ['container_5fbase_5fdispatch_3c_20key_2c_20null_5ftype_2c_20_5falloc_2c_20splay_5ftree_5ftag_2c_20policy_5ftl_20_3e',['container_base_dispatch&lt; Key, null_type, _Alloc, splay_tree_tag, Policy_Tl &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10328.html',1,'__gnu_pbds::detail']]],
  ['container_5ferror',['container_error',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10048.html',1,'__gnu_pbds']]],
  ['container_5ftag',['container_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10128.html',1,'__gnu_pbds']]],
  ['container_5ftraits',['container_traits',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10272.html',1,'__gnu_pbds']]],
  ['container_5ftraits_5fbase',['container_traits_base',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10220.html',1,'__gnu_pbds']]],
  ['container_5ftraits_5fbase_3c_20binary_5fheap_5ftag_20_3e',['container_traits_base&lt; binary_heap_tag &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10268.html',1,'__gnu_pbds']]],
  ['container_5ftraits_5fbase_3c_20binomial_5fheap_5ftag_20_3e',['container_traits_base&lt; binomial_heap_tag &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10260.html',1,'__gnu_pbds']]],
  ['container_5ftraits_5fbase_3c_20cc_5fhash_5ftag_20_3e',['container_traits_base&lt; cc_hash_tag &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10224.html',1,'__gnu_pbds']]],
  ['container_5ftraits_5fbase_3c_20cntnr_3a_3acontainer_5fcategory_20_3e',['container_traits_base&lt; Cntnr::container_category &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10220.html',1,'']]],
  ['container_5ftraits_5fbase_3c_20gp_5fhash_5ftag_20_3e',['container_traits_base&lt; gp_hash_tag &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10228.html',1,'__gnu_pbds']]],
  ['container_5ftraits_5fbase_3c_20list_5fupdate_5ftag_20_3e',['container_traits_base&lt; list_update_tag &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10248.html',1,'__gnu_pbds']]],
  ['container_5ftraits_5fbase_3c_20ov_5ftree_5ftag_20_3e',['container_traits_base&lt; ov_tree_tag &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10240.html',1,'__gnu_pbds']]],
  ['container_5ftraits_5fbase_3c_20pairing_5fheap_5ftag_20_3e',['container_traits_base&lt; pairing_heap_tag &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10252.html',1,'__gnu_pbds']]],
  ['container_5ftraits_5fbase_3c_20pat_5ftrie_5ftag_20_3e',['container_traits_base&lt; pat_trie_tag &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10244.html',1,'__gnu_pbds']]],
  ['container_5ftraits_5fbase_3c_20rb_5ftree_5ftag_20_3e',['container_traits_base&lt; rb_tree_tag &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10232.html',1,'__gnu_pbds']]],
  ['container_5ftraits_5fbase_3c_20rc_5fbinomial_5fheap_5ftag_20_3e',['container_traits_base&lt; rc_binomial_heap_tag &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10264.html',1,'__gnu_pbds']]],
  ['container_5ftraits_5fbase_3c_20splay_5ftree_5ftag_20_3e',['container_traits_base&lt; splay_tree_tag &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10236.html',1,'__gnu_pbds']]],
  ['container_5ftraits_5fbase_3c_20thin_5fheap_5ftag_20_3e',['container_traits_base&lt; thin_heap_tag &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10256.html',1,'__gnu_pbds']]],
  ['context',['Context',['http://docs.opencv.org/3.4.0/d1/d45/classcv_1_1ocl_1_1Context.html',1,'cv::ocl']]],
  ['contourfitting',['ContourFitting',['http://docs.opencv.org/3.4.0/d5/d72/classcv_1_1ximgproc_1_1ContourFitting.html',1,'cv::ximgproc']]],
  ['convert_3c_20cv_3a_3amat_20_3e',['convert&lt; cv::Mat &gt;',['../struct_y_a_m_l_1_1convert_3_01cv_1_1_mat_01_4.html',1,'YAML']]],
  ['convert_3c_20cv_3a_3apoint3d_20_3e',['convert&lt; cv::Point3d &gt;',['../struct_y_a_m_l_1_1convert_3_01cv_1_1_point3d_01_4.html',1,'YAML']]],
  ['convert_3c_20cv_3a_3avec3d_20_3e',['convert&lt; cv::Vec3d &gt;',['../struct_y_a_m_l_1_1convert_3_01cv_1_1_vec3d_01_4.html',1,'YAML']]],
  ['converttuple',['ConvertTuple',['http://docs.opencv.org/3.4.0/d9/d6a/structcv_1_1cudev_1_1ConvertTuple.html',1,'cv::cudev']]],
  ['convolution',['Convolution',['http://docs.opencv.org/3.4.0/d4/d25/classcv_1_1cuda_1_1Convolution.html',1,'cv::cuda']]],
  ['convolutionlayer',['ConvolutionLayer',['http://docs.opencv.org/3.4.0/d5/dcf/classcv_1_1dnn_1_1ConvolutionLayer.html',1,'cv::dnn']]],
  ['cornernesscriteria',['CornernessCriteria',['http://docs.opencv.org/3.4.0/dd/d63/classcv_1_1cuda_1_1CornernessCriteria.html',1,'cv::cuda']]],
  ['cornersdetector',['CornersDetector',['http://docs.opencv.org/3.4.0/de/d95/classcv_1_1cuda_1_1CornersDetector.html',1,'cv::cuda']]],
  ['cos_5ffunc',['cos_func',['http://docs.opencv.org/3.4.0/d6/dfb/structcv_1_1cudev_1_1cos__func.html',1,'cv::cudev']]],
  ['cos_5ffunc_3c_20double_20_3e',['cos_func&lt; double &gt;',['http://docs.opencv.org/3.4.0/db/d23/structcv_1_1cudev_1_1cos__func_3_01double_01_4.html',1,'cv::cudev']]],
  ['cos_5ffunc_3c_20float_20_3e',['cos_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/dd/d7a/structcv_1_1cudev_1_1cos__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['cos_5ffunc_3c_20schar_20_3e',['cos_func&lt; schar &gt;',['http://docs.opencv.org/3.4.0/dc/d25/structcv_1_1cudev_1_1cos__func_3_01schar_01_4.html',1,'cv::cudev']]],
  ['cos_5ffunc_3c_20short_20_3e',['cos_func&lt; short &gt;',['http://docs.opencv.org/3.4.0/d7/d03/structcv_1_1cudev_1_1cos__func_3_01short_01_4.html',1,'cv::cudev']]],
  ['cos_5ffunc_3c_20uchar_20_3e',['cos_func&lt; uchar &gt;',['http://docs.opencv.org/3.4.0/dd/d3d/structcv_1_1cudev_1_1cos__func_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['cos_5ffunc_3c_20uint_20_3e',['cos_func&lt; uint &gt;',['http://docs.opencv.org/3.4.0/da/dc1/structcv_1_1cudev_1_1cos__func_3_01uint_01_4.html',1,'cv::cudev']]],
  ['cos_5ffunc_3c_20ushort_20_3e',['cos_func&lt; ushort &gt;',['http://docs.opencv.org/3.4.0/df/d35/structcv_1_1cudev_1_1cos__func_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['cosh_5ffunc',['cosh_func',['http://docs.opencv.org/3.4.0/dc/d8a/structcv_1_1cudev_1_1cosh__func.html',1,'cv::cudev']]],
  ['cosh_5ffunc_3c_20double_20_3e',['cosh_func&lt; double &gt;',['http://docs.opencv.org/3.4.0/d5/d3a/structcv_1_1cudev_1_1cosh__func_3_01double_01_4.html',1,'cv::cudev']]],
  ['cosh_5ffunc_3c_20float_20_3e',['cosh_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/db/d8d/structcv_1_1cudev_1_1cosh__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['cosh_5ffunc_3c_20schar_20_3e',['cosh_func&lt; schar &gt;',['http://docs.opencv.org/3.4.0/df/dd8/structcv_1_1cudev_1_1cosh__func_3_01schar_01_4.html',1,'cv::cudev']]],
  ['cosh_5ffunc_3c_20short_20_3e',['cosh_func&lt; short &gt;',['http://docs.opencv.org/3.4.0/dc/d8a/structcv_1_1cudev_1_1cosh__func_3_01short_01_4.html',1,'cv::cudev']]],
  ['cosh_5ffunc_3c_20uchar_20_3e',['cosh_func&lt; uchar &gt;',['http://docs.opencv.org/3.4.0/de/d73/structcv_1_1cudev_1_1cosh__func_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['cosh_5ffunc_3c_20uint_20_3e',['cosh_func&lt; uint &gt;',['http://docs.opencv.org/3.4.0/d5/ddd/structcv_1_1cudev_1_1cosh__func_3_01uint_01_4.html',1,'cv::cudev']]],
  ['cosh_5ffunc_3c_20ushort_20_3e',['cosh_func&lt; ushort &gt;',['http://docs.opencv.org/3.4.0/d2/dd3/structcv_1_1cudev_1_1cosh__func_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['countnonzeroexprbody',['CountNonZeroExprBody',['http://docs.opencv.org/3.4.0/dd/d49/structcv_1_1cudev_1_1CountNonZeroExprBody.html',1,'cv::cudev']]],
  ['cparams',['CParams',['http://docs.opencv.org/3.4.0/d8/dd8/structcv_1_1face_1_1CParams.html',1,'cv::face']]],
  ['creatornotfound',['CreatorNotFound',['http://docs.opencv.org/3.4.0/db/d35/classcvflann_1_1CreatorNotFound.html',1,'cvflann']]],
  ['croplayer',['CropLayer',['http://docs.opencv.org/3.4.0/d7/d86/classcv_1_1dnn_1_1CropLayer.html',1,'cv::dnn']]],
  ['ct_5fassert_5ffailure',['CT_ASSERT_FAILURE',['http://docs.opencv.org/3.4.0/da/d73/structNcvCTprep_1_1CT__ASSERT__FAILURE.html',1,'NcvCTprep']]],
  ['ct_5fassert_5ffailure_3c_20true_20_3e',['CT_ASSERT_FAILURE&lt; true &gt;',['http://docs.opencv.org/3.4.0/dc/dcf/structNcvCTprep_1_1CT__ASSERT__FAILURE_3_01true_01_4.html',1,'NcvCTprep']]],
  ['ctype',['ctype',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a04992.html',1,'std']]],
  ['ctype_3c_20char_20_3e',['ctype&lt; char &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a04996.html',1,'std']]],
  ['ctype_3c_20wchar_5ft_20_3e',['ctype&lt; wchar_t &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05000.html',1,'std']]],
  ['ctype_5fbase',['ctype_base',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07436.html',1,'std']]],
  ['ctype_5fbyname',['ctype_byname',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05004.html',1,'std']]],
  ['ctype_5fbyname_3c_20char_20_3e',['ctype_byname&lt; char &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05008.html',1,'std']]],
  ['cubicinterptr',['CubicInterPtr',['http://docs.opencv.org/3.4.0/d3/def/structcv_1_1cudev_1_1CubicInterPtr.html',1,'cv::cudev']]],
  ['cubicinterptrsz',['CubicInterPtrSz',['http://docs.opencv.org/3.4.0/d2/d00/structcv_1_1cudev_1_1CubicInterPtrSz.html',1,'cv::cudev']]],
  ['custompattern',['CustomPattern',['http://docs.opencv.org/3.4.0/d3/d3e/classcv_1_1ccalib_1_1CustomPattern.html',1,'cv::ccalib']]],
  ['cv16suf',['Cv16suf',['http://docs.opencv.org/3.4.0/dd/d0f/unionCv16suf.html',1,'']]],
  ['cv32suf',['Cv32suf',['http://docs.opencv.org/3.4.0/d9/df3/unionCv32suf.html',1,'']]],
  ['cv64suf',['Cv64suf',['http://docs.opencv.org/3.4.0/de/d55/unionCv64suf.html',1,'']]],
  ['cvabstractcamera',['CvAbstractCamera',['http://docs.opencv.org/3.4.0/d0/de8/interfaceCvAbstractCamera.html',1,'']]],
  ['cvattrlist',['CvAttrList',['http://docs.opencv.org/3.4.0/df/dea/structCvAttrList.html',1,'']]],
  ['cvavgcomp',['CvAvgComp',['http://docs.opencv.org/3.4.0/d5/d8a/structCvAvgComp.html',1,'']]],
  ['cvbox2d',['CvBox2D',['http://docs.opencv.org/3.4.0/da/d13/structCvBox2D.html',1,'']]],
  ['cvchain',['CvChain',['http://docs.opencv.org/3.4.0/d9/d08/structCvChain.html',1,'']]],
  ['cvchainptreader',['CvChainPtReader',['http://docs.opencv.org/3.4.0/d9/db9/structCvChainPtReader.html',1,'']]],
  ['cvconnectedcomp',['CvConnectedComp',['http://docs.opencv.org/3.4.0/d3/df6/structCvConnectedComp.html',1,'']]],
  ['cvcontour',['CvContour',['http://docs.opencv.org/3.4.0/dd/deb/structCvContour.html',1,'']]],
  ['cvconvexitydefect',['CvConvexityDefect',['http://docs.opencv.org/3.4.0/d7/dec/structCvConvexityDefect.html',1,'']]],
  ['cvfeatureevaluator',['CvFeatureEvaluator',['http://docs.opencv.org/3.4.0/d0/d0b/classcv_1_1CvFeatureEvaluator.html',1,'cv']]],
  ['cvfeatureparams',['CvFeatureParams',['http://docs.opencv.org/3.4.0/db/dfc/classcv_1_1CvFeatureParams.html',1,'cv']]],
  ['cvfilenode',['CvFileNode',['http://docs.opencv.org/3.4.0/dc/d73/structCvFileNode.html',1,'']]],
  ['cvfont',['CvFont',['http://docs.opencv.org/3.4.0/db/d2b/structCvFont.html',1,'']]],
  ['cvgraph',['CvGraph',['http://docs.opencv.org/3.4.0/db/da6/structCvGraph.html',1,'']]],
  ['cvgraphedge',['CvGraphEdge',['http://docs.opencv.org/3.4.0/d0/db1/structCvGraphEdge.html',1,'']]],
  ['cvgraphscanner',['CvGraphScanner',['http://docs.opencv.org/3.4.0/d6/d89/structCvGraphScanner.html',1,'']]],
  ['cvgraphvtx',['CvGraphVtx',['http://docs.opencv.org/3.4.0/d3/d89/structCvGraphVtx.html',1,'']]],
  ['cvgraphvtx2d',['CvGraphVtx2D',['http://docs.opencv.org/3.4.0/df/d9e/structCvGraphVtx2D.html',1,'']]],
  ['cvhaarclassifier',['CvHaarClassifier',['http://docs.opencv.org/3.4.0/d5/de9/structCvHaarClassifier.html',1,'']]],
  ['cvhaarclassifiercascade',['CvHaarClassifierCascade',['http://docs.opencv.org/3.4.0/d6/d3d/structCvHaarClassifierCascade.html',1,'']]],
  ['cvhaarevaluator',['CvHaarEvaluator',['http://docs.opencv.org/3.4.0/db/d35/classcv_1_1CvHaarEvaluator.html',1,'cv']]],
  ['cvhaarfeature',['CvHaarFeature',['http://docs.opencv.org/3.4.0/d7/d82/structCvHaarFeature.html',1,'']]],
  ['cvhaarfeatureparams',['CvHaarFeatureParams',['http://docs.opencv.org/3.4.0/d9/d90/classcv_1_1CvHaarFeatureParams.html',1,'cv']]],
  ['cvhaarstageclassifier',['CvHaarStageClassifier',['http://docs.opencv.org/3.4.0/db/df3/structCvHaarStageClassifier.html',1,'']]],
  ['cvhaldft',['cvhalDFT',['http://docs.opencv.org/3.4.0/de/d27/structcvhalDFT.html',1,'']]],
  ['cvhalfilter2d',['cvhalFilter2D',['http://docs.opencv.org/3.4.0/d2/da8/structcvhalFilter2D.html',1,'']]],
  ['cvhistogram',['CvHistogram',['http://docs.opencv.org/3.4.0/df/df3/structCvHistogram.html',1,'']]],
  ['cvhogevaluator',['CvHOGEvaluator',['http://docs.opencv.org/3.4.0/d2/dd9/classcv_1_1CvHOGEvaluator.html',1,'cv']]],
  ['cvhogfeatureparams',['CvHOGFeatureParams',['http://docs.opencv.org/3.4.0/d4/d4a/structcv_1_1CvHOGFeatureParams.html',1,'cv']]],
  ['cvhumoments',['CvHuMoments',['http://docs.opencv.org/3.4.0/dd/d46/structCvHuMoments.html',1,'']]],
  ['cvkalman',['CvKalman',['http://docs.opencv.org/3.4.0/d5/de6/structCvKalman.html',1,'']]],
  ['cvlbpevaluator',['CvLBPEvaluator',['http://docs.opencv.org/3.4.0/d1/d26/classcv_1_1CvLBPEvaluator.html',1,'cv']]],
  ['cvlbpfeatureparams',['CvLBPFeatureParams',['http://docs.opencv.org/3.4.0/d2/d3c/structcv_1_1CvLBPFeatureParams.html',1,'cv']]],
  ['cvlevmarq',['CvLevMarq',['http://docs.opencv.org/3.4.0/d2/d70/classCvLevMarq.html',1,'']]],
  ['cvlineiterator',['CvLineIterator',['http://docs.opencv.org/3.4.0/d9/d22/structCvLineIterator.html',1,'']]],
  ['cvmat',['CvMat',['http://docs.opencv.org/3.4.0/d3/db2/structCvMat.html',1,'']]],
  ['cvmatnd',['CvMatND',['http://docs.opencv.org/3.4.0/d4/d4c/structCvMatND.html',1,'']]],
  ['cvmemblock',['CvMemBlock',['http://docs.opencv.org/3.4.0/dd/d24/structCvMemBlock.html',1,'']]],
  ['cvmemstorage',['CvMemStorage',['http://docs.opencv.org/3.4.0/db/d76/structCvMemStorage.html',1,'']]],
  ['cvmemstoragepos',['CvMemStoragePos',['http://docs.opencv.org/3.4.0/da/d36/structCvMemStoragePos.html',1,'']]],
  ['cvmoduleinfo',['CvModuleInfo',['http://docs.opencv.org/3.4.0/df/db0/structCvModuleInfo.html',1,'']]],
  ['cvmoments',['CvMoments',['http://docs.opencv.org/3.4.0/d6/dc6/structCvMoments.html',1,'']]],
  ['cvnarrayiterator',['CvNArrayIterator',['http://docs.opencv.org/3.4.0/d3/da5/structCvNArrayIterator.html',1,'']]],
  ['cvparams',['CvParams',['http://docs.opencv.org/3.4.0/db/d7c/classcv_1_1CvParams.html',1,'cv']]],
  ['cvphotocamera',['CvPhotoCamera',['http://docs.opencv.org/3.4.0/d4/d1d/interfaceCvPhotoCamera.html',1,'']]],
  ['cvphotocameradelegate_2dp_2dp',['CvPhotoCameraDelegate-p-p',['http://docs.opencv.org/3.4.0/d7/d2f/protocolCvPhotoCameraDelegate_01-p.html',1,'']]],
  ['cvpluginfuncinfo',['CvPluginFuncInfo',['http://docs.opencv.org/3.4.0/df/d6a/structCvPluginFuncInfo.html',1,'']]],
  ['cvpoint',['CvPoint',['http://docs.opencv.org/3.4.0/dc/dd1/structCvPoint.html',1,'']]],
  ['cvpoint2d32f',['CvPoint2D32f',['http://docs.opencv.org/3.4.0/da/db6/structCvPoint2D32f.html',1,'']]],
  ['cvpoint2d64f',['CvPoint2D64f',['http://docs.opencv.org/3.4.0/df/d5d/structCvPoint2D64f.html',1,'']]],
  ['cvpoint3d32f',['CvPoint3D32f',['http://docs.opencv.org/3.4.0/d7/db2/structCvPoint3D32f.html',1,'']]],
  ['cvpoint3d64f',['CvPoint3D64f',['http://docs.opencv.org/3.4.0/d4/da0/structCvPoint3D64f.html',1,'']]],
  ['cvrect',['CvRect',['http://docs.opencv.org/3.4.0/d0/d76/structCvRect.html',1,'']]],
  ['cvscalar',['CvScalar',['http://docs.opencv.org/3.4.0/d6/db3/structCvScalar.html',1,'']]],
  ['cvseq',['CvSeq',['http://docs.opencv.org/3.4.0/d6/dde/structCvSeq.html',1,'']]],
  ['cvseqblock',['CvSeqBlock',['http://docs.opencv.org/3.4.0/dd/de2/structCvSeqBlock.html',1,'']]],
  ['cvseqreader',['CvSeqReader',['http://docs.opencv.org/3.4.0/d8/de9/structCvSeqReader.html',1,'']]],
  ['cvseqwriter',['CvSeqWriter',['http://docs.opencv.org/3.4.0/d6/d41/structCvSeqWriter.html',1,'']]],
  ['cvset',['CvSet',['http://docs.opencv.org/3.4.0/d8/dad/structCvSet.html',1,'']]],
  ['cvsetelem',['CvSetElem',['http://docs.opencv.org/3.4.0/d0/df0/structCvSetElem.html',1,'']]],
  ['cvsize',['CvSize',['http://docs.opencv.org/3.4.0/da/dcb/structCvSize.html',1,'']]],
  ['cvsize2d32f',['CvSize2D32f',['http://docs.opencv.org/3.4.0/dd/d16/structCvSize2D32f.html',1,'']]],
  ['cvslice',['CvSlice',['http://docs.opencv.org/3.4.0/d5/d3e/structCvSlice.html',1,'']]],
  ['cvsparsemat',['CvSparseMat',['http://docs.opencv.org/3.4.0/dd/d4b/structCvSparseMat.html',1,'']]],
  ['cvsparsematiterator',['CvSparseMatIterator',['http://docs.opencv.org/3.4.0/d8/d39/structCvSparseMatIterator.html',1,'']]],
  ['cvsparsenode',['CvSparseNode',['http://docs.opencv.org/3.4.0/df/d7a/structCvSparseNode.html',1,'']]],
  ['cvstereobmstate',['CvStereoBMState',['http://docs.opencv.org/3.4.0/dd/d3f/structCvStereoBMState.html',1,'']]],
  ['cvstring',['CvString',['http://docs.opencv.org/3.4.0/d7/d16/structCvString.html',1,'']]],
  ['cvstringhashnode',['CvStringHashNode',['http://docs.opencv.org/3.4.0/da/dbd/structCvStringHashNode.html',1,'']]],
  ['cvtermcriteria',['CvTermCriteria',['http://docs.opencv.org/3.4.0/d8/d2b/structCvTermCriteria.html',1,'']]],
  ['cvtreenodeiterator',['CvTreeNodeIterator',['http://docs.opencv.org/3.4.0/d7/d14/structCvTreeNodeIterator.html',1,'']]],
  ['cvtype',['CvType',['http://docs.opencv.org/3.4.0/d1/def/structcv_1_1flann_1_1CvType.html',1,'cv::flann']]],
  ['cvtype',['CvType',['http://docs.opencv.org/3.4.0/d3/dba/structCvType.html',1,'']]],
  ['cvtype_3c_20char_20_3e',['CvType&lt; char &gt;',['http://docs.opencv.org/3.4.0/dc/d89/structcv_1_1flann_1_1CvType_3_01char_01_4.html',1,'cv::flann']]],
  ['cvtype_3c_20double_20_3e',['CvType&lt; double &gt;',['http://docs.opencv.org/3.4.0/dc/d69/structcv_1_1flann_1_1CvType_3_01double_01_4.html',1,'cv::flann']]],
  ['cvtype_3c_20float_20_3e',['CvType&lt; float &gt;',['http://docs.opencv.org/3.4.0/dc/dd6/structcv_1_1flann_1_1CvType_3_01float_01_4.html',1,'cv::flann']]],
  ['cvtype_3c_20short_20_3e',['CvType&lt; short &gt;',['http://docs.opencv.org/3.4.0/d2/def/structcv_1_1flann_1_1CvType_3_01short_01_4.html',1,'cv::flann']]],
  ['cvtype_3c_20unsigned_20char_20_3e',['CvType&lt; unsigned char &gt;',['http://docs.opencv.org/3.4.0/d7/da5/structcv_1_1flann_1_1CvType_3_01unsigned_01char_01_4.html',1,'cv::flann']]],
  ['cvtype_3c_20unsigned_20short_20_3e',['CvType&lt; unsigned short &gt;',['http://docs.opencv.org/3.4.0/d9/d57/structcv_1_1flann_1_1CvType_3_01unsigned_01short_01_4.html',1,'cv::flann']]],
  ['cvtypeinfo',['CvTypeInfo',['http://docs.opencv.org/3.4.0/d7/d7c/structCvTypeInfo.html',1,'']]],
  ['cvvideocamera',['CvVideoCamera',['http://docs.opencv.org/3.4.0/db/da9/interfaceCvVideoCamera.html',1,'']]],
  ['cvvideocameradelegate_2dp_2dp',['CvVideoCameraDelegate-p-p',['http://docs.opencv.org/3.4.0/d3/d54/protocolCvVideoCameraDelegate_01-p.html',1,'']]],
  ['cylindricalportraitprojector',['CylindricalPortraitProjector',['http://docs.opencv.org/3.4.0/df/d3f/structcv_1_1detail_1_1CylindricalPortraitProjector.html',1,'cv::detail']]],
  ['cylindricalportraitwarper',['CylindricalPortraitWarper',['http://docs.opencv.org/3.4.0/dd/d19/classcv_1_1detail_1_1CylindricalPortraitWarper.html',1,'cv::detail']]],
  ['cylindricalprojector',['CylindricalProjector',['http://docs.opencv.org/3.4.0/dd/d96/structcv_1_1detail_1_1CylindricalProjector.html',1,'cv::detail']]],
  ['cylindricalwarper',['CylindricalWarper',['http://docs.opencv.org/3.4.0/d7/df6/classcv_1_1CylindricalWarper.html',1,'cv']]],
  ['cylindricalwarper',['CylindricalWarper',['http://docs.opencv.org/3.4.0/d3/dd6/classcv_1_1detail_1_1CylindricalWarper.html',1,'cv::detail']]],
  ['cylindricalwarpergpu',['CylindricalWarperGpu',['http://docs.opencv.org/3.4.0/d9/dbd/classcv_1_1detail_1_1CylindricalWarperGpu.html',1,'cv::detail']]]
];
