var searchData=
[
  ['radialvariancehash',['RadialVarianceHash',['http://docs.opencv.org/3.4.0/d5/d97/classcv_1_1img__hash_1_1RadialVarianceHash.html',1,'cv::img_hash']]],
  ['radiusresultset',['RadiusResultSet',['http://docs.opencv.org/3.4.0/d2/d69/classcvflann_1_1RadiusResultSet.html',1,'cvflann']]],
  ['radiusuniqueresultset',['RadiusUniqueResultSet',['http://docs.opencv.org/3.4.0/d8/d4a/classcvflann_1_1RadiusUniqueResultSet.html',1,'cvflann']]],
  ['random_5faccess_5fiterator_5ftag',['random_access_iterator_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06668.html',1,'std']]],
  ['random_5fcondition',['random_condition',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09628.html',1,'__gnu_cxx']]],
  ['random_5fdevice',['random_device',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05424.html',1,'std']]],
  ['randompatterncornerfinder',['RandomPatternCornerFinder',['http://docs.opencv.org/3.4.0/df/d8d/classcv_1_1randpattern_1_1RandomPatternCornerFinder.html',1,'cv::randpattern']]],
  ['randompatterngenerator',['RandomPatternGenerator',['http://docs.opencv.org/3.4.0/d7/d43/classcv_1_1randpattern_1_1RandomPatternGenerator.html',1,'cv::randpattern']]],
  ['range',['Range',['http://docs.opencv.org/3.4.0/da/d35/classcv_1_1Range.html',1,'cv']]],
  ['range_5ferror',['range_error',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02924.html',1,'std']]],
  ['range_5finvalidation_5fguarantee',['range_invalidation_guarantee',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10124.html',1,'__gnu_pbds']]],
  ['ranged_5fhash_5ffn',['ranged_hash_fn',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10668.html',1,'__gnu_pbds::detail']]],
  ['ranged_5fhash_5ffn_3c_20key_2c_20hash_5ffn_2c_20_5falloc_2c_20comb_5fhash_5ffn_2c_20false_20_3e',['ranged_hash_fn&lt; Key, Hash_Fn, _Alloc, Comb_Hash_Fn, false &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10672.html',1,'__gnu_pbds::detail']]],
  ['ranged_5fhash_5ffn_3c_20key_2c_20hash_5ffn_2c_20_5falloc_2c_20comb_5fhash_5ffn_2c_20true_20_3e',['ranged_hash_fn&lt; Key, Hash_Fn, _Alloc, Comb_Hash_Fn, true &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10676.html',1,'__gnu_pbds::detail']]],
  ['ranged_5fhash_5ffn_3c_20key_2c_20null_5ftype_2c_20_5falloc_2c_20comb_5fhash_5ffn_2c_20false_20_3e',['ranged_hash_fn&lt; Key, null_type, _Alloc, Comb_Hash_Fn, false &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10680.html',1,'__gnu_pbds::detail']]],
  ['ranged_5fhash_5ffn_3c_20key_2c_20null_5ftype_2c_20_5falloc_2c_20comb_5fhash_5ffn_2c_20true_20_3e',['ranged_hash_fn&lt; Key, null_type, _Alloc, Comb_Hash_Fn, true &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10684.html',1,'__gnu_pbds::detail']]],
  ['ranged_5fprobe_5ffn',['ranged_probe_fn',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10688.html',1,'__gnu_pbds::detail']]],
  ['ranged_5fprobe_5ffn_3c_20key_2c_20hash_5ffn_2c_20_5falloc_2c_20comb_5fprobe_5ffn_2c_20probe_5ffn_2c_20false_20_3e',['ranged_probe_fn&lt; Key, Hash_Fn, _Alloc, Comb_Probe_Fn, Probe_Fn, false &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10692.html',1,'__gnu_pbds::detail']]],
  ['ranged_5fprobe_5ffn_3c_20key_2c_20hash_5ffn_2c_20_5falloc_2c_20comb_5fprobe_5ffn_2c_20probe_5ffn_2c_20true_20_3e',['ranged_probe_fn&lt; Key, Hash_Fn, _Alloc, Comb_Probe_Fn, Probe_Fn, true &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10696.html',1,'__gnu_pbds::detail']]],
  ['ranged_5fprobe_5ffn_3c_20key_2c_20null_5ftype_2c_20_5falloc_2c_20comb_5fprobe_5ffn_2c_20null_5ftype_2c_20false_20_3e',['ranged_probe_fn&lt; Key, null_type, _Alloc, Comb_Probe_Fn, null_type, false &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10700.html',1,'__gnu_pbds::detail']]],
  ['ransacparams',['RansacParams',['http://docs.opencv.org/3.4.0/da/dc7/structcv_1_1videostab_1_1RansacParams.html',1,'cv::videostab']]],
  ['ratio',['ratio',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02828.html',1,'std']]],
  ['ratio_5fequal',['ratio_equal',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02840.html',1,'std']]],
  ['ratio_5fnot_5fequal',['ratio_not_equal',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02844.html',1,'std']]],
  ['raw_5fstorage_5fiterator',['raw_storage_iterator',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06776.html',1,'std']]],
  ['rawvideosource',['RawVideoSource',['http://docs.opencv.org/3.4.0/d6/d55/classcv_1_1cudacodec_1_1RawVideoSource.html',1,'cv::cudacodec']]],
  ['rb_5ftree',['rb_tree',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08152.html',1,'__gnu_cxx']]],
  ['rb_5ftree_5fmap',['rb_tree_map',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10896.html',1,'__gnu_pbds::detail']]],
  ['rb_5ftree_5fnode_5f',['rb_tree_node_',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10888.html',1,'__gnu_pbds::detail']]],
  ['rb_5ftree_5ftag',['rb_tree_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10164.html',1,'__gnu_pbds']]],
  ['rc',['rc',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10908.html',1,'__gnu_pbds::detail']]],
  ['rc_3c_20typename_20binomial_5fheap_5fbase_3c_20value_5ftype_2c_20cmp_5ffn_2c_20_5falloc_20_3e_3a_3anode_2c_20_5falloc_20_3e',['rc&lt; typename binomial_heap_base&lt; Value_Type, Cmp_Fn, _Alloc &gt;::node, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10908.html',1,'']]],
  ['rc_5fbinomial_5fheap',['rc_binomial_heap',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10912.html',1,'__gnu_pbds::detail']]],
  ['rc_5fbinomial_5fheap_5ftag',['rc_binomial_heap_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10200.html',1,'__gnu_pbds']]],
  ['rebind',['rebind',['http://docs.opencv.org/3.4.0/d3/dd1/structcv_1_1cudev_1_1Avg_1_1rebind.html',1,'cv::cudev::Avg&lt; class &gt;::rebind'],['http://docs.opencv.org/3.4.0/da/d52/classcv_1_1Allocator_1_1rebind.html',1,'cv::Allocator&lt; class &gt;::rebind'],['http://docs.opencv.org/3.4.0/d2/dff/structcv_1_1cudev_1_1Min_1_1rebind.html',1,'cv::cudev::Min&lt; class &gt;::rebind'],['http://docs.opencv.org/3.4.0/d1/d1d/structcv_1_1cudev_1_1Sum_1_1rebind.html',1,'cv::cudev::Sum::rebind&lt; class &gt;'],['http://docs.opencv.org/3.4.0/d1/d7c/structcv_1_1cudev_1_1Max_1_1rebind.html',1,'cv::cudev::Max&lt; class &gt;::rebind']]],
  ['rect_5f',['Rect_',['http://docs.opencv.org/3.4.0/d2/d44/classcv_1_1Rect__.html',1,'cv']]],
  ['recursive_5finit_5ferror',['recursive_init_error',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01648.html',1,'__gnu_cxx']]],
  ['recursive_5fmutex',['recursive_mutex',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02728.html',1,'std']]],
  ['recursive_5ftimed_5fmutex',['recursive_timed_mutex',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02736.html',1,'std']]],
  ['reducetocolumnbody',['ReduceToColumnBody',['http://docs.opencv.org/3.4.0/d5/df4/structcv_1_1cudev_1_1ReduceToColumnBody.html',1,'cv::cudev']]],
  ['reducetorowbody',['ReduceToRowBody',['http://docs.opencv.org/3.4.0/da/d58/structcv_1_1cudev_1_1ReduceToRowBody.html',1,'cv::cudev']]],
  ['reference',['reference',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08716.html',1,'std::tr2::dynamic_bitset&lt; _WordT, _Alloc &gt;::reference'],['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01820.html',1,'std::bitset&lt; _Nb &gt;::reference']]],
  ['reference_5fwrapper',['reference_wrapper',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05776.html',1,'std']]],
  ['regex_5ferror',['regex_error',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05912.html',1,'std']]],
  ['regex_5fiterator',['regex_iterator',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05804.html',1,'std']]],
  ['regex_5ftoken_5fiterator',['regex_token_iterator',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05808.html',1,'std']]],
  ['regex_5ftraits',['regex_traits',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05792.html',1,'std']]],
  ['regex_5ftraits_3c_20_5fchartype_20_3e',['regex_traits&lt; _CharType &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05792.html',1,'']]],
  ['regionlayer',['RegionLayer',['http://docs.opencv.org/3.4.0/d1/d21/classcv_1_1dnn_1_1RegionLayer.html',1,'cv::dnn']]],
  ['relu6layer',['ReLU6Layer',['http://docs.opencv.org/3.4.0/dc/dcd/classcv_1_1dnn_1_1ReLU6Layer.html',1,'cv::dnn']]],
  ['relulayer',['ReLULayer',['http://docs.opencv.org/3.4.0/dd/df0/classcv_1_1dnn_1_1ReLULayer.html',1,'cv::dnn']]],
  ['remapptr1',['RemapPtr1',['http://docs.opencv.org/3.4.0/dc/d09/structcv_1_1cudev_1_1RemapPtr1.html',1,'cv::cudev']]],
  ['remapptr1sz',['RemapPtr1Sz',['http://docs.opencv.org/3.4.0/dd/d03/structcv_1_1cudev_1_1RemapPtr1Sz.html',1,'cv::cudev']]],
  ['remapptr2',['RemapPtr2',['http://docs.opencv.org/3.4.0/d1/d32/structcv_1_1cudev_1_1RemapPtr2.html',1,'cv::cudev']]],
  ['remapptr2sz',['RemapPtr2Sz',['http://docs.opencv.org/3.4.0/d4/d59/structcv_1_1cudev_1_1RemapPtr2Sz.html',1,'cv::cudev']]],
  ['reorglayer',['ReorgLayer',['http://docs.opencv.org/3.4.0/d6/da3/classcv_1_1dnn_1_1ReorgLayer.html',1,'cv::dnn']]],
  ['reshapelayer',['ReshapeLayer',['http://docs.opencv.org/3.4.0/db/d15/classcv_1_1dnn_1_1ReshapeLayer.html',1,'cv::dnn']]],
  ['resize_5ferror',['resize_error',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10060.html',1,'__gnu_pbds']]],
  ['resize_5fpolicy',['resize_policy',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10532.html',1,'__gnu_pbds::detail']]],
  ['resize_5fpolicy_3c_20_5falloc_3a_3asize_5ftype_20_3e',['resize_policy&lt; _Alloc::size_type &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10532.html',1,'']]],
  ['resizenearestneighborlayer',['ResizeNearestNeighborLayer',['http://docs.opencv.org/3.4.0/d4/df2/classcv_1_1dnn_1_1ResizeNearestNeighborLayer.html',1,'cv::dnn']]],
  ['resizeptr',['ResizePtr',['http://docs.opencv.org/3.4.0/d5/db1/structcv_1_1cudev_1_1ResizePtr.html',1,'cv::cudev']]],
  ['resizeptrsz',['ResizePtrSz',['http://docs.opencv.org/3.4.0/d3/d8a/structcv_1_1cudev_1_1ResizePtrSz.html',1,'cv::cudev']]],
  ['resultset',['ResultSet',['http://docs.opencv.org/3.4.0/d8/d42/classcvflann_1_1ResultSet.html',1,'cvflann']]],
  ['retina',['Retina',['http://docs.opencv.org/3.4.0/dc/d54/classcv_1_1bioinspired_1_1Retina.html',1,'cv::bioinspired']]],
  ['retinafasttonemapping',['RetinaFastToneMapping',['http://docs.opencv.org/3.4.0/dd/d73/classcv_1_1bioinspired_1_1RetinaFastToneMapping.html',1,'cv::bioinspired']]],
  ['retinaparameters',['RetinaParameters',['http://docs.opencv.org/3.4.0/d2/df5/structcv_1_1bioinspired_1_1RetinaParameters.html',1,'cv::bioinspired']]],
  ['reverse_5fiterator',['reverse_iterator',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06612.html',1,'std']]],
  ['rffeaturegetter',['RFFeatureGetter',['http://docs.opencv.org/3.4.0/dc/dca/classcv_1_1ximgproc_1_1RFFeatureGetter.html',1,'cv::ximgproc']]],
  ['rgb2gray',['RGB2Gray',['http://docs.opencv.org/3.4.0/d9/d5f/classcv_1_1cudev_1_1color__cvt__detail_1_1RGB2Gray.html',1,'cv::cudev::color_cvt_detail']]],
  ['rgb2hls',['RGB2HLS',['http://docs.opencv.org/3.4.0/de/d2b/classcv_1_1cudev_1_1color__cvt__detail_1_1RGB2HLS.html',1,'cv::cudev::color_cvt_detail']]],
  ['rgb2hsv',['RGB2HSV',['http://docs.opencv.org/3.4.0/de/d72/classcv_1_1cudev_1_1color__cvt__detail_1_1RGB2HSV.html',1,'cv::cudev::color_cvt_detail']]],
  ['rgb2lab',['RGB2Lab',['http://docs.opencv.org/3.4.0/db/df2/classcv_1_1cudev_1_1color__cvt__detail_1_1RGB2Lab.html',1,'cv::cudev::color_cvt_detail']]],
  ['rgb2luv',['RGB2Luv',['http://docs.opencv.org/3.4.0/d0/d2c/classcv_1_1cudev_1_1color__cvt__detail_1_1RGB2Luv.html',1,'cv::cudev::color_cvt_detail']]],
  ['rgb2rgb',['RGB2RGB',['http://docs.opencv.org/3.4.0/de/d9d/classcv_1_1cudev_1_1color__cvt__detail_1_1RGB2RGB.html',1,'cv::cudev::color_cvt_detail']]],
  ['rgb2xyz',['RGB2XYZ',['http://docs.opencv.org/3.4.0/d1/ddf/classcv_1_1cudev_1_1color__cvt__detail_1_1RGB2XYZ.html',1,'cv::cudev::color_cvt_detail']]],
  ['rgb2ycrcb',['RGB2YCrCb',['http://docs.opencv.org/3.4.0/da/d08/classcv_1_1cudev_1_1color__cvt__detail_1_1RGB2YCrCb.html',1,'cv::cudev::color_cvt_detail']]],
  ['rgb2yuv',['RGB2YUV',['http://docs.opencv.org/3.4.0/d6/d96/classcv_1_1cudev_1_1color__cvt__detail_1_1RGB2YUV.html',1,'cv::cudev::color_cvt_detail']]],
  ['rgb_5fto_5fgray_5ffunc',['RGB_to_GRAY_func',['http://docs.opencv.org/3.4.0/d8/ded/structcv_1_1cudev_1_1RGB__to__GRAY__func.html',1,'cv::cudev']]],
  ['rgb_5fto_5fhls4_5ffull_5ffunc',['RGB_to_HLS4_FULL_func',['http://docs.opencv.org/3.4.0/d2/d93/structcv_1_1cudev_1_1RGB__to__HLS4__FULL__func.html',1,'cv::cudev']]],
  ['rgb_5fto_5fhls4_5ffull_5ffunc_3c_20float_20_3e',['RGB_to_HLS4_FULL_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/db/deb/structcv_1_1cudev_1_1RGB__to__HLS4__FULL__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['rgb_5fto_5fhls4_5ffunc',['RGB_to_HLS4_func',['http://docs.opencv.org/3.4.0/d9/d77/structcv_1_1cudev_1_1RGB__to__HLS4__func.html',1,'cv::cudev']]],
  ['rgb_5fto_5fhls4_5ffunc_3c_20float_20_3e',['RGB_to_HLS4_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/d6/d6b/structcv_1_1cudev_1_1RGB__to__HLS4__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['rgb_5fto_5fhls_5ffull_5ffunc',['RGB_to_HLS_FULL_func',['http://docs.opencv.org/3.4.0/d5/d13/structcv_1_1cudev_1_1RGB__to__HLS__FULL__func.html',1,'cv::cudev']]],
  ['rgb_5fto_5fhls_5ffull_5ffunc_3c_20float_20_3e',['RGB_to_HLS_FULL_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/d1/d6f/structcv_1_1cudev_1_1RGB__to__HLS__FULL__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['rgb_5fto_5fhls_5ffunc',['RGB_to_HLS_func',['http://docs.opencv.org/3.4.0/d8/d24/structcv_1_1cudev_1_1RGB__to__HLS__func.html',1,'cv::cudev']]],
  ['rgb_5fto_5fhls_5ffunc_3c_20float_20_3e',['RGB_to_HLS_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/d8/d04/structcv_1_1cudev_1_1RGB__to__HLS__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['rgb_5fto_5fhsv4_5ffull_5ffunc',['RGB_to_HSV4_FULL_func',['http://docs.opencv.org/3.4.0/dc/d3a/structcv_1_1cudev_1_1RGB__to__HSV4__FULL__func.html',1,'cv::cudev']]],
  ['rgb_5fto_5fhsv4_5ffull_5ffunc_3c_20float_20_3e',['RGB_to_HSV4_FULL_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/d5/d76/structcv_1_1cudev_1_1RGB__to__HSV4__FULL__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['rgb_5fto_5fhsv4_5ffunc',['RGB_to_HSV4_func',['http://docs.opencv.org/3.4.0/d8/db1/structcv_1_1cudev_1_1RGB__to__HSV4__func.html',1,'cv::cudev']]],
  ['rgb_5fto_5fhsv4_5ffunc_3c_20float_20_3e',['RGB_to_HSV4_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/d9/da5/structcv_1_1cudev_1_1RGB__to__HSV4__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['rgb_5fto_5fhsv_5ffull_5ffunc',['RGB_to_HSV_FULL_func',['http://docs.opencv.org/3.4.0/da/dee/structcv_1_1cudev_1_1RGB__to__HSV__FULL__func.html',1,'cv::cudev']]],
  ['rgb_5fto_5fhsv_5ffull_5ffunc_3c_20float_20_3e',['RGB_to_HSV_FULL_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/d0/d0e/structcv_1_1cudev_1_1RGB__to__HSV__FULL__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['rgb_5fto_5fhsv_5ffunc',['RGB_to_HSV_func',['http://docs.opencv.org/3.4.0/db/d4e/structcv_1_1cudev_1_1RGB__to__HSV__func.html',1,'cv::cudev']]],
  ['rgb_5fto_5fhsv_5ffunc_3c_20float_20_3e',['RGB_to_HSV_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/db/d37/structcv_1_1cudev_1_1RGB__to__HSV__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['rgb_5fto_5flab4_5ffunc',['RGB_to_Lab4_func',['http://docs.opencv.org/3.4.0/d2/d21/structcv_1_1cudev_1_1RGB__to__Lab4__func.html',1,'cv::cudev']]],
  ['rgb_5fto_5flab_5ffunc',['RGB_to_Lab_func',['http://docs.opencv.org/3.4.0/db/d41/structcv_1_1cudev_1_1RGB__to__Lab__func.html',1,'cv::cudev']]],
  ['rgb_5fto_5fluv4_5ffunc',['RGB_to_Luv4_func',['http://docs.opencv.org/3.4.0/d5/d72/structcv_1_1cudev_1_1RGB__to__Luv4__func.html',1,'cv::cudev']]],
  ['rgb_5fto_5fluv_5ffunc',['RGB_to_Luv_func',['http://docs.opencv.org/3.4.0/dc/db6/structcv_1_1cudev_1_1RGB__to__Luv__func.html',1,'cv::cudev']]],
  ['rgb_5fto_5fxyz4_5ffunc',['RGB_to_XYZ4_func',['http://docs.opencv.org/3.4.0/d2/dd8/structcv_1_1cudev_1_1RGB__to__XYZ4__func.html',1,'cv::cudev']]],
  ['rgb_5fto_5fxyz_5ffunc',['RGB_to_XYZ_func',['http://docs.opencv.org/3.4.0/dd/d54/structcv_1_1cudev_1_1RGB__to__XYZ__func.html',1,'cv::cudev']]],
  ['rgb_5fto_5fycrcb4_5ffunc',['RGB_to_YCrCb4_func',['http://docs.opencv.org/3.4.0/df/d11/structcv_1_1cudev_1_1RGB__to__YCrCb4__func.html',1,'cv::cudev']]],
  ['rgb_5fto_5fycrcb_5ffunc',['RGB_to_YCrCb_func',['http://docs.opencv.org/3.4.0/df/d9a/structcv_1_1cudev_1_1RGB__to__YCrCb__func.html',1,'cv::cudev']]],
  ['rgb_5fto_5fyuv4_5ffunc',['RGB_to_YUV4_func',['http://docs.opencv.org/3.4.0/d9/d7a/structcv_1_1cudev_1_1RGB__to__YUV4__func.html',1,'cv::cudev']]],
  ['rgb_5fto_5fyuv_5ffunc',['RGB_to_YUV_func',['http://docs.opencv.org/3.4.0/d7/d9f/structcv_1_1cudev_1_1RGB__to__YUV__func.html',1,'cv::cudev']]],
  ['rgba_5fto_5fgray_5ffunc',['RGBA_to_GRAY_func',['http://docs.opencv.org/3.4.0/db/d04/structcv_1_1cudev_1_1RGBA__to__GRAY__func.html',1,'cv::cudev']]],
  ['rgba_5fto_5fhls4_5ffull_5ffunc',['RGBA_to_HLS4_FULL_func',['http://docs.opencv.org/3.4.0/d0/d56/structcv_1_1cudev_1_1RGBA__to__HLS4__FULL__func.html',1,'cv::cudev']]],
  ['rgba_5fto_5fhls4_5ffull_5ffunc_3c_20float_20_3e',['RGBA_to_HLS4_FULL_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/de/d5e/structcv_1_1cudev_1_1RGBA__to__HLS4__FULL__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['rgba_5fto_5fhls4_5ffunc',['RGBA_to_HLS4_func',['http://docs.opencv.org/3.4.0/d6/d31/structcv_1_1cudev_1_1RGBA__to__HLS4__func.html',1,'cv::cudev']]],
  ['rgba_5fto_5fhls4_5ffunc_3c_20float_20_3e',['RGBA_to_HLS4_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/d8/dcb/structcv_1_1cudev_1_1RGBA__to__HLS4__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['rgba_5fto_5fhls_5ffull_5ffunc',['RGBA_to_HLS_FULL_func',['http://docs.opencv.org/3.4.0/dd/db8/structcv_1_1cudev_1_1RGBA__to__HLS__FULL__func.html',1,'cv::cudev']]],
  ['rgba_5fto_5fhls_5ffull_5ffunc_3c_20float_20_3e',['RGBA_to_HLS_FULL_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/d4/dd3/structcv_1_1cudev_1_1RGBA__to__HLS__FULL__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['rgba_5fto_5fhls_5ffunc',['RGBA_to_HLS_func',['http://docs.opencv.org/3.4.0/d9/dd5/structcv_1_1cudev_1_1RGBA__to__HLS__func.html',1,'cv::cudev']]],
  ['rgba_5fto_5fhls_5ffunc_3c_20float_20_3e',['RGBA_to_HLS_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/d2/d0c/structcv_1_1cudev_1_1RGBA__to__HLS__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['rgba_5fto_5fhsv4_5ffull_5ffunc',['RGBA_to_HSV4_FULL_func',['http://docs.opencv.org/3.4.0/dd/d19/structcv_1_1cudev_1_1RGBA__to__HSV4__FULL__func.html',1,'cv::cudev']]],
  ['rgba_5fto_5fhsv4_5ffull_5ffunc_3c_20float_20_3e',['RGBA_to_HSV4_FULL_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/d1/d1f/structcv_1_1cudev_1_1RGBA__to__HSV4__FULL__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['rgba_5fto_5fhsv4_5ffunc',['RGBA_to_HSV4_func',['http://docs.opencv.org/3.4.0/d7/d25/structcv_1_1cudev_1_1RGBA__to__HSV4__func.html',1,'cv::cudev']]],
  ['rgba_5fto_5fhsv4_5ffunc_3c_20float_20_3e',['RGBA_to_HSV4_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/db/d05/structcv_1_1cudev_1_1RGBA__to__HSV4__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['rgba_5fto_5fhsv_5ffull_5ffunc',['RGBA_to_HSV_FULL_func',['http://docs.opencv.org/3.4.0/db/d47/structcv_1_1cudev_1_1RGBA__to__HSV__FULL__func.html',1,'cv::cudev']]],
  ['rgba_5fto_5fhsv_5ffull_5ffunc_3c_20float_20_3e',['RGBA_to_HSV_FULL_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/d0/d1c/structcv_1_1cudev_1_1RGBA__to__HSV__FULL__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['rgba_5fto_5fhsv_5ffunc',['RGBA_to_HSV_func',['http://docs.opencv.org/3.4.0/d1/d7d/structcv_1_1cudev_1_1RGBA__to__HSV__func.html',1,'cv::cudev']]],
  ['rgba_5fto_5fhsv_5ffunc_3c_20float_20_3e',['RGBA_to_HSV_func&lt; float &gt;',['http://docs.opencv.org/3.4.0/d0/d9b/structcv_1_1cudev_1_1RGBA__to__HSV__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['rgba_5fto_5flab4_5ffunc',['RGBA_to_Lab4_func',['http://docs.opencv.org/3.4.0/df/d38/structcv_1_1cudev_1_1RGBA__to__Lab4__func.html',1,'cv::cudev']]],
  ['rgba_5fto_5flab_5ffunc',['RGBA_to_Lab_func',['http://docs.opencv.org/3.4.0/d2/d37/structcv_1_1cudev_1_1RGBA__to__Lab__func.html',1,'cv::cudev']]],
  ['rgba_5fto_5fluv4_5ffunc',['RGBA_to_Luv4_func',['http://docs.opencv.org/3.4.0/d7/d2e/structcv_1_1cudev_1_1RGBA__to__Luv4__func.html',1,'cv::cudev']]],
  ['rgba_5fto_5fluv_5ffunc',['RGBA_to_Luv_func',['http://docs.opencv.org/3.4.0/de/d88/structcv_1_1cudev_1_1RGBA__to__Luv__func.html',1,'cv::cudev']]],
  ['rgba_5fto_5fxyz4_5ffunc',['RGBA_to_XYZ4_func',['http://docs.opencv.org/3.4.0/d9/da9/structcv_1_1cudev_1_1RGBA__to__XYZ4__func.html',1,'cv::cudev']]],
  ['rgba_5fto_5fxyz_5ffunc',['RGBA_to_XYZ_func',['http://docs.opencv.org/3.4.0/d7/d53/structcv_1_1cudev_1_1RGBA__to__XYZ__func.html',1,'cv::cudev']]],
  ['rgba_5fto_5fycrcb4_5ffunc',['RGBA_to_YCrCb4_func',['http://docs.opencv.org/3.4.0/d0/dd4/structcv_1_1cudev_1_1RGBA__to__YCrCb4__func.html',1,'cv::cudev']]],
  ['rgba_5fto_5fycrcb_5ffunc',['RGBA_to_YCrCb_func',['http://docs.opencv.org/3.4.0/d1/dd1/structcv_1_1cudev_1_1RGBA__to__YCrCb__func.html',1,'cv::cudev']]],
  ['rgba_5fto_5fyuv4_5ffunc',['RGBA_to_YUV4_func',['http://docs.opencv.org/3.4.0/d3/da0/structcv_1_1cudev_1_1RGBA__to__YUV4__func.html',1,'cv::cudev']]],
  ['rgba_5fto_5fyuv_5ffunc',['RGBA_to_YUV_func',['http://docs.opencv.org/3.4.0/db/d21/structcv_1_1cudev_1_1RGBA__to__YUV__func.html',1,'cv::cudev']]],
  ['rgbdframe',['RgbdFrame',['http://docs.opencv.org/3.4.0/d3/d9c/structcv_1_1rgbd_1_1RgbdFrame.html',1,'cv::rgbd']]],
  ['rgbdicpodometry',['RgbdICPOdometry',['http://docs.opencv.org/3.4.0/d2/d0f/classcv_1_1rgbd_1_1RgbdICPOdometry.html',1,'cv::rgbd']]],
  ['rgbdnormals',['RgbdNormals',['http://docs.opencv.org/3.4.0/d1/d5b/classcv_1_1rgbd_1_1RgbdNormals.html',1,'cv::rgbd']]],
  ['rgbdodometry',['RgbdOdometry',['http://docs.opencv.org/3.4.0/d0/d60/classcv_1_1rgbd_1_1RgbdOdometry.html',1,'cv::rgbd']]],
  ['rgbdplane',['RgbdPlane',['http://docs.opencv.org/3.4.0/d6/d50/classcv_1_1rgbd_1_1RgbdPlane.html',1,'cv::rgbd']]],
  ['ridgedetectionfilter',['RidgeDetectionFilter',['http://docs.opencv.org/3.4.0/d4/d36/classcv_1_1ximgproc_1_1RidgeDetectionFilter.html',1,'cv::ximgproc']]],
  ['rng',['RNG',['http://docs.opencv.org/3.4.0/d1/dd6/classcv_1_1RNG.html',1,'cv']]],
  ['rng_5fmt19937',['RNG_MT19937',['http://docs.opencv.org/3.4.0/db/d3e/classcv_1_1RNG__MT19937.html',1,'cv']]],
  ['rnnlayer',['RNNLayer',['http://docs.opencv.org/3.4.0/dd/dfd/classcv_1_1dnn_1_1RNNLayer.html',1,'cv::dnn']]],
  ['rope',['rope',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08168.html',1,'__gnu_cxx']]],
  ['rotatedrect',['RotatedRect',['http://docs.opencv.org/3.4.0/db/dd6/classcv_1_1RotatedRect.html',1,'cv']]],
  ['rotationwarper',['RotationWarper',['http://docs.opencv.org/3.4.0/da/db8/classcv_1_1detail_1_1RotationWarper.html',1,'cv::detail']]],
  ['rotationwarperbase',['RotationWarperBase',['http://docs.opencv.org/3.4.0/d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20compressedrectilinearportraitprojector_20_3e',['RotationWarperBase&lt; CompressedRectilinearPortraitProjector &gt;',['http://docs.opencv.org/3.4.0/d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'']]],
  ['rotationwarperbase_3c_20compressedrectilinearprojector_20_3e',['RotationWarperBase&lt; CompressedRectilinearProjector &gt;',['http://docs.opencv.org/3.4.0/d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'']]],
  ['rotationwarperbase_3c_20cylindricalportraitprojector_20_3e',['RotationWarperBase&lt; CylindricalPortraitProjector &gt;',['http://docs.opencv.org/3.4.0/d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'']]],
  ['rotationwarperbase_3c_20cylindricalprojector_20_3e',['RotationWarperBase&lt; CylindricalProjector &gt;',['http://docs.opencv.org/3.4.0/d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'']]],
  ['rotationwarperbase_3c_20fisheyeprojector_20_3e',['RotationWarperBase&lt; FisheyeProjector &gt;',['http://docs.opencv.org/3.4.0/d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'']]],
  ['rotationwarperbase_3c_20mercatorprojector_20_3e',['RotationWarperBase&lt; MercatorProjector &gt;',['http://docs.opencv.org/3.4.0/d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'']]],
  ['rotationwarperbase_3c_20paniniportraitprojector_20_3e',['RotationWarperBase&lt; PaniniPortraitProjector &gt;',['http://docs.opencv.org/3.4.0/d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'']]],
  ['rotationwarperbase_3c_20paniniprojector_20_3e',['RotationWarperBase&lt; PaniniProjector &gt;',['http://docs.opencv.org/3.4.0/d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'']]],
  ['rotationwarperbase_3c_20planeportraitprojector_20_3e',['RotationWarperBase&lt; PlanePortraitProjector &gt;',['http://docs.opencv.org/3.4.0/d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'']]],
  ['rotationwarperbase_3c_20planeprojector_20_3e',['RotationWarperBase&lt; PlaneProjector &gt;',['http://docs.opencv.org/3.4.0/d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'']]],
  ['rotationwarperbase_3c_20sphericalportraitprojector_20_3e',['RotationWarperBase&lt; SphericalPortraitProjector &gt;',['http://docs.opencv.org/3.4.0/d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'']]],
  ['rotationwarperbase_3c_20sphericalprojector_20_3e',['RotationWarperBase&lt; SphericalProjector &gt;',['http://docs.opencv.org/3.4.0/d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'']]],
  ['rotationwarperbase_3c_20stereographicprojector_20_3e',['RotationWarperBase&lt; StereographicProjector &gt;',['http://docs.opencv.org/3.4.0/d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'']]],
  ['rotationwarperbase_3c_20transversemercatorprojector_20_3e',['RotationWarperBase&lt; TransverseMercatorProjector &gt;',['http://docs.opencv.org/3.4.0/d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'']]],
  ['rtrees',['RTrees',['http://docs.opencv.org/3.4.0/d0/d65/classcv_1_1ml_1_1RTrees.html',1,'cv::ml']]],
  ['runtime_5ferror',['runtime_error',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02920.html',1,'std']]]
];
