var searchData=
[
  ['improved_20background_2dforeground_20segmentation_20methods',['Improved Background-Foreground Segmentation Methods',['http://docs.opencv.org/3.4.0/d2/d55/group__bgsegm.html',1,'']]],
  ['interface',['Interface',['http://docs.opencv.org/3.4.0/d1/d1b/group__core__hal__interface.html',1,'']]],
  ['inverse_20square_20root_20calculation',['Inverse square root calculation',['http://docs.opencv.org/3.4.0/d0/d5d/group__core__hal__interface__invSqrt.html',1,'']]],
  ['intel_20ipp_20asynchronous_20c_2fc_2b_2b_20converters',['Intel IPP Asynchronous C/C++ Converters',['http://docs.opencv.org/3.4.0/d6/dcf/group__core__ipp.html',1,'']]],
  ['intel_20va_2dapi_2fopencl_20_28cl_2dva_29_20interoperability',['Intel VA-API/OpenCL (CL-VA) interoperability',['http://docs.opencv.org/3.4.0/d1/daa/group__core__va__intel.html',1,'']]],
  ['initalization_20and_20information',['Initalization and Information',['http://docs.opencv.org/3.4.0/d8/d40/group__cudacore__init.html',1,'']]],
  ['image_20filtering',['Image Filtering',['http://docs.opencv.org/3.4.0/dc/d66/group__cudafilters.html',1,'']]],
  ['image_20processing',['Image Processing',['http://docs.opencv.org/3.4.0/d0/d05/group__cudaimgproc.html',1,'']]],
  ['image_20warping',['Image Warping',['http://docs.opencv.org/3.4.0/db/d29/group__cudawarping.html',1,'']]],
  ['image_20registration',['Image Registration',['http://docs.opencv.org/3.4.0/dc/def/group__datasets__ir.html',1,'']]],
  ['image_20segmentation',['Image Segmentation',['http://docs.opencv.org/3.4.0/d3/d2d/group__datasets__is.html',1,'']]],
  ['image_20processing_20based_20on_20fuzzy_20mathematics',['Image processing based on fuzzy mathematics',['http://docs.opencv.org/3.4.0/df/d5b/group__fuzzy.html',1,'']]],
  ['image_20file_20reading_20and_20writing',['Image file reading and writing',['http://docs.opencv.org/3.4.0/d4/da8/group__imgcodecs.html',1,'']]],
  ['ios_20glue',['iOS glue',['http://docs.opencv.org/3.4.0/d2/d92/group__imgcodecs__ios.html',1,'']]],
  ['image_20processing',['Image processing',['http://docs.opencv.org/3.4.0/d7/dbd/group__imgproc.html',1,'']]],
  ['image_20filtering',['Image Filtering',['http://docs.opencv.org/3.4.0/d4/d86/group__imgproc__filter.html',1,'']]],
  ['interface',['Interface',['http://docs.opencv.org/3.4.0/dd/d8b/group__imgproc__hal__interface.html',1,'']]],
  ['invalidation_20guarantees',['Invalidation Guarantees',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01534.html',1,'']]],
  ['i_2fo',['I/O',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01476.html',1,'']]],
  ['iterator_20tags',['Iterator Tags',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01511.html',1,'']]],
  ['iterators',['Iterators',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01510.html',1,'']]],
  ['image_20registration',['Image Registration',['http://docs.opencv.org/3.4.0/db/d61/group__reg.html',1,'']]],
  ['images_20stitching',['Images stitching',['http://docs.opencv.org/3.4.0/d1/d46/group__stitching.html',1,'']]],
  ['image_20blenders',['Image Blenders',['http://docs.opencv.org/3.4.0/d9/d46/group__stitching__blend.html',1,'']]],
  ['images_20warping',['Images Warping',['http://docs.opencv.org/3.4.0/d0/dfa/group__stitching__warp.html',1,'']]],
  ['ios_20glue_20for_20video_20i_2fo',['iOS glue for video I/O',['http://docs.opencv.org/3.4.0/d5/d26/group__videoio__ios.html',1,'']]],
  ['image_20segmentation',['Image segmentation',['http://docs.opencv.org/3.4.0/d5/df0/group__ximgproc__segmentation.html',1,'']]]
];
